name: laplacian-vsharp-rts
version: 1.0.0
copyright:
  - license: MIT
    url: https://github.com/kamesy/QSM.jl
architectures:
  - x86_64

build:
  kind: neurodocker
  base-image: ubuntu:22.04
  pkg-manager: apt

  directives:
    - install:
        - wget
        - build-essential
        - libfftw3-dev
        - jq
        - curl
        - python3
        - python3-pip

    - run:
        - pip3 install nibabel scipy 

    # Install FSL with neurodocker template
    - template:
        name: fsl
        version: 6.0.7.16

    - environment:
        FSLOUTPUTTYPE: NIFTI_GZ

    - workdir: /opt/qsm

    # Install Julia in the container
    - run:
        - wget -q https://julialang-s3.julialang.org/bin/linux/x64/1.9/julia-1.9.4-linux-x86_64.tar.gz
        - tar xf julia-1.9.4-linux-x86_64.tar.gz -C /opt
        - rm julia-1.9.4-linux-x86_64.tar.gz
        - ln -s /opt/julia-1.9.4/bin/julia /usr/local/bin/julia

    # Copy algorithm files
    - copy:
        - main.sh
        - /opt/qsm/main.sh

    - copy:
        - pipeline.jl
        - /opt/qsm/pipeline.jl

    - copy:
        - install_packages.jl
        - /opt/qsm/install_packages.jl

    - copy:
        - laplacian_vsharp_rts_algorithm.jl
        - /opt/qsm/laplacian_vsharp_rts_algorithm.jl

    - run:
        - chmod +x /opt/qsm/main.sh
        - chmod +x /opt/qsm/*.jl

    # Julia packages will be installed at runtime to avoid compilation issues

    - environment:
        PATH: $PATH:/opt/qsm

    # Boutiques descriptor for laplacian + V-SHARP + RTS algorithm
    - boutique:
        name: laplacian-vsharp-rts
        description: QSM reconstruction using Laplacian unwrapping, V-SHARP background removal, and RTS dipole inversion
        tool-version: v1.0.0
        schema-version: '0.5'
        container-image:
          type: docker
          image: astewartau/laplacian-vsharp-rts_1.0.0:latest
        command-line: >-
          laplacian_vsharp_rts_algorithm.jl [OUTPUT_FILE]
          --mag_files [MAG_FILES]
          --phase_files [PHASE_FILES]
          --echo_times [ECHO_TIMES]
          --field_strength [FIELD_STRENGTH]
          --mask_file [MASK_FILE]
        inputs:
          - name: magnitude_files
            id: magnitude_files
            description: Multi-echo magnitude images
            type: File
            list: true
            optional: false
            value-key: '[MAG_FILES]'
          - name: phase_files
            id: phase_files
            description: Multi-echo phase images
            type: File
            list: true
            optional: false
            value-key: '[PHASE_FILES]'
          - name: echo_times
            id: echo_times
            description: Echo times in seconds
            type: Number
            list: true
            optional: false
            value-key: '[ECHO_TIMES]'
          - name: field_strength
            id: field_strength
            description: Magnetic field strength in Tesla
            type: Number
            optional: false
            value-key: '[FIELD_STRENGTH]'
          - name: mask_file
            id: mask_file
            description: Brain mask file
            type: File
            optional: false
            value-key: '[MASK_FILE]'
          - name: output_file
            id: output_file
            description: Output QSM map file path
            type: String
            optional: false
            value-key: '[OUTPUT_FILE]'
        output-files:
          - name: qsm_map
            id: qsm_map
            description: Quantitative susceptibility map
            path-template: "[OUTPUT_FILE]"
          - name: metrics
            id: metrics
            description: Evaluation metrics (if ground truth available)
            path-template: "metrics.json"
            optional: true
        tags:
          evaluation: qsm-ci.yml
        custom:
          evaluation-config:
            output-patterns: ["*Chimap*.nii*", "*chi*.nii*", "*qsm*.nii*", "out.nii.gz"]

deploy:
  path:
    - /opt/qsm
  bins:
    - main.sh
    - laplacian_vsharp_rts_algorithm.jl

categories:
  - phase processing
  - image reconstruction
  - quantitative imaging

readme: |-
  ----------------------------------
  ## Laplacian V-SHARP RTS/{{ context.version }} ##

  QSM reconstruction using Julia-based QSM.jl package with:
  - Laplacian phase unwrapping
  - V-SHARP background field removal
  - RTS (Rapid Two-Step) dipole inversion

  This algorithm provides a pure Julia implementation of the QSM pipeline
  with proven algorithms for each step.

  ## References
  - Unwrapping: Schofield MA, Zhu Y. Fast phase unwrapping algorithm for interferometric applications. Optics letters. 2003.
  - Background removal: Wu B, Li W, Guidon A et al. Whole brain susceptibility mapping using compressed sensing. MRM. 2012.
  - Dipole inversion: Kames C, Wiggermann V, Rauscher A. Rapid two-step dipole inversion for susceptibility mapping with sparsity priors. Neuroimage. 2018.
  - QSM.jl package: Kames C. kamesy/QSM.jl. GitHub; 2024.

  Example usage:
  ```bash
  singularity exec laplacian-vsharp-rts.sif main.sh /data/bids /output --subject 1
  ```

  The algorithm expects multi-echo BIDS data and outputs susceptibility maps
  in BIDS derivatives format.

  ----------------------------------
