name: brainager
version: 2.1.0

copyright:
  - license: LGPL-3.0
    url: https://github.com/james-cole/brainageR?tab=LGPL-3.0-1-ov-file#readme
architectures:
  - x86_64

build:
  kind: neurodocker

  base-image: ubuntu:20.04
  pkg-manager: apt

  directives:
    - install:
        - wget
        - unzip
        - ca-certificates
        - openjdk-8-jre
        - dbus-x11
        - python3-pip
        - git
        - r-base
        - build-essential
        - gfortran
        - libblas-dev
        - liblapack-dev
        - libxml2-dev
        - libcurl4-openssl-dev
        - libssl-dev

    - environment:
        MATLAB_VERSION: 2017b
        MCR_UPDATE: "9"
        MCR_VERSION: v93
        # LD_LIBRARY_PATH: /opt/mcr/v93/runtime/glnxa64:/opt/mcr/v93/bin/glnxa64:/opt/mcr/v93/sys/os/glnxa64:/opt/mcr/v93/sys/opengl/lib/glnxa64:/opt/mcr/v93/extern/bin/glnxa64
        LD_LIBRARY_PATH: ""

    - template:
        name: matlabmcr
        install_path: /opt/mcr
        version: 2017b

    - environment:
        MCR_INHIBIT_CTF_LOCK: "1"
        SPM_HTML_BROWSER: "0"
        SPM_REVISION: r7219
        SPM_VERSION: "12"

    - run:
        - wget --no-check-certificate --progress=bar:force -P /opt https://www.fil.ion.ucl.ac.uk/spm/download/restricted/bids/spm12_r7219_Linux_R2017b.zip
        - unzip -q /opt/spm12_r7219_Linux_R2017b.zip -d /opt
        - rm -f /opt/spm12_r7219_Linux_R2017b.zip

    - run:
        - /opt/spm12/spm12 function exit
        - chmod +x /opt/spm12/*

    - environment:
        DEPLOY_ENV_FORCE_SPMMCR: "1"
        DEPLOY_ENV_SPMMCRCMD: run_spm12.sh /opt/mcr/v93/ script
        PATH: $PATH:/opt/spm12:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        XAPPLRESDIR: /opt/mcr/v93/x11/app-defaults
    
    - workdir: /opt

    - run:
        - git clone https://github.com/james-cole/brainageR
        - rm -rf /opt/brainageR/.git
        - rm -rf /opt/brainageR/templates
        - curl https://object-store.rc.nectar.org.au/v1/AUTH_dead991e1fa847e3afcca2d3a7041f5d/build/brainager_neurodesk.zip -o brainager_neurodesk.zip
        - unzip brainager_neurodesk.zip -d /opt/brainageR_chris
        - mv /opt/brainageR_chris/* /opt/brainageR/ 
        - rm -f brainager_neurodesk.zip

    - workdir: /opt/brainageR
    - run:
        - pip3 install osfclient
        - osf -p azwmg fetch pca_center.rds
        - osf -p azwmg fetch pca_rotation.rds
        - osf -p azwmg fetch pca_scale.rds

    - copy: dependencies.R /opt
    - copy: predict_age_patched.py /opt/brainageR/predict_age.py

    - run:
        - Rscript /opt/dependencies.R
        - chmod a+x /opt/brainageR/brainager_segment.py
        - chmod a+x /opt/brainageR/predict_age.py

    - environment:
        LD_LIBRARY_PATH: /opt/mcr/v93/runtime/glnxa64:/opt/mcr/v93/bin/glnxa64:/opt/mcr/v93/sys/os/glnxa64:/opt/mcr/v93/sys/opengl/lib/glnxa64:/opt/mcr/v93/extern/bin/glnxa64
        PATH: $PATH:/opt/brainageR

deploy:
  bins:
    - spm12
    - brainager_segment.py
    - predict_age.py

readme: |-
  ----------------------------------
  ## brainager/{{ context.version }} ##
  Software for generating a brain-predicted age value from a raw T1-weighted MRI scan. This uses a Gaussian Processes regression, implemented in R, using the kernlab package.
  

  Example:
  ```
      mkdir -p brainager_test
      cp /opt/brainageR/chris_t1.nii.gz ~/brainager_test
      cd ~/brainager_test
      brainager_segment.py chris_t1.nii.gz 
      predict_age.py --subjname chris_t1 ./chris_t1
  ```

  To run container outside of this environment: ml brainager/{{ context.version }}

  ----------------------------------

categories:
  - "structural imaging"
