name: brainager
version: 2.1.0

copyright:
  - license: LGPL-3.0
    url: https://github.com/james-cole/brainageR?tab=LGPL-3.0-1-ov-file#readme
architectures:
  - x86_64

build:
  kind: neurodocker

  base-image: ubuntu:20.04
  pkg-manager: apt

  directives:
    - install:
        - wget
        - unzip
        - ca-certificates
        - openjdk-8-jre
        - dbus-x11
        - python3-pip
        - git
        - r-base
        - build-essential
        - gfortran
        - libblas-dev
        - liblapack-dev
        - libxml2-dev
        - libcurl4-openssl-dev
        - libssl-dev

    - environment:
        MATLAB_VERSION: 2017b
        MCR_UPDATE: "9"
        MCR_VERSION: v93
        # LD_LIBRARY_PATH: /opt/mcr/v93/runtime/glnxa64:/opt/mcr/v93/bin/glnxa64:/opt/mcr/v93/sys/os/glnxa64:/opt/mcr/v93/sys/opengl/lib/glnxa64:/opt/mcr/v93/extern/bin/glnxa64
        LD_LIBRARY_PATH: ""

    - template:
        name: matlabmcr
        install_path: /opt/mcr
        version: 2017b

    - environment:
        MCR_INHIBIT_CTF_LOCK: "1"
        SPM_HTML_BROWSER: "0"
        SPM_REVISION: r7219
        SPM_VERSION: "12"

    - run:
        - cp {{ get_file("spm12_r7219_Linux_R2017b_zip") }} /opt/spm12_r7219_Linux_R2017b.zip
        - unzip -q /opt/spm12_r7219_Linux_R2017b.zip -d /opt
        - rm -f /opt/spm12_r7219_Linux_R2017b.zip

    - run:
        - /opt/spm12/spm12 function exit
        - chmod +x /opt/spm12/*

    - environment:
        DEPLOY_ENV_FORCE_SPMMCR: "1"
        DEPLOY_ENV_SPMMCRCMD: run_spm12.sh /opt/mcr/v93/ script
        PATH: $PATH:/opt/spm12:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        XAPPLRESDIR: /opt/mcr/v93/x11/app-defaults
    
    - workdir: /opt

    - run:
        - git clone https://github.com/james-cole/brainageR
        - rm -rf /opt/brainageR/.git
        - rm -rf /opt/brainageR/templates
        - cp {{ get_file("brainager_neurodesk_zip") }} brainager_neurodesk.zip
        - unzip brainager_neurodesk.zip -d /opt/brainageR_chris
        - mv /opt/brainageR_chris/* /opt/brainageR/ 
        - rm -f brainager_neurodesk.zip

    - workdir: /opt/brainageR
    - run:
        - pip3 install osfclient
        - osf -p azwmg fetch pca_center.rds
        - osf -p azwmg fetch pca_rotation.rds
        - osf -p azwmg fetch pca_scale.rds

    - copy: dependencies.R /opt
    - copy: predict_age_patched.py /opt/brainageR/predict_age.py

    - run:
        - Rscript /opt/dependencies.R
        - chmod a+x /opt/brainageR/brainager_segment.py
        - chmod a+x /opt/brainageR/predict_age.py

    - environment:
        LD_LIBRARY_PATH: /opt/mcr/v93/runtime/glnxa64:/opt/mcr/v93/bin/glnxa64:/opt/mcr/v93/sys/os/glnxa64:/opt/mcr/v93/sys/opengl/lib/glnxa64:/opt/mcr/v93/extern/bin/glnxa64
        PATH: $PATH:/opt/brainageR

deploy:
  bins:
    - spm12
    - brainager_segment.py
    - predict_age.py

readme: |-
  ----------------------------------
  ## brainager/{{ context.version }} ##
  Software for generating a brain-predicted age value from a raw T1-weighted MRI scan. This uses a Gaussian Processes regression, implemented in R, using the kernlab package.
  

  Example:
  ```
      mkdir -p ~/brainager_test
      cp /opt/brainageR/chris_t1.nii.gz ~/brainager_test
      cd ~/brainager_test
      brainager_segment.py chris_t1.nii.gz 
      predict_age.py --subjname chris_t1 ./chris_t1
  ```

  To run container outside of this environment: ml brainager/{{ context.version }}

  ----------------------------------

categories:
  - "structural imaging"
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAV8klEQVR4nOVbCXRdVbn+9j7n3Dlzk6ZTOmObNFCGKFMtFrDIe4oVUkARBAV8qO8tdRVQLEkYpAx1yfT0PVTGPnkNb4HKJCBtQUsL9jG0DZ0H2qZN2yQ3w53OsPdb/z7n3twk96ZJW+Qt3a6s4rlnD98////+D/APPtgnsamkfeXgkzD1098ZASTAmuvB66vnMtRUSGxslqwJIue7DeBoqWeoPui+W98s2GBS/f8ngKR1l9dztcHCZmfQ7w3gXaNrizrbuAJXEhCs2xdOVv1wTSLXuysxl5/TuMr5OIjBjudiUoKhuZ5ng97XcGqIB+1ZQoozhJSzOVBlOqg0OBtjCVcQdM7hCNmja9jmOLILDOsk42t4wHm36octHZn1l9drQ0nQJ0kAJpf3Ad9y/zR/YTI43xH4spQ4lzFUhX0cQgJCStgCsByiljuIrRoHfBoDYww6B5KWRMoW7bqGPzPgd3EHL069ZUNbhhDHST3YsS6wvB7awmYo4NvvnDU6wNm/MIZLfRqbwTlDwhQwbZIN6bC0lBDKPvzuQRgkDe9UpEXc4IwHDCIIQ8wUbVLKPwjJ76+65YMNaULkUrG/GQFWNMzVP9e0yt7QUO0rDmg3MsjvhX1aRcISSFhCcEaiysgW8JGdyvUHksglJQkOfBrXwn6OuClMAMt6Hb74Uz95f58ynI2QRysN7GgmKS42gpEu7rijZr5f40tDPl4TSwlYQtgEmmVAu/4tPTH/SbgrGEJACst7pAFcV/OkEJ4UMb0oqCFliYOmI++oumXDg/Tu8uXQFi50JfFjJYBsAE8bod131jT6da2BFolbjg3JNMa8NYnxxEnHIiaS3AOa4T5Txi+LGFyDNOOQVhLcHwEPlajHItULkYiq37m/wJ2j9EQ6Oud6YYCjNyWW7+2ybvjMkk3tR6MSbGTgGzhrahIf3FVbMgr4bdjP53fGHeINOPM4TgDBIFI9inNaZBSY5gOkgNN7GNKxwAMRgGkuZ+l/yW74x81G5KSL4J9YB6N0ogJL76f2vofYhheR2LoS0P1gREQp3KlMOsVBXU9aYmtXSnxtRsPGd2TDXJ01rbKPOwFkFvhS4I+Ffl7XHrMtxpjRtxpXAOGYCE4/BwWnXArf2Fng/jCksGEd3IrYhufR+/5zkHYK3AiAOSkUzP1XFJ19PRiJe54R2/gi2l9ohEh0gfmCgHAZLaS0I35Nd4Ts7EqJ+SMlAhuJ2KfBhwxe15UYAN4TYy1UilEL7kVw2py861mHtqH9Dz9G1+Y/o/jL92H0GV9VHJfCAVM2M8tBpu0G12Du34gDT3xDSRfT/UoSPCI4QYMMBvqIMEx1YEcE77mrD++aUVrIjJfCPl7XGbdtzpjej/M26W8hKq98DL4xNRkOuU4gs5orvlwHS0Xx+MNL8fJ2Db+5dxGCoZDCSoYw5zmERY7RJcJjV0A4JhipkWdLhJQiaHDarLM74VzwqaaWt9NSOxQ+fiQCqMiOQYaF9nRhgNdF47bVDzw5bWGD+yIZ8PT/iWPqjwBl/riy6sK2AH8x+KQ56DzwkWvps3lBlEj/ZWhsAMJS65d8/mbIZC+g8HpAGOMJSzicsZKwn/+BYhI0NUnlJo+WACtIlxY2O9ubahqLQ/p57b0DxN5zVTLRjaKzr3XBO8SpNH2ygWRZfSIEPbPi0HRvOZIMkhoS62yi0cg819V/R06+GP4JsyHNWD8J44xpMdOxgz5eoUn5pNqyZmgp5/l+IB2iIGf77bXnRQLardG44wwETwcUdhLGqMkoOOUydUjlu+mwSgWygbCs50rWwcm9UcSgwHFwTVf/CjMOkYopN+iekiTJPapyqVxHZPbFym26NiMLEGN6d9KxS0P6+Ttvn3UrWwhHhc55hp4/0GmWFOFpkA/TaR0pGelCf/waRCqK8BnXgIeK+7ivQLsLCeISvav5wHSfSxPym1Jg09YdmDJ5IoLBIMz2XUhuXYn41pUwWze43gSAMWoqglPPQmjGefCPOynjBgNVdeC+AlfdBgFgWjThiICBW3bcVvs0W9i8WcoGzthge6Dn1fumZmf7bWxRcUg7oTMxwOil9yFXzDj8409WnFWHA5DcuQa963+P1EfrYHftd7kdKIB//GyEZ16AYPUFSu87uuPQpYXkmz9H66sPQiY6oBWMhn9sLZgvpICa+1vQsf1NdP5pKcK1X0TZBT+BXjIBesk4aAXlsHvbvDgjy14wMEdIEfJpRsoSDwCYj8amnFBZTu4zYHPDCWVBn2+zxliJytzSEV7WVBJHznWMufYZGOXTYLZtRucrdyG28SUlskbFdBijpqhFnd5DCoxIdsFfVYeyL9yCnz27Hqfs+yVqg/uBqjNRfOY1CE4+E1rh6MwuItmtgqHut59E7P3nFPjKq55U9ubA419HYsdqN0qUOT2eE/Zxrddy5k2+ZeOKXK5RHzSlca7GsMreYfi+UxzUSjvits1ycF+Rg7juL1TgE9vfxMH//i6cnoMomvNtRE6+BL6KE1x/rSgrYHXsQrzlFURXPoADy65DfbASkQqB4Jw7UHLWtZ43SHPClVYeKERw2mfVX/zkehx67kbsf/RyjL3uOfBgcZ+7zTEoaFZ5lWCLyaZTLSEXjEHc37P09IAT79kQMPjkpC0k6+/M3UG+0bGgF1Zi1EVL0LbsW8oAVlz+HwhM+kzWop7aZS1hR/eibdm1sFvfQ2zqAlRf8++uYaQcIZ1DZB0qswYFQwdasO+hC9QepFaJbW+A+cJ97wwe0tDg2MyZPfHmDzcOtAV8kO7TUoneeQUBbUrClrnBp6fapuLa4ecXQ1oJVH5jmTqYMmDqQCqt7wNPBks4kLYJp6cNerAIkYNrYR3a7nrJbNeXReh0TCEdE77KapR8/iYkd76lbE3e46XRQzoUKkuLX60eNK7sN4HnmVevcSYpxMn5K0V+Vhz6qCkITj0byR2rUTzv+14cYLrGsF9Im5mogERXPQi7qxVvpmphdh9CzztPeTWAoVN6FQxJgcK6K6AXj4e/6jQEJn3aTbxUVJiLAoxTUQbAP1OlCk2rnJwEkKQuC5ud/feeGJZSnp8wBSN3kmdVZQDLF9yL8Mz5iNRepPyyWmSIhCbNXa24CiWnXoz3jDOwJ+6HvflFOGbc5fSQNQM3muTBIoz51nIVeVbUPwi9aBykkxosPe4UnrCk9Bt8Ou8J1CoyywaeQwIa1GwzJWb6DT46RY5/kOWn/XWIeBcKT71MubXA5NNRefUyZQsy4W5eAFwZptJzv4/wxQ9jx+5W7J16NUouebjPAObJBfoPCb2kSv1LtYPS8xdBpuL592YqWSIlOnugGvDMS95DBzgz5FOsyGFeXcNHHCg881ue4XL1ekR3GlLATibQ0x0Fxp0GY8Jpbpg77OFFj3R8KRCqvgD+8Sep6DEnESTFXlQ+YG6K2rIqc1ieecl7yKSsUxWOXNtyrsLTyIlfhFE2SZWvFOdUJjqC2opX/tI0TeUDIyagt4YrLUIFQoVnXK2qTzkliDFm2mr9WR8tPT2IZlWcVi/2EaDaPQEDG6fwD6ja0lCGGkDwhHPdF9hIuC77khq1swGbzAwZtuz8Ib87yzNcCMEpZ0MLl7keaCARJBiV4qWUoy3L8mVfwfGsIqck6khgNL08KDFXft9WwYeK7hQphlHsTftxz52pZIkeJ6II6w502014OGWF6aQn2/cPiwBkC4qgl05QLjaXNDoS0qczHzeTY9WDRtfm6dn4PlraHQT4BAp9lQQMXEc6YIFiVefzZh0BfLoqzlSESL47tulV2NF9yvcvrWHA9tXY+9BvYBSPV1Wk4PS5MMome3ru5HdvmYN7HNR80CLlfVlo9itM2QDh9/FgUorxVN9BTUt/AqjzmhpZCuvI2jwM0ffAO7HDiK64H73vPQu7a58yoEbxBBjjT8aHm7agvGI0KjQT8W1vovf9Z9XvoRM+h5J5P1D1xD4iDmcMfS5VvOXSTTO9oWMkg8TESilr65ap853DPXRy1xoc+p8fwGzdqDhbcv4iBKd+FnrJeFjcwJJLb8CVn/4Kvr7gPJjRVlh7/oreD36H2IYXkNiyEmVfvAMFdZd7ktA/sCIrpq7UvFoDpcUynxcYYuj98CUdBp38UQ4ZUEGOARFrh314J3SVsZGeDhBRT2zjm1/Hgce/Br1oLCq/8SRCNReqGCJtSPfs2K0IWTvNVUmjeCx8xV9CuPZLSO5ai45X70bbb6+D3XNASUO2OrhlePeMQlBGyiGTMViHd7o1hzx3p+pKwhZ67kgQYLGQYzGwKCUEOVoYVO5PlE7uXuulwwNeUVVNDifeifbnF0MrqETlVU8pUMr4UR7gUAFDIpZIImVaMAw6MOFzMl6A8onKK59AuOaf0PnaUkUQ9x7BAV0z0vnWHurCf+1oU+BppPatV/cIbsFksCpQiGY70tKZFlUP6qvVS+4dPoFtAJt50+YeSOzw6W7AOFgIKP0No+fdZyDiUbcclfUa/U5bRVfer8R/1EV3wVc5U+UH6TwgLcp0cHUVlp7Psn6nYMsfQfklPwMzAuh47T61jy1JQBk+6OjFlW+04DtvbcKvN+9T/I6ufSyz/+BzQ+qcsaQl4sLStrlPm/oIoEZL+kpLRvNGo0R9PQC7fTd6/vdpL7TtCxjTLs4/9kQUz/uBezeganj9S4lHHMRF4agYP1xzIay2TUh27lV9BB909KB+xXrEHQHbtvFhApD73kViy+uqdpCnMKKkBkBPJJTMnQyBWlhcVXiHrqNzqYD6nYogwUJ0/eVXyp2p5CezqbtLZPZXVKLEKU8fmN8PdyhJkSi78FZUfu81BErGKM7Xr9iAmC3QY1q4oWYi7ps9DodevmtQcXTgqf1KqllL+U2be9RFj4ePZ96hnhy1r1ibtDxlzr2YawzjURx65t9UySqtn5mhdDk3J4YdO6YryZFy+AtHY33UVJwn8L2Whes+NRZ3nzYNh19oQHzX20pl8gZPDFJT99Vyjftgbo5kqL5ZzeYB9m7SdKLUnOB5mhwoKCAqQHL3X9H21Dchkl4+nq7QKl3u7x2y3ZZD1WJv5RymJjPI4NEqJPaXvP6+C940cd2M8bin7gQceqEBXat/DT00dGmMmGlSXVPKVdnM7kcAZY8awCf8sKVTAm8FDTZ0PCpsaOFSJHe/jbZl31QW2L3LF4OmEWCSOeJpr2UrIoSoD4YMoWc3coFPGzwl9paN3lQS18+aintOm4ZDz9+K7tW/hhEpdy9U8gyiu09jPJES+x0juC6b2TQGiPlcVRKTTDZr2pFTHZUah0qR/GgdWh/5iqrPZUpgdB3ucZcAv9veg4UrNuDsF9bhF9sP4pX1WzEqGED1pHFKMrI7BvqDX4+YaSEmOb59Si3unizQ+uhX0bPmcQ/8ES6BmaTKMEnca1NvXtelKsNZ9o31A0QJHoPccufscj/sFo2xstwl8QGDSg1WCnBSCJ+0AEVzboBePlVRlzrBHmzZiwc27sbhlAWdcWgah8+xMbHzIH5+yXk4fWw6t6D3JQyeDd5EXI/gmjEalrDV2LvyF+rmSA/QpciReyEoBw0ZnCVM+7xJi1teH1gaZ4MmeC/suG3Wr0rD2jfpUoTaUoZrtKxkDwL+EMqnfgZ/PnURfrojhXWHohC+MD5dFkaRJrH6QAcE5/D7DNjxOM4ZW4qrpo/DOWOK4ecc73X04rIV65W+J/zFuCz6J9zR1YxoeysQKIBGEWUeI9sPi1SXIyxmik2T7bITkaPXUB80q75auYBdGu6Lm+IKzpjh2a8hpSBt1Ep9BtpYAPcerkDzmj3o9ZegxOC4VN+Cm6bXoKxiEt6IjsFda7fhnWgcrLAYL7V245W9h3HyqCIsmFSBRzbvQ3cqhVSgFJd2vIym1v9EFwywcCkYRZPDAK8IAJUC86Qp7qaGCVlDd4T9L0ZYzomeFGy/reaxsrB+1ZGkwGYaQiIJn7Dw++I5eKD8MuwKjFc6VRffiBsPPIFTE1vQwwKQvjDKKqqwv8vBhq5erBx3LlZETsE+owLCTIDbCYQNHT1GES7veBm37X8EMR6g4i7YCIolxP2gT2NJy9liFqROmt6xzcrVTcZyTvZaz3bdWz3asLQWcBRZtiT7kPP9QieGLf4q/LJ8AV4sPAspZqDSbscVHS/jqvYX4ZcmengQGpWvhAPbNmFoDCGNgzsWWo1yPFM8D68WnY4d/vFUvEB99DU07v8V4gRelSZGVjKj27iCANe6k878KYs3vpKvY4TlXSAtBbdXf6c8bDzUHstzRQbgd0WfxUPll6BNL4MOB+f0rMOig09hZnI3oloEAhw8k6G5lx+q6ka6RZerwkRYJNGhFeAvkRNRbkdRm9gOh67KwUcMnvqGSsO63tFrN0+5dePCodpl2HAaIXfePuuZkpB2Md0Tpm+JHRILJ4aHyy/GHZVXI+IkMNE6gG8ffhYXRckdQomuPhxjRV1ljEOXtiIErU2cdw84YvDUKsMcBzuF6dRNQEt0qEZKNuTBvMLoR0tqizUp1/l0Prk36TicMyodqQN36EW4fsLNmJLahx+3PY5x1iF0ahE1n49UbFU8QBynuSPvhxaU9Wle5peyz5jS8OFaLwbLuxgfakFFtcYGNvFH6zuTKSykVrSgj2tEZQJnMx0Vdid+uWcJ7ml9CKVOF9r1QgV8pODVfqq8Io4ePFc+n8eSzvUKvBv0iGNvk1vu6tCmppq6Ij//I7X4U0OSxphGPaCGtGExt9pzNMCPdWTA+8jo2ddNWdzyyHB7BflwNiDwtCD131EfHrWihXwaSYJNQkLg6d9PAryU0qFW+6MBT2PYFUQVSGQRQUq5vzCo61JK+4jXuh/ToL0DBtcCOnOOBvzRNUt76tDy4xljCiP6owUBbX407qhuTeZ2Ln7sw/vuAqUhjcdNsTVuiqunNWz8y0jBH3W7fPZHEtQxbmj8Rz6N+XpS1OtOt8o5mwOOE3ApSf1I7C1bPB3tsr9bfZSd4jiWQzY0gDd6/nXbnTNmBZl+j6HzL1BORN8NSMgB3w0c3VCxEpOOkEwL+Tjza4xa8zcwxm4ce/P6l+id5fX12sLmo/tyhB3L4dQBsyi/b8ms85lki4SU8yJ+TaMvR1R5jUkH2Z/KuG2EuTrUFEHVJwHeZzNUzAj5OH12Qx9WfSAg748mxVOzmlrMY/1aBMdLTAce5MA9s050HHxdSlzIOasOGVzF96Yt1AdTpMCOAH30lBlEEI16XRlAZXkqzFIZy7TFXl1jr0LK376xbubraU5nq+GxDIbjOOhQ9csVMJmWjsO7t55iWs5ZEnKOlJgJyEpboLAgQG7UOwRzvxKDRKeQspcBH0op3+K69kaAp96hSm56D9X2urBZHK+vTBk+hpH+2JHyiH7P6fCxLQW79thjisN6ZbTX/TkS0NGdtHunFOpbW6O6Oa5pXXzQvGbqYjt+wP8mQwKMpILc01ANywNH9px0PvJ38fG0TCd3jWCoqe+3d3NzM0h9PqmPqPGPOv4PDFkPIEAvH7UAAAAASUVORK5CYII=

files:
  - name: spm12_r7219_Linux_R2017b_zip
    url: https://www.fil.ion.ucl.ac.uk/spm/download/restricted/bids/spm12_r7219_Linux_R2017b.zip

  - name: brainager_neurodesk_zip
    url: https://object-store.rc.nectar.org.au/v1/AUTH_dead991e1fa847e3afcca2d3a7041f5d/build/brainager_neurodesk.zip
