name: amico
version: 2.1.0
architectures:
  - x86_64
  - aarch64
structured_readme:
  description: >-
    Accelerated Microstructure Imaging via Convex Optimization (AMICO) from
    diffusion MRI data
  example: |-
    python
    import amico
  documentation: https://github.com/daducci/AMICO/wiki
  citation: >-
    Accelerated Microstructure Imaging via Convex Optimization (AMICO) from
    diffusion MRI data

    Alessandro Daducci, Erick Canales-Rodriguez, Hui Zhang, Tim Dyrby, Daniel C
    Alexander, Jean-Philippe Thiran

    Neuroimage 105 (2015): 32-44.
    https://doi.org/10.1016/j.neuroimage.2014.10.026


    Orientationally invariant indices of axon diameter and density from
    diffusion MRI

    Daniel C Alexander, Penny L Hubbard, Matt G Hall, Elizabeth A Moore, Maurice
    Ptito, Geoff J M Parker, Tim B Dyrby

    Neuroimage 52.4 (2010): 1374-1389.
    https://doi.org/10.1016/j.neuroimage.2010.05.043


    NODDI: practical in vivo neurite orientation dispersion and density imaging
    of the human brain

    Hui Zhang, Torben Schneider, Claudia A Wheeler-Kingshott, Daniel C Alexander

    Neuroimage 61.4 (2012): 1000-1016.
    https://doi.org/10.1016/j.neuroimage.2012.03.072


    SANDI: A compartment-based model for non-invasive apparent soma and neurite
    imaging by diffusion MRI

    Marco Palombo, Andrada Ianus, Michele Guerreri, Daniel Nunes, Daniel C.
    Alexander, Noam Shemesh, Hui Zhang

    Neuroimage 215 (2020): 116835.
    https://doi.org/10.1016/j.neuroimage.2020.116835
build:
  kind: neurodocker
  base-image: ubuntu:24.04
  pkg-manager: apt
  directives:
    - template:
        name: miniconda
        version: latest
        install_path: /opt/miniconda
        env_name: amico
        env_exists: "false"
        pip_install: dmri-amico
    - environment:
        PATH: /opt/miniconda/envs/amico/bin:/opt/miniconda/bin:$PATH
    - deploy:
        path: []
        bins:
          - python
categories:
  - diffusion imaging
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAWZklEQVR4nOVbCXTWxbX/zcx//b4sBGRTxI1aCFStLFbEilSLuKI1LNbq8/W89rW2fU9rW+05bZL3fLXVLs9up31aq221mNSqAQQKAu4iWBckbGoQRUhISPKt/3XmnTtfPgghhLDac3pzvpP8/5lvZu6de39z7507wD85sY9qXAXVy0SYOuYTwVEnxaqq6nlly2A2dshOta6yStXWMtlby+pqxRsb6xm1bRyyU9XVV0l2lIXCjk63itVV1XP6a1b9rLg3Rp3Nz5d72VaFAYAfHsf8UHg/q5+c760tVq7kNc9MjY+GMNiR7ExBsfoq8Fn1bDfT1V9akwjTreMU1LkAO4sxjIzjcJgQxnAZF5oxxqEg04yLt1UsO8HZq0ziZUvy12rrL9lV7Kuuqk6sq1ynamtre9Wgj1IArK6qjhdX++tff8ou32VMlyqeCYXPMMZGWoZLAoJUMaQsfHaPrgpCEMIAAwfnHFEUIJZhG4N4HoI9KSP+1F3zLmqm5lVVdeJImQc73A5oMvVdjN8x58mhnDlfAcNsQ5ijiakw8ogRpQDdhoExpcAYU7tnT5NQiinGQO30ExS44AY3DRuMCYRRnpifLyN27111098qakRvJnbMBFB9wQqj9pkLo6qqOut0s/TbCuzrluEOiWIfYeRLMEgoxhkt6yGQ0vIgwFQQzBCW6SKIvABQD+fD6Hs/q79iG2FETS3UoWoDO8SJsZpqMELzb8+dP91g1k8swx4bRHnEcRQBh850H2MSgwSEhmOVIIrClliGd94179Jf9NTEoyqA6upqXgShO+YurBHcqqZOgtiLAAhScRxdUkqpWHDDsM0Egihf15Fr/uqvnrix7VBMgh1MY1I3WvXbr1tQIWD82TLc6bkgLWlxGBn8MSStEQqxa5caYRxu9sLU539S97nVRbM84gKo3s38wxVcDVpiW4mJOa8zZIyZ+AhJKhk5ZsKQSrbnw/T0gxUC77/a72HeMp1/COaJOOOGH+ZjQFU4ZumSb856bGIXMIsjogGKAFYBd9zw+EAeJRYR83k/FTHGDfwDkVRSWobNFVh7GGQuubv+mleKWntYGlBfBU6bNkJrnm0lJ+b9dHgsmFdsz6c/xBnnYRzQLlFhGO588klqa6GqUd0nj7yvf1ZXrzDIrf3O7CdrXLvsopzXcdTVnhimHd0KFKxQ6d/9FQIDE2GUj0zDGaKU+CO9a6wa2+e32f7+UdxXb79uwUUmt/8WRgE5JP2yq0MlyQE7UMjbHKvPcuE5HKOafJy6NUBosN3CORAppaKEU25k8x01d9ddWdvX9sj20wWrrgZDY73hCXetJZzTg8iTxa2OJkGTPZKxGfXnego7Bwk8e04SLccZMGIg5sDYTT4+9WoO5EOTILg68BZJrQQ3YsbkJ+58eMbG/eEB762DuiroxnnufMu1y4j5qPs+71vsoFSzz8l22bmbV3j7ZAtPXViGXRUCpfkYThgj6cdo/JiNRdNKkS4RcHylhdUX6XgDUglhmmEY/bzvtj2I2KKXt86dP8hSYiNnvCJW5N0y5ngKW0408dynkjh3TQ6jtgTw7MOIyTggYoDHCn8f5+Lvn3BhSYk4FsjCAgXJ1HU5PPgmg+0rTKZxmwrj0uwPMHZsGa4IZX7aXY9cvqI3d5n3/EZN9UpB3VoKN7t26cBYRjExb0QKzYMNPH9OEr7NsOK8ErxR6cAMlZ5Ev4GKggRRmDz3JHIcePq8Erz2yQRKYols5CDBffxv2Tw8VH4/rnTeQAoOjJBBmsDy80qw5kwXZqy08A44LmOQsfwe/VlZWbWPuFjPZ6UUbp31kmPzXW8ZhnVKGAeKgnQSAKnh1hNMJDIMhoiQsQ2M3eTpVaGJkL32tSLEuJ+PEAYSCUdADnfxwoQE3i1n8Dt9eMLBRHcnflI6D2ebW+ArEyaL8EDufHw/PVP3kWQ+MpaBk7aFmPJKFsmc1NqxX1xQUFwYMZfqrDvnzVjXEwuM7m2rqupoz4+/O2fBNMNMnOr7GckoO6FBj2HyqzkoJOENCdESlGOAl8f6UTY6ygQuei4D25cILAbeA2qK4VE2FeCk0ytw9gUjMGrMIJSMLEEkGDrTHl7elcG6bY34cv5eDBUemmUFeFfS5Cb3eYw2tuO21GxsiobiOD+D94830XBxGS58KYPjd0QFk+glraqgYttMGHkvdROA24CVpPWyVw2oq1Ni1iza9xc86NolN+T9dEzarxtyiSCVwKmVmzDjsoX477aZeMwfj0Esq1egLC0x9aUshrVEyLl7hEDMSwlEYYzpc0Zj2jWjIMT+UCxE1PwsOjb8HLZqBTctnRvJ+C4G8Dx2ySS+m74Gj3njcRzLIBLEIMPEN/IYt8HTwuy5O9HamcLiYeRvzHWKM3+xeEZAqNU9GdMN/Jj65vVLkkYYbDKEdXwkA0o0FBzB0MSwoc247vJ6lDkZCKnwX9krcF/u00ioANJSMH2GyWuye8Cxa4DAizHra2dh0rSROqpXkqLHLunQLkDv9A+jeBpxeiMaft2AHTuSGH/GWxg7qhH50IGlYtg8xE+zn8W92YtgQMJmIXKW0GOSKTqkhWYPYFZKCWErJcNzfjDvsjXdzYAX21CCg37bUTTGMOyhcVxgvls3mH7e0zhuYBtysY20cvGD0r/iR6V/QUBKEggoU2qQerMLHAVjyGZCzPj8GM18HFGSqIAFjBd618+MEgkMBgkjjmGUfhwfv+gr2PDOqZg3/1osWDEDlgihDIlU7OL2kqfw0IDfYRDPIKUclPqR3kIXXViKtgoBM9p7i6Z0nGnYXEJOKbzRZqCpmy4WXkrEky3DFsUcXqEHBiFiPPXMZ7HxnVFQMYdjeWiOynGD+xLqKn6DhPA1giejCC9MSOLFc5IIcxFOPW0Aps4cBRnrJN8Bwy8uBChbPHZ8CaZePgyQHVi9dgIefOzz6EwNQImbQ0tUjmnWBjQM/Dk+ZTahRZUi6cXoGMDRcHE5dgwx9xJCQYcVlMT59NzYuFPtI4CxY6fql1KxiVJbyJ6Z0hPnEs2tQzBv4bW4r+5GvLWxEmWJNNpkEhPNJjxZ8Uucab2PZlmGMi/ExtMdPDElgdFXngwhutzY/jpOlCZXwKTPnAKLOXDtHLZ+OAK/q7sBazeOxYBECu0ygYEsh0cqfoubk8uRgouACQzpCDCgI0ZMWtbFJiUW4zggbsfdUvWiW19fJYvi4cUx160rnFUx4ASlJE12r+mSc2lbvnZSOlLl+MvimXh+zWQkLQ9p5WAkb8MfB9yPzzmvYidKYeVjpE5yMHT84C6m+sm85r8w+OCRLqxPpBDmBFw7gBeaqH/qaix7cSoSpoeYMwTSxJ0lj+NXFX/EsEweE5+LkQhiyL1nz3QaXmGohQ+s7jDJCxJSrKYG6paqOhfAUGqsiOMeVHxliRi27WHB8kvQ8PQM2CJEnplwVITflv8BNydWoF1ZGCwsjHKswkAHkSqklpIAzjSRn7IRm8Y8Qz4dLDCYdh7LXrgQDzfMRj7v6kVpicpwtft3PFbyG4xytyOrbO1Fdu9PKXKNDUvxxPH0rqa6Zm8NIDMpQ5nLwE6UMtQO9f4mGBoBeGAjmUxj9Ztna/uMQwPcitAeJ/E/pY9pcAyZQMQOJ4BksAMHO05aj/WTFiHvZGAELhLJNDY1nYb7Hr0RW7ediPJkGu1BKQYPasUX5z6Ik0/YiiC0dERQ5E4qqQxhu4KxEfSmsbEQJvPuw/mEHExp7nuSYhJGYCM1cAfWTmlA2/AmCD+BhJvDlg9H4P66G7G9eZjGheZoAG5KvIT/S/4aeT9d7OEgWWfwVYT34xTcMIF0xQ40nrsQrcPfhfCScJ08MvkE/vD4XG2KrpWHaYR6Di1tg7Wn2tNPJtPmglZ3D/Heht6XefK7TaQrWtA07gVEpoe3z1qJD099EwhtJCwfbZ0D8Kcn5uDNDeO0EDpUGc6UazEovapwvKH6f5ynMYjMYHszhq3ZgDhpgUUWFA+x+ayVeP/0V/W4FlNgIsbCFdPx1yVXYcfOoWh4+jJk8wkN2r2LfO9kFu/+4IcGxQJGryJRDFtHr0a+pBM8smGEJprGvoSmcS9CxiZcI4IfCdQtvAbPrzkXrukh4Bby21do9O8FUvZPsT4sROfy5bhh0RZctyaFiEuE3IAVGloAGycsRWD5MCITiWQGb26sxH2P/gvaU+UaF3objwKxWMXGfgSgmOF7IQPrKIT+3XwpRS5mjJMbz0FFy0jYsY+8xeB4LlpO3ID1kxYj5DEsJWA5eQ2O85+eDst2wTuXI/X+ajDO9f5+ICJHiBkCfnMzPnz0z/AGluHTjSn8x7JWHJcJkXE4HM9Bx+APsO7cBUhVNEN4Cdi2r81M0I7fK/O0FUYhF6yje2TICyvMFGWA7mmYmZYK7wphag917w5iiOwJOH/VqfjO4m0YvyWPtMtgBjYyFTuw7tyFyJS1wfQTSJaksOqN8Xik4VqseOVi/PT7O/FBU7t2cuJYUgZ3X/Wkc44oAhMCUTaHLTXfBe/cCWZYyFgcpzX7uHVJCyY05dCZoHEtxKaHDROXaFMkUGaKQ/YSjpJIODPIF8hlefA2vaPzRHTXAKrM6JJUR88NgPLiESwMwruYnFqEsqzATc+34rNvpeBZ0CYRuClsmLAUO49/R4NUIpHD2++dhGdWT0M6HeGB6lex+Y1WHQhxxgsjUJREn+ISGQby2z7Ee7d9FTvWbUVzxZmwwwzILc1ZHHYo8a/PteHK1zrhW+SqCgjJsaVyFTZ/cgWkiLRJ7Dl37r6AmtW0JfbULuwlgMrKwV1cq9WcC30Ah+7EGMZnlqEsbkPesHQEOPuVDsxd1Y7IkFCSJBHqiegVCS1YRgzLSaOEJ9HKW3DLkmrc8+xvsH77JnSCPDOuP6T2+S1b8OEfHkLTl6/HO5tSWHHizVianI11ickwlAdTxYiE0OOSAP59eStK/Rh5k0zRQevx72D9pCXIlu6C6CEEBiaFsCAVGu95YGaagqGin2gUGxX9Y26oVWHsa++3+D+dEVERXim5BDwTYViwBXlegk4HOH9jBkM7I9x/wSCdqHADrsExn+zUmGEEJWg5YTO2jHtZq2zDG0tR/86zuHZnKa7ZWaI9trC9Hf57W8DTrdg8aCrWDL8ciGNY8PFKcgZ2GiNwTvYp2DKHgDlIu8C4bXnctjjE76cMxMbhDkrzLvIl7doUR6+5GKW7hiE2QjA611FKUVqDAy8XONqTEzCKTBYqLgAvsF6zedAhuEG5wN0RIYdEuxiCFaVz9GRO8dciQAIZW2BUi4dbF7fgoSkD8fYQG+U5Fy0nrUfgZlDSPhQffOw1GJQuimxYZQ6uer0Tn3ntA3TEISQ4DCHBLRtrRlyPDdYEmHFemx0J3lZZNNnj0G4MxXnpJzA02gpPJpG1GEq9GF9b1oqGT5Zh+ZhycKZQ0VYBN10BJSLNfBfxOA6hOH+m+2IT7WXsXXGy+s7shgW2VTojCLMkpd2uHNU7xBSFMwMTsn/DmPzLiJmJiHO4gUTW5nh0UgVWn5JAia8Qiwgxuc2+hbzFtY8+Z1U7Jr2bQ9YRlKuCJT1keSmeS16NHebJsFVeM96dSPgBs2GqQI97uvcqQmYjZgJcSSR8hVdOc/DXM0/AyNcvQ3naQWgWBEAAKLhJO8B2SHvMj+ov7izmPrCvI6RVQwG8nnOu84PdSYFDIIapfKwquRQvl1yuhWKSDZsCdiTxxefacPG6FDyTajsMuJ6NtMtxQnuAbyzdiYnv5pByCWMo95BBsxiBRWU3ocUcCVtRym3fLYy0hJin3y+UXKU/9LclfUjG9dY4sSmDWxZ3YHg6C697jlAhpsoSKLWMmKesV/d0Ce8+UE3tVI2QPMEXen6mlWp0uiozugmBpMrgyAw2OhOwtOwL2uGxpYeQCz34nFUdmPtyO2Ku0J5gesW/sWwnRrSHSLmGzibRSm9wJmJp+RfgsSRM5WkB749oTBI2CYnGXVZ+PdJiIBxJByYMWcvGgKgFl6Tux7BwK0JGoVNhkSNK7HL+ID3U19fv1S/rOVBVnRL1lBec1XC/65Z/Me/RSXAhL9iTaEIhc1AW78J56ccxNHxPgyPFDaWexNoRLpqGWLjsjZTO3wVcwCwEWlidvEQLwFLebnvvLxVMwtGgWMQjnyVhIECrOB4ryuYgoiNMJaVpOCwMvQ1Oc8kZNSunUo5zrwXlPTuv1HkBxbjAj8PQ8xm5cPuJZGjFaOVSogLLy+biXecMOCoLoRgyjsDoHR6ueK0TnsG0djjSg8eTWmuIedKC4uoeDBVMwtOr/Gxpld4pLJVHABsvlM6Ez10tJOraECa5AD+imoH6Wfvyy3oboHiC8q1ZDQ8mnfIbC/UAvWtBX+BIIKXr3cjeVV6D3HOl1yDHyw6o8v2hLhXXJnSa/7rur8kZpzVDKqZXP4r8TdlOfubAc1aFtbW19IW+NYCosn4dbZ1Mufz2IMi1C27ugwUHBEclYcoApoy77H1Sv+29v7Qbj1QGW+xx2GqPhi1pF9GepuL6CEp+4xeLL/W74v8DngztowXfmdNwc8Ie8Muc19GvqhDSBp8lMCzcgknZRRqkXk9cgM3OBM34wdr7wWqDFoqSkWuXGzm/s/7uR6+c1VcJHTtQgURt7YXR7bPn/8Wxyz6X8zsjqsk58GQIHAv7tlAR8jwJS/lHhfGepJSSpmEzqeKmfMgmllVO7+irkJL31Rltizo3KNi/+WGuiY6YqEbvgJPo2reJYQKqY8i84l24I6V/3c+6Cq37Or/mfXVIX6ypAfvhI5e3R8qfpZRsN4UlqCDpgJMpXoE4Siq/z3ja3xfSNB0eBvkv/3DezFV1VUocdpFUbS2TVGJyz7yZa6gOTzHWXqjGOrAmHCvazbzhCC/Mfunu+pn3Ua1g97L9/RHvzwBUX0MdUhGiF6anA6zdFI4gsMFHTHSCRfmF3czPu+I+jV1HslCSiDosCoE0AUptd6xSwgRKvx7zuz5EtABkkkJY8V7M1x6FUtkiFbeU/7z6seGum/y9YySm54OUPoenMjUcAyKkJ4kn7DIext5mP/Ru+nHdVS8cbJ0wETvsSxJzF9YwZtxhCNPygyydqVEUzg+17wMxTqhqClsQ2scynNeRy33tV09c00aA1x+b70nsUCdD9cM1NTWKgotvzpo/zhHG3VyYMyj1HITkjanocC5L9LwnQGG9abjMECbdQnlLgX37B49MX3Q4dwVwJFapexHiHdcvvphL9i0FNc2m6iy6OVJIr1Gti/ZbCwpSyL/u21vBAy9cnSlcmzGEyU3DQUQZHSXfVEzdawapP9XWzwoO97YIjpSadtcGer7jhmVnsDD+AiAvZZxXmsLRpz2xDPVlKfq7py9BZ/icCV2OSKtMKh7JEHEcfsAZX8q4+PMGf9fy4kofzqrvNS6OIPW8zUV2udZadnaM+DxInK8gxzDFhsWIy2wzQdtoYRKM6VtiSql2BZlhwHqp2EsGM54NEsnV9zwwJd1D4+iLR2TnYTgKRBqBlVN5T0QmgWxLvF663ds23LZLhnleRmdlDcdB6OUytnviZrS9H9QuuDK39/fqBOVx6o8g40ViR7Kz3vqn0rviVdj+qixp0p7vVMmjeaeYHa2O9zceIRsVJxTP57tTMTX/UVyixj8r/T/EBoFCrt0AKQAAAABJRU5ErkJggg==

readme: >-
  ----------------------------------

  ## amico/2.1.0 ##


  Accelerated Microstructure Imaging via Convex Optimization (AMICO) from
  diffusion MRI data


  Example:

  \\\`\\\`\\\`

  python

  import amico

  \\\`\\\`\\\`


  More documentation can be found here: https://github.com/daducci/AMICO/wiki


  Citation:

  \\\`\\\`\\\`

  Accelerated Microstructure Imaging via Convex Optimization (AMICO) from
  diffusion MRI data

  Alessandro Daducci, Erick Canales-Rodriguez, Hui Zhang, Tim Dyrby, Daniel C
  Alexander, Jean-Philippe Thiran

  Neuroimage 105 (2015): 32-44. https://doi.org/10.1016/j.neuroimage.2014.10.026


  Orientationally invariant indices of axon diameter and density from diffusion
  MRI

  Daniel C Alexander, Penny L Hubbard, Matt G Hall, Elizabeth A Moore, Maurice
  Ptito, Geoff J M Parker, Tim B Dyrby

  Neuroimage 52.4 (2010): 1374-1389.
  https://doi.org/10.1016/j.neuroimage.2010.05.043


  NODDI: practical in vivo neurite orientation dispersion and density imaging of
  the human brain

  Hui Zhang, Torben Schneider, Claudia A Wheeler-Kingshott, Daniel C Alexander

  Neuroimage 61.4 (2012): 1000-1016.
  https://doi.org/10.1016/j.neuroimage.2012.03.072


  SANDI: A compartment-based model for non-invasive apparent soma and neurite
  imaging by diffusion MRI

  Marco Palombo, Andrada Ianus, Michele Guerreri, Daniel Nunes, Daniel C.
  Alexander, Noam Shemesh, Hui Zhang

  Neuroimage 215 (2020): 116835.
  https://doi.org/10.1016/j.neuroimage.2020.116835

  \\\`\\\`\\\`


  To run container outside of this environment: ml amico/2.1.0


  ----------------------------------
copyright:
  - name: AMICO software license agreement
    url: https://github.com/daducci/AMICO/blob/master/LICENSE
