name: topaz
version: 0.2.5

architectures:
  - x86_64
  - aarch64

build:
  kind: neurodocker

  base-image: ubuntu:22.04
  pkg-manager: apt

  directives:
    - environment:
        DEBIAN_FRONTEND: noninteractive

    - install:
        - wget
        - git
        - curl
        - ca-certificates
        - unzip

    - template:
        name: miniconda
        version: latest
        env_name: topaz
        env_exists: "false"
        conda_install: python=3.10

    - environment:
        PATH: /opt/miniconda-latest/envs/topaz/bin:$PATH

    - run:
        - |
          bash -lc "source activate topaz
          python -m pip install --no-cache-dir topaz-em==0.2.5
          "

deploy:
  bins:
    - topaz

readme: |
  ----------------------------------
  ## topaz/{{ context.version }} ##

  A pipeline for particle detection in cryo-electron microscopy images using convolutional neural networks trained from positive and unlabeled examples. Topaz also includes methods for micrograph and tomogram denoising using deep denoising models.

  Example:
  ```
  topaz --help
  ```

  More documentation can be found here: https://github.com/tbepler/topaz

  To run container outside of this environment: ml topaz/{{ context.version }}

  The packages included in this container:
  - topaz - {{ context.version }}
  - miniconda3 - 4.7.12.1
  - python - 3.6
  - cudatoolkit - 10.2

  Citation:
  ```
  Bepler, T., Morin, A., Rapp, M. et al. Positive-unlabeled convolutional neural networks for particle picking in cryo-electron micrographs. Nat Methods 16, 1153-1160 (2019).
  ```

  License: GPL-3.0

  ----------------------------------

categories:
  - cryo EM
  - machine learning
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAASZElEQVR4nOVbe3Bc1Xn/fefce/chS/JTtgW2sXn5iR2CMxhwwG9ehRRmTZoGJsxkmkB4GAhp+gcjqdOhJW0ChkDbZKbNJOngaCkJAwXCy5hgjLGNIdjCRsYQbPBD2JK90j7u45zOd+6uvCutpF3JDn/kszW7e/fuOd/7db4L/IUDfWH7an1id13AhPSfH5FTDpqQSIpLZ0+ghrYOnZyd0GghVfbWJi3QlqTee1sTCnRqmUKnZllNiURSAAkkkxT0+7pJi3m59+pF5oghTsUs6szJ7P4HL8qUu/dSvCo2NF8WnApm0EldTWtKJCGSq08Q/eWmrfHM8Z65RGIRNBaAMFUpfxKRmKxVYDAgktBapYSQe7QKjmlB2wD1Juno9rYHLzpaWCuR0DI5u1mjpaW8Bn2BDKBEq+4l/Kzbn4049phVhOBrgFoG0FThxAGtmFBABdDK77OCAEkbRMwRCR24UL57hEi8rkk8JTzx7I6HFx3iWxOJVnmyzINGugASrRLJ1YbwuXe8NFHbkVs06AYh7ZlEAsrPMTFaa5h7iCnUmsD/ep2fsRodukbNTlETIEhagqwoSAgEbuYQCE8rz1+76+ElO3o1opyJ/bkYcGnTemtDyxJ/dqLVoamTf6A1bpdOvEH5WSgvx2qqyIgWYng7MN+I1QZCWpK1SLkZF8D/uD25+9r/c/mnxnE2Qw9XG2iYeBGaQezN59z5yipYzo+FHZ2j3DRU4PsjI3rAPTlwBkRkyWgtm8dhrfx/avvJVx/pq4mnlgFNTaLghGbdtaFZSruJVwncrE+ADI34lAKzIhDSsoRTwxrRGuQO37rr0euOGN9QJROoqq1Z3VpIzbvlmTFBvP5xacdXBdnjRkXBBl/tzqy0uuhzcWJUkUbowIrVW8pz2+H1/O3Oh1dsKZhlNWhUT3ys/vcyUrPQz3R5BLJRDfCOHP0UoCWg879mV0Ze+L22KmSC4YPypVNjKRV0kpdeVS0TqBq17yXeji70c6nqiecNfSCoJfgNAn49QUc47AHkaohuDbtDwTqqoVmfRGWMMCZhRaQGeplQqTlQBcubcDXztpfGikj0OUN89rhPJFhOVQFLPTdVwp0iQimrouyfJZ8n2D6sEN0TGGaxlgzEhBB5DpwcP5USVlQwE5BLXd7208vfamrSomWgtDsPYkisWyE4xAjLXmfUniVfRHxoukOLidHIni2RmxFuyepuInjBD6j8NR/wJgmk51qheQyAviSFQBN8LSFIQQghlJ8LBNEYOPGnOSdpaeGVmwalUQz2JdsSVlMw686Xm2Wsbnlfmy9FwsihDOUhUUbypwlQroRz/e419+eAoJ6QOdcKNaSMnna5ccQsF6OdNFJeDJ4SEAIy8LK+sKMNSshfmR8m5gyq5TTQFwUbmrVm/XJpRV9QPic2RiF7IeVFMT6agiMCHMzUIyI92BQYlewFznxrCOkFVVoM7+YA0d0BnM9UqA15/gZa4OZz/oDrp29FVHp47eC5eOi9lTjmxmDLAErBt+KjraCnq7nt4aUtg/kDKr+7JjSBZiNpoWvCe8KOnBN4WUVFoW5QJESeCfzfA7JnhXZf8PIVAWfEFmAd04i/6xvWSygj+e/Nfhl//6WncSw7CkoTxkRTeH7ffNy28UZELS+fTwsNaQXSz817b+2y3QP5A1Fu70QCJuTpo2PvlbE6Jt4vEM9qz5Jn4hmJCdEUaqwcvnHWRvzjBU8axhTHc0acvf5AtjwgMPMCIIgTghi/1/C0NPsx05l4V1lQEDicHo3FE9vxpfGfIO1HIIgtR2khbdsHPczLtQywjSjDekomoc65e/14SPtu5fZoIhjVZxv3VKVImKLGqK6OGoyqzzuLfm/eazLaFZE+k1fid1gwMekajQhxJancdCCdmpVzbn9pCQuUTWFIBlza9Krk4GQp/T0rOmqsCnxOUXpR5y0rReKkQdguM/bNvub1g+dgTOy42Ycd8LhoD9qPT8T2I1MRt1zDqDz/zG+VEPfxW9ONGoIBxJ2XC+96I6Y13aT8LFdZoi/xFSORV+OqbL8P4eb3btg/5DXZ0T64YyWe/2SB2afOzqCtsxH3bbvOaB4LoSi1YC3QJJ3Fs9a8PIe1gH1B8RZW8YdEolUkiYLuNa8slZFRM1QupYiL8SLgtL+AxJhIDxZP+sBsWowEI2a0IO8EOcNjP2DifjWMEIDoAUS6KEmiwDja2zZ+05gba9z2I9OQ9p0T+5bgqwPLiVl+xrsZwPdfxau8Uq9HohIGtGrJXZ1Zd67/hRUddZOfTZnys79gQocUKDE4EvkcwB9LyMyzIIIqfCGHwQgQ+Ugh8lFQEgaNyRGQ9iJQIMStHKRxe2W5q8hyhPLd3V6Qmb/nkSvc4u6zKOIVMfHnffP3NSC9Qvk5Lmz7OY1eU6DAhJxtHWeYEMgJUT8JFELZUQ15SCFDiuvlIWk3ZYBDEN2A82nQrzgKU19CjZ1DrZ019w/id4T2c1pI5+yojM1j4ovNQBTeNJmqHlDjnVlCRidyG6vY+ZVjQqVIKALqP9E4y4mh0/NgEUGUWVoQzHdppZBKeYjv9gf1H7wf/w2ViHM7TtgRoTUu4c95MyhlQOFioPVFwo7IQg9vKBgKCSboeNbDX53XgGevXIBVjePQkfXQ7XEUyf/KhDgg4yscSOewYEIt7mk8Hd6RAChS/WEDEXH3QBEW88cNbR29K1qFNxvmXFaIGgtN57bSWnTQfQFPadTFbXxr+VTU2RbWLZmLdXsP4dd7D+LDVAY9Abf7ydA5PRbH1VPG45ZZp2OUJbF+cwf2Hkwj5gioEaDCroi7zKQxlyPcmw8uyppsF1QUEnaG1GrgNG5fg0YezCVLP+3juyumYUZDHL7SRtJfnzERzyyfjws6oqC3XTjveviPBefilSvOx73zpiEuhXGWf/2Vych5qqy5VAesppyeY6LXs98p4wQ1Nzn1hXe1xkA0kW+mQjYxTGCcs57CaWMjuOmyKYZwZgirPf9t+bALb7xzBGMyArnPXGzdftR87wZMethRXb2oEePrHLgBpyMj5YHSZFlONja60XxuajYrntAAIn0cdTECpmjFhfnIWuZMTMYNsOaqGRgdtwzR5syDAD/Q+NHv9hjnqCQQq7Hw1NuHcKTbgy25oQwESmNcrY2rzm9AT9YfoRYQacW1QSRG0jndXGoLy2RRgnTWZ0EZ6kcCQhC6swHmTq1F4qJGQ7wUZEyACXn+nQ5s3N2JuqiFINCIWgKffJ7BM1sPhsQXnCOAr198GmyLNQcjBz6ZIu2V4Ip+MPI8vkDEnVfNgCXCk3D+4zCXyvh49PmPUBMJtYKBX+OOxP++ecCYjTTHQqG5zJ4yCpfOHofujG+YWG6vSjpSJ6A0rxPFHwLXKvRkKya07+aM5LG0j6Vzx2HV/AmGEXyNX5moX722H3/8UwrxyAnPzq/xiMT2j4/jrfYuExVCXxEy4voLG0u0oqqOVAnC7Av9EvrEibeaAp1l9ejig52hhhUG2pzxtCXh1lXTe8NKwQF+nnLxyw37UR+3jI33W1MQfrlhX3hkyJWMOUbUWH7eeMw5fRTSuaDEF5S2xaImPR+QCVyRK9+TTB9DvjIU+W81d4B2/9fXUlB6L5/ShtX8wFBuc1sCnT0ebri4ERecWQ+lQukXHOBDz+zF/iMZRCxhmFIMzJCaiMTru45i76G0IdSchXHxZQlc+5VJ+ZCYv18L0xlqXfYYnlj+U9y/8AnU2xnTr+jPBK1JWKR8Ny07u/aYS6ZhiiINaEuGVbdgDg3uB8pu7mSQ8QTq4xLfXjYtf1iEXiZ8dDiN3751EPVx2zjDcmDlnSdrgUEb2mgBw+pFp5mQGKgA3X6FHaliMFqtU1lZeposCm94LMVsqrCFBB/Z9De6wdph9y/8HY72KHx3xRmY3hAzUjdSzCPzz7/dY4gr58hOMFajJirx4rsdJiRyNEGfkNiV1miIdVfWkcoDnzCTdPhNm9FyUwyFN4jCTTyTE4oBm7XvmvP5EgYO0g7ryIzGwnHv4+qzD+GGxdOM5Jh4RpwluPXDY3jh3Q7Uxcrbfi+iGiYkftxRPiT+zSWNsKQ0lWhVHSnNJiDYzb1phF2uGEomE6ZUJ+1uD/xcFw8nhCgVrTNAO0wIgZzn44fXTkFDreAssjfpcX2FB55qNwypJJcZLCTOOr0Wy+fWo/1oHG8cOreitlgoPAgd+DxosaFE2CiRMjtCLdoevLyTtNpEViQcThiiHcYVflR3IVJ/Fs6deUFoOSRKk55dnaiNcgNl6Hg9VEi87sJGWOThoQrbYsYBWrZQfuZALO1uKxY2Q0lMNNNYgA9QkoR1Za8nG7Adttt4/rcPNqJh+j2og2NaOcz9gZKeSqEQEhfPHmtQ4ASZmbvsvAlYMC2O9z/L4Y5NN2L+2D8N2hbjsl7aMcvLHH9p289WHCt0vcoyYEPLZeYLR2X+z82Kz4W0xmnl93Kh0Akq9OQuaNgHN9eDsY1fxmPT5hkERV767NELSU9DvWPy/0qhb0g8c2KcT3tMhcgh8ZqFk7HzyQ8Qj2nTkSq0xcr1BI36+54WpH9hLiSTGCQVJs0ceueRKzuU9p8STpzNuSRsFJgQszxsOTwNmzpm4jsrZ8ARYalbadIzFAweEhsxrjaCnK8xyhm4I6W1VsKOUuBndk2oF6+xavY9IhN9N55t+gKaLCn+TXnZXL4r3M8ZsqTdXDdu/uoYLDyzHlzFVpr0VJLHVxISe7JMC6fUA+Z/3BJndB7ggYnE6v70ir4X+PyMpzx3/GTJLuXn1snoKMGt5RLE2bsHGuProrjnmnPMNVbRoIqkZ6g8frCQyC9cZTJTBlIulr60o8LPpXa7QXYdD3kkkxWeDSaTO1mfiTzxwyCX6RTS7hcSDRGC8Pjrn+Io1/FWGOb4pn+pIOmpJI/vGxJ5uYJfnj+tDlef32Acbdkq0cRniycV79jzyJW5RFj/D3kylIcWlVidFG2PLTkInbtPRGpKtCC0c6An5+P+J9tx7QNvoXXTZyZMvb33GJ5/5/CgSU+leXxxSNzc3mnWt2ToG57cfAB7D6cRtdkE+mqP8mW0Xqpcd3LnQ8teGMbxeAiFYaNZa9Y/YUVrr/czx/qNxjBCWVchlfVxycyxpmDZuS9VtpHJal/Z8fYJtFi63FfkivD+b8zEbzZ+Zpj9yedZU3VGnVIfEzq+CHeAPoLuWdhWt6orLHzKV7dU7mLRckYg8259fXQQxTZh2dMDN82nRSUHJiZOE0smVMdQKn030kbyHKp+s+wxk1JzKs32HyhCjeXiW699G9s+P8PUF31iuWE0h8Z9RzJGK6K2NJIvEb6JwzJf+eUWvb926ebCdNswZ4RINzWD3vv3xZ2Bm1nNo2hmGkuzyyvetxC7rbLEj/RkmRnM63OpPXaUA8cS5nMZ4jnsicDv+Q4Tz7PEgxFf0ZBUGBVa5e5HV27lETSewjLTWH0iA0MhZS0HVZ8slwHWgn6ElxLPdv93u9au/DmbbyWD1AIVADsQXpDn7wpMkHaUNaHiicy+qXRleXz/3/e7xmOXQqBAfNvaZT8/+YOSeSgsPOeOFxfCjj9Flj05yKZ4fIaHKipaq+KT5QqABSDsqAUIX3vpW6slflgt4EJImbnmuclCjvpv6cRXBZnj5hy+r3McCKo83u4P4dkdZKxOKC/bjsC9eedDSzdWS/zwe+BFo+k8MS6E/AeStqNyPUqTOVMzXdWhlil0bdjmK6oWtGYXo9n8ICSU761TucO3hZPiw3t4gjBc4Pnh5mbzoMLMO9bPlZb8EUnnCtN6dtOsESfnuYHCcwLQUtgx4oat8nI7FOkfvP/jxc/xLcMZkz9ppyCJIs7PvfsPKxTRvdB6qXTikp8c0V7OEBBGM/6fn50puzcHdnMqya4+/9iMLYQTg/ZdKKX+qKHX0r4Dv25LrnbDGD9wklMJEE4GFGkDf5z7/U3nKR3cSEpfCUGzhR01ZqsDL//AFM+/lOYS5mEiIUOlkQ64Mcv3K9/dT9J6kRQ9vmPfvld6nwoZ5hMifYFwMoGRKn6aq1XLOZu3nA+Vu1hD83DCLEBP0lrVsYaYY3iDRfhwFbTq1Fp3E9H7WulNZDmvBUJv2f2vl6T6aBz/8KQ8Q0g4FVB42LGPR+Zmywc7P671u9onwxk7CdkuwOIhoiiQS3VbY8a3Wwf2udt+dk267++S3MlJrj5phBeATuZiZddPtJrHZs1YSqUqm2iVvY/PmgbmqXt8lk7VwgPuxy6xGZRoS1KhO5fgbJPfGPP5Yh6ixl8q/D85mxeDp5iw/QAAAABJRU5ErkJggg==
