name: topaz
version: 0.2.5

architectures:
  - x86_64

build:
  kind: neurodocker

  base-image: ubuntu:22.04
  pkg-manager: apt

  directives:
    - environment:
        DEBIAN_FRONTEND: noninteractive

    - install:
        - wget
        - git
        - curl
        - ca-certificates
        - unzip

    - template:
        name: miniconda
        version: 4.7.12.1
        conda_install: python=3.6 topaz=0.2.5 cudatoolkit=10.2 -c tbepler -c pytorch

deploy:
  bins:
    - topaz

readme: |
  ----------------------------------
  ## topaz/{{ context.version }} ##

  A pipeline for particle detection in cryo-electron microscopy images using convolutional neural networks trained from positive and unlabeled examples. Topaz also includes methods for micrograph and tomogram denoising using deep denoising models.

  Example:
  ```
  topaz --help
  ```

  More documentation can be found here: https://github.com/tbepler/topaz

  To run container outside of this environment: ml topaz/{{ context.version }}

  The packages included in this container:
  - topaz - {{ context.version }}
  - miniconda3 - 4.7.12.1
  - python - 3.6
  - cudatoolkit - 10.2

  Citation:
  ```
  Bepler, T., Morin, A., Rapp, M. et al. Positive-unlabeled convolutional neural networks for particle picking in cryo-electron micrographs. Nat Methods 16, 1153-1160 (2019).
  ```

  License: GPL-3.0

  ----------------------------------

categories:
  - microscopy
  - machine learning
