name: romeo
version: 3.2.8

copyright:
  - license: MIT
    url: https://github.com/korbinian90/ROMEO.jl/blob/master/LICENSE

architectures:
  - x86_64

build:
  kind: neurodocker

  base-image: ubuntu:20.04
  pkg-manager: apt

  directives:
    - install:
        - curl
        - ca-certificates

    - workdir: /opt/romeo-3.2.8/

    - run:
        - tar -xz -C /opt/romeo-3.2.8/ --strip-components 1 -f {{ get_file("romeo_linux_3_2_8_tar_gz") }}

    - environment:
        PATH: /opt/romeo-3.2.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:~/.local/bin

deploy:
  path:
    - /opt/romeo-3.2.8/bin

readme: |
  ----------------------------------
  ## romeo/{{ context.version }} ##
  Unwrapping of 3D and 4D datasets. Coil combination of 5D datasets.



  Example:
  ```
  ROMEO is a command line application.

  Example usage for single-echo or multiple time points with identical echo time (fMRI):
  $ romeo ph.nii -m mag.ii -k nomask -o outputdir

  Example usage for a 3-echo Scan with TE = [3,6,9] ms:
  $ romeo ph.nii -m mag.ii -k nomask -t [3,6,9] -o outputdir

  Note that echo times are required for unwrapping multi-echo data.
  ```

  More documentation can be found here: https://github.com/korbinian90/ROMEO

  To run applications outside of this container: ml romeo/{{ context.version }}

  Citation:
  ```
  ROMEO: Dymerska, B., Eckstein, K., Bachrata, B., Siow, B., Trattnig, S., Shmueli, K., Robinson, S.D., 2020. Phase Unwrapping with a Rapid Opensource Minimum Spanning TreE AlgOrithm (ROMEO). Magnetic Resonance in Medicine. https://doi.org/10.1002/mrm.28563

  MCPC-3D-S Coil Combination: Eckstein, K., Dymerska, B., Bachrata, B., Bogner, W., Poljanc, K., Trattnig, S., Robinson, S.D., 2018. Computationally Efficient Combination of Multi-channel Phase Data From Multi-echo Acquisitions (ASPIRE). Magnetic Resonance in Medicine 79, 2996\u20133006. https://doi.org/10.1002/mrm.26963
  ```

  ----------------------------------

categories:
  - "phase processing"
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAIAAAAlC+aJAAAACXBIWXMAAC4jAAAuIwF4pT92AAADHklEQVRoge2Wv07rMBTGv1zdrbD2AToYsYAEYmkGhIPUgYUFap6AIexMZgBVnTJWAql9AMyOwgBSJYJYWMpWlE4wlBG1c+5g4evmD6S6g8WVf5vtk/P5s49P6yRJgp/ML9Mb+FesAdNYA6axBkxjDZjGGjCNNWAaa8A01oBprAHTWAOmsQZM89eA53lLS0uO4ziO43neycnJ+/t7Kvrq6uro6EiGHRwc9Hq96XSaipEZBoNBVszzPMdxer1eKjjFfIrJJwAYY1EURVEkhCCEEELG47EKCIIAAOc8DMMoioIgkDFxHKuYKIpkWs55MksYhnKp2+3miirmUpwxQClNbSUIAj2XEELfUxzHhBBK6WQy0b+ilBJCUgY455TSrAFdVKekYqEBfSaO49xDTZJECKHLKNsAwjBUYZPJhBDS7XZTeYoMlFcsfMSj0QjAzs4OgKenJwCu62bDNjc3AZyfn8vh29sbgN3dXUKIKicA19fXw+Fwa2uLUqrPF1Fe8Xfu94PBoN1uM8YODw8BPD8/A2g0GtnIarVKKX19fZXDj48PALVardlsXl5enp6eyvl+v88Yq9VquRkeHh7UcGFhYWVlpbziTAnp+L6v6kzWbvY2s6uySJLPJyurSNaDvHRKqV4z2f3J1fKKMyWkGgLnvNPp3N/fy/nl5eWsUko1NdNoNFQVyXpYX18v+lbf3O3t7XyKRe+JMaaG8lz1BqcYj8cAfN/Png3nXPYi3/dzA7KiivKKhY94e3v77u5O/h5tbGwAUI1cp9/v4/Nhpc7Gdd3hcHhzc9PpdFSA7ArfModi0WHI21fdinOOgq7MGFMzqRKXq4QQ9ZzUI/n6Bsor5nchAPV6Xdrd29sDcHx8/PLysr+/zzl3XXdxcfHx8fHi4mJtba3VaqmvqtWq/gek2WyenZ1xziuVip58NBqpjpTqQgBWV1crlUpJxa8Ow/d9/fCSJBFCqAqhlAoh9NVsEr0X6Tegijv37PTS/1bRKcryU/iP/k7/UKwB01gDprEGTGMNmMYaMI01YBprwDTWgGmsAdNYA6axBkxjDZjmD/3zZajTfmT5AAAAAElFTkSuQmCC

files:
  - name: romeo_linux_3_2_8_tar_gz
    url: https://github.com/korbinian90/ROMEO/releases/download/v3.2.8/romeo_linux_3.2.8.tar.gz
