name: gimp
version: "2.10.18"

build:
  kind: neurodocker

  base-image: ubuntu:20.10
  pkg-manager: apt

  directives:
    - install:
        opts: --quiet
        packages:
          - gtk2-engines-pixbuf
          - gimp
          - gimp-data-extras
          - gimp-dcraw
          - gimp-dds
          - gimp-gap

deploy:
  bins:
    - gimp

readme: |
  ----------------------------------
  ## gimp/{{ context.version }} ##
  Whether you are a graphic designer, photographer, illustrator, or scientist, GIMP provides you with sophisticated tools to get your job done. You can further enhance your productivity with GIMP thanks to many customization options and 3rd party plugins.

  Example:
  ```
  gimp
  ```

  More documentation can be found here: https://docs.gimp.org/2.10/en/

  To run container outside of this environment: ml gimp/{{ context.version }}

  ----------------------------------

gui_apps:
  - name: "gimpGUI"
    exec: "gimp"

categories:
  - "image processing"
