name: mritools
version: 3.3.0

copyright:
  - license: MIT
    url: https://github.com/korbinian90/CompileMRI.jl/blob/master/LICENSE

architectures:
  - x86_64

build:
  kind: neurodocker

  base-image: ubuntu:20.04
  pkg-manager: apt

  directives:
    - install:
        - curl
        - ca-certificates

    - workdir: /opt/mritools-{{ context.version }}/

    - run:
        - tar -xz -C /opt/mritools-{{ context.version }}/ --strip-components 1 -f {{ get_file("v") }}

    - environment:
        PATH: /opt/mritools-{{ context.version }}/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:~/.local/bin

deploy:
  path:
    - /opt/mritools-{{ context.version }}/bin

readme: |
  ----------------------------------
  ## mritools/{{ context.version }} ##
  Unwrapping of 3D and 4D datasets. Coil combination of 5D datasets. And Susceptibility weighted imaging

  mritools contains ROMEO, CLEARSWI and MCPC3DS

  Example:
  ```
  Example usage for single-echo or multiple time points with identical echo time (fMRI):
  $ romeo ph.nii -m mag.ii -k nomask -o outputdir

  Example usage for a 3-echo Scan with TE = [3,6,9] ms:
  $ romeo ph.nii -m mag.ii -k nomask -t [3,6,9] -o outputdir

  Note that echo times are required for unwrapping multi-echo data.
  ```

  More documentation can be found here: https://github.com/korbinian90/romeo and https://github.com/korbinian90/CLEARSWI.jl

  To run applications outside of this container: ml mritools/{{ context.version }}

  Citation:
  ```
  romeo: Dymerska, B., Eckstein, K., Bachrata, B., Siow, B., Trattnig, S., Shmueli, K., Robinson, S.D., 2020. Phase Unwrapping with a Rapid Opensource Minimum Spanning TreE AlgOrithm (mritools). Magnetic Resonance in Medicine. https://doi.org/10.1002/mrm.28563

  MCPC-3D-S Coil Combination: Eckstein, K., Dymerska, B., Bachrata, B., Bogner, W., Poljanc, K., Trattnig, S., Robinson, S.D., 2018. Computationally Efficient Combination of Multi-channel Phase Data From Multi-echo Acquisitions (ASPIRE). Magnetic Resonance in Medicine 79, 2996\u20133006. https://doi.org/10.1002/mrm.26963

  clearswi: Korbinian Eckstein, Beata Bachrata, Gilbert Hangel, Georg Widhalm, Christian Enzinger, Markus Barth, Siegfried Trattnig, Simon Daniel Robinson,
  Improved susceptibility weighted imaging at ultra-high field using bipolar multi-echo acquisition and optimized image processing: CLEAR-SWI,
  NeuroImage, Volume 237, 2021, https://doi.org/10.1016/j.neuroimage.2021.118175.https://doi.org/10.1016/j.neuroimage.2021.118175
  ```

  ----------------------------------

categories:
  - "phase processing"
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAACXBIWXMAAC4jAAAuIwF4pT92AAAF9ElEQVR4nO1bT0gbTRx9fnhLbkJAekvLihQNtheJheJqUfEmWjc9F3rYhUIKQg/Jod4K602wYKGnElYoBVEiaorghIIH0VJKA8nZ5NDT5jzfIZ3JbpL9M5v9uu3XPFiY7M68eXk7/3bnt0OUUoq/GP9ELSBqDAzwk2lvbw9DQ0P8aDabvivI5/O2sk78mqZB0zSMjY3Z8mcyGeTzeRwdHbnWo2maax2OoD6g6zoFwI9iseinGDVN01bOqTpVVbvy9TpkWabVatWTQwS+WkCtVgMASJIEAHj37p0vc8/Pz23l/KBarYJSCkopTNMEIQS5XA4AUCqVsLS0hEaj4ZvPC0JjwPr6OgCgUCj4EsGMYuWAtplOSCaTPB2LxZBOp/Hq1Svoug4AqFQq2N/fF5HtCiEDJiYm+N08OztzzdtoNFAoFAAAMzMz/LxpmqIaAQDZbJbXfXJyEoijF3wZsL29zdPPnj0DAHz48MG1DDNIURSMjo4G1WfDo0ePAIAbGwaEp8G7d+9yEW7dYGdnBwAwPz8fUJozRMYULwgZcOvWLTx48ID/duoGtVoNpVIJADA7O4t4PM6vff/+PYhONJtN3hKtY0q/8DTAOufH43HEYjGoqgrAuRt8/PgRACDLMpLJpG1gC4o3b97w9Orqat98DJ4GVKvVrnMPHz4E0OoGvUZ1JvbJkyf96kO5XEY+n8eLFy8AAIZhYHJysm9ehuEghZgBAPDp0yfbHS6Xy6hUKgBazV8UTis5WZaxubmJdDotzOmGQM8CiUQCiqIA6J6SPn/+DKA1+vdq+l++fAlSJWZmZpBKpQKVdYOnAdZB6/bt2zy9srICoHs2YM2fXWdgI/ePHz9c62OrQEop6vU6DMMAAGxubuLp06dCzyF+INQCYrEYT1u7AZsNrq+vefO3Xgfac7gIEokE1tbWuAmFQgGHh4fCPG4I/Dhs7QbMgIuLCwBALpdDIpEIQV4La2trkGUZQHt9ERb6eh/Amjmbn9+/fw/AvvTtxLdv3wLVxWaUUqn0ax+GrEvaTlib+dHREV/8WBdLnWB5RDE+Ps7Tl5eXgTh6wXcLGBkZ6Tpn7QavX78GAOi6bhsrGDrHBFHcuXOHp79+/doXlxV9vxJj3YDd2enp6X4peyKRSPBx4ODgIDReTwO8+qz1zkqS5GuhErQPLy8vAwh3HPA0gN3Zqampntet3WBjY8NXpTc3N3712WB9svR6H+EXQ5QO9gX+agwMiFpA1BgYELWAqDEwIGoBUWNgQNQCosbAgKgFRI2BAVELiBp/tAEsJEbTtMAcw8IxNWi9u/+/4I9uAWFg+OrqynaCbT8pioKXL19GoemXYthpp3VkZCTUXdjfFX99FxgY0E/hZrPJozxZhKemaXj79q3v19ZhcDih0Whga2sLmUzGNmXu7e21d5k7IyfxM9pSVVXXCEtCCJUkyTWy0yuitF8ON63FYtGVlxDS4ghiwNXVlS181SqSEEJlWfb8A2FwOGmt1+vcWEVRbOG1hBCq63qbQ9QA0zQ5uSzL1DTNnnnYH5AkqStPGBxuWg3D4Nd6lbNCeAw4PDzkQRAbGxs9N0JjsRjfJapUKl1BDWFw+IVXRImwAdYYn4WFBcd81mud21hhcLjh/v37PP38+XNcX1875hU2gBACADxW0A0sz/Hxcegcbkgmkzy4ulAoIJVKYW5uzj76/4SwAUECHFhzD5PDC9lsFoQQvqVeKpXw+PFj3Lt3z/bxhbABQeJ0O8uEweEH6XQap6enIITYwu0XFxdRLpdbmURnAb9fZli/FsnlcqFz+NHaiWq1apseKQ0wC3TGBTmBfS0CtL4zCJsjCJLJJJ9ZeMi9qKvWOdxpfrY67bUOCMoRpAVQ2v7+SZblFkcQUusys3MVVywWbctbtuT8LzictBqGQXVdp4QQbly9XrctkAzDCG5AL5GdhyRJjsLD4nDSqiiK63OAqqrcmMAGUNpydXd3lw9qkiRRVVWpYRieS9AwOJy0dnKyVpbL5bqeKwYxQlELiBoDA6IWEDX+BZKyjpXkkGWtAAAAAElFTkSuQmCC

files:
  - name: v
    url: https://github.com/korbinian90/CompileMRI.jl/releases/download/v{{ context.version }}/mritools_linux_{{ context.version }}.tar.gz
