name: dicomtools
version: 1.0.0

copyright:
  - name: dcmtk license
    url: https://support.dcmtk.org/docs/file_copyright.html
  - name: dcm2niix license
    url: https://github.com/rordenlab/dcm2niix/blob/master/license.txt

architectures:
  - x86_64

build:
  kind: neurodocker

  base-image: ubuntu:24.10
  pkg-manager: apt

  directives:
    - install:
        - wget
        - zip
        - libgl1
        - libgtk2.0-0
        - dcmtk
        - xmedcon
        - pigz
        - libxcb-cursor0

    - template:
        name: dcm2niix
        method: source
        version: latest

deploy:
  bins:
    - xmedcon

readme: |-
  ----------------------------------
  ## dicomtools/{{ context.version }} ##
  Contains a collection of tools useful for DICOM to BIDS conversion

  Tools included:
  ```
  dcm2niix: dicom to nifti conversion https://github.com/rordenlab/dcm2niix
  dcmtk: https://support.dcmtk.org/docs/pages.html
      dcm2json: Convert DICOM file and data set to JSON.
      dcm2pdf: Extract PDF file from DICOM encapsulated PDF.
      dcm2xml: Convert DICOM file and data set to XML.
      dcmcjpls: Encode DICOM file to JPEG-LS transfer syntax.
      dcmcrle: Encode DICOM file to RLE transfer syntax.
      dcmdjpls: Decode JPEG-LS compressed DICOM file.
      dcmdspfn: Export standard display curves to a text file.
      dcmftest: Test if file uses DICOM part 10 format.
      dcmicmp: Compare DICOM images and compute difference metrics.
      dcml2pnm: Convert DICOM images to PGM/PPM, PNG, TIFF, or BMP.
      dcmmkdir: Create a DICOMDIR file.
      dcmodify: Modify DICOM files.
      dcmprscp: DICOM basic grayscale print management SCP.
      dcmpschk: Checking tool for presentation states.
      dcmpsprt: Read DICOM images and presentation states and render print job.
      dcmpssnd: Network send for presentation state viewer.
      dcmqrscp: DICOM image archive (central test node).
      dcmquant: Convert DICOM color images to palette color.
      dcmscale: Scale DICOM images.
      dcmsign: Sign and verify DICOM files.
      dcm2pnm: Convert DICOM images to PGM/PPM, PNG, TIFF, or BMP.
      dcmcjpeg: Encode DICOM file to JPEG transfer syntax.
      dcmconv: Convert DICOM file encoding.
      dcmdjpeg: Decode JPEG-compressed DICOM file.
      dcmdrle: Decode RLE-compressed DICOM file.
      dcmdump: Dump DICOM file and data set.
      dcmgpdir: Create a general-purpose DICOMDIR.
      dcmj2pnm: Convert DICOM images to PGM/PPM, PNG, TIFF, JPEG, or BMP.
      dcmmkcrv: Add 2D curve data to image.
      dcmmklut: Create DICOM look-up tables.
      dcmp2pgm: Read DICOM image and presentation state and render bitmap.
      dcmprscu: Print spooler for presentation state viewer.
      dcmpsmk: Create DICOM grayscale softcopy presentation state.
      dcmpsrcv: Network receive for presentation state viewer.
      dcmqridx: Register a DICOM image file in an image database index file.
      dcmqrti: The Terminal Initiator Telnet Client Program.
      dcmrecv: Simple DICOM storage SCP (receiver).
      dcmsend: Simple DICOM storage SCU (sender).
  xmedcon: GUI X Window System Medical Image Conversion Utility - https://xmedcon.sourceforge.io/
  ```

  To run container outside of this environment: ml dicomtools/{{ context.version }}

  ----------------------------------

categories:
  - "data organisation"
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAUf0lEQVR4nOVbe3hU1bX/7b3POXPmkQSQp0ps8QUBlQI+akt9BIpVa2nt4NerVbm+i4ryaev1FpNoe22tFkX73Va/29rb9tpmrlpbK1cUAWt5SlUMAUStJdrwCknmPeex9/3WnkyYhEyYhKB/dMH5Mo89e++19nqvtYF/cmCf2LpKHVhdFXbC1Me/kSMOiiEa4+fUjGKjm/eqWE1UoYHJPofWKY7mGOse2xiVYEeWKOzITKtYNBrjQBSxGPMP+rpO8VNyb1fxTJtGTgYN1p4T2Q+XnJ3pa+w5WMVX15/rHwlisCGdTSkWjYHH5h1Aenrd66FMPDWFMf5ZKEwFQ7WU3ljG+Dglfb0DxgSUkgnOxbtK+p2Ks02AXMeU/UbzkrP3F+aKRpWI1dQrNDT0zUGfIAFYtFF1I37CLS8ELHP4HAZ/LiBrAVbNrRCgJCEKSB9Ker1m4GDCBGNEEQHlO5Ce08YYf00x/hx3+QtNSz+7m4ZGo41iqMSDHe4EiDYKxOZpxKfc+vIYZQZuUmCXcWFOZIxDejlCRikFPYYRhkox0L9u5aelRuVVoyKlqBjAmTA4M2wwzuE7md1g+KN0vUe2LT2vqZsj+hKxj4sA59StNFY3nOfVRBstVj3u20rhFmGFRksvC+nmiE0l00cLPrgViG6M2AZcGIK4SDoZB8BvnFRu8Y6fzfpIK856qMFyAxvkvhjqwUibT174yhwY1kPctCdLJw3pe97hIV1yTTKcPmPMEHYFicceJb3vNf/4C4/25sQjS4C6Ol5QQpNuX10vhFlHs/hO1mOAyAvxEQUihc+FYXArTBzR6Of2fGvbT77WpnXDAInABrQ0sVsDk6fc9PxwP1T1lDBDc/xsXLMoSOA/TtAcoXwjWGVI19kBN3X5lqWzNxbEcugJUFeEfLDqRREIn+5lOlwGZuITBKWkJ6ywIaXfztz0nIESgZfP9kXIm3YP5ImK2noN8VMOMMYN30n7DBiuzNCLk2996XRCnsShrN/jkKC0uZp488sjeMBeppHPxj1amL4VnMHxJOQQ+2i0Mcvk2g6QhB1yl0pKbthcAe3IJS5ofuyCDXV1ijeUcruL1ukfGpXAPObXLFz1kghVzurN9h1pF2OrbIQs2mz5J1cKCq6BLxVa2rMImQKmkY+dDv1b5QvDFlJ6e7jnnNq0tHYPUM+A0p6j0d+EWpbmMW/SwhX1Ingw8q6vcM9XT8IlZ45FDhIGHxoD4CsFi3O8/W4nvhvbjs6UV5II3eafXCcw4bsZT9gVo6X0fwWwOYg2MsRKr8VKfVEwKZNuWzlLGPZy6ZFjo0SB7duSDuovPQnnzhyN61dvxf6cC0FO3mEiz4q4oO70CahOmbh0yesIBQwtDr2Rz3mmHh8QnnYt8+6k8ozQMMNPddQ3Lz2/oT/zyPrehmKoA6tBzEDHqLe5GTjJd7OSMcaJxT0fCAcEli8+E9E1TVi3K46jbAN+0f4OhxdoDZeUigLe/NqZuPuJZqzc2obKoKFFg0Awib3ZCtwwaRVOqtqFuzZEETIcGMzPO9PgCsLwhZc75e1HareX0ge8rw1Eo9BaX+0fcacIVhLyHiFf+F4qhUhAIC0l9mVdHGWbMBiDxRkswRA0OA5HGuigA4Ij40u0pHOIWAayjg/PV5r7DC7RlovgyhPX4Dun/QnzJmzAD89ohMEJ+bxNUpCKC9P0wJbSnA3l6wDFYjHIkxatHAnJF0knpRjDQSaFiEBLEeIks93sr6CJMi5kaQU2WJEgViNCVlgCFUEDY4fbiNgCH+1LIYMqXH3yWjRMewYdTghVVgaThrUiwD2kPUtzB+kD6aR9YYW/OPmWl8/b0sBW9iUKRu+Fz6lbJciOGvKVBcKOjPAynXT6JZVlbwRJMd53+gR8vXo0nNzhKUaaO8IFFl7yadzwpeMQtIBXd3jYsuGX+Pbkp9HphjHMSuOt/dW4/s9XI+UFYAsXUivErr0xQHK+GMBKnY3qBUav94wyL2fF1wQ7Ze5K6WUpyirLWSLW3JtxcP+ZJ+DC4HBc9/Cb6Eh6EPxgIg0EiLuIGzjz4bBhePwr7+Dr059BazyEo+w03mwbjxteu6oLeYcY/wAyAHGBYsKaOem2FZO3NrAtvXWBUbxYNNrIY4z5ydteOV8EIhNkLiEZBeOHAKK34yscHQrgsuoxmL/kDbz+fidGREz4RWpnMD4C/YQjL/PfOH4FxuyJYbdZhZHBDN7cV40bX7sKSddGUDjwi5AvAAVOhhU0vIw7H8Adq7CKBnXvivcYHY3qP75iUcZYPhYvE0gnhC0DmayPtoSDERFLs79l5J+g1aUYu3QHme9DPwocPuJeBeZPXIcHzvo9rOAwBFkC61qPxr+uvhLtWQth04U8WE3lCcgYp/wEGC6mTNXqhnNL6QDFKKV16hUvhl2mZksvR4FtWf50MRHolA3BtLkisSiY7rZ4DmOGBxHU9rw8Mym4RNyN4JujV6F+2jNIOCFIL45hx07HU+9dBWY4GB/x8MHeHIKWUcpZ4srLKS4CJ9rAKQB7vVgMjMKoujqwhgYoOdKaxEVgjPKzg3Zse2/C9ST+PVqDuTNGwnOyEILyJf0Dg0TOEwgkViLc8jSSXggmz8KJTETimO/i3nlh5HJZGJaNN1pyuOd/mtCZ7ttjpHScMAOG9JzPA3i9WAyMwqDCh75SZxtmQHge2f7+XeVDAXHAvriDustqcPFJDhruux/xeFIToLdX1/N3Ch1pA1+e2o7LZ+xA3LNRFfax9aMQlqyohOM/oG2+lmDGcNM3v4L/vPEziP5oPSzD0P5gT2qSPCvKz80E8PDq5r3dA4zCi9WTzy1YjdN15larB3V43pyntP2+9IyRWFz/H2ja9h6qKiOQpBlLsIBgFGAJXDy1A5dN24WEY6Eq5GPbP2zc98fxSKbTMA1fmzr653ke6n/8JH73xP2YWTMaq5t2ozJEyvfA3im6piwzU5hy1u1rguuWfDabDx6YOnDCW7r9mGMofQ3WZUwPA6RUCAdM5LJZtHcmNPIG51B9GBatcJhCe0pg7ox23Fy7F0kngGEhie2tIdz73NFIOwwhm3SN2aWcFAIBG/FEBnv3taMyEoDXZ1yumE7FA2Pc1IcWwDJd0RO6dqKTnOqs2xuDYGwMDWaU+BwCyCtGBkMISCk1lfMx/oGH7Hwum8GeToWLprZjwfmtSOYMWCyD9ds83PmbEch6BoKmgkchWfdv80SmjZJY0amX3LSSihmGlQ0OO1q/r6MwGUVmkDEVR2WQAeOVdIlvhjS52ZfME2Ho6Yx34lMnnIJbv1qB67/QgqwfgMmTsEdNReAz38fU6dPgZpPIuRKiD+4pzFx6w4wpSbFBIMiEdaz+qHmyHt5DyYmsp7xAgGJ+HGkgxIkjHCeL+fOvw6VnpGHuXIZ4JgRTJLHjvbFY/rs5mHz6CNx57bXYfsF2/PjRJ5FIpGDbAf3bAQNVpphyiz/ifWztcPAayG408gtvWYQrZwlkm7+HzjQD8+OQwRqkxtRjVPVYrH1pOxqu+T8Y+8ei4e5FqKwIw3Xdw8i+9zRsvPiN7xgMKFKMRwiEEEgkErjiivm4aHocu/9yB2BWQagURNUpCJz2I3zhy1Nw3d3T8N0nLsAZs47Dij9swcQJx+E7i26EX+xfDwSI63zPKEEAxXyVJfbooMLOkWpWIIWXzaRwcs00zfZt674Dwx4O5sXBK6do5JlRgXTGQSrjIRA2Me/WabjtofOQ9RzMOHUS5tTORDKZ0oqvbGBgSnquIPwIuiJD3vWtogzQ9p/PTUCq96lKm8+qHAkCKG3eak/eBXPnEkgeAfMS3cjDqAB8F1wIcMHguhK+W/AbmM4+z66dCdMytQUoD5Ri3GDSc9KiveNd/VFDHj/ePaY5ll+CE4XKl6+BSCI5Oe0pjrkzkpjz6fWIZwS4TB2EfJ4Du+bXkVNe1ZPcO57CcceOw9Fjx8Bx3PKNlZ5TJbKiZzWZF15QWwr9VRIbGRd9261eiJON17mXcpDX7q3ARVM7sKC2FT7CMAXJ/BRYJZA/aE3KPvk+KsJBjBszSnuB5ShDimqZsOhFs+ZyqnJ1iTgvDKKeHP3CwHrlObo+39+knlI65UWDKIFJKbFSyR8KbAru7c21u5HKmWBIYMeOUdi893bYVO11nX6R7zlfnhhlgyIRoMwMW0dvqeWm8BUvvIjFolq1MuW84Xu5DmpOODiuy39iGxw727LYvCOOe888XjNLR85FwtHu5kEhraMi+PLUTiyo3YVkTsDiWYRGTcPyTddg++ZUV6dE/8iTvNPDOUcm56K9o1Nbk3IKJnSYyveo0WJ1j8NGj1VJESrevOSCdqbkWmYESiZEyKENWwJ3/XYrRnVwbJx7Bl66aBqenX0qIqbodkkpjZVwI7A6XsDlM95B1rNQGVR4628Mb/lXYfKZJ+O9zS1IJj0YJi+p1Ohz2zYQsAUsg6N1zz7s/LAVlkXK+lAmUSlmmFx6mdZg2tlUfNjoTfYu1iB1EyOtWYq89DHF3RR/f+PRv+Ke/9qK/479Hb9+bidyjtTam5CPe5WYM3oVwh8+iHjWRIXtY3trAN9/vhpPP/8azrlkPFJxHy/8qhkBSqVzknFFbrt+pJ8/9bBt4O11rXh7/T90jvG1tZuQSpdnBikXwM0gzfPypsdnd0ap1Fdk4nnx4EK6yJKZP/nZ5D5eQgyKiRCyBF7dvh//u2kXlm3eA8eVOo3Vlq3AFSeu1ZkcR4VQFVbY1mqj7tmjwa0INm3chOa/N+Oau2di2a+b8OwvmnQmKRI0uk7bQDhoaOQ3rGrBY3etxjsb9mP3/nY8+4cXEQpqpMpjf89VnKkn9QexnnUyo9dwRRSKzWN7Jy5c8ZxpVV3jZeIlEyMF0lTYBmxTIWIbqAoxuGwYvjFhBe6d/nsk3BBMlsHWj8I6nqeQ1jYlYNl46JGf4wf33okbFp+DXz60Bs0bWjHjvGqMP3E4iPa7W+LYvOYfeOsvH2H21ydj1hXH494HliCZSiEUIgLIfpWhUkoK02a+l9k2uoq/StJASd9+CADU6LyAYoZY9aB0s1cwxs0uVEuuRDJvcqaLFi9vlfjpV3bo7G3KGwbpxnUaizI5lMygeJ5CWtM0kEymcdc9D6L+7gVY/NMLsew3W7H8t9uRy+TjFcMUOHbCCCy8vxZHHQ80PLAETU3voLKyQpvDMoBS4px52R/qnoFmJWLId6sVgPVbGF244kkjWHVVngtKF0f0ZrnE7lQYN526EXXTn8HuhIUgS6Ji7DQkxzfgukU/QCK+H8Iwu10M0ugU2Liuj0suPg+zz/0cKgIj4KQoJFEwbAXfSGPDG2/hqcYXtPsbDod6IE96I5nK4mcP3o0lf/bxh3U7MTxiwfNl1+nn3nH9zGnvjljvoqFBpyN67Bt9QCy2hbINjC1YdZfPM5dwYVYp6ZZMklIpal82gqsnrtUVGypajAxmsa61Gk+9Px8N80IwOKWue6aZiYUNw9DPM79/Cc+/sArV1WNxzDFj9Mm0tXXi/Q8+0iFwJBzUbF/mydNOFTjlnzK3vvvohTl9qEX1gH4JADTI6LzJxAW7am57eTG3Rzzmpdv75AIqQ1KVlgqVVKujcpWu2OyrxrfWXAlm5uDk0lrf9iWvBW7QuUKlsLNlN95778P85gyBQMDC8GEVXX7AwSavMGNeH3TNKaUn7CrDz3TGmh+pXd5feZyXoiD9gBokmh+e9RMv0/k0dWNRQ1Jv5HO+qUvU9dOezRcqzQPlqqQbwLCAh6Bta+Rd19NsT6+JdYsf3RJJBVHb0sSgh06cxue/y7N796Pn4Jponi8R1txB6ktJbtnCd9Lvgzs3km9TbPfLJkC3WSQ/Imdc5+cyf6NuLCo1oQjoAKk+bwpfV2nf2k/IX42Ea2OY7eNvezL4a0sOC66aq0vXiWQa6UxWy22PJ01/M0gkM4gn0/qhsfTZQWO7xqfSGXQm0rh8bi14ZAxe29KqKkK25hblu//SvOSCrkbr0qE9wyGgUEU5ecHyGcIOL6duLOlRswSdAwkV0ydN9XkqUV+9+lpdqKRaHZWrqChSFTKw9NrT8KmKLNrb22EaJEmH30tCiRFKj6nQaNzxyya16YOErKqIiFyy4/ptj33xiXJ6iVk5SxVkiFrQqBUtT4Qcta0K0jWeErozg9pU4m6wR5W2UB8gNj170ihUhQN5uT/sbqr8HDTv2q27VDILWVEREU42cf22R2qfKLdXkJW7XmHCAhE4Y8OpIYna5Qq9OVSsIHNYqM93L9L1NpnxuuOEocq2UIQcCZrcDITZQJEnGNAxFBMBZug5Zpjj/GyCrAP51+xQiJHiGspOYlLK3LANqZjnuelvDRR5ggFvpyAOE29bNo6LyC+EFZrjZ+K6Dp8nxMcA+dodRLCSSze7A74zf8vD5/9loMgTDO48ilrTqWOcc/FvTJiWzKWkYrqmxgc9d3+gKEaEEqZNCUNIz/2tzO25Od8pPrjLE2zQm6H+4fp6fVFh4q0rpwhDPMCE9SWdenbSuldvSO4NFO4JQAluBhklbKWba5JMfXvrQzOX0ZDBtMkXgB3W5npdW5my6M+zJWN3QqnzhRUS1Jmh3JxGIK+v6L+uypZYmwp+uiqpi3/5azMm51YQynPI29usoB5hLa2/bo7Nc/Id7Dp/MWidyjAUUMQN9HbKHWtPlcr/JpPqQnBWw01bi62ipKe+MEUVzl5+LV0mokyKvjxlgRKzNF56zodMGC8xyZ5qaml5pftWyCBviPQGhqEE2lTxba5GJSav3zgNMvc5BUXNCZMANVYpWUkcosvwehf5y1VQsl0plWSMbVVSrWWG9arP1cbtP/p8ohfHyaGypAxHAgqXHXtpZEq2vLPlgwqvY8c4WCPGIttBEQ9g2EAukTSGj9xhtLY4mx6/JN37dzHK5MTmDRniH1cllCHaqK/N6raUclk22ii6r8/qQObIXZ9lR2rikuuRSqwHizbHWCE7R815+rUWn0/mEjX+WeH/AWB+iYI+COZYAAAAAElFTkSuQmCC
