name: nighres
# https://github.com/nighres/nighres/releases
version: 1.5.2

copyright:
  - license: Apache-2.0
    url: https://github.com/nighres/nighres?tab=Apache-2.0-1-ov-file#readme

architectures:
  - x86_64
  - aarch64

variables:
  jdk_archive:
    try:
      - value: openjdk_20_0_1_linux_x64_bin_tar_gz
        condition: arch == "x86_64"
      - value: openjdk_20_0_1_linux_aarch64_bin_tar_gz
        condition: arch == "aarch64"

build:
  kind: neurodocker

  base-image: ubuntu:24.04
  pkg-manager: apt

  directives:
    - environment:
        DEBIAN_FRONTEND: noninteractive

    - install:
        - git
        - pipx
        - python-is-python3
        - python3-pip
        - python3-dev
        - curl
        - locales
        - wget
        - build-essential

    - run:
        - tar -zx -C /opt --transform=s/jdk-20.0.1/jdk-temurin-20.0.1/ -f {{ get_file(context.jdk_archive) }}

    - environment:
        JAVAHOME: /opt/jdk-temurin-20.0.1
        JCC_JDK: /opt/jdk-temurin-20.0.1
        PATH: $PATH:/opt/jdk-temurin-20.0.1/bin

    - run:
        - python3 -m venv /opt/python-venv/

    - environment:
        PATH: /opt/python-venv/bin:$PATH

    - run:
        - pip install nipype pandas nilearn JCC
        - pip install 'numpy<2.0' 'psutil>=5.9.0' 'antspyx<=0.5.2' 'matplotlib>=3.8' 'dipy>=1.5.0' scipy

    - run:
        - python3 -m pip install --upgrade setuptools wheel

    - workdir: /opt

    - run:
        - git clone https://github.com/nighres/nighres.git
        - cd nighres
        - "git checkout release-{{ context.version }}"
        - ./build.sh
        - pip install --no-deps .

deploy:
  bins:
    - python

readme: |-
  ----------------------------------
  ## nighres/{{ context.version }} ##
  Neuroimaging at high resolution is a collection of python/java tools for processing
  of high resolution neuroimaging data, including UHF-MRI and microscopy.
  The package includes many tools for quantitative MRI, brain parcellation, shape analysis
  optimized to scale nicely with resolution.

  Example:
  ```
  cp /opt/nighres ~/ -r
  cd ~/nighres
  python examples/testing_01_quantitative_mri.py
  python examples/testing_02_cortical_laminar_analysis.py
  python examples/testing_03_brain_slab_coregistration.py
  python examples/testing_04_massp_subcortex_parcellation.py
  ```

  Tests:
  ```
  cp /opt/nighres ~/ -r
  cd ~/nighres
  make smoke_tests
  ```

  More documentation can be found here: https://nighres.readthedocs.io/en/latest/

  To make the executables and scripts inside this container transparently available in the command line of environments where Neurocommand is installed: ml nighres/{{ context.version }}

  Citation:
  ```
  Huntenburg, Steele & Bazin (2018). Nighres: processing tools for high-resolution neuroimaging.
  GigaScience, 7(7). https://doi.org/10.1093/gigascience/giy082
  ```
  (see also specific citations in individual python modules you use)

  License: Apache 2.0 https://github.com/nighres/nighres?tab=Apache-2.0-1-ov-file#readme

  ----------------------------------

categories:
  - "structural imaging"
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAcoUlEQVR4nOV7CXhV5Zn/7/vOcrcsN2QjgYSwCBIElEUoLklwmSporXiZWjtdbIvzt2rHsda6jJc4too8ldpaOqBjp31QO2TaOm3BpYMkVkGBKFQIoJKwL0lIQpK7nnO+7/+837knXDBs1ul/5vl/mnBv7j3n+979fX/ve4D/zxf7q+wiwaILo6xlQovar31bO0MtgMbM55nXJRNKJL2tjlTLetRLMKj3/zsZEI3yyIQW1l7crvYo6SiRDZGVAoydnigJFsFK3t64jZXUtkg0AA3bqiXq68X/CgZEo1He0tLCEAFWRlYK5hEcjfK55Yf8SXQbehKmNIOhJJKg//1hP5C2U8l4fwKGaaOjPdlU32Sr6yRYzcIazdOOhvkNxAj5P44B0WiUN6KR16JW1GekNXXZ3GCBlhMGM87TNTYFDquWkOVSiBKm8UIhJFMMYqQXTj8k3y8leiTQIoFmJuX2QLfZ+bv7nuvz9gBADJYNDQ3O/wwGSLBIQ4Qru2X1oiZao4eqqooczmbBca5ljM/UdF4GXQtKR/hpQyklpJAAy2wvJRhjYNw1esZZWgqZEGnrKAPelYy/Imynqbc3deDtexoSgzH7/wkDIpGIVn17Nauvq7fpdfc1+igu9Zs1xm7QAsZoKWSedASEJSEghHQgFfXENXHi1oITHQyQjHENjGmcc87AdA5oLC5SzmHHka9Jx/lFf196CzEisjKiKR/xF2gD+8TE0+auTTo1T0eGmn7fNzRd+5pm6JVSCN1OWVIKOJBCEUXfleoF/U/C98SvFACc/gbuen73P/eAnEnBoDGdMa5zKaXscFL2S3D4ktdu+8VOurxmbY3eVNvkfJKowT4B7axmbY3WVNdkk7r7h1bO4QF+Pze1qcKWup20HSFtqUFnnGcUW+1CFErSAwhiStbSOJk2YAsHlmPDEa5AOePQORcaDKlxJh0IcEPTNVODY4tWaYkf9x3teW7dfb/rm7psgdG8YLl9rkxg50r81GUL9ObblltXLovkM+6/Ww8Z3+YSYTtu2cIWSrS6pmmSSaRtC7Zjg1SBBK9rGkxugHNNMYGsgYi3hY1YOkG+EHn+HIQDYXWw/nQM3YlexZCA7oPBDUGLGKkHDJ0beiqdslcmemPRP93V0BZdG9XrG+sF6iE+fQZIsAXLF+jLb1tu1S2+cYRZlLtE9+nX20lLc1K2BTJdzjWucSStFFJWCj7dhyHBMHy6CXIAR+M9iKXjMDQdAT2gCI6n47ClwKSy83H5qBm4YOhYFIUK1cGOJfvwQUcb3tqzCRv2vqc0JMcMEVOFFFIwgzMzZGqOZb+b7LXuXnvHC29M3bTAaG5dLjAfzqfJALZg0wJ9+bTl1lWLIyN5YfBfjZBRl+5L2tISpKuaxjnjTEN/KqYInFk5BVeMvQSjC0e4DBACB44dwhttG9G4az16Er0wDQMB04ebLpiLz1VfhfxArmLKySueTigmLF//Ag72HUHYnwdHCDiO43CNCTM3YNiWaLWOpb6+5s7nG6tXRsyWbQ322WgCOxe1v+zHkZGBUOA5M2TWpvoSaTJ1rnONDq2BozvVi4r8Mtw56yuYWjEJAcP/sZuRjbd27cXSdb/A261bcOfMr+KLMz4H8vhkClm+kZyn8hscXP19y8Ht+P7rP8HBniPID+TBkQ4c2yH7ss08vyls0Wb1pm8lJpytT2BnJD9ao6O+yb5scWRkkCQfMOrS/cm0cKTGNaZRnqcxHb2pPpTll+DBK+7E5LLxEBTrlbNT7v148kbf5xraY51Y9OyzsPY5WHj/HQgPyVUOkvxE9iI/IeD6C53rignR155Ed+IYcswgHCkgHCElk7aZEzBcJsRvXXPnvzfWrI3qTbX1p40O/HS0k5fHwianJvq5cKDAt8QMGXWpvmRakOQ1ptFtSe1jVhxFOUPw4Ow7FPGWsFUc45wrJ6cx+tHUDxFCzrEkVIRJhePRdmA/YqmE8vgUD8k5KslmfujkSgPgasjk8vH46rSISqTSju1eR3mDZHq6N5nWTW2kmRf4Wd2SyLimunq7prHmRI6eLQOi0SgvmfAtSXm4WZ73D3rQN1fZvCOU2g94cGkj7aQx74LPYnJ5tXJU7nGZIjabGCKOKWZwpSE2LPj8hlJvJWn1ORtgFv1QDFW5E4O6hr4ze8wsTCw7X/kGxWjpBlsKNCQgzdTP13PMRZc+NqegtrFWeDnL2TNAgjXWNvKG+fMds6TiGjNkfttJWsyxBDjpKKWuSq+Z8vijCkfgqrGXDRDhqTxJJ5sYOqEKf7RBRr01TXfTYMZgGiZSdhqdsS4c7uvAkf5OFTWUJjENOtcUg3P9IdSN+Yy6xnEcFVbpXpQ9SiE1K5ayzZB/TrAofKcqzI7XER9b+qCq31ijUWZ17dORoY6Jh8EQdizb4pzpRDz9R4eh+EySvWzkxRgSKlDvyU5JauSle1P9iFtJxQyKBCEzCFMz1B798Th27zuIitIyhPNysad7P97YtQHvHdqK3V37YTmOIrAstxiTysfjkqppqC4dA1MzFbHVJWOQ789BPJ2EruluXSHJ7JgmLMdyLFvX/cbtRy9Lv/L6/IYNlCMMFhX0wVS/paNF1tTWaNYtxjfMkO9CO54moyYxuu5EaSRTDsjHTYwrHqnUmiSVtFPYfGAbXt+1DjuO7FKJDDGMiB9dWIlLRkzH5aOn082Q7EsjKRNY8f5v8OutL6O95yjKwiWoCg9H0AyoiLHv2EH8ctOvsaL5N6gbMwvfnHEzRg6pwJBggWJ6b2pf5jyZpRST6U7CdrRcX6kWMO6veTryd2hEnEyBUvfTMqCxtpFTmnv1018aw0z+NWEJXdrSptJkID/PhCrK8igml+eVKnXf0b4Lz77zIt7cvVGpbGW4HGOKRqjvd8d7sH7vu1i9fS0uqrwAX570eYTLcvH7jnVYv3EDLiypxrdmfAVThl+AIcF8FSlI0n2pfuxsb8Wq7Wvw8o5G/PnQDiyeez/GFFZhaE4RPurc7ZqU5yuIGRpjwpbMStnCCPmukGlWU19fv4pqBmV9WVGBfUz6hOJsa2e+sooHjTzfQ1YszaQjGCMRZwUTnWk4lupD1ZAKLJv3GHa0f4T7X34CPYljuGnStfibsTWoLChHwPCpbSzHwpG+TjS2vo2GP69S1WBICyGOOCKT5iAy8Vrk+nOOu6FMieyttGPhrbaN+P6ap9X3Hr/mPry09TW81PIq8ny5SgCkkV7ZIR11A8cM+fR0PLXqWEJ+ccNdK/oiDfN5thboJ0i/sZETEnPlT75QDh03ClvoUghbpXgnRVI3PDGV2285tB2L1i5Vcf8nNzyCiysnD2R0JBRaft2HXF8OxhRVYfaoWVi45kfYfGgbrqu6ErdMvgE+01QqT/7DI1zhBrSTyjU0ZQKUAN39u0fw5J+eRb4/D37dnykdXcfqHY60QDqSOWkbWsCYkS+t8WDsnfa1Udd7ZxITnsVyF6gkrvi0GUbAN9KxbKLpY9mp8uaUnJCzkwJP/elflbdePPdBzKi8UDlDitn0GaUxKpWRQklREUWFkpWCn/vQ2r8XB/oOD/CXVJ+k6f2oUKisTygGTRl2Ab5+8d9i4773sX7Pu24EOVWmQ6HTFg7nvEAC86qjEbO2FhQWB+jm3ovI/Pm8cWGjMzU6Nyi4mAMhc8jFMxLzScTTiqVjyiuPLa7C9iMf4QuTr8OF5dVK1T1ClGPM/CjGck2Fuee3vIRdHftQmazA7s79aNi2Wl1Hn59cKrt0MBVdlKOHxFVjL8fEoWMVM6YNn6hCMV3n7TOgBZQiUfYgBLnvK4tDGEKoVfa9de9F++3tCp+reerzQ6TULpGkEW51O2D7KvwxTYU2v+HH7Z/5spJ0wkri6nGXu0kJSY0PlncwBXrQvUYUDMfc82cj3mxjT+wA3m/frkrfIYHwoAwYOCx3j1scKsCjn/0OCgL5yufc3/eECp255nEfkpEWpdeMWQJ60KjktjwPwOEMUq1O47Isy3wMf06V7jeLqbYnZfU+IeJIHUmtKdRdM64OE4aOxUXDJuCBK+5ARX65ktTgxFPK7O5paAZunnQ9/n7al3D0cA9qh8zCdy5doMpcz9bPtIgRFeFyhHxBDA+X45aLbiD2whKWGz0GwlWGSkcIjbMc6Hw6IhENjbXk8BVligHUtCjp+JZElDApOV0zWEhShZG5iXc3Un8ivjhUhOurr8qorERA959DYQ2VDDmORFdfLy4oHocLh06AoXKsswdzqLwm7aNrPjNiqsIRKClymZ1lCq6DEMKBT0h58axpqWDTwnrHa9Jw+kVvVkYiYmr5XD8gJwlb+imrPV7HkfS5cm5kqzWjL1YhTuXuGRDvrA5NtYGgmkC60tIYUk5SOTdKcU+n/icvcow609U1+f5czB0/WwmEzkcMGMgJwDh5cnVGJscaIV+Ijqy6U8hygmT/BQgYGmelSm3cs2TikavCdEjK/KYPn6Sk6No82bZb/pyacKEIJ0/uOkWGoB4AtzWY8CkAhfAAYiOl0G69cOalHHJmW6pCi3MKVaRxk8HMB/QVEiXRz3kBLO6CFJmIx9XviPvGshCgLpariZmiRh6/GRGRF8jFsLyhJx7iFIsYRAQdjwpkMg7iVgId8aOw/Rb6ZUxBX1RCU51FFSYxk1T8bEzCY3yOP4ShecVKSKp4POlc0pFUyAWgm0WK/kbFAabcanujqw6mQACcFaksTLh1dhY1ypByfKETMrZTEp+pDIlw+pfgsHf3b8OGfZtVlXe4twPJKSmsSr+GDb9tRmlukQqjF1dMRmXBsAEckfz06ZjsMdrgBsKB/Ayi7pom6RFdKphkkA4M0/D7tLSSXsuEFmUVblzxurRu5jYo24//8XTKfvxAym9wDYf62vF882/xxw/fRFe8ByEjgOEFZSoUtrbtQ35ujsIGtxxqUVhhyAhieuVkfHnaPEwcOi7DSNfUzn653z35CpUvavqpiyHucClP0b1VdpWp9ijuZ290wiaZA5Mqb9i7GYublilkd2rFRHxl2k2YUj4BQ/NLEeuO457fLcI1V9fi89dfgc7+Lmw9/AGaWt9G0663sXH/Ftx16Vdx3fir1L0oJJ2KCQotItNS0LpH7CBkEG7ET6RPV7/JHOoBW1pcY76PBWLXg7oxuid+DIf7O5SaethAdu5OKTJJ/s22Tbh31fdVzb5ozvdw6cjpbqzPrH1dh5BIJDGqqkL9PWdISBVWBKy8f2gHfrZ+BR5+5Ul0xXpx68XkpOTgtp0hNJFO4FDvEVVmkxchqH0QITJI60ShI8sEZEBLScfpc1MkN4x4i25H3jphJ/H+oQ8UEHJyCFTEMw0Hjh3GEipWfDn44XUP47Pjal0A07GRttKKUT39fUg5aao71D3o77bjqD2mVUzCE3MeUEz7+cZ/x3sHWlT08NCkbG3zVuvRPejoP6oSLVUNZoGwKgsFh7Adi0utJ9vxc/rl9d6dZDrGIPdTl1YxK7OD65Wdgfz+9Y/eQkd/V6ZIcTdyYzhBXhK/2vJ7bD20E3df/k1MKD1PYYYUDRQeqDqflBHqLgOFW6C7RZAbCqleKAyF8b26/6MYunTdL11ozIvvWdIn0pJWEqt3NCrTNHVDnSHbPCm7oyarY4uYk5IHBhw/81Jh926MhhOEZD1KsT3gICsVpt9+w4e2rr34rw/fdF1dFpjp2qjEeYUjsWDmF1VlSJ9TNe0SfloQOgOI8gG4bVh+GWafd4lynuQjFOiRRTxpIe257fAHWLfnPdWJUnCc0s6BL2Z0nwKBjDlGKp2t9br3vUjDSt7e8NMku6ViKzi7kYSdQaUz9uPifJSykpr9duurmDViKkYVVroxnJFEXSLmjK+DkDWZCo6pAipLH8+4BvJ5IXD7rL9DitLvnEL3swwTPfyxN9mPFe+9hKSVUBmhC4pkRW8V0ymU0ju7lXP0U8elZML843gAze60F/+UNTU12brkzUywGOF/cpAz0wZBM4jDve146s2fq5hucF3l5a7qeV1dV9VPtc6U5HhmUZJTqAofAlTc40i1F31GZfC/bWzApv1/VsR7GelAZupuL9RbjVmQ7F3rYHsssnL+SXgAOx4a0o6900qne7imM07IxUlLJalSqozw7b3v4bE1SxXURUwgP+GlsVkF5qBLtcQzIfN0i+5HWaH32s5InuqHZ955Eb9o/rXSTILnOhNd6En2oi/dj7RwawJldhQYhIzD1t8mxIvKYTWwhSwToCkuOnXfQtaZP0xs5garsqkApK5TVgCmF2RjFG6GBPKxfk8zHl+7FHdf/g0FgipnmGlkDBa2vEXOj2saDH1QZH5guXCE2y0izhKjCSj90ZvP4bfvv0rNGGvi0HFWVcEwixrGxIwdRz4yP+jcbbR176M+PfJDYWal7SNSS2zLuvGJkFj1tmpJ42kb6p/vA9gfmM7iXGMUDDNIY9ahFCTu4vaFoQK8s/c9PPjyE3izbaOL63n5fMZRebMA2SGsbd8BBIMBDC0pyjpTVj6Rca5edFHNFa7h/cM78OAri8GEjP/yC0s6n7zuoa5LqqYlHOGoiw3dkDddOKf/6Rsf6Xxy7j8dnTlqarov3S+l7bzFen1HCfpTws4s3XtBw0aRhaqFJDXJG+2EdUQz9ZFIWIMnVcopkhfmCpzc3b1fNS2vPO9S3DjxGlSGh2UQYS9BoqI8ox2Sobu31+38am4u4WpOdvHl2jItqvAIVqfewVttm8T36m7vKgoVimfeeSF3074/+7uSPYxMwzsXhdiynBKnZvSMxKN/c0/vG3s29X73D4/9x+Z7V8Wi3xmt12ehwuxjQ0/V1fLV3hZf7vm+J82Q7zY7nnKEFJxl9QVOUOWBFhhHwkojaSdRHBqCKcMmom7MTFSXnIfcQA58mnnCdc+t+A1e/uMb+PGiB1E2tFgxh7bwFkWWeCqO1q59SrPWfLSOHJ31sxsfPbp6x+vBpetX5FF0CBpB1+GedCbSxH4rjrKcYvuB2Xckp1dObtx+YPtXxw8b360a7xkTYCcLtmZtVKOu6hU/vWW6mWf8QdiiWKaoAedWjqdeBFy6oEnSSSFt28pzV4TLVCNzfOkYBZsVhQrUGEzDylfxyn/9CYt/8F0UlxTAsm0k7ASOJfuxv+cQdnbswvuHdqpZgq5ED+GF4j+/8kz7sxt+lfvz5v8IFQUKMuM1gw+CqGjAuUqqYqm4/P6ce9kVoy9ZyRj7gpSSWqnqwo95qAEtyGvx5eaYT5k5/m9a/SlbQtIIyKBakM35gSaoEEqKKgt0HAWgBHxBlR6X5hXjWGc/2juPYsL5YxDw+9CXjLnN0FRc9RTp4OR7zcx0ybORRZ3vHdhqLmpaljc0VKR8C0mZcpLTIUnukSV6kn32v3z+Ue3CYRPuYYwtkVJqxIRBXfTUZVON5tuarat/fPP5LM9czTkb6cQsW01CnGF5SaiH/NB7quspz6dDU5FCBJmGDsMwEE8kVBjzzIiQIdqG1JpsuTcVo/GZ+M0XXd//pRf+oYRSXfIpRDyly5SSB03/APByKiZQFTssr1Q8E1nUETD8Mxhje0gTBs1N5x6c61Aj8bW7XtwpUtaPuKGlmKExcUKOOfjyPiapkAaQSVC+TpIMGAHkGSGlBT5mgllMVYL5vlzk+XLUa7JpAkPI47tESVwzvi7+zNsv5JFpKVg+ncDnJlyFf5n3A1SXnodjib4ByHywRWcJGn7s7GjF6p1rSwHM83jDB7vAGz+NyiiL9fT/3I4lf22EDJqDcghiPlsE2EtJleQzzKC63U2Vjt/EzfEzwxSZrhJpCVWe44pG2aU5hU7z/q2+XDOEvnQMM6um4NuX3YrCYAEWzblfDWbQ0NXpIHWFXht+9tbuTbT5PCkl9emdU1Yn1ECkXiENIYp4+iE7bW0283wmJLPdxuPZMcFjxEn5+QDG4BVT2amx+jajhqqNscUj0x917DaOJntUf5YcK+EF1CmmlesL4Yk59ys4zasYB1t0fyqWPuzYzQ4dOzKC+iuMsaxqcJDVVNfk0KDRH+9qaEv1Jb9tp0Wbkec3pZTnzIRzXV7GOaqw0t7bc0D3pkfdWSEHj7++FH/YvkZpC+GUP7j2XpTllWRQ4UGQKgXRcXYs3isP9rdT9jWS/n76+hSQNGVFI2dr71j5Bo2g0RSWmec3JECTYmdtDp90ndwmJ/NROQUDnnnnV2oukZhDydiw8FBYTvqMIGqGQcrMz8QAhYs0H1zu0PAhzd+5TJBt/ny/j3FKwChJ/+979sSr+b3bkxkQ0VT9LZ7zAPL8ucph7mzfhQ872hA0CNn3otDHEWW6l8Y5nVmd+8wMoFUP0YIGh8ZQiQl2v/01YckWX67f1GiC2xGfukmQRyDPvqO9zRhXMiatoC41aGmhPL8US65/mPyDIvLDzjZ8Z9UP0BnrRtJOqyhBvQf6l/IJWsRCy7FlUW4hq8wffgTAR/T3M8b1gTUfTnN0uVQDyXX1TXVLbrnRDBuPGSHzOjvl6E7KtmksxW0UZUQm/zLVp+Tpg/ZdZnleSW9ZTrHoShzjZHUFwbAay6H1QUcr/vH3/6y8/JPX/ZOCxLzr6TCtR/fip2/9EgHTj1QqRQ1dWRDM20GjyPJUecApVz1EfW29s4B8wt3P70z2dN+ajqUeZRpvp1EUbqgy0JE0L+8I4aIxHqZ+jgxgEn7dBJW0O4606bWjZ8Z70zEFrm7evxX3r16EDfu24L7Vj6vOEkWDmSMuUjMD9DN1+MSB+QGvaLOEJWpGzqDbr8ikwvyTKa0Em7rcnR+uqanRjb8dPk3zs+/qfnM2BPIdy4FDc27EAbc543kemkE4ddci828GjBWUQMWtOJs5ckrqkav/se+Lz981pDfVrxNjElZKfd3LHv1GAPfV3qbmFk7UgD1Ytv55JOyUnDViKnti7gMtAC4DQEXRX/jIzMqI5j0r9NmnbskTYfNy5ji3cV2byTReACE0kaYYL9R4u+rwZHrONGCTfS8V+wljVY/OcPcxCw2aYZgK4Xmo5o4jYSM3dOd/PhwI+/NoMt8trzO5hIsmp44zMvN3miskRxo0/PZz8xdbpbnFNzHGVp+2FjiX5T7ABN5UX68ec7vy8Ui+VuSvZpzdICVmaz59FNdZkFruqpEiMkiykzXcp5BjToNNSl2oAwXOaNYmZqetw0zKN5OO9dLar79425pd6657aPVi22/4dEpvXdDkOBbpLXfYitMEiczz5zpL5z2qV4WHRxljj3jE41N9bE5GuZoyq3Of94tEI2ZPqS/M/XKcAJ/OwKYziDFgGsG7OTqJRp2AOpdgZDKOI3rhyBgkWqUm3tUh33GSztaS3OFdK778w1hbd1u4Kly1fPOBlnk/bFoud3TuYgHdz3y6yah48kBcSo6SdkpajiVqRs3k99QsSJTmFi1mjC0k4pV5nQIP+FQeoaPhgxMeaYtGeU1xSzAQQECmg6FEKlHsC/uLkLJJ2pJrOk/bVp8Gtp9LmXS60/Hu1tZ48/Jma+BplWb3gQ31Vsp7Elby3lU71pau27OJ0ltq2al5HmrqFOcUMhrfIYc3e8wssvnvMcZ+n8EBTigbGf57FotEIry92n1G2H1stoGyRnlOjPQeu11aQg9KUlRxb84Y+ckxAG4EcMOhvvaKg71HijMPbjhVQyoO5wdy6YmyF3vRuzqf5R/NVvsTDoq/1oPTLS3MYwgNJzSicaAld/ID1QOPyZ6CadnErFy5UotEItTzpwJHDZlQksMY6xrs+399BuAU6+S8cWAY5ywvl6qQo6g6KGFqzE/NCcIZeH55kPV/AXaGB9J7sqFpAAAAAElFTkSuQmCC

files:
  - name: openjdk_20_0_1_linux_x64_bin_tar_gz
    url: https://download.java.net/java/GA/jdk20.0.1/b4887098932d415489976708ad6d1a4b/9/GPL/openjdk-20.0.1_linux-x64_bin.tar.gz
  - name: openjdk_20_0_1_linux_aarch64_bin_tar_gz
    url: https://download.java.net/java/GA/jdk20.0.1/b4887098932d415489976708ad6d1a4b/9/GPL/openjdk-20.0.1_linux-aarch64_bin.tar.gz
