#!/bin/sh
set -e

exec /usr/local/bin/mneextended-run /bin/sh -ec '
    mkdir -p "$XDG_CONFIG_HOME/Code"
    exec /usr/bin/code --extensions-dir=/opt/vscode-extensions --user-data-dir="$XDG_CONFIG_HOME/Code" "$@"
' code "$@"
