name: lstai
version: 1.0.0
copyright: []
architectures:
  - x86_64
build:
  kind: neurodocker
  base-image: ubuntu:24.04
  pkg-manager: apt
  directives:
    - deploy:
        path:
          - /opt/miniforge3/envs/lstai/bin/
          - /opt/lstai/bin
    - install: wget python3-pip git python3 unzip
    - workdir: /opt
    - run:
        - wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
        - bash Miniforge3-Linux-x86_64.sh -b -p /opt/miniforge3
    - run:
        - /opt/miniforge3/bin/conda create -n lstai python=3.8
    - run:
        - git clone https://github.com/CompImg/LST-AI/ /opt/lstai
        - pip install -e /opt/lstai
    - run:
        - git clone https://github.com/MIC-DKFZ/HD-BET /opt/hdbet
        - cd /opt/hdbet
        - git checkout ae160681324d524db3578e4135bf781f8206e146
        - pip install SimpleITK --only-binary ":all:"
        - pip install -e /opt/hdbet
    - run:
        - wget "https://github.com/CompImg/LST-AI/releases/download/v1.0.0/greedy"
        - chmod +x greedy
        - mkdir /opt/lstai/bin
        - mv greedy /opt/lstai/bin
    - run:
        - wget https://github.com/CompImg/LST-AI/releases/download/v1.0.0/lst_data.zip
    - run:
        - unzip lst_data.zip -d /opt/lstai/LST-AI
    - environment:
        PATH: /opt/miniforge3/envs/lstai/bin:/opt/lstai/bin:${PATH}
    - test:
        name: Simple Deploy Bins/Path Test
        builtin: test_deploy.sh
categories:
  - image segmentation
  - machine learning
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAACsElEQVR4AexTTWgTQRh9s02a2tiEWmjpIZf2oNAq/mCxVKrQeLCIh55ESLCgVdGLPbS9tJrEi6AHT0qhKglYexBvFRESUawSBFGMBBrSijHBv7RJk5Btftb5Jm5MIMYc9CC67JvZ/b6Z92a+NyN1PLUqtWLr8xEldadTSd7Q1wwJf/j5RwUUBfgYU7D0WUEmV73GZSXKfUnhw4l5BPucAkv9LiSfvAc4IdHkYmlcureCztEUOs6l0D2ewqaRJCzXZLxczoOEaVwpygTUhN1uRzweh+2CTQ0hH5cRvrIA21wU7oU3nEwRyOUVDJ68juFpGf5wvjhe/agooCZLe3lxBfHHy/D5fDAajRgYGABjDA6HAxaLBeMXp3H7WRZytnQWUJsAX2X2UxL7+/YJcr/fD7fbLZimpqYQCATQ29uLF8E8EmlFxNWmNgG+UklfD88jD4icVk87UUm6urpAIPJ0Ro0W+poEFL4DSa+FtlUPs9kMq9UKk8kkPFC4s2952UwtDObuOhgbC8RqW5tAOov4XT/WI2tinsvlgsFgEB7Qbgzck5tzDzH/KodoQgwpNtUFeDkTD4JYnfUhE04IM0OhkOhVBvKCytbe3i7uxtc1PklN8r66AB+Q9LzD6q3XWF+MglYei8UwMTHBM4WXTlBPTw8ikQhaDQwtTayQ+N7+VECn02FycrJYZ1mWQfeDzKS5VHuC0+mE1+sV3hzgHpAI5VVI6kdpT0ePBBhjos6MMdA/xY2NkjgxjP3IkfGWvRqMDmrRoC1lQvk9YPwoGoY2o/n49opoO7UbM2faMDOiw2mzFod31mHskBb3xxpw1apDy0ZWzs7/JI7iK23QoOlgJ5qHt1VE67EdGNzViCN7NLh8tB6zZxtwfqge/VvqoNOg4iNVjP7G4H+BXxbz7y/RNwAAAP//C9arogAAAAZJREFUAwAwtjUFVcEnVAAAAABJRU5ErkJggg==
structured_readme:
  description: ""
  example: |-
    ml lstai/1.0.0
    lstai --help
  documentation: https://raw.githubusercontent.com/CompImg/LST-AI/refs/heads/main/README.md
  citation: |-
    @article{wiltgen2024lst,
      title={LST-AI: A deep learning ensemble for accurate MS lesion segmentation},
      author={Wiltgen, Tun and McGinnis, Julian and Schlaeger, Sarah and Kofler, Florian and Voon, CuiCi and Berthele, Achim and Bischl, Daria and Grundl, Lioba and Will, Nikolaus and Metz, Marie and others},
      journal={NeuroImage: Clinical},
      pages={103611},
      year={2024},
      publisher={Elsevier}
    }
readme: |-
  ----------------------------------
  ## lstai/{{ context.version }} ##



  Example:
  ```
  ml lstai/1.0.0
  lstai --help
  ```

  More documentation can be found here: https://raw.githubusercontent.com/CompImg/LST-AI/refs/heads/main/README.md

  Citation:
  ```
  @article{wiltgen2024lst,
    title={LST-AI: A deep learning ensemble for accurate MS lesion segmentation},
    author={Wiltgen, Tun and McGinnis, Julian and Schlaeger, Sarah and Kofler, Florian and Voon, CuiCi and Berthele, Achim and Bischl, Daria and Grundl, Lioba and Will, Nikolaus and Metz, Marie and others},
    journal={NeuroImage: Clinical},
    pages={103611},
    year={2024},
    publisher={Elsevier}
  }
  ```

  To run container outside of this environment: ml lstai/{{ context.version }}

  ----------------------------------
