name: niistat
version: 1.0.20191216

architectures:
  - x86_64

build:
  kind: neurodocker
  base-image: ubuntu:22.04
  pkg-manager: apt

  directives:
    - environment:
        DEBIAN_FRONTEND: noninteractive

    - install:
        - octave
        - curl
        - ca-certificates
        - wget
        - unzip
        - liboctave-dev
        - patch
        - make
        - fonts-freefont-otf

    - workdir: /opt/niistat-{{ context.version }}

    - run:
        - curl -fsSL --retry 5 https://github.com/neurolabusc/NiiStat/archive/refs/tags/v{{ context.version }}.tar.gz | tar -xz -C /opt/niistat-{{ context.version }}/ --strip-components 1

    - workdir: /opt

    - copy:
        - SPMinOctave.m
        - /opt/SPMinOctave.m

    - run:
        - octave SPMinOctave.m

    - environment:
        PATH: $PATH:/opt/niistat-{{ context.version }}

deploy:
  bins:
    - octave

files:
  - name: SPMinOctave.m
    contents: |
      %% Store current working directory
      cwd = pwd;
      %% Download SPM12 r7771
      unzip ("https://github.com/spm/spm12/archive/r7771.zip", cwd);
      %% Patch SPM12
      urlwrite ("https://raw.githubusercontent.com/spm/spm-docker/main/octave/spm12_r7771.patch", "spm12_r7771.patch");
      system ("patch -p3 -d spm12-r7771 < spm12_r7771.patch");
      %% Compile MEX files
      cd (fullfile (cwd, "spm12-r7771", "src"));
      system ("make PLATFORM=octave");
      system ("make PLATFORM=octave install");
      %% Add SPM12 to the function search path
      addpath (fullfile (cwd, "spm12-r7771"));
      cd (cwd);

categories:
  - statistics

readme: |
  ----------------------------------
  ## niistat/{{ context.version }} ##
  NiiStat is a set of Matlab/Octave scripts for analyzing neuroimaging data.

  Example:
  ```
  octave
  >> addpath('/opt/niistat-{{ context.version }}')
  >> nii_stat
  ```

  More documentation can be found here: https://github.com/neurolabusc/NiiStat

  To run container outside of this environment: ml niistat/{{ context.version }}
  ----------------------------------
