name: syncro
version: 0.1.1

copyright:
  - license: BSD-2-Clause
    url: https://spdx.org/licenses/BSD-2-Clause.html

architectures:
  - x86_64

build:
  kind: neurodocker

  base-image: freesurfer/synthstrip:1.8
  pkg-manager: apt

  directives:
    - workdir: /opt

    - install:
        - git
        - ca-certificates
        - curl

    - environment:
        DEBIAN_FRONTEND: noninteractive
        PATH: /opt/:$PATH

    - run: 
        - pip install scipy antspyx
        - cp {{ get_file("MNI152_T1_1mm_brain_nii_gz") }} MNI152_T1_1mm_brain.nii.gz
        
    - run:
        - git clone https://github.com/neurolabusc/py_synthsr
        - cd py_synthsr
        - cp {{ get_file("downloaded_file") }} models.zip
        - unzip -jo models.zip -d py_synthsr/models
        - mv py_synthsr/models/* /freesurfer/models
        - rm models.zip
        - pip install .

    - copy: SYNcro.py /opt/

    - run: 
        - chmod +x /opt/SYNcro.py

deploy:
  bins:
    - SYNcro.py

readme: |-
  ----------------------------------
  ## syncro/{{ context.version }} ##
  syncro is a spatial normalization toolkit based on ANTS, SynthSR and SynthStrip. It supports normalising brains with lesions.

  Example:
  ```
      SYNcro.py input.nii
  ```

  ----------------------------------


categories:
  - "structural imaging"
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAATqElEQVR4nOVbeZBdVZn/fecub+l+vabTSejuJBiWkAUYiU4C6SRAJoDDMkA3KVHRUZlxr3JKHcuaolFrSlyqRJ0Zq1BQwSR2ozWIQIEMSUiQNYUICYlEknQWyNbb29+993xT33nvdV53v9fpJN3xD7+u5L1737nnnG/fzgX+xoH+ausyl7lLfPY3MtXATOjpUWhqIhxdydgOxt2kK4xV6OmhFU1NtPnoUUZHh55qothTMy0TuqHMV6IAQDDyZ1Ztj71eS95xgxw7jaRTicwBorRcbx41Fps2KaxcGUwFMWjyuQ2FToO0gZm/fSUa9nmhD15KrC8hpjbtezPItmbCD/I7UAoIdJxsazfrYJCAbUz0gmZ69UDnsr7h+bvZwvYuxt13l5egvyIBCN08jPi8xx8PZdPT1hDxTdB8FRG1UTgiBAJ0AA4CsO+DCqsLW0kpkO3IF8BS4FwO7OWOQ1lbyaJHFAWP77lx6WHzQHe3NVnqQWc6gdlMZ6dBfO66p5v9UOxTRLhN2e6FwlnOZgQRZlBgEGYQiMl8jtgJMeTP/EdMxAqWrZQbBiwLOpM+TMyPBhTce+CWy9/Ir81WqbSdfQJs3Ghj1Sof3d1um2r9MpT6nApFphukc1nhkIiq2IK8PThVYBEZ0kZyHNtSkagQIgfGL3Ui8R8HPnr1QWMjDFlPTxroNDcmz5Eg2LLhuTWWY32PwpEFnE5D+75PdAZIj0+MAARbVcWgvdwRaO+bvbcs++FoSZxaAtx1lyoaodae57qU7d4lysyZjA+wBSpq9pSBkCIgy7JVVTV0OtntHzr06UOfu/n46agEneLSSrje9sst9Qg761Wkao2OD+ZFlMR6nUVgIxKBVV1js5d7S2WTt+9Zu/LlYbWcdAJwEfnf1SM07UkVrV4SDPV7ROSczv7FCo6Y/nTNEbPP4agdBH5/yEuvOVUiqAmLfSny4ciSYKjvlJBXYFjQUOYfw4cFD9bwJ40YMzF7JptPBtq+JKqCzjnT6/vJfXLBhk1LCobZmsgcNEGDh1m/eLrBroo9YZCPD/mkaEJRpCCkQciwiwzbsEmbe9NUwiBqYgAw+rkKGXbgQ8FBgCjlhp+tJB02EY5kPWxYuRBLG6v14ideUzZRv0oPXbPn9qtfKkrtePuzJ4CDTBLY3Vs3WFXVS/zBfo/UyTkvmxdkBjgKFz4utN/BMnc33uvsQz2lMMc+ZsYIciIVvUEjBnQU2/1ZeM6bh9e8VvTpKlSpLMLwEYySC+F+wg9wWWMMV82sR9hS6raWuuD+vX31jZHYo3PXPb14D3Ck1GifMgFWbNxobybyW9dv7lLVtVcb5E8i9kWuCkdjlMaHIi/g1vArWGAfQp1KIWAyQp5lu8D9vP4LYYQg14Zfx2f4Gez2p+OJ7CKsS/89eoMG1Ki0kQwhhFmHCNlA47PzWwR5M9en57daPXuO+IETm659/0EQ1qB7wbhSThV/KfjVtg1brqZw5CkT2DCPq1eCgIixiO2t4W34eHQLFtkHjSSk2EWO8/RWxMgLe56nQgAj8IUA0aEAEfIQJg/7g3qsT78fD6SvQJ+OooYyYLKQ9APMr43iyTWXwlYEzQxXKXzxpbdw384D/ozmZjs3cLyrd2373R3dbPVUcI80XqBzUc92O84Dr1uh8Pk6k5bITo2HfILDmKEGcU/Nw1gTegNpdpHkkEEsRD6qKWM0WgyfiHfOCCAbQjSqpFEV+T3FIaQ5L2hCBOH+Dn8WvjTUiRe8c9GoUujzGA+1L8C1LY0j9vFuOof2x17hNIMt2w7I9xbt7bxiVyV7QBUIIAFN0Lr+2a9ZNXXfNEaPKquLjcCI/GXOXtxX+3PMVANG94WbYXiIqaxBeEtuHl7w3oO/+E3YHzQgzmGDvA2N2dZxtFj9eJ+7B+3uLrRZfUaahIAiJ9WUNZ9fi9+MB1KXo9lK4NJpdUYViojI7xYR/tSXQH8mF7ixmBUkE0/1rl2+ZuIE4LzVn7luU6PjuruIVL1kbpUiPNl8P0eNDj9Y9xPUUNpIgnCyjlI4pGuxLr0Uv8suxk5/htF/kRZRAasQvsv/oh6i3yItrVYfrgq9iY9EnsdiZz8GdQQBLPNMFeXw5XgH7k9djrAeRGBSgZLtA4jayngIEzFGoxZSqSv3rb1iY7lwmcZgVAgi2jY8e5eqqe8KhgYrcr8o9pc4vfhF3U+NiIv4yv16lcSvM+/FN+LXY1/QaNxahHLDmxyTDJYER6IaCR1CjcrgU9GN+ELV0/DZQgaOkTaRhi/FO7Aus8wQWaxJ6WxiD/KVFgQqWmUF6fjG/be1X1lOCmiMRDCjpef5sGL9BjnuXEllywVMIrpZ2JhGCTza8AM0qbghhnBJ9Pabievx49QKhOAbxPMh0MSiPSGEBYYHhUEdxT+EtuPemvWoVWmjEkUi3D7wSTyTm49aSg17h7HADNsNWOcu2d+xfPtoIqgRY7u75UdW4CspWnUu5zJlkc8TVyhNxuCJzos+C+cF+a/Gb8G9yatRS2lj/MToTRT5/NxkuCoLC2Gfyi7ARwf/2aiC2BSZT9zot2t60KL6kIUzJrQ+gT4FKhK1ofljcr1CymsloEovOjo68l80dxApZqiyAYSgM8hVuDXyKtaEthuDJxJRp5KG8z9JtaNZDeZ1+gxKDoKShMlChJe8ufjk4B2AcaEBUnCN4fxi9e+R0m7F8FlSc6lPgOkf5937eGiz1BbLEoCZeoiC5l88WQXi1ZzNiBkp4/fzbizGg/i48xjSvgaTjTqVxm8y7zViP10NmTGTBUKERkpga+48fCtxnbE1grBEjteH/ohFzgGjGkLuMiAEYBUKnZdtqlmUrzydsJyqZKBhlWtXzYcbaja6X8byi5uJewE650zDxQs6kI7MQ9g7hkN+Fb6RuMHo/GlnduOAELRBJXFfqh2bcxcYbyPGUj4/Ed0CTzx3hWdNOc4NKyi+YrQaqOKX4k2y9DIViljyULnJRKRDivHhC86FavsIapb+FLWLv4r1wXXY59UiqvwzEvvxQPRc5v5xaqX5LHqh1aHtJrfIVLAFVGzEEC2Xa9NzGE2A6StX5j0H0xJobZRnNEjQkfYDLKivxvzaMDQHcJSNzIwb8TivRATjWeMzB5lbrP+L3ly84begirLGGEpmeYW7G+lKtkDKsJ5xwQtbuv8QMRXlQryjimN68jZHBp8jBKDCgBEEAJAJNFbOqDdxt8dkeP3cwWN44/gxRG0xtlPb3ZLAK64j+G3mEuNxjLoxsNLdZXKMssGt4BL4Ytyb3f6kW1pAVcMDADbUYWo2g6W7M3qeQg7+/qbaEfefPTxksryz0WgUM+eSh5e8OYjrsEmcJGS+yD5oDKXEDmVdotZMruMGNc4sc93VNVICClSR7kUrB565U25xybzqQ4WsrjDkz0OpfOiJqYditngwqMcgR0xQJKViUQ2JNuX7GCAiFgI4oYhmq8XcW5BPk1XpOOUJH+GVEyO542mNprCL98Qi5p4QQ9LSfYkMXEvsDJ8VAogaSOwhIbZLPjzYJvSeax+Fx5WDIrCGIsHvBKgxg9T4giw/C7dPEIUx5PnGQJ6t3rYJw9kxHiBfgKHhrPKke7BHpjWq9EI7FjEXqhbjQGm4YYqZU94KGAtC7tEW/6QdU2FS4NsVI8H0kPbANGC6tRVaTYKqVYKvfD1b+j+81ZIKMo9KoMYB4sD32KIBc9XRYQYXe/jGfxz/xBVxEN4m2833KEctKogez3rYE8+Ye75mxFwbc2Nh5Hx9ViQhX1FSJu+Yax8zdQTJQKUgIzbBoTKRKDOTbRNnsymV8HaXoIQTEtDTU3xqoFwQdCIQ0ujP5XsO+ZouMLtKChZn77yNX0iQJA2W78J5qTkOcaSyFJDxWfFw4JRPhlbIERYD+mVpR5s+9SiQwT4zXutL5EcWRixrrp3yAGikAXRxsXMQ9SplJCBEHt72p5uym2SKY3MR0uSGxEbs2CVSnq8JjJSAYnxMGi9yLiv12TEeQgY4irDp3T6DsHwXWDWzHnOqw8hIBDnFBGBScDiDD9gvwoccqCDTbNmam2c8Q7lQ2DBTDmAovFAxGYLEx8JVy36Vc9kBsm012rEHzIjaFrYdi6M3mTWZocQGjSHHVGcTXmDuTRXIZlMBsCgGXN4UQTybgqOTGNJhbMxdgJDyRh1GyoMwk31PnOXmiskQCnnygc5l/cz6eQqF84cTRoFDhIGcj//dd/TE9AA+cf45qHVteHIWZGrwh1KEtOfhUwvPQ82SHyG0sAvVsXPwUm4OdvmzEIWcnVBjDaDjKJ3JvGMjta2U2QIjRhdEQ+oAPVAmJsBoECmodizc/9Yh9GU94xkCzZhXE8G/LWwzxJEIcbJB1K0v6+OGtibc3NaIgC1Un3MNQu97APfTh+Brr2zh2tQCwlGJAp9+u3P1YEe+5F9GAgAUy0Uh6Md0Mn5MOWPVQC7CSmFvIoMH//LusMMQwnz+olZc3zoNh9M5ky1OFgiRh7wArVUhfP/95xtvpFky1gAvHsvimX4HNTYjKJsJs5LiDin1M7nu6ekZ8bsaOdqogbW7s/0o6+ARilRRaWEk37hiYwDrHAv//eZ+7E9mDMeLa/9o6QVYPqMORzK5YSN5RsgrMk3Qetc2naBpYccQW4gg9YGv//EvgPYrpcFahSOks+mdvU25Z03WO6ovoMqsKUQgFVjf1Zl0lpRphxkxkKRD/G5OHlM2Dmc1/uX53cYdyiAhjGx0/YqFpmZwJCPJab6MdqogCArn+7M+miMuelYtwuKGaoO8bEbm/M/X9mLr4UHUOBXqEBLMOa4sfk/hwESZ8v5okJp5T4/ad/vlO5HLblBVMSkPBxIZTFNx04hooBRqkMTsUA47juzHXdt2mg3LSrJBMYa/uWoRvrigDQlfY7AQOAlCxXFjli0kWoKYfKb8AEezHq5pacD/XXPpCeQLUrH+7cP4wY79aHAdE5uMAWZN4bAKkoO7Qu/GNxQPeYweZpfZC7B9u5EC6tn07zqdvEHZVm3aA3+v5lFa7v65pKcXYAjVWL3rDtMI/e6Sc80m5Z8g0nXpXFw9qx4/3HEAfzgyiGM5DyGlTOosxDhhtNhklX7ApuIUspQpu915/iysPbfZjBhGnvLIf/aFXai2hS0VAzCWc4bI6M/v/sJ12cKJkQk2R0vb4+u2fMapr/1RX3/GXx3ZaT9Ud59pW4k1aFAJfCdxLb6Vuh4614c7L2zDPZfNG84TBL+i+O8YSOLhvUfw4tFBUz8QbyHIFrNJiSWmR1xc0lCNm2Y3ob053/gU9IoElbGlyBu1w1hgZt+K1do6PtjTu3Z553hH6AgnOyCxapXf+qstDzvVsVsGB7P+Qw332yvcnYbjEnt/oO/zpjgRJo2+nG8CIrHU08OumUM4K9ljaaIkyPcmMsN1BOHqe2oiqHPtEfai9Fkhwjf+uBf/9eYB0/yshLwRfTdMzP4eHfCSAx1LB8Y7SEnjEaBYOW1bt7XOCqltcbt27opgW/Cz+p9b0qL6dvIa3JO41lRlJUOTzffnPMypjuAri2fjltnThz2BICN/Nqlxay65QoLhlgx69t0B3PP6Pmw9PIAGN3+ypCw2LBSzmSyb/Exm6cEPtr94snNCNC4B8kQwE7Su23iZHY4+FedQ/a+i39cXu4fU8uNfMXW50gREiCCiLUbs0sYY/vXCc3BdyzTEnJGdIjFcpbZrtMsUjouF/583D+CZd/rNPZmjrMHL75NhWeL2LB0fuLP3g6vuK55zGA89wkSgoEPnP/j4kiPRtif/KbSt/iLeE3w9eaM1jeJjegEixZJ8Sr1QOH9uLIL2GXXGIF7cEDOIiOsqBSFa0guwcyiFje/04elD/XhzIGlsSY2bH6tPhnwoYul0/M7e29rvm+hZQcJEoTBhy4ObljhVkScthfpM2vOVqnxypOjyihIh101hBxHbwnk1keFKkoyRyFLcpRRcZLwcfBJdlxlEGioCcwCllApH6VSRFzi1CKWECFRd/YhlWzODZMIXYz/eGeHSuqFkj6LmkjqXKrK4RlEfUQVBW4otxXpDJRBrr0JhG0Q+Z1OfPlXkBU49RCu6xwefmIlo/QOF88J5ThBZE11wdPnMVPfKVWHKAbMxaipWq3Q28xZymY/1rm1/7lSRFzi9YL3Er8qJcbLsryrbcXUqKU3FfJV6SipkLEdHmcJhy1StfG+DHx/67KE7Vp/WSXGc0SYltOzqMv61ZcPGhcqOfJsc51rRBJ1OiYWfnPcGiu8JsLYoHCFyXOhc5g0CfXnfze974kzeFZikV2ZOUL711y+vVqS/xJqvVJGoxbmsvDKTR0B6jfJnXpmhSifU8gFL3kOaspwUMygUkdduRPL/ROB7q/zeh3Z0dubO9G0RTJqY3sUKXSc2MveRbYt14H9Ya32dUuoiQUA6zlKWMkfuRIW1WMESENGxLJKzmMLlgojLy1MHYNu/Z4X1+7N7nhnm9BlwfcSymEwY/TZXN1st4Vf/zvJylzNjOVjPB2gGAr9Gjq+xoQGB5KhrLisS0A/WCYDeZMbzZFvPRqzal3fdND8+SuLkwUkpQxOmAkQiVm5Soy2ylKNe2rQ3hnf3zUSsdoafSOaDiHAYQSaRsJpnv5WLH8+9c8NlqRHzCdJygqGzc9IQLwJN5mRl55ejd+a12aM8YZEVSSo+M8Wvz9JUTVxxPTFvXSAsGO5EnYBitfav8BI1/lbh/wHZ+8vuTnguZAAAAABJRU5ErkJggg==

files:
  - name: MNI152_T1_1mm_brain_nii_gz
    url: https://git.fmrib.ox.ac.uk/fsl/data_standard/-/raw/f6db877e56047a1ad91fd9b28d38654376087029/MNI152_T1_1mm_brain.nii.gz

  - name: downloaded_file
    url: https://osf.io/download/jqdcm/
