name: gingerale
version: 3.0.2
architectures:
  - x86_64
structured_readme:
  description: >-
    GingerALE performs meta-analyses via the activation likelihood estimation
    (ALE) method. It also includes the transforms for icbm2tal conversions.


    Available for download at brainmap.org/ale

    For an in-detail description of the algorithms, input and output data, and
    interesting uses - like Meta-Analytic Connectivity Mapping (MACM), see the
    GingerALE User Manual

    If you have trouble using GingerALE, or have questions about settings and
    thresholds or about meta-analysis in general, the GingerALE Forum is a good
    place to get help
  example: ''
  documentation: https://www.brainmap.org/ale/
  citation: "For\Presearch\Pusing\Pa\Pcontrast\Panalysis:\P \nEickhoff\P SB,\P Bzdoc\P D,\P Laird\P AR,\P Roski\P C,\P Caspers\P S,\P Zilles\P K,\P Fox\P PT.\P Co‐activation\P patters\P distinguish\Pcortical\Pmodules,\Ptheir\Pconnectivity\Pand\Pfunctional\Pdifferentiation.\PNeuroimage\P57,\P 938‐949,\P2011.\P \P \nFor\Presearch\Pusing\PGingerALE\P2.x:\P \nEickhoff\PSB,\PLaird\PAR,\PGrefkes\PC,\PWang\PLE,\PZilles\PK,\PFox\PPT.\PCoordinate‐based\Pactivation\Plikelihood\P estimation\Pmeta‐analysis\Pof\Pneuroimaging\Pdata:\PA\Prandom‐effects\Papproach\Pbased\Pon\Pempirical\P estimates\Pof\Pspatial\Puncertainty.\PHum\PBrain\PMapp\P30,\P2907‐2926,\P2009.\P \nand\P \nEickhoff\P SB,\P Bzdok\P D,\P Laird\P AR,\P Kurth\P F,\P Fox\P PT.\P Activation\P likelihood\P estimation\P revisited.\P Neuroimage\P59,\P2349‐2361,\P2012.\P \P \nand\P\P\P\P\P\P\P\P\P\P\P\P\P\P\P\P\P\P\nGingerALE\PUser\PManual\P–\Ppage\P13\P Turkeltaub\PPE,\PEickhoff\PSB,\PLaird\PAR,\PFox\PM,\PWiener\PM,\PFox\PP.\PMinimizing\Pwithin‐experiment\Pand\P within‐group\Peffects\Pin\Pactivation\Plikelihood\Pestimation\Pmeta‐analyses.\PHum\PBrain\PMapp\P33,\P1‐13,\P 2012.\P \P \nFor\Presearch\Pusing\PFalse\PDiscovery\PRate\Pthreshold:\P \nLaird\PAR,\PFox\PM,\PPrice\PCJ,\PGlahn\PDC,\PUecker\PAM,\PLancaster\PJL,\PTurkeltaub\PPE,\PKochunov\PP,\PFox\PPT.\P ALE\Pmeta‐analysis:\PControlling\Pthe\Pfalse\Pdiscovery\Prate\Pand\Pperforming\Pstatistical\Pcontrasts.\PHum\P Brain\PMapp\P25,\P155‐164,\P2005"
build:
  kind: neurodocker
  base-image: ubuntu:24.04
  pkg-manager: apt
  directives:
    - install: openjdk-21-jre
    - file:
        name: gingerale.jar
        url: https://www.brainmap.org/ale/GingerALE.jar
    - run:
        - mkdir /opt/gingerale
        - cp {{ get_file("gingerale.jar") }} /opt/gingerale
    - group:
        - file:
            name: gingerale
            contents: |
              #!/bin/bash

              java -cp /opt/gingerale/gingerale.jar org.brainmap.GingerALE
        - run:
            - cp {{ get_file("gingerale") }} /opt/gingerale/gingerale
            - chmod +x /opt/gingerale/gingerale
        - environment:
            PATH: $PATH:/opt/gingerale
        - deploy:
            bins:
              - gingerale
      custom: shellScript
      customParams:
        name: gingerale
        path: /opt/gingerale
        content: |
          #!/bin/bash

          java -cp /opt/gingerale/gingerale.jar org.brainmap.GingerALE
        executable: true
        addToPath: true
        makeDeployBin: true
readme: "----------------------------------\n## gingerale/3.0.2 ##\n\nGingerALE performs meta-analyses via the activation likelihood estimation (ALE) method. It also includes the transforms for icbm2tal conversions.\n\nAvailable for download at brainmap.org/ale\nFor an in-detail description of the algorithms, input and output data, and interesting uses - like Meta-Analytic Connectivity Mapping (MACM), see the GingerALE User Manual\nIf you have trouble using GingerALE, or have questions about settings and thresholds or about meta-analysis in general, the GingerALE Forum is a good place to get help\n\nExample:\n```\n\n```\n\nMore documentation can be found here: https://www.brainmap.org/ale/\n\nCitation:\n```\nFor\Presearch\Pusing\Pa\Pcontrast\Panalysis:\P \nEickhoff\P SB,\P Bzdoc\P D,\P Laird\P AR,\P Roski\P C,\P Caspers\P S,\P Zilles\P K,\P Fox\P PT.\P Co‐activation\P patters\P distinguish\Pcortical\Pmodules,\Ptheir\Pconnectivity\Pand\Pfunctional\Pdifferentiation.\PNeuroimage\P57,\P 938‐949,\P2011.\P \P \nFor\Presearch\Pusing\PGingerALE\P2.x:\P \nEickhoff\PSB,\PLaird\PAR,\PGrefkes\PC,\PWang\PLE,\PZilles\PK,\PFox\PPT.\PCoordinate‐based\Pactivation\Plikelihood\P estimation\Pmeta‐analysis\Pof\Pneuroimaging\Pdata:\PA\Prandom‐effects\Papproach\Pbased\Pon\Pempirical\P estimates\Pof\Pspatial\Puncertainty.\PHum\PBrain\PMapp\P30,\P2907‐2926,\P2009.\P \nand\P \nEickhoff\P SB,\P Bzdok\P D,\P Laird\P AR,\P Kurth\P F,\P Fox\P PT.\P Activation\P likelihood\P estimation\P revisited.\P Neuroimage\P59,\P2349‐2361,\P2012.\P \P \nand\P\P\P\P\P\P\P\P\P\P\P\P\P\P\P\P\P\P\nGingerALE\PUser\PManual\P–\Ppage\P13\P Turkeltaub\PPE,\PEickhoff\PSB,\PLaird\PAR,\PFox\PM,\PWiener\PM,\PFox\PP.\PMinimizing\Pwithin‐experiment\Pand\P within‐group\Peffects\Pin\Pactivation\Plikelihood\Pestimation\Pmeta‐analyses.\PHum\PBrain\PMapp\P33,\P1‐13,\P 2012.\P \P \nFor\Presearch\Pusing\PFalse\PDiscovery\PRate\Pthreshold:\P \nLaird\PAR,\PFox\PM,\PPrice\PCJ,\PGlahn\PDC,\PUecker\PAM,\PLancaster\PJL,\PTurkeltaub\PPE,\PKochunov\PP,\PFox\PPT.\P ALE\Pmeta‐analysis:\PControlling\Pthe\Pfalse\Pdiscovery\Prate\Pand\Pperforming\Pstatistical\Pcontrasts.\PHum\P Brain\PMapp\P25,\P155‐164,\P2005\n```\n\nTo run container outside of this environment: ml gingerale/3.0.2\n\n----------------------------------"
copyright:
  - name: BrainMap GingerALE 3.0.2 License
    url: https://www.brainmap.org/ale/license.html
