name: musclemap
version: 1.1.0
architectures:
    - x86_64

files:
    - name: musclemap.py
      filename: musclemap.py

build:
    kind: neurodocker
    base-image: pytorch/pytorch:2.4.0-cuda11.8-cudnn9-runtime
    pkg-manager: apt

    directives:
        - environment:
              DEBIAN_FRONTEND: noninteractive
        - install: bzip2 ca-certificates git wget build-essential python3-pip python-is-python3

        - include: macros/openrecon/neurodocker.yaml

        - workdir: /opt/
        - run: 
            - git clone https://github.com/MuscleMap/MuscleMap
            - cd MuscleMap 
            - pip install .

        #openrecon application

        - run:
            - cd /opt/code/python-ismrmrd-server
            # - git remote add stebo85 https://github.com/stebo85/python-ismrmrd-server.git
            # - git fetch stebo85
            - git stash
            - git remote set-url origin https://github.com/kspaceKelvin/python-ismrmrd-server.git
            # - git checkout -b stebo85-enhanced-dicom-support stebo85/add_enhanced_dicom_support
            - git fetch origin pull/13/head:pr-13
            - git checkout pr-13
        
        - copy: musclemap.py /opt/code/python-ismrmrd-server/musclemap.py
            
deploy:
    bins:
        - mm_segment

readme: |-
    ----------------------------------
    ## musclemap/{{ context.version }} ##

    An Open-Source, Community-Supported Consortium for Whole-Body Quantitative MRI of Muscle

    you can build this recipe with:
    ```bash
    ./builder/build.py generate musclemap --recreate --build --login --architecture x86_64
    ```

    ----------------------------------
