name: musclemap
version: 2.1.1
architectures:
    - x86_64

files:
    - name: musclemap.py
      filename: musclemap.py

build:
    kind: neurodocker
    base-image: pytorch/pytorch:2.3.0-cuda11.8-cudnn8-runtime
    # base-image: ubuntu:22.04
    pkg-manager: apt

    directives:
        - environment:
              DEBIAN_FRONTEND: noninteractive
        - install: bzip2 ca-certificates git wget build-essential python3-pip python-is-python3

        - include: macros/openrecon/neurodocker.yaml

        - run:
            - pip install SimpleITK

        #openrecon application
        - run:
            - cd /opt/code/python-ismrmrd-server
            - git stash
            - git remote add stebo85 https://github.com/stebo85/python-ismrmrd-server.git
            - git fetch stebo85
            - git checkout -b stebo85-enhanced-dicom-support stebo85/add_enhanced_dicom_support
            - git remote set-url origin https://github.com/kspaceKelvin/python-ismrmrd-server.git
            - git fetch origin pull/13/head:pr-13
            - git checkout pr-13
            - git checkout stebo85-enhanced-dicom-support
            - git config --global user.email "me@docker.com"
            - git config --global user.name "My Name"
            - git merge pr-13

        - workdir: /opt/
        - run: 
            - git clone https://github.com/MuscleMap/MuscleMap
            - cd MuscleMap 
            - echo "test"
            - git checkout origin/improve_efficiency_v2
            - pip install .
        
        - environment:
              MKL_THREADING_LAYER: GNU
              NVIDIA_VISIBLE_DEVICES: all
              NVIDIA_DRIVER_CAPABILITIES: compute,utility

        - copy: musclemap.py /opt/code/python-ismrmrd-server/musclemap.py
        - copy: nifti2mrd.py /opt/code/python-ismrmrd-server/nifti2mrd.py
        - copy: enhanceddicom2mrd.py /opt/code/python-ismrmrd-server/enhanceddicom2mrd.py
            
deploy:
    bins:
        - mm_segment

readme: |-
  ----------------------------------
  ## musclemap/{{ context.version }} ##

  An Open-Source Whole-Body Quantitative MRI tool of Muscle

  ----------------------------------
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAB/ElEQVR4AbSUS8tpURzGn+1e5BYGKIpiZqbMTQyUAV/WJ5CJZOSSJHIXueTueNab98z81+m8r/ayN2uv57ee9b+YADx1RzgcfkajUe33qUvA6653FYtFVCoVmEz6y/TffO1hv99jNBrh+aSJ1x8alzYgEAjgfr/DbDbD6/VqSH+9IgKsVitKpRLK5TLm8zlmsxny+TwKhcKXgvAtAoLBoDqSbreLzWaD3W6H4/GoQDpORADPnS4sFgt8Ph8SiYQ6osfjAcMwIH1EAMUZWIrTDWOQyWRgt9txOp0kfYgA7jQUCiGVSiGdTsPtdmO1WuFVE7jdbv8PYEput1uVQc1mE3zu9XoYDoegO4kgOqDA9XrFeDxWDpLJJKbTKc7n8884YNXmcjlEIhG1ezrIZrPq9+VyIf/jEB0wqNxxtVpFp9NBq9VCvV6HzWaD0+n8KM5JEcDqZd5z58wcj8ejgrxYLFTaUuTTEAEsrFqtBr/fr9oEz54F1mg0VF/6JM45EcAATyYTxGIxrNdrsPBeLVsFmQLSEAFvATqIx+NgFhmGXMHvddoAxoKpOhgMtNLznwHsoqxg3tlV3wLSXdvBcrkE48H+czgcJN3veW0Ai4riPCr2p28F4UEbYBiG6j0OhwMul0uQ/TutDWA9cBkBvxKDdrsNdlG2in6/T5bW+AMAAP//wtg5bQAAAAZJREFUAwAZcfw0V/0rGAAAAABJRU5ErkJggg==
categories:
  - body
copyright:
  - license: MIT
    url: https://github.com/MuscleMap/MuscleMap?tab=MIT-1-ov-file#readme
