name: connectomeworkbench
version: 2.1.0

copyright:
  - license: GPL-2.0
    url: http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
    
architectures:
  - x86_64
  - aarch64

build:
  kind: neurodocker

  base-image: neurodebian:bookworm-non-free
  pkg-manager: apt

  directives:
    - install: connectome-workbench

deploy:
  bins:
    - wb_view
    - wb_command
    - wb_shortcuts

categories:
  - "functional imaging"
  - "data organisation"
