name: vesselboost
version: 1.0.3

architectures:
    - x86_64

build:
    kind: neurodocker

    base-image: pytorch/pytorch:2.4.0-cuda11.8-cudnn9-runtime
    pkg-manager: apt

    directives:
        - environment:
              DEBIAN_FRONTEND: noninteractive

        - workdir: /opt/code

        - install:
              - build-essential
              - libxslt1.1
              - libhdf5-103
              - libboost-program-options1.74.0
              - libpugixml1v5
              - vim
              - dos2unix
              - git
              - cmake
              - g++
              - libhdf5-dev
              - libxml2-dev
              - libxslt1-dev
              - libboost-all-dev
              - libfftw3-dev
              - libpugixml-dev

        - run:
              - git clone https://github.com/ismrmrd/ismrmrd.git
              - cd ./ismrmrd
              - cmake .
              - make -j $(nproc)
              - make install

        - run:
              - git clone https://github.com/ismrmrd/siemens_to_ismrmrd.git
              - cd siemens_to_ismrmrd
              - mkdir build
              - cd build
              - cmake ..
              - make -j $(nproc)
              - make install

        - run:
              - pip3 install h5py ismrmrd matplotlib pydicom pynetdicom nibabel

        - run:
              - git clone https://github.com/ismrmrd/ismrmrd-python-tools.git
              - cd ismrmrd-python-tools
              - pip3 install --no-cache-dir .

        - run:
              - git clone https://github.com/kspaceKelvin/python-ismrmrd-server
              - find /opt/code/python-ismrmrd-server -name "*.sh" -exec chmod +x {} \;
              - find /opt/code/python-ismrmrd-server -name "*.sh" | xargs dos2unix

        - workdir: /opt

        - run:
              - git clone https://github.com/KMarshallX/VesselBoost.git
              - cd VesselBoost
              - chmod a+x angiboost.py

        - workdir: /opt/VesselBoost/

        - run:
              - pip install -r requirements.txt

        - workdir: /opt/VesselBoost/saved_models

        - run:
              - osf -p abk4p fetch osfstorage/pretrained_models/manual_0429

        - run:
              - osf -p abk4p fetch osfstorage/pretrained_models/omelette1_0429

        - run:
              - osf -p abk4p fetch osfstorage/pretrained_models/omelette2_0429

        - workdir: /opt/VesselBoost/

        - environment:
              PATH: $PATH:/opt/VesselBoost/

        - copy: vesselboost.py /opt/code/python-ismrmrd-server/vesselboost.py

deploy:
    bins:
        - python

readme: |-
    ----------------------------------
    ## Vesselboost/{{ context.version }} ##
    This containers provides an interactive deep learning vessel segmentation algorithm

    Example:
    ```
    prediction.py --ds_path $path_to_images --out_path $path_to_output --pretrained $path_to_pretrained_model --prep_mode 4

    ```

    More documentation can be found here: https://github.com/KMarshallX/VesselBoost

    To run applications outside of this container: ml vesselboost/{{ context.version }}

    ----------------------------------

files:
    - name: vesselboost.py
      filename: vesselboost.py
