name: vesselboost
version: 2.0.0
copyright:
  - license: MIT
    url: https://github.com/KMarshallX/VesselBoost/blob/master/LICENSE
architectures:
  - x86_64
build:
  kind: neurodocker
  base-image: pytorch/pytorch:2.4.1-cuda11.8-cudnn9-runtime
  pkg-manager: apt
  directives:
    - deploy:
        bins:
          - python
    - environment:
        DEBIAN_FRONTEND: noninteractive
    - include: macros/openrecon/neurodocker.yaml
    - workdir: /opt
    - run:
        - git clone https://github.com/KMarshallX/VesselBoost.git
        - cd VesselBoost
        - chmod a+x angiboost.py boost.py prediction.py test_time_adaptation.py
    - workdir: /opt/VesselBoost/
    - run:
        - pip install -r requirements.txt
    - workdir: /opt/VesselBoost/saved_models
    - run:
        - osf -p abk4p fetch osfstorage/pretrained_models/manual_0429
    - run:
        - osf -p abk4p fetch osfstorage/pretrained_models/omelette1_0429
    - run:
        - osf -p abk4p fetch osfstorage/pretrained_models/omelette2_0429
    - run:
        - osf -p abk4p fetch osfstorage/pretrained_models/t2s_mod_ep1k2_0728
    - run:
        - osf -p abk4p fetch osfstorage/pretrained_models/BM_VB2_aug_all_ep2k_bat_10_0903
    - run:
        - osf -p abk4p fetch osfstorage/pretrained_models/VB2_aug_off_ep2k_bat10_0903
    - run:
        - osf -p abk4p fetch osfstorage/pretrained_models/VB2_aug_random_ep2k_bat10_0903
    - run:
        - osf -p abk4p fetch osfstorage/pretrained_models/VB2_aug_spatial_ep2k_bat10_0903
    - run:
        - osf -p abk4p fetch osfstorage/pretrained_models/VB2_aug_intensity_ep2k_bat10_0903
    - workdir: /opt/VesselBoost/
    - environment:
        PATH: $PATH:/opt/VesselBoost/
    - copy: vesselboost.py /opt/code/python-ismrmrd-server/vesselboost.py
readme: |2-
    ----------------------------------
    ## Vesselboost/{{ context.version }} ##
    This containers provides an interactive deep learning vessel segmentation algorithm

    Example:
    ```
    ml vesselboost/2.0.0
    prediction.py --image_path $path_to_images --output_path $path_to_output --pretrained $path_to_pretrained_model --prep_mode 4
    ```

    More documentation can be found here: https://github.com/KMarshallX/VesselBoost

    To run applications outside of this container: ml vesselboost/{{ context.version }}

    ----------------------------------
categories:
  - image segmentation
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAEVElEQVR4AXxTS0ycVRT+7j8wM4xKEWpSO1NQnBoKaYyxWmbUDh1a46ZLF7KFhYK2WqtLFrggqc/6fsCCTDcaNibaGEN4bCAhLqptCAkLI4y1MvU1aNuZljk9373z6pT25v/+e+49537nda/333hINsZCkv0yJP9+EZJ/Pm+w+PuzBvnr0wb585OgXPo4KJmPHNY/DMofHwTl4qmA/P5+QC685/Dbu35Jv+OXtbf9svqWX349WW/hiRgABIrDgHsixaXVOT33iJKmNHOPgLVFcTgedSBKSEBngjJBGSgUKBPYUi/K7EC9VNmL2gs8ulMbXVCikZv55z7nWohmLcUMRWUUIxe7x2wJ2OFVIpSy90IBZZmHqteUXcTV9hWZOnISlDUDg18ywJNv5tD84hW0DF7F9qErOHnmOvKbwDXFqR+uY8exnMXOV3MgwsfziLyWx64TebS+nkfbG9csTny9ict5Bl/Vgx3bgMNd6kv3p6amkE6nkW1K4FJWkMkW8P25Akr7o6OjyGazWlK5CblcDiMjI8oA3SecXpsMBOqA3i4f7gkC8/PzaGxsRGtnAufSgrOrgu27e9DR0YHl5WUsLS1ZkvHxcRhjyggEAhgeHrY6lpXgQh2IrXfH/UAs6mF2dtZGuL87jjM/beLbswU8daAHJJiYmOCZO8IS64/1Z7+0LkYPGGxrMHh2rw8zM9M2UkZ8MZTA5I+biMfjWF9fx+lUSm1v/3lKFWs38GtFxN4uoHyLjJ7rfshD+33GlokRh8NhJJNJW56FhQU0361Gxa+/v19rLWWwbwfVljdV9McMCK9ob6fIvQbJPR5WVlZsSRKJBPr6+mxP5ubm0NbCMKwpansQiUQwMz2tDp2efzrSHkB7QAjqfYJedTD5VQpra2uIxWIWi4uL+GYyhdbmigMS1EIfPc5fKOD/q2I5yw6qDbvCBvse8MCSdHZ2IhqN2pI98aCH5rvu7IA8P6dRfAdcAZqBaFoEdIY2G3imy4Al2djYQCaTUXkWh/YYm6E7BtT2gPUeGxuzHIyca75m2wPRjou4oz69CvGo3qbvTtvas7ar52fwWJuBUZOU3qRGfSfGGBhzMwYGBtSi9BkVDPQWMXJmIFo3h7Zm4JVDHlr01uxsMjjW6yHSBDy92+D4Yc+uuXc06YF4+aAH4qjOzz8ONNQ7noJGXcyATqCDXmHv8ZFHfCCe22e0ZB4C9Qbd7R4Gezy8pERD5dlgqMdgMGHwwgGDI3sNQn6l4qdVqemB88z68UYlHiapgc+I1rYEFwxtCL5WDfS2enVgABDuoJMNtBXYr6/y0V1M0igB7CCZFfRXLetSvwqPaF+hvOpAyrVnRAS7TwTrBHWeKLmDi1aK9i6gij3XTsc9ghwMD27QeyVSqHcXBQ8S1OOWIVrn0mZJ5kxwX2+RVEVYkklYLW+9ZoQkctjaXjNgZAT9ES4LHuKqNJfkyppnCDonKBO0JMhjcAMAAP//XmBjawAAAAZJREFUAwDbnijio+Pt8gAAAABJRU5ErkJggg==
