name: laynii
version: 2.2.1

copyright:
  - license: BSD-3-Clause
    url: https://github.com/layerfMRI/LAYNII/blob/master/LICENSE

architectures:
  - x86_64

build:
  kind: neurodocker

  base-image: ubuntu:18.04
  pkg-manager: apt

  directives:
    - environment:
        DEBIAN_FRONTEND: noninteractive

    - install:
        - wget
        - ca-certificates
        - unzip

    - workdir: /opt/laynii-2.2.1/

    - run:
        - cp {{ get_file("LayNii_v2_2_1_Linux64_zip") }} LayNii_v2.2.1_Linux64.zip
        - unzip LayNii_v2.2.1_Linux64.zip
        - rm LayNii_v2.2.1_Linux64.zip

    - environment:
        PATH: $PATH:/opt/laynii-2.2.1/

deploy:
  path:
    - /opt/laynii-2.2.1/

readme: |-
  ----------------------------------
  ## LayNii/{{ context.version }} ##
  LayNii is a standalone software suite for mesoscopic (functional) magnetic resonance imaging (e.g. layer-fMRI).
  It is a collection of C++ programs that depend only on a C++ compiler.
  The purpose of this package is to provide layer-analysis software that are not (yet) included in the other major MRI analysis software.

  Example:
  ```
  cp -r /opt/laynii-{{ context.version }}/test_data/ ~
  cd ~/test_data
  LN2_LAYERS -rim sc_rim.nii -nr_layers 10 -equivol
  LN2_LAYER_SMOOTH -input sc_VASO_act.nii -layer_file sc_layers.nii -FWHM 1
  LN_BOCO -Nulled lo_Nulled_intemp.nii -BOLD lo_BOLD_intemp.nii
  ```

  Tests:
  ```
  cp -r /opt/laynii-{{ context.version }}/ ~
  cd ~/laynii-{{ context.version }}/test_data
  ./tests.sh
  ```

  More documentation can be found here: https://github.com/layerfMRI/LAYNII
  Algorithm explanations can be found here: https://thingsonthings.org/
  and here: https://layerfmri.com/category/laynii/
  Video tutorials of how to use LayNii are available here: https://youtube.com/playlist?list=PLs_umVHtShfadNm8brOweXHUSmqVDTk4q

  To run applications outside of this container: ml laynii/{{ context.version }}

  Citation:
  ```
  Huber, L., Poser, B. A., Bandettini, P. A., Arora, K., Wagstyl, K., Cho, S., Goense, J., Nothnagel, N., Morgan, A. T., van den Hurk, J., Mueller A. K., Reynolds, R. C., Glen, D. R., Goebel, R. W., Gulban, O. F. (2021). LayNii: A software suite for layer-fMRI. NeuroImage, 118091. https://doi.org/10.1016/j.neuroimage.2021.118091
  ```

  ----------------------------------

categories:
  - "functional imaging"
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAACXBIWXMAAC4jAAAuIwF4pT92AAAI2ElEQVRYhWWXS4wcVxWGv3NvVfV73g+PZzx+2xnHTuJYITFEkSIgiUKExAYJiUVAFhESyppFFohFUDYgFiDEgg1igwKLiE2kICKCHWxE7MROIo8zfkzG855uz6OfVfceFlXdMwkltbqr+tZ53f/857/yizde1067Q+8SQEFQFEAE9R6XJKgqItk6VRRJ75V0bfY6dO+190T2PPEK1lpKpRKBtTbz2H01fUcR1CtJ3KEcBRw7dZLhqUOo+HS9FbwH9QYTeEQVvGROUsfdpd1LgY6HSmi5c/s2C/fvE5Blude7qieOY8q5kMceeoj8qfP8zRzk/c0QaYDUwK2CvQ/RSof20QgZBSaACNRniZdBQ8CnllsxPD2ivHFKQJV78/NZAL2qKnHcoRhazp6eoXjmPG8m0/x5NaQ27+B6AnWFm5bico1XJ3/FM8MX+d1br/DWxnfgWAjTCi6raFFhCHjEA4anRxzf7Fd+/FHEy3GMiKQBpI5jCmHA6ZnjlE89ydvhMf64GLJed5BLkBWFdYFA0A3hcH6Rl4+8ycmX7rD2+zH+vvoi9fUI2Z9iAw+yJWjOgxe+Ou752XHPqzcMJm+IjEFRAlVFgEdOHmf0sfP8VY7yl2XL0o4DE2ODzNgMyLCHTUHHE+Y+OcZP5n/D0d/OcdF9jc4TBcITMfRLCkoDDCuuT3h6XPn5Cc+PblhubVvOV4A49Ruo9zz34reYevhxPm0oD28lnDuREJgMmwZUsj216bckoF5oV5/FxV/nfC4mGHBpZ4QmhbmmnRIpjIbCKzeEW1WT2tkDuSBnhWphmG9fEhKnhFGItBWaCoEgmwrtLCOR3YYRUONBHBILWgygBCRAATQCjYUDuYQLB4XZNYO5BH5E4VAWHxCA0kk8NWdIGsB1B6sK2wItgVigIbCjGUfIngwUMNCnUNC0QgWgAkwIHBJCMWCAbeBB6lHiPRXokkQQgPvMI58I1AT/uYFNA6IEJOiel3pk0c0jEpwP0t4fVOy0w68p3oA9kwW6BBiBbfA7QLgnAASkDawA64r/KCSUDmOlVfK2jRWH8wYR33PtyUCiYIwSq2UnKfNgdZBkPSI4m+CXFDnFbuWCdBt7MNA9AdBU2AG/YMjZFocG7hLRwSP091cZHljHOcNg/xalYoPV9RHixCLAWm2MnZ0+KmGdwVyNO7Uj+MUApjx0Wd6Dv2+h4jExEGpa+ZQqFbUCTYFNy3BxmZCYUmWLs6evMjq0QS6KccaikmY+Ob2MqMd6T6udY2l9lGs3zkJLqeQ3qa2PQkezPfdw1yLXPVqxaA20knJ0IKQ4kk2gI4h4craFiufxM9eYnrhPyxXp+BxDazVy7WY6oETYLlfYKZcIQs/x6XskccSVa1+hEDSpJQot4IHivSFaqvPD6T+w0Bpm48730Kl0IwLNuosWaBtCiYkkZrCvytjgGk1XolBvcOb6VcaWFhHvezB0QcCtkzPcfOhhWkmeAxPLfDy7Q8flMDh8U6ADneWQM6v/5pfffZ3Zrf28tvEC3gUpE/YQbYAtIAa8YbC/TpDz+LbjicsXGVpfJewkDK9tYhNPq5RjbXSAU9evoSLcOjlDlOtQLjWobY+kdhopf5jIsxNVWN0eZG17kDiKEMm6r9fUsjs3VZQoauJswL6VRQY21sk3OxyZm8ccdvgxGPoIytt17h6Z5PCtWRamD9Eu5HE+QDJ674IvGk+YHZ7hwtu/ZqXdT/EHFWyQoCKY7vRW7VJLKh1GhqqAMrqyiHWOyYUlzBmHe83CG4bOBUOFLQaq2+TaTcpbm6gRSoWtzIbs0p2AHgx4Z/U5rgdPYqd7mWJ2Q01BIZJWwGNQL9g4xsSOnMbwrGBeyqHPjBI8DxyBwnYrtaUGMY79E8v4HlkaRMGHwIQiTzl41KF96SxBSNtQ9+5A9m3FgUAnyqFWcLHBfOjh4w52qobeFMwyJJFN1RAKalnbGMtqqD1j0q1GX8qGYnbZPOguSIdN2hKKsLXTz4QuUx0ewQWGpX0jHPrXEvpTjx6G4H1HoxpRPVGhE0Y0iwUkUaqbfakyM3tnBpBXREHz6acr14IeJ7IbtChsb5ex3rE2NsFWuQ9UmWcfQ/99gPkA4jDP4tExvMC9g4fZ7h8g8h2M9Wk196pUBcYNXFeYUlwRTN1mAWRDDs/uRBOl3irhE0tSCLh67jwzN64SBwG1oQrWK4k1xEHA4sQBZmfOECYx7bjETr2CFZ8Om6KCyzRiGfRRhQnL86UOizfmkMBkFdC0RPR5EglINGRldYzFtSkO7p+jOj7G5YFnKW/VGF9aJOp0aBZKLE9O0ij3YYySD1t8Nn+cZr1I0xdwaqGYQFERJ5AX9LTlYMnwjcYs/7x9m7BUyTShzwASgqrQSQr0Bdt8cOMszodMjs0jkWFnbIStfcNZtyjihcB5Gs0ydz8/zsc3ZwhNQisupGXNC/RrWl2vkMD3p+qs/OcSLadEIrvDCAdSBPo9a7URStEOvt7k4pVzjI8eJR+1KBXrFIsN8Ol0rW0OEich1Wo/9UYeYxwNV6ZWH0ImFc0BTnqENDNseCGe4525e4RhhPTGsQeKAiUwU564GnG7eoSR4gaFoMn8UgRdcvkCtFOkWeNouzyNpEi1MYS3Frvf4UugkWQsJ1wYrbNy+QqJCKFoxgPdQ0kEOp5Kb/t4gp83rGyNI14xsUOd7B5gRDOlCqgiecWl6g4z5rAHE+gXdELBKh0v7O8znNua5R+f3SEMw14eQZeKkwQ4JjjrYTVlLhKPxuCqpLO9y1aSOk71oaZSvJBAoPhQYADYp3BAcEmqSS6MNVh4/wpOpaeCtEtEuTBkPIKmMchjFul4aKYiReopeHp88SVRKqT/azEDnQctmBTQsdAfKE+NBvi5T3n38wWCcPcwJkDQjJX8xgJ/GmwRe9clw6zCWYbdVv3CGbL7LPvh99z73f+tMVRut3nvvXdxItg9NpxzBOVKmcuX3ts9JMqXje/63+tYRVOO/79gvrwOYucxxlIpV75AkLl8nv8B98w4PMmULVAAAAAASUVORK5CYII=

files:
  - name: LayNii_v2_2_1_Linux64_zip
    url: https://github.com/layerfMRI/LAYNII/releases/download/v2.2.1/LayNii_v2.2.1_Linux64.zip
