name: test-tzdata
version: 1.0.0
architectures:
  - x86_64
build:
  kind: neurodocker
  base-image: ubuntu:24.04
  pkg-manager: apt
  add-default-template: false
  directives:
    - install: [curl]
readme: Test recipe for tzdata issue
copyright:
  - license: MIT
    url: https://example.com
