name: bart
version: 0.9.00

copyright:
  - license: BSD-3-Clause # has to be SPDX Identifier
    url: https://github.com/mrirecon/bart/blob/master/LICENSE
    
architectures:
  - x86_64

build:
  kind: neurodocker

  base-image: docker.io/nvidia/cuda:12.0.0-devel-ubuntu22.04
  pkg-manager: apt

  directives:
    - install:
        - make
        - gcc
        - libfftw3-dev
        - liblapacke-dev
        - libpng-dev
        - libopenblas-dev

    - workdir: /opt/bart-0.9.00/

    - run:
        - tar -xz -C /opt/bart-0.9.00/ --strip-components 1 -f {{ get_file("v0_9_00_tar_gz") }}

    - run:
        - CUDA_BASE=/usr/local/cuda/ CUDA_LIB=lib64 CUDA=1 make -j 8

    - environment:
        PATH: /opt/bart-0.9.00:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:~/.local/bin
        TOOLBOX_PATH: /opt/bart-0.9.00/

deploy:
  path:
    - /opt/bart-0.9.00/

readme: |-
  ----------------------------------
  ## bart/{{ context.version }} ##
  The Berkeley Advanced Reconstruction Toolbox (BART) is a free and open-source image-reconstruction
  framework for Computational Magnetic Resonance Imaging. It consists of a programming library and a
  toolbox of command-line programs. The library provides common operations on multi-dimensional arrays,
  Fourier and wavelet transforms, as well as generic implementations of iterative optimization algorithms.
  The command-line tools provide direct access to basic operations on multi-dimensional arrays as well
  as efficient implementations of many calibration and reconstruction algorithms for parallel imaging
  and compressed sensing.

  Example:
  ```
  bart
  bart version
  bart bench
  ```

  More documentation can be found here: https://mrirecon.github.io/bart/

  To run container outside of this environment: ml bart/{{ context.version }}

  License: 3-clause BSD license, https://github.com/mrirecon/bart?tab=BSD-3-Clause-1-ov-file#readme

  ----------------------------------

categories:
  - "image reconstruction"
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAIAAAAlC+aJAAAACXBIWXMAAC4jAAAuIwF4pT92AAAF8mlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNy4xLWMwMDAgNzkuN2E3YTIzNiwgMjAyMS8wOC8xMi0wMDoyNToyMCAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV2ZW50IyIgeG1sbnM6ZGM9Imh0dHA6Ly9wdXJsLm9yZy9kYy9lbGVtZW50cy8xLjEvIiB4bWxuczpwaG90b3Nob3A9Imh0dHA6Ly9ucy5hZG9iZS5jb20vcGhvdG9zaG9wLzEuMC8iIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIDIyLjUgKFdpbmRvd3MpIiB4bXA6Q3JlYXRlRGF0ZT0iMjAyMS0wOS0yOVQwODozNjozOSsxMDowMCIgeG1wOk1ldGFkYXRhRGF0ZT0iMjAyMS0wOS0yOVQwODozNjozOSsxMDowMCIgeG1wOk1vZGlmeURhdGU9IjIwMjEtMDktMjlUMDg6MzY6MzkrMTA6MDAiIHhtcE1NOkluc3RhbmNlSUQ9InhtcC5paWQ6MGRiNTUyODAtZTdiNi03YTQ5LThmZGQtYjY4NTM0NzNkYmJkIiB4bXBNTTpEb2N1bWVudElEPSJhZG9iZTpkb2NpZDpwaG90b3Nob3A6OTNiNGYzYWMtYzBjMS05MTRjLWFkNDUtNDQxN2UzODVlODc2IiB4bXBNTTpPcmlnaW5hbERvY3VtZW50SUQ9InhtcC5kaWQ6OWNhY2I3YjctNmQzMS04ZjQxLTk0OWEtMzc0MGM1MGMwMDRhIiBkYzpmb3JtYXQ9ImltYWdlL3BuZyIgcGhvdG9zaG9wOkNvbG9yTW9kZT0iMyIgcGhvdG9zaG9wOklDQ1Byb2ZpbGU9InNSR0IgSUVDNjE5NjYtMi4xIj4gPHhtcE1NOkhpc3Rvcnk+IDxyZGY6U2VxPiA8cmRmOmxpIHN0RXZ0OmFjdGlvbj0iY3JlYXRlZCIgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDo5Y2FjYjdiNy02ZDMxLThmNDEtOTQ5YS0zNzQwYzUwYzAwNGEiIHN0RXZ0OndoZW49IjIwMjEtMDktMjlUMDg6MzY6MzkrMTA6MDAiIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkFkb2JlIFBob3Rvc2hvcCAyMi41IChXaW5kb3dzKSIvPiA8cmRmOmxpIHN0RXZ0OmFjdGlvbj0ic2F2ZWQiIHN0RXZ0Omluc3RhbmNlSUQ9InhtcC5paWQ6MGRiNTUyODAtZTdiNi03YTQ5LThmZGQtYjY4NTM0NzNkYmJkIiBzdEV2dDp3aGVuPSIyMDIxLTA5LTI5VDA4OjM2OjM5KzEwOjAwIiBzdEV2dDpzb2Z0d2FyZUFnZW50PSJBZG9iZSBQaG90b3Nob3AgMjIuNSAoV2luZG93cykiIHN0RXZ0OmNoYW5nZWQ9Ii8iLz4gPC9yZGY6U2VxPiA8L3htcE1NOkhpc3Rvcnk+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyIj8+iWh8igAABgxJREFUaN7tWslLHGkUt9t2S4w74pq4xF1REdxFxUgUAhEED8khFzdE8TR/gKhgEG9xuXgScxL0YCCCKO5eXFoxYkSNGy64xDXGuMwvvuFNpbqrujOjTMvUOyRfffVV1fu99fc6UV1fX5vdZ1Gb3XNRACgAFAAKAAWAAkABoAD4PwPQ0F+bm5vHx8dqtSSeq6srd3f3hw8fmhoAFdHpvLy8Dx8+yADAsdbW1pcvX5qoB2D+09NT+aPfvn0z3RAyNzf/eaHRpKSk2NraImB0Q8jb29t0AZA8ePCgpaXF09PzHleh8/Pz+11G792IrJG6MTg4+PHjR5VK9XfBUqk8PDwSEhIiIyMNnsfJ4uJivvzx40dDQ8POzo7wERsbm5CQkPT0dAcHB9ppampaX1+XUgmJWlJS4urqKjY55MWLF1jb2dktLCzQTlVVld63WFtb4y1nZ2fXv0pBQYHwGHTa3d3lu6hygKT3hUFBQb29vXQMeOTtPTk5KfquZOG3srLSuw/VYcu6ujrR/tLSkvASGq+srAi99+jRI70vnJube/XqFTopF0O5tiWICAMhJHRcUlISPr+2tqbVammzubm5rKyMdYK6IgAXFxfYiYqK0n0hXBEdHY1qMTY2tre3h52NjY2Ojg6EXEZGBvq9hYXF4eHh8PAwVXO4xc/P7/LyEvv29vZ6WqzeEKqtraUDaAtfvnzBDmyflZXF4TszM8N+hBVxjPzGrnv79i0fODk5QajQ/ps3b2izu7ubD+fn5wsD4/Pnz3zr3bt319JiFJlDCpJymZmZbGBhwUW0wAlYBAcHcxxDCSlaRYvExMTHjx/Ten9/X+RAXsP2hssorIs/YSfdHiysrVJkDn6jRWhoaEREhGhTRiwtLUWodKu5fGXXsDEozygSpOT79+9/PabRCLOcjR0QEMD7cMvR0ZFU7ooNqVb/qz5QUVEhk/iMamhoiBagG0JqND8/TwtkG+osrbe2tlBb5AFQcEKcnJxuuZEJyUVjY6OLi8vo6GhbWxttFhYWMiocQJbT+smTJ+wBBOTy8jJ8InohigktpqamUNloHRsbe1cAEDaVlZVCX/9xI7yzvb1N7ROqwzPQD6SQyDmq07Nnz0QvHB8fr6mpwVMwBx17+vRpTk7OXQHQFRRQmBbGpkusqYYgDNDnkR5wF3WxT58+6e2mEL4MDw9HE8AjdzUTo5HFxcWBsaBEUrno7OxELafCRRlMhQI9CJ0ElYpZA+eGjAA8OtodDvXoWe/fv+/p6cFnysvLabOvr48TmrVEJFCr9/HxYefoznFubm7Pnz+Pj48n4oDwgzlmZ2fv8FcJKtKIbNA4ztGJiQkRAASDaLF1I6K3QXvw1pGREbRYqp5wJqLISI1RG5A/ILZUwYwCwK0ENZF7GWo8tczFxUXeGboRHq8PDg7gBKm3vX792svLi9bT09NGAqiurg4LC4ONUAx+O4nVNyIkhuDMzOBrb0T0COClpqbqBYCOgbyndOeMMihfv36luYK4zO/1P3ybez7pAe2BQeYRmTyGCUTmMEaYctMjhj2Acxw24L0UOUxjwJmJeCE3wDdZD5QmSl9iGcbrd/t9ALnS3t4O4oDsQUvm5k9VlVlQTExMf38/WzQ7O7urq4s88JP0GqI6/xihYQCIztLSUtEmCmVaWpqwVfn6+grnKX9/f1qsrq4iZB0dHeXLg5A/304ZlWHh6Fb19fXOzs7IB3RlpnHCM3yJPoU8BjaeH1hXWJ0BiOZ97DPzlZ8HJD0Am4EsiDyLTXTloqIimhUxxCD0iVNgShSeRJmjx6EKlMMCLqICgEYm7PFEQ3AAYyRMwwkWGBhIGKS898uPu3pJKIJHBABdGVRH2OCQGPyrnjCEhLcAEgrxtAS2x5QbXyEtoQZKBb8BJ9FMaGjER5nAQjCLowNiMTAwkJycrJGZlXhckmkLUnRf95beaU7qK3hcarQS/XKhMTNJAQGBc3RLE7RHdzd1AAib3NxcrVarW3wBScQOTdQD9C9G8meoOpkoADBWdED59kczkEr5H1sKAAWAAkABoABQACgAFAAKgP9M/gSSsouQLi2nsAAAAABJRU5ErkJggg==

files:
  - name: v0_9_00_tar_gz
    url: https://github.com/mrirecon/bart/archive/v0.9.00.tar.gz
