name: voreen
version: 5.3.0

architectures:
  - x86_64
  - aarch64

build:
  kind: neurodocker
  base-image: ubuntu:24.04
  pkg-manager: apt

  directives:
    - environment:
        DEBIAN_FRONTEND: noninteractive

    - install:
        - build-essential
        - cmake
        - libglew-dev
        - libboost-all-dev
        - libboost-math-dev
        - libdevil-dev
        - qtbase5-dev
        - libqt5svg5-dev

    - workdir: /root

    - run:
        - cp {{ get_file("voreen_src") }} voreen-src-{{ context.version }}-unix.tar.gz
        - tar -xf voreen-src-{{ context.version }}-unix.tar.gz

    - run:
        - cd /root/voreen-src-unix-nightly && sed -i '/math_c99l/d; /math_tr1l/d' cmake/FindBoostVRN.cmake && perl -0pi -e 's@static void cpuid\\(int CPUInfo\\[4\\],int InfoType\\)\\{\\n        __asm__ __volatile__ \\(\\n            "cpuid":\\n        "=a" \\(CPUInfo\\[0\\]\\),\\n            "=b" \\(CPUInfo\\[1\\]\\),\\n            "=c" \\(CPUInfo\\[2\\]\\),\\n            "=d" \\(CPUInfo\\[3\\]\\) :\\n        "a" \\(InfoType\\), "c" \\(0\\)\\n            \\);\\n    \\}@static void cpuid(int CPUInfo[4],int InfoType){\\n#if defined(__i386__) || defined(__x86_64__)\\n        __asm__ __volatile__ (\\n            "cpuid":\\n        "=a" (CPUInfo[0]),\\n            "=b" (CPUInfo[1]),\\n            "=c" (CPUInfo[2]),\\n            "=d" (CPUInfo[3]) :\\n        "a" (InfoType), "c" (0)\\n            );\\n#else\\n        CPUInfo[0] = CPUInfo[1] = CPUInfo[2] = CPUInfo[3] = 0;\\n        (void)InfoType;\\n#endif\\n    }@s' ext/tgt/cpucapabilities.cpp && mkdir build && cd build && cmake -DBoost_NO_BOOST_CMAKE=ON -DVRN_DEPLOYMENT=ON -DVRN_ADD_INSTALL_TARGET=ON -DVRN_MODULE_STAGING=OFF -DCMAKE_INSTALL_PREFIX=/usr/share/voreen/ .. && make -j8 && make install && rm -rf /root/*

deploy:
  bins:
    - voreenve
    - voreentool

categories:
  - visualization

gui_apps:
  - name: voreenGUI
    exec: voreenve

readme: |
  ----------------------------------
  ## voreen/{{ context.version }} ##
  Voreen is an open source rapid application development framework for the interactive visualization and analysis of multi-modal volumetric data sets. It provides GPU-based volume rendering and data analysis techniques.

  Example:
  ```
  voreentool -platform minimal -w someworkspace.vws --script somescript.py
  ```

  More documentation can be found here: https://www.uni-muenster.de/Voreen/documentation/index.html

  To run container outside of this environment: ml voreen/{{ context.version }}

  Citation:
  ```
  Jennis Meyer-Spradow, Timo Ropinski, Jorg Mensmann, Klaus H. Hinrichs:
  Voreen: A Rapid-Prototyping Environment for Ray-Casting-Based Volume Visualizations. IEEE Computer Graphics and Applications 29(6): 6-13 (2009)
  ```

  License: GNU General Public License
  ----------------------------------

files:
  - name: voreen_src
    url: https://www.uni-muenster.de/imperia/md/content/voreen/release/voreen-src-{{ context.version }}-unix.tar.gz
