name: hnncore
version: "0.3"

copyright:
  - license: BSD-3-Clause
    url: https://github.com/jonescompneurolab/hnn-core/blob/master/LICENSE

architectures:
  - x86_64
  - aarch64

build:
  kind: neurodocker

  base-image: ubuntu:22.04
  pkg-manager: apt

  directives:
    - environment:
        DEBIAN_FRONTEND: noninteractive

    - install:
        - python3.9
        - python3-pip
        - libpython3-dev
        - build-essential
        - openmpi-bin
        - openmpi-doc
        - libopenmpi-dev

    - run:
        - pip install numpy scipy matplotlib NEURON

    - run:
        - pip install ipywidgets voila scikit-learn joblib mpi4py psutil

    - run:
        - pip install hnn_core hnn_core[opt] hnn_core[gui]

deploy:
  bins:
    - hnn-gui

readme: |-
  ## hnncore/{{ context.version }} ##
   ----

   Description:
   Simulation and optimization of neural circuits for MEG/EEG source estimates

   Example:
   hnn-gui

   https://jonescompneurolab.github.io/hnn-core

categories:
  - "electrophysiology"
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAKM0lEQVR4nO1aC3BU1Rn+zn/v3r3ZJBvyICEJiAYCCIohoTgRCANUDUZbajt1qtPWwdE6MmortiK1WqdTxMfYmaodX/Xd+mK0KiCiBOoLqAQjEMLT0JCkFfPcZDd3773nnM65m0Aey8vH2M7tl/lzds/uOfec7/yv8ydMSgk/g+BzEHwOgs9B8DkIPgfB5yD4HASfg+BzEHwOgs9B8DkIPgfB5yD4HASfg+BzEHwOgs+hJ+u89a47t4XRNWpFzQXiV2Vv0WuNU8SBSCYtn75OLPzxXWfk5WQ5qpbIGPO+z7mAphGqqxsL2jYv/6R65/h4LK4FZk/ahyc3zpLfKmpkc0ra6yquvGd+VhakGkuUGKsghQQjhsba9pR37ri/UQ+6vLkhh02rqMPW6hIpBcPZ57ZEZi/9+dTsolGWEAJENGx85HC39uilT2134iKTMSmklIMO+NaPflFwUhrwyI6zCg7HKH/xlNWFIXTl72kLFV5c8HH+7tZQYVc03Vv5wFJq/1bCZre+de+YnNLT6vLPG1eX29ap5wZZT96s4m05azYVzF330vOLFWfHKsQGzV5qa0rLsSIib+JZe3I1aeVGDgfysnOb8+KdvPjlX254SHABBpZ8DgnEIvHT3KiTb/c4hU7UzR8oyZ5JyTrvKFkv6jtysL09TxSltYlrJm7x2tq2Qjc7tWPQpgciLWhh2hkN6LFS3KAeR8npB/GTivexaV8xZozbafX8c/MD69buLVLaorRmKIOkSzlmQhMEk+LfTVkQEhh7ZiOy8jpRX5dnde9tX7TxoQ/mq9NWp54Mms5syaRgxFzVDpSTJuC5T8vErLyDOD29C02xMBGTaI2HqHLMHrh8uNX0L6W5I1M+saECvbaB7PQefB5Jx7v1EzFj3AFqOJxlPPtuqfvog+9t/Pxwj04DN9HX2FYA9TXjwR0duaNbEc7qhhF0UP9RMZgUhoWYveWxmrWHapvTSSMobUgKCRJSkGoHyckS0BQN4zfbLkTMDaA43AqDOALE8eutlYjwwKBND4Shc5gBB69vLcGuQ6ORmxHBnMm7saZ2qiKCwikRYVlszH0r3lmh/IcYosaMSRiGg6YDo/BZ40hEIyHs3zEWms69tXIBklLqry97c6VjOYPZ/4KgZJ0GOchN6cZTe2agJRb2CPjDjjnINqPQ2LGfKCXz1pNmWqhrLoDLNfzl/XIcas1GRigGl5MhhWXt2tG5ZOWLH08fZgp9cwRNGz1dqZ5GqNdHCJJS53Ct2CHrgnX3brjM0wIhvnoCJBi4JKQGY2iJZeDP+8qQbsQgJMEVkrlcIplw9QUVFQQh3bRQ31yAaDyIkGF7fQpCSoNzy3768a0bGg60mooEMcSeFQmkCU8j1OuBEEKacRm3tr9Y/8L+9z7NSZAgv548QPSdaIrueKQoZKYZjq4xGDpBtUqChua14ZAR6/doamww4Hgao14f3ZxSYw4hWNp9K6qf4O6pn6CA0Dm4eOP2t9ZaEas/Gn91ecBQKJ/qtZB02zM1P8tIDbRJyRhjCSP2NsUgIg0d50g37vnzRH+CwGHzSRiQttV4MPajpx7f9NxV185ccyp/o5RC6oJc22nlZat/9/bi7997yYNf1Bfox/tQeX9Fbn/Ooja6cstnf8IQytU7lzGMjPZionAgpZlUsxLJSYJMZQpMWtYrL+1aPX3G2KxzSkd3cGV3x4MKZX3jpYARJ8vav/bgA9sr6lZNvWTKQcmH2MtJgI71gVJdi+twBHnRQNmjN4DHbI1HrWRC3LKTZwj90EmR4G1AglwudLWp++/euCpucwQCGj/meKbimk4eCX2QkLoLx133+43V0fYYBVICQmnHlybAIIH2eArKsptx+bhafOe0Xei2gyAmwAUMl8NMJlyp9tAHMLi6HkRJaeF9k6fkPqxRCoHBTexA6pCu3dHOz3vskQ9/kJpmOEO1C8TcABnImzDylQnzi5aaFCJG8EKD2iyXrhBRccYbt6+9RQuQZIzElybg83g6pmW34OnZLyEcsHB7yXpcO2kzWq00aAT7WEJgiY0NgAQEYxrSM8zmm5bOv4GRtIiRUGmA+pwLaTo85r7x6s6XV72280Jdl51AQs0HzSMZXfzbC+81MvXtBF1XmV6CBBgWLLthY+Py9x7dXGmmGY2KoS9FwILC3fjbvGcwNrUTGhPQSeDB8tew7JxqxBEypGYawpOUQSK1gJ4sM5FSoLvLKiwcneFccWXJPE1LMYixowFeCF05wZUv1K5yHJ421CGq93YsnpOaFRIX3Xn+BboypQFkSy4NW9rig8e3rIl1WBO45F42eDIE6Ek7NRe31CxA3NU8tQfUL0kGcfHw1ZOmjgiPaGUQR3TVuxgSE/tqW8re/mvtasa9xQ2aW9fIUvu67PLpm2r+0fhAfR2/nknL9iJCYpaEVcvka9J03RKuwMS54z+bfOn4n+5+9dOn49Rrqbygb3jCuQqReH+S0JN1vtk0CZ0xCY1xtSDPLFUsJ8nEPdOK6kdlpiS1s5y4W/O2FwGTB/fETRBYcsu3l1x39cs/jFt6phDOEc9+IqiAr+4PlUvPf/bglievdJqcuZJc91Qd30BQss6wbiErGMMIo/eIZCoJ9iISswNcSDhcOUQv+4PtqLREImo5wRMl5yr1HVUQdq65rryCmGEQ046awonQp3NGKCC/u3zB98AgiJGrWnyVBHCZSIWHC4NGTGrktcNExbgTPpCYR0Jl1eS9ZefmLiMyTTB50iSoq7C6BY4tG9N17qLSi4IwzUH+5H+hJMZUCBASN9489+5QOttNzCCw4RHkRKYw74bZb4WL057XETD7Q+N/BQGsTxGU30imFP3lsMzMkLjhpor5xDRdIzpKQH/mKZKPV597ZTWdsPCuixYxjfUw5Ua+gCnQqQ444YRM3Qw1b+HqFhh3Al7fsUxh5uyilrnnj72KmGkySNu7AXJ1wgzBkA3X0YflRt74voJI3sSRVsWN5fNMmAYxsr9RAohJ9NoB7+5/+czNqJr2CWZN2o+OaAhMG344qrCpTvLa6yuezMrWPyTNMKTQlFNDeeU2nF2+B9Nm1SHWYybVhH5/cN6iGR+NLM36o8GMUzYFStapaqyK9qGtwPHDjc01ZKb24rZLX6fJo1u8k7v5ktWkqsNRa/gFqT8shlINuWTZvCpIssEkLbji7zhz+n6vIDJn4WaaMX87rJiubp9DxisTSRRIFy6vWkKpWgNJzcsrWJKfZNCTdaYY1OVwpHhVKwGVWQp1JSYidekbdhT9U4eCrryx6h2rOL/d7oqmGYwJGAHYiyvXG+v/NdqrYQ2oZh8xBXWKJVMLOi9eeOZl4zsfe35SaZMV6UwzGUnELcMtr6rRzW0jLVVvGVBNTzy7b/yIwgx33k0zqzbc/f6HtrQHJFjHB/v//wr7HASfg+BzEHwOgs9B8DkIPgfB5yD4HASfg+BzEHwOgs9B8DkIPgfB5yD4HASfg77pBXzT+A8olAy+9KTwAwAAAABJRU5ErkJggg==
