name: blastct
version: 2.0.0
copyright:
  - license: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
architectures:
  - x86_64
structured_readme:
  description: |-
    Brain Lesion Analysis and Segmentation Tool for Computed Tomography - Version 2.0.0

    This repository provides our deep learning image segmentation tool for traumatic brain injuries in 3D CT scans.

    In version 2.0.0 of this tool, we also make available a model that has been trained on a set of 680 annotated CT scans obtained from multiple clinical sites.
  example: |-
    # Example usage

    ```bash
    # Run Python interactively (assuming you are already inside the container)
    python

    mkdir blast-ct-example
    cd blast-ct-example
    svn checkout "https://github.com/biomedia-mira/blast-ct/trunk/blast_ct/data/"
    ```
  documentation: https://github.com/biomedia-mira/blast-ct
  citation: Monteiro M, Newcombe VFJ, Mathieu F, Adatia K, Kamnitsas K, Ferrante E, Das T, Whitehouse D, Rueckert D, Menon DK, Glocker B. Multi-class semantic segmentation and quantification of traumatic brain injury lesions on head CT using deep learning – an algorithm development and multi-centre validation study. The Lancet Digital Health (2020). Monteiro and Newcombe are equal first authors. Menon and Glocker are equal senior authors.
readme: |-
  ----------------------------------
  ## blastct/{{ context.version }} ##

  Brain Lesion Analysis and Segmentation Tool for Computed Tomography - Version 2.0.0

  This repository provides our deep learning image segmentation tool for traumatic brain injuries in 3D CT scans.

  In version 2.0.0 of this tool, we also make available a model that has been trained on a set of 680 annotated CT scans obtained from multiple clinical sites.

  Example:
  ```
  # Example usage

  ```bash
  # Run Python interactively (assuming you are already inside the container)
  python

  mkdir blast-ct-example
  cd blast-ct-example
  svn checkout "https://github.com/biomedia-mira/blast-ct/trunk/blast_ct/data/"
  ```
  ```

  More documentation can be found here: https://github.com/biomedia-mira/blast-ct

  Citation:
  ```
  Monteiro M, Newcombe VFJ, Mathieu F, Adatia K, Kamnitsas K, Ferrante E, Das T, Whitehouse D, Rueckert D, Menon DK, Glocker B. Multi-class semantic segmentation and quantification of traumatic brain injury lesions on head CT using deep learning – an algorithm development and multi-centre validation study. The Lancet Digital Health (2020). Monteiro and Newcombe are equal first authors. Menon and Glocker are equal senior authors.
  ```

  To run container outside of this environment: ml blastct/{{ context.version }}

  ----------------------------------
build:
  kind: neurodocker
  base-image: ubuntu:24.04
  pkg-manager: apt
  directives:
    - install: git
    - template:
        name: miniconda
        version: py311_25.5.1-0
        conda_install: ""
        pip_install: scipy numpy pandas SimpleITK==1.2.4 "torch>=1.9"
        install_path: /opt/miniconda
    - run:
        - pip install git+https://github.com/biomedia-mira/blast-ct.git
    - deploy:
        bins:
          - python3
    - test:
        name: verify_installation
        script: |-
          # Test Python and conda installation
          python --version
          conda --version
          # Test that pip packages were installed
          python -c "import sys; print('Python path:', sys.path)"
          pip list | grep -i "blastct" || echo "Warning: blastct not found in pip list"
          # Attempt to import the main package
          python -c "
          import importlib.util
          import sys

          # Try common package name variations
          package_names = ['blastct', 'blastct', 'blastct']
          imported = False

          for pkg_name in package_names:
              try:
                  __import__(pkg_name)
                  print(f'Successfully imported {pkg_name}')
                  imported = True
                  break
              except ImportError:
                  continue

          if not imported:
              print('Warning: Could not import main package. This may be normal if the package has a different import name.')
              print('Available packages:')
              import pkg_resources
              for dist in pkg_resources.working_set:
                  if 'blastct' in dist.project_name.lower():
                      print(f'  - {dist.project_name} ({dist.version})')
          else:
              print('Package installation verified successfully!')
          "
    - test:
        name: Simple Deploy Bins/Path Test
        builtin: test_deploy.sh
categories:
  - structural imaging
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAEHklEQVR4AZRVXUieZRi+nvf7Po0GEpXQSYixgm0uMdtKWAcSYhFKbtVBP3ooQj9QY9jpKqwg2FGZoKCWtbKf9QMyJMr+N2srdyANymQQFNTRFvrpd3dd9/M+n36jk72813Pfz3Xfz/33Pp9mpU+XrO6Tn6308U9W+uislU6cifjwRyt98IMV31+00nunrTh7KuLd7634zndWPP6tFd/+xgpvfW1FojDzlRXe/NIKbyxYYfoLK0x97siCGfQELgIFIE7gJnGS7pvzNPkrXv6yue5svtA3My5mFViFoI7LkHgjL7idvhByTnxEBYl3P9ozZQ2xCUh3Q16AdHGqLunJlKRs8tE+xZEv8phZqlBkVWd1SY+V0ZvVOEeb+6Z9LlV5ja+mQlumzDrg4KZajXQ6JJ5bf91OfnvlbtCS81LlJ5/MA9Dg8tJFbM68ivKhfSg/sB/lB+/AxkN3YvPwo6icmIYtnUbl+OvYePgANh65CxtHHoP9ulwz99RFkjGBUgpKRDk1NcV8VkXl9/P457UR3HP2JOzCbxgdHUW5XI7fjP50RJp5qlyc9EyZfH6crescdwgB6+vraGpqQnNzM7q6ulBfXw8lBhOEEJBlrA186K9gppkrhqBCCX0zv0V082o0s1SK0WF1dRUrKyuYn5/H8vIy6urqgH8vyX0blAHxPPKHZ5VUu0xZFCwhtVoqlTA+Po6JiQksLCygtbU1dlB/lc5F5IHSWUkPnPPSvQOvnKRmFk/CR9Db24uenh60t7c73dbWxgb5Y/Ld1lJznnGqFuqZsgrKlrqRw9raGhobGx07duzA0NAQOjo6sKvxWpm3cNnMPZY4QQkUeMsbPkv8zzM3N+dsZ2enS1/+/gv2yxKv76mIc4sIf6xClybQIXDevArmhEgl4+WkCT6i7u5uCMPDw1hcXKTZMDk56fYQAg7ddy8Olv/EwQtnHNfPHIOdPwfb3HRfqxjiL9mPxEV/T9SmPrKqFkZGRvwGDQwM4OLVDe4YQsDs7GwN+vr6os1X+DQy46yYji9r111mW/39/Qgh1KChoQHTJz8DdrZgcHCwxhZC9B0bGwMDwWMyrqTfIvBjBKFYQmg/gOzwy8RLyJ55EdnTOZ49hsKRVxDuvh/hqReI5yOefA7hCeEowuNHgZt2gfNFejKNo4pCAaHpFoRb9yPsjcDefXDc3AK75jqgaSdCy+0IeyKwm1d4DyG5+zbghhvB9pC+qf9HC4iP5u8au+GkXJVN3XmXYmSTFKi7fZsuVb4uucQOOC9lTJ3IwfQ9GEBzNErn6Oe6pEBee/lU7eRdl4167S0i6dUys1fGPVXogIMb8RSQ1D1PvDhBvDjFkZ6pchEJXhEDJ5n4JFVtshnveeKTrNryGLEDbq545ixXFVLUdshYiVcX/wEAAP//hmPUngAAAAZJREFUAwCJ1DDk1JIfoQAAAABJRU5ErkJggg==
