name: hmri
version: 0.6.1

copyright:
  - license: GPL-2.0
    url: https://github.com/hMRI-group/hMRI-toolbox/blob/master/LICENSE

architectures:
  - x86_64

build:
  kind: neurodocker

  base-image: ubuntu:20.04
  pkg-manager: apt

  directives:
    - install:
        - wget
        - unzip
        - ca-certificates
        - openjdk-8-jre
        - dbus-x11

    - template:
        name: matlabmcr
        install_path: /opt/mcr
        version: 2023a

    - environment:
        DEPLOY_ENV_FORCE_SPMMCR: "1"
        LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/opt/mcr/R2023a/runtime/glnxa64:/opt/mcr/R2023a/bin/glnxa64:/opt/mcr/R2023a/sys/os/glnxa64:/opt/mcr/R2023a/sys/opengl/lib/glnxa64:/opt/mcr/R2023a/extern/bin/glnxa64
        MATLAB_VERSION: R2023a
        MCR_INHIBIT_CTF_LOCK: "1"
        MCR_UPDATE: "9"
        MCR_VERSION: R2023a
        PATH: $PATH:/opt/standalone-hMRItoolboxv0.6.1
        SPM_HTML_BROWSER: "0"
        SPM_REVISION: r7771
        SPM_VERSION: "12"
        XAPPLRESDIR: /opt/mcr/R2023a/x11/app-defaults

    - run:
        - cp {{ get_file("standalone_hMRItoolboxv0_6_1_zip") }} /opt/standalone-hMRItoolboxv0.6.1.zip
        - unzip -q /opt/standalone-hMRItoolboxv0.6.1.zip -d /opt
        - rm -f /opt/standalone-hMRItoolboxv0.6.1.zip
        - /opt/standalone-hMRItoolboxv0.6.1/spm12 function exit
        - chmod a+rx /opt/standalone-hMRItoolboxv0.6.1/ -R

deploy:
  bins:
    - spm12

readme: |-
  ----------------------------------
  ## hmri/{{ context.version }} ##
  SPM12 standalone with hMRI toolbox in Matlab Compiler Runtime

  Example:
  ```
  run_spm12.sh /opt/mcr/R2023a fmri
  ```

  More documentation can be found here: https://hmri-group.github.io/hMRI-toolbox/

  To run container outside of this environment: ml hmri/{{ context.version }}

  ----------------------------------

categories:
  - "quantitative imaging"
  - "structural imaging"
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAOX0lEQVR4nOVbC2ycx3H+Zvf/78GHKMq2ZLmSUQWNLZGS5TQx4EccPR25RhEYCU6p0bRGgMJoYkeygziN0RokW6No2qaO5DZGk6II0BgJeEVRNy/4SSlNIyuOELeWKFkSrKBSJYuUxOc9/tdOMfvfkXfkHUnTPLFmR1rpf+zt7szO7O58Mz/w/5xo0fplnuydyyMhvvoDaTgxIZNVWzquo5X9g5ztyDB6yNSs2sUK/VmaqNubMaDGCoUa0yxTJpNVQAbZLEXTXnex2uS92aYKly1zJu3QkKeL556+s1Cr7hYcUAe7t0aNEAYtaGvMlMlCZXdPMv3hrl80FUZzG4nUHWDcCsKNxoTXE6nVbCI7AiINZjOmlD7NJhphRUcA8xpx6pf9T995pdxWJsM629HN6OmprUGLKADK9PIE47/xhR8lE277LkJ0P2B2AHSjSjQBbIRRwERgE05pQYG0CyKRiAZHPkzoXyZSP2VSz6tA/ejo/jsuStVMplcvlHnQe20AmV6N7G7L+MY9L69iN/k5Bn1aaXc9kYIJPWGGmWHrkHDITJA/E4uftRqOl0aWRZEJUKQdRU4KpBQiv3ARhO+bINx3Yv+2oxMaUcvErpYAtnT1OQd7toUdmd4E3bj6y8z4gk40rTRhESbwRE0N2amFml8PIjcStYHSjhYtMn7BB/Ccn/OePPX3O//HLpzd4PlqA81zXIRukKzmnXtf3QUn8TXlpjqNn4eJwvC9MV23T9k4IyJydKpVzGOATfhU/9987JmpmthYAXR1qfIitOGxg91au13SSuQXQwJ0bMQNJRFFpLTjqESzaERv5A18/sTfffKyXRvepRDoXXUt6tZDZtPnftAeNbV9V7tNu6LiqFVRiMFfTbIawZGTbnNM4J9CkPvdY/vveb1slgsvgK4K5tNtL+hk821hYTggkItFJGYT6kSzY0w0REF+17sVgpq72lcw76b+TzAvRKScyM9HBLSz2/RC556XbhPmxRzm9HvMSmy3q/WPvLxCJVM/tswXR0PpuPaA0FASa6v93BjlpBQDQ/DG7u3/23t/3tXFqqfesbtENGuPvayxm6KOvQde0k3Ldtabea1i/yaIjN3eG0WuIihFiMz0XmRN0E5KGxMOqNC/5ej+HQNANwH1T47OTJ1ZW9pN4Ya9r3Tr9MzMjxZCK82VbUmoBmrBlfEA+XyItmZnmkYQSEdBIdSp1pXGRP8E0C5kegnZ+u1RvRflLWXDo307tZN60YRysOFpdqVImA+wbeO1eHDLGmz+9TYrkAU3BXtABM4M5NH7s/PoPXQeCa2g1HSzYObQaVruRLnh7v7923tm2h6pTm+ELlAHsg6Gr3tTucmboqBoaMpWJ4yO5AM8uHUt/vTTN+NqUvbQeTzx3AmkXFXD5EQkiqGdSIfepjf37Xir3nqgajWeycCu+nxlxeM6vUyYD2sxL2q/rfMay3xouKZdCslzGZIUIw5RHaYiEx8pbJHrGnWEAz8IkbnjBuy5bx2G8yGcaTYn52LDSrtuCNovT3rq9EnTH4kfAtz0xQPXaKPeUoraY8+tWqlF9ceKIb6z50O4a/2KiYaG/BC6dCPySGllS6XfIzRaHIcS/Y1XcCSdJBLaLdUr12aYwoj1DuOKBuSmQE4SxrBlftdTr2GsEMLR8SI8VabKbdJcHNt+7JmdfbVMwZn6iy1dB7Tso4559WGdalkRFkZk9qvqiSj8yOD6tiQ617baof7n5XHs/flJDBZ9OOLwlRWRgD/ZvA6ZdSvts1ODb+Mv+p7FUH4EWk2qrziHD93+AD5+08fEs4F//iguP/8VROOXAO1MGjoR2nd8CS2b78eKFhcb17ai7+hlLGtyEE2RgL0jwCj1JIA+i0bNYgIkyMvtj/0szUy/b8KieFl1D0siCFG/gBl7D5/EkUujGPMjXPICXPYCDPkB3in49t3bY0UQR/jzvmdx/OIp5Pw8hgujGCmMYrQ4hku5K/jqq8/i7MgFEBsM/usfoXjuDRhvHFHuMqL8FZjCMMLRi1Yw3qUzlWzWHh+gjZ9n0om7Nzz6SqeYtawFdQWQyfQqMZ9xLm7XyeYPcFC0fnm9DqRrTQTPGAwUfbQnXav+LpEtogktrgPfGLxTDAAOcCU/jNZkCzQpOMqxRZNGc6IJoQkxmB+xgEk0PgjVtBxQOgZKtGtNQSVbwFGAcORCaRAznzrEcdKJtANWn5X7AzhQXwDIZOx/EVOGiGJffA4kJiDMigpa1a8oRlopvZeawmx5IeSKP/Isrlcakqi9QGZ2/ysVey1DEod7xiPM5NiIlOATIPy2IFUHe7ZGdQTAJJDWLZ95oRnE95jQE8d2Tudp++tZ3pXfxyKavd7MM1tVczZSHHqsdOKDKZ3eJNB7pRmo8kWX9eoBc21ig9KpVQJjNf5kf3VI4DjlJhUzPjrVDFT5ovwwYr5TuUldxvCWBFl7ZsHn7pbbg/2DPE0ABzu3lneN2yxyu8CI1mKS4MyCMhNjo+xwyGbkWG+1e5LLY7FRMfBrdqGhuMLSICYLxQOrgty5RGUITk1U6Abf/lhvGkSrpDIJ8LmUiA2T4ySK6eU32Puu7ikaQMSjWJYmYC2bID6aLRkiYiO+QTJNOrHGPurvnCIA2XqLocU0Fi9o3GCS8wdxUPlITa+1RJmfoOoDlKq8iXyHAJ7bEev9SCRrYejUPQlGLAd2DEtgZzGSFRpKJD5WGGjhT6jkGarSWxYE6K1/vH8Mht8Wx6OEQC0RYiblkAn9vB4aPm0f9cT8qYk6/dk4SUWJhJbgOmC1mseKujqarMoXkpYi/7PB66R0HJhdIiReLemEXPRbLbfOUGziqlxJcnLshYPDHPoz4gDvO2IxAYGP6TW5lZSb8itVvsja87HIxf9lFHrDkpwwK9rwPiGZTI5CSbQ4WDXZqJplWQhZ9T997xCxOUROcs6ASKmThR/2ghAzOa4yYeFCOu8fqZxsoSo1L6mG4ABZWTXnqgBleKIWehDjQDFCPPGsRsW4HlkEaaLVmnBEqUXrsc4VC0gLivzykW/eM5KRUN90ZyimMlyUMIUfRsXxS2oOZiADFrhL0N8gYosRqlKRaxmmgKbN0hQpKFIIotAiwuV68kxAMsEEm9xkzDgpcBhYTNCu4FLkWmqaEJRssf3zXNQ/DFgRf9s+yFbHydSU6iwSeuOZ+wYNh8+rRBPNBIwI0/IypRT+ePM6y/BoECEXhBi3JcKIH+CRDWvRuTwNCSv+4e0PQCuNMS+PfFCcKGNeDr/zoU/gg9fcCFYOrtn5uMX9TGEU7Ofi4uXsfdtdf4DU6k47BkfXX6uZ2Sg3RVFYOHFdm/qJWMOscYEOiwswOfrAX5ug+Bki5Za0YEIf5c5VCpfGfJy7VEDrmhbsXrcSH7m2FefynkWEhQQkbXE1bl3RWpottrh/x6qbcHFs0CLCQgKINiXSuPm6D5R7sLh/cu2tiIbPA4IIy7CMASWbkbxhk9W8oh/hzEABrqsqTKdaBqQTisLiV23OQD/rbDxnk1OOmQKje1/5tpNuezAsjE4Ljkg8QCK1D25dg6ceWA8vlOhO7dmolJ4MVNS+Zj1ZdsvvLChTuz0/jJBwNP7tFxfx8D+8ifZmd1pYTmZf29n3TgZRYfPpFYcD9PRMQ1NVrQ6y2WMSzCMK1FcirzCktDttLZBYoISov/cf55E9dGGC+cBwVZF6Fo8rlXIMMIyi6lKKBZbrCUhujIGJoqoighHmj/73GP4sexLNSV1z9m1wSgnIbvacfuY+LxP7/7NGhkrUYzK7s6r/G9veAXtPqmSzkgADalDCUXjiueP4+g/P4OKIZxMYKotoyuRiV1oclYKjdXWpWhRLRZ5pXVVyPuNfDl/AZ7/xBoZyAVxH1QiPm1Cn2rTxxrPHvr7jxXmEx2MqJxtteLTvn51U66fiOGF1RKKsscO5EKvbk+hY0zqRILGQoHqciAb8aqCA0+/k0JTUcPV0248XvqQgQGfAudv6l+0ajh2f2t4tzdKtjXJu+vxPl0cpHFGOu84mJEl28xSScLkfGhQDAVzRMEo4hFQiVvtpmi+2pnTJ8/PuOL5v++Fydlu99mi2DsuJBTc//OJHdKr5RcnGMqEkS5Ri25WN2czvxoKJNRmfZF62PR16Iw+d2Pfxb80ll5jm0mnZhiQFTVLRYiF4NTVhUaiCeeONP9S/b8e35porqObSvjAvDUoSoiQjSiqadlNaFhssMkn+sCQKzYd5oTm7vNJglRCYL+hUqxMLYXG8RulbOQlNOhnNh3mhd+XzlzMwRQhRNPphE3ovSDaWxd3rbJMNIYndMRvJEwbzKYSFrfNhXmh+61VFarpkjCulnyDtJoyXM0w2pqbm3fZMxCznPRbzE8fIhMH3jDfwSJwpPr+PJ2jeg5H84e5u+6HC+j19G7Wj/5J04rcs9Oznba7egnw3UP5OAKyVmyYBbE3gHTXEXz7+tbt/LFXmkyZfJnpPg5vy2crGL/77PYbocTBv14kmLZkZHHiWgXiXlL+iIDH+WotbCd3Y04fAWPazGVepRBoc+nI0/i8G76OzF77Tn93tx3t8/UPOXIiwEFShDXK78UuHbjEc/R4Zvg+KOpSbis02CkofTMlhSf6pHIkks+hYaXQCAsxKfRP650g7L5Gh7x49e/bVia9C5vmFyFQiLCTJoCq/5upl3Xn49d+E8e5isCQnbAD4emazTDRkAtUpfVwFNkPMPE5Ex9nwIXISP4kUv/7WX310bIrGyQ8XZOchNILKHztOWZEFbDl57Fet4fCp1UisuB7FYcBxACcFeGPjTvu1p5wLZ/0j3/xEfurvsoLkZHcvGONlooVsrGb7mV772axNS5mrymZ69cTnsxbAbFyYjhrVcN3+ZEnsBmX6s1RG5yQ5z15b87HVlgQcj/cD/S9q1MHzW5h5mwAAAABJRU5ErkJggg==

gui_apps:
  - name: "hmriGUI"
    exec: "bash run_spm12.sh /opt/mcr/R2023a fmri"

files:
  - name: standalone_hMRItoolboxv0_6_1_zip
    url: https://github.com/hMRI-group/hMRI-toolbox/releases/download/v0.6.1/standalone-hMRItoolboxv0.6.1.zip
