name: qupath
version: 0.6.0
architectures:
  - x86_64
structured_readme:
  description: QuPath is an open-source software for bioimage analysis, especially digital pathology.
  example: qupath --help
  documentation: https://qupath.github.io/
  citation: ''
build:
  kind: neurodocker
  base-image: ubuntu:24.04
  pkg-manager: apt
  directives:
    - file:
        name: QuPath-v0.6.0
        url: https://github.com/qupath/qupath/releases/download/v0.6.0/QuPath-v0.6.0-Linux.tar.xz
    - run:
        - tar -xvzf QuPath-v0.6.0-Linux.tar.xz
        - mv QuPath /usr/local/bin
        - chmod u+x /usr/local/bin/QuPath
    - deploy:
        path:
          - /usr/local/bin/QuPath
    - test:
        name: testScript
        script: |-
          #!/bin/bash
          qupath --version
          exit 1
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAABgdJREFUSEu1lmtQVGUcxp9z23NjWWCBXXZZYLnKpUVRNGN0HMjUgvKCZZnNqGNMg2P2gUb70JXpNtNYU9Ntuvihi1OZVlB5Qc1JES+IYIsiIZcFN1xcdkH2cm7N7sAMkTl+6f10znnf8/zOef/P/J+XwP88iDvQpxIKKvJMhZVzDWmFKQytQ3DENeRp++HM1bPfdgHQbqdxG4BFyKh6+km92V7LG8zZkYUaNERfIEgwOhaEHOhitPC7R97c8RFwTroV6JaA2MKq0tTSdV+IRmsuQRDQNA2KFIYUDkYxNMOC1nGIzFEUBZ6jnfLguerjn9R2zoTMBBCGux6qsN39xPeCIVGvqSpkvxvZogfJkgv0xDVkly1Fv9uLk2e7cSOmEKIpByRJQRQEnzbWfe+xXY+enQ75B0CXnOfIvv+FYzGJ1nhFlmD0NGPb+nvg6ziNlPxiqJqMlKISqKqKPxr34fKwBz+1+aDYl4PhRIgC7xls/Wx2V8OHg1OQ6QA+veq1Q6bchWWqpiHTfwIVKaOYU/4AxsYnwHEc4rLyouJdh37EwNVLMFnsYHMdeOfTBoxZ7wej4yFyRMOR+kVV/wLwqaWr81a+vFfHCUiUXNjxSC66m37AeNCPJL0JnF6PnOWrMHS+BW2nm6AoCjRJBs/p0ePqQ5MvD+KsFeB4ET5n49z2719sjfphkkRbyuv2Wec8UBm5fzypA0tWVKDj6M/weAZgz3Ig/Z5y9B9owFXXJXCMiJAcAptgwo3eLoyrYbT3edGbUQM+Jh48rb3/2+tLaqcDkrPW7Oow2kuSY6TreHZBABZbOoIUC7/nOuJtGfjz98OQRkbQ53cjp2AB9NYM/PXHefR2nYdEEhgbu4mjchk423yQSvDKqV3LcqcDHPkb97TqjSlUHjOEdWmj6Ol3onh+BRIccyHLMpq/+hjaqAd+RYbJng85EELvQCdsMUkgk81gOREfHR+CbF8BHSeov9eXsgDkyS2iFxU9+c1xIdaIfKoLS4gOjFIAoahYXL0FdKwBfrcLnY37QGgaWEs6+pxnYWBF3LV+C3QE0Hn4F+xucSOUWw2a4dD54Yo4r9frm6rBwvyNe07ojSlEEetCOc5jWAuBVzSkFS9EYtYsUDwPj6sfo4ODMDtK4HcPgWF0MJjNGO/tRsfhBux3JyCUWQmS0mmn3ljIAwhNAfKyqt85bcyYHZvBB7E03AAfoUJRFSiyglnFZbAVzwNFEmAoEkFJjrpjQlIRvjaA5savYVQZfD5WCCJ1PuQJ32Dr+w+mAVCnAAbT4q3H0kqrZ4uiHhvM7fD1tCAYAYTCKK/eBNFohD+kIEHU4cbNMCiShKJpcJ07id4Lzei7MYHmuMfBxcRhwtO/5+LuDY9OLzLJpcyuz1/z6k4dHwOHOIJ0XyNkSYLIili0dhMM8bG47g+AIAAt0j8JItqL2hu+xV/DvWjypCOcWhF1/VDr3srBo+82TgdErotsy54/nFJUbmJ5ESXSUehH22C1ZGHOgw9DUVRcOvQT3H1XcPfazRi+0omkzBzc9Pvx5b6D6DauBK1jMe7pv+DcvWFexEEzARQdn1mX89Ar9frEVEoURDjkM1helgkxyRRt+hd/3Q85HIBj6Upc/PU7GK0ZaFNsaOpmQbEC5FBAs8utq/d+8Nz+W/WiyDODYJv/ln1Z3UYxLpmkaQbpBiAjcAHJ2jU4lldB8nkx4vHiVFsfnEEr/JwFBEkiHBjHwMHXULN28cmtW7c+ZrFY+mb+wRTUyFtLXrYtfmqzwZLNEgQJkqLA6DgwpAopMIEwaGiqEl0fyYpxrzt49ed6Iui+yAqCgG3btrVs3779MbPZ3PNfiSZQXPyqeMfKZxJnVRSLCWaaouhoYSdVoaoKAv4RaXSg/cBwy1cvSb6eBQDeACDyPI+ampq2urq6dbfL5MhcAihhgZg+7z4hOa+A5vUJJEEosiy7A9f/POPvP/EjbnojKRaJSwbAegBvR7Y6AqmtrX3mTkI/8tEkAHpSRJ0UjLpkxqAArAPwHs/zn1VWVu68U8DtDg63ghQUFBRcdjqd4b8BYn5V3gzDcA0AAAAASUVORK5CYII=
categories:
  - functional imaging
readme: |-
  ----------------------------------
  ## qupath/0.0.1 ##

  QuPath is an open-source software for bioimage analysis, especially digital pathology.

  Example:
  ```
  qupath --help
  ```

  More documentation can be found here: https://qupath.github.io/

  Citation:
  ```

  ```

  To run container outside of this environment: ml qupath/0.0.1

  ----------------------------------
copyright:
  - license: GPL-3.0-only
    url: https://www.gnu.org/licenses/gpl-3.0-standalone.html
