name: quickshear
version: 1.1.0

copyright:
  - license: BSD-3-Clause
    url: https://github.com/nipy/quickshear/blob/master/LICENSE

architectures:
    - x86_64

build:
    kind: neurodocker

    base-image: freesurfer/synthstrip:1.6
    pkg-manager: apt

    directives:
        - environment:
              DEBIAN_FRONTEND: noninteractive

        - workdir: /opt

        - install:
              - wget
              - git
              - curl
              - ca-certificates
              - python3
              - python3-pip

        - run:
              - pip install quickshear==1.2.0

        - install:
              - build-essential
              - libxslt1.1
              - libhdf5-103
              - libboost-program-options1.74.0
              - libpugixml1v5
              - vim
              - dos2unix
              - git
              - cmake
              - g++
              - libhdf5-dev
              - libxml2-dev
              - libxslt1-dev
              - libboost-all-dev
              - libfftw3-dev
              - libpugixml-dev

        - workdir: /opt/code

        - run:
              - git clone https://github.com/ismrmrd/ismrmrd.git
              - cd ./ismrmrd
              - cmake .
              - make -j $(nproc)
              - make install

        - run:
              - git clone https://github.com/ismrmrd/siemens_to_ismrmrd.git
              - cd siemens_to_ismrmrd
              - mkdir build
              - cd build
              - cmake -DBUILD_DYNAMIC=ON ..
              - make -j $(nproc)
              - make install

        - run:
              - ldconfig

        - run:
              - pip3 install h5py ismrmrd matplotlib pydicom pynetdicom nibabel

        - run:
              - git clone https://github.com/ismrmrd/ismrmrd-python-tools.git
              - cd ismrmrd-python-tools
              - pip3 install --no-cache-dir .

        - run:
              - git clone https://github.com/kspaceKelvin/python-ismrmrd-server
              - find /opt/code/python-ismrmrd-server -name "*.sh" -exec chmod +x {} \;
              - find /opt/code/python-ismrmrd-server -name "*.sh" | xargs dos2unix

        - run:
              - cp {{ get_file("invertcontrast.py") }} /opt/code/python-ismrmrd-server/invertcontrast.py

        - entrypoint: bash

deploy:
    bins:
        - quickshear

readme: |
    ----------------------------------
    ## quickshear/{{ context.version }} ##
    Quickshear uses a skull stripped version of an anatomical image as a reference to deface the unaltered anatomical image.

    Example:
    ```
    mri_synthstrip -i input.nii.gz -o stripped.nii.gz -m mask.nii.gz
    quickshear input.nii.gz mask.nii.gz defaced.nii.gz
    ```

    More documentation can be found here: [link_to_documentation](https://github.com/nipy/quickshear)

    To make the executables and scripts inside this container transparently available in the command line of environments where Neurocommand is installed: ml quickshear/{{ context.version }}

    Citation:
    ```
    Schimke, Nakeisha, and John Hale. \u201CQuickshear defacing for neuroimages.\u201D Proceedings of the 2nd USENIX conference on Health security and privacy. USENIX Association, 2011.
    ```

    Licenses: BSD-3-Clause license

    ----------------------------------

files:
    - name: invertcontrast.py
      filename: invertcontrast.py

categories:
  - "data organisation"
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAWLElEQVR4nOVbCZRU1Zn+7r3v1V69QDdN0yCLYWtBEAGVmLQQFlGyODmFMSYziUaNTqLHDZdEG8wkk0XHEGM0iSacyRiVTjIxGhVQFqPIKoiEHRREtqa7uquqa3vLnfPf96q6urt6AcXMObmcPnRV33fv//3/f//7bw/4Jx/sH7WvLPYlID92QnCGhwRYQyTCK0+cYJcMGCBRWyvZokV20bn19bxhxw5GcxsHDJCRhgb7TDOFnSnQiES42qChwery9/p6fmjTptLmREKBE6EQSwSa0tMa1qWKzV29ejW/ZM0a60wwg50J4IWgN82bFxDZ5DjO+EWMyYmQOCsr7YEaeLUpHTyCATZkXGN8nyntVg622eb2Oq/t2TJu+fLm/PqRiEBtg2SLUFSD/pEMYLIA+J5LL/VmpTnHgvwCID8Dxs8KCgFbSgIKAm7aMr85sYEzBg9noH+CMWRsG1nbahKMv85tPGeb9ovnrlx5PM+Ij+h4sA+7wNJIRMx3gW+bMaOK6exGMFypcz6GQKUtAmJLBjhaISUZQAbGOuytwEipdIIxRr9xjXPuF0IxJ2lax5mUz9uSL564YsV2tVQkIoodsY+NAavq6rTpa9aYSyO1ntGx6gWM4dsBoQ1IWRbSlmVzxkhVyRbwU6PKIUvxQ0ql7hrnIqhpSJpmFsBTbYa8b9rKlR+QjVCPdGNYe90KpzGUBOvrGW26ac4lczxMPOQX4pykacGQ0oRUQnNAFwraPfNFB+dKKaRlqR/1KH2naeo5u12LtBJdQ8bGCVvT/uPc5198xFlaCvqPOUw/cwyoB/gislkAtsyavlAXWj1hTFmW6dozliOehm2aeeBM1/MgOxAhBKxkEnY2AxEIQistdZ5NJmG2tgKagAiG1DqSGMG5xU1TC5gmsv36L62Yf8Vd1Vd9/T2XEYyO0BlhgKyv5yT1v11+cXmp5X06ILQ5rYZhk6YyxjpI3Eq2AbaE3q+fAk7EG83NkIYBEQwq0NImkwjY8TiCteeg/+w5CE2YCN+gGrUGzU/s+Duiq15F67o3wTwecK9XMUarHCAHff0au/LCi4QVCseFrq8C8APG2HqyH33VBHY64EtM37KQJqZEs4bBGPT8YpzDNgwFsvTCi1A573MIjB4D4fcrqafeexfNr76CpuUvw85mIXxeIJPFwK9dg4Ff/oqj7t2M6KqVOLj4v2A0NcFbU4MxjzwGT2Wl4jVpnjuNtHAuGHsVDhOsj4QB9a7a58D7BZ8SMwg80zuocSql1Hf4vfehdOoF3a6XPvgeDv7kh2hcvwFD7v0uhl7xLzn1di6HArtB39FnYm5y317svP5anHXbnaic91nFbE5Mc1TeAOABsAvAOcBCMNa7YWR9MniQ2PCZmf18Qr7k17QpMdM0GZAXFxFnZTLQQiGMevBhBEaNdgh3rrT2tcgW0HEh9Y/H8MSPFmNV3MCTP7gb/oBfHYdOt2P7s5alnku9ewBaWRn0snJ38w7zSeK8dfv2uWXjxy8jw9ibFvDeGKA8OzCpcflMyKM7ki8ATwTYlgURCGDUQz91wJumY8HJEOYk6kqRQJiGARYugX/KVDS9fxgQouttkfvJbUNzpIR/+Ajo5f0c0XVllvqi5dnfL3llQLCKzAtp72kzYFVdnUaOxsZZ0xeWefSZ0Uy2g9rnpR+LYeBVVyMwcpQDvvAsFwNDjCGVpyNDBtKdp24HV+XzP670c0dB2jmBkmK2a7j6u21zMx63zZ07BpaPn/w7mr8wEmGnxYClkYggJ+etOXUzA5p2f2s2a3UGr6SfzcI3ZAgqP/t5RXzeuueuugIw+e+JGeQouF5eDrQ6z2RIUyl1LVptbc4SQrjXqg3GBay2g5B2ljjpHFLal/7OOY7+929F05EjZnkwOGvj7Bn3kwCV69zN0Lo997W1cnuk1pNp4Y+Cg+6ULgpHm5rJJKoiV0IrKXGknyfWkSoBIWExTQf3eNzAwTF4u/YcwIgRQ9X5Tx8+jNZ1a9V1l9y9S61FOuMfOhTh86eg/OJPIjh2HMz4XsQ23QKttBbBUTdBhEZQIAHj5Ekce+b3OP6nBmjhsGhJp20/49/ZMGf6M6yhYXfuFusTA0DnftEia+PsGXeWefRRrYZhMsa6zFVGizOExo13jJSr+vEtb6FpxXIk3tmG7IkTigEiFEKo9hyU112Csrrpam400QZuWWha8gT2P/kkrFgrPBWVCIweDeEPKCYl9+5B6/o38cFjT6D6X2egdNq7kEYbjKYNaF23DZ7q0Yht9OJ4wy6YrY0QobCKN2wpbV3jeiZr/wzAnO40gBWVPoDN8+r6i4zYzTgrp+gt5+G1P+moNNcExjz2a/iHDkPqwH68/4ufI7p6pVJP//Dh8A05S02n+5vAmIk4QuMnYOi3b8Yjazbj7OeXYlRbMzwTz0f1lVchfP75igm5YSViaNu1D43P/xKhcVvhqQxD2ppysnjARuubaZz4swnu84HrekcvU0oroGmizbJmTF6+clVh4NatBqyuq1Nnf1NW/HvYo/drIel3pynEAF9IgY9t3IB9930HRtNJDLz6q6iYezn8I87Oqz3NTX9wGNE1a3B0yZPYc/cCzKqohN/H0f+GBai+6mrH0hesTWdehEoQPo8MeiusRAmkTbeBDVEiEFvP0fiCFyLoU6Lr7GLnr1Up7yObHqmt7eIis86facabkQt9nhb/dq8QwymULWosSQNME56KCgy7+zvYe9cd6job+YMfITzxvE5AnGAnNzJHj2Lv3XcivXMH7BmzMfWHP2x3hHJXp7TI+sGM7UZs062QRgJMD7jI4jCaR6JpuR+pfdvBfV5IRWbXQfePh9FBsyaet2zV36WyGO0JFd5hsrrzIf0x34yQro9IW1Zx8DkG0H2uaTj40E9gp9MYs/jnCrwyYAScrL1rndX6bqQnTUNpih4OQ9++FamDB/NrdgAf34P4W3dA2kkwT9BxorQ0sseH4/1HDyF1YIcj+Z79OSugCc2y8XX1qa6uAx5e7AlbsghnjJzp4q4kXX/ptLr+SqZMRWzzJtRce10HPyAvyc6PCoEjS36D7LFj2Fw9AummJjT+7x9d4LIj+M23wzbjYMLv0GVE4R30RfS/9BfQSv0IT5iA0IRJsNoSHTSsw34AT6ujwea9eOmlXqxZ0+Gc8Nwv6mZuaLCWzZoVlBKz0pZFx6Hb+5NUe/i996P805eg/6zZ6D/3cgdA4TnuwjeHIZ5BNRh42eXYM2o8jkqB5JpVMFMpdaN0B15mm+EfdhUCn/g29H4lGPvYrzDqwZ/i7Ae+B2/VQMisUZThhJE02Sv4yCozNV6x2U2i0GhnW329erpCZsd6uajKWhYlILr6muTKxmLK8QnW1iJ83iSMXvxzJzIjd7cbX97Zjat4YPC112HQA9/HgUMfoGXeF3HWA993KGG8W/C+oV9CcMytjvcnJbyDapSR00pKUXPDjbBSyXb/owvRzPIJwTkXF6vPq1cXYcBq50vJ2DSfRt5M8SCCzrAWDqPqS1/Ou6/5897XYdswkinEW1rhGX8uAuPPBff6+wY+bydUDkKt1a9uOkK1tcrpKsoEykNKwJL4lPpM9YkuDBjgfCklm6ISHMUYSX5/IoF+M2fBN3iwkmbe8+tJ8t2kv4SmQSYTindm666+gc9RlnOviQZdR1XkS8ooF7U7jLGsiiHkuLWRC/1YupTuDDWxnQHuHckYapTlk3QCOjFSbQqUXfypU5O4s167ttA+mgaLbiNvOZjxPmKbbus7+EJwrsRLpkyBVl7mpOA6MYHAus5cVVvU8BSmzHhuAhYulIo7QBVNpsxaJzYqC6+FS+AbMrT3814IPJfUoODHNZJWvAUBUwOLboX597sgzYQDnhKg6Sb4hszvFXyOLnqG6PJW10Bms0XporydxrmnH4KD6PNC1+Zp7eswuXb2hX4GNsRwpFRkFRu8pETl+foyco4NEUT3fuytzWh5/W/IHjuC5P4juGcIQ03VDsSjHIKcHJUzSCI45mvwD78J0nKCq17zNu4x8PTvj7ZdXU0X6S3FBgFN81tSDgaw85wdOzoygIalaxJZUMKj1w17HS54IxrFkd88gZPLXlJ3v1YSgrf6bIQn9kfF9A8gSnywsu6JtOOIvp6BGTuIwTfsRmDkaDd07n07h6ye6aLKFGOMUmf5oXWe1ONedAyyWWVtKbPb/U62MnQUFR743iIk9+5G6dQLMfi6G1D2yTpwbzNSBxbBSAiYWakYJY0W6BXzlIMVXfkcWte/hqF3LMCAz1/R7iL3RBc5u93dAj0A1go/CMNkEp7igY9yQzWYLVGk3z+kYgA3Hd5xmktsy9o3sPuWbyknZfTDP1NhMNM9sLMH0brubtjpFjAtoDxzZfDOuhLBsbehZBJQNf8KHH78Mey7ZwGMxkbUfOP6PFOL0aU802QS6cOHVOq8O00gSo1OmHl+HTonPm4AsoWyNMUKjwTWNi0ktm5pd107M4kxVcw4+NCP4RkwAKN++gj6zZytwJstO9Hyxk2wMzEwPag2kNmoY+3H3qbcYEp5hSdOUvnFfjNm4oMnfok47UdakgusOmzp0NC2eyfM5uZ8JakresYsKQ2Nsxb6mIsMucsZSZ7gxX9ZG5fAAY+Ts+uyChFAyc+TL76gvMFcbq/w78SYI799UhE9bME9CHziE8qQm7E9iG9dAGm1gWnOVedhCXiHRAqsPSVShbpt6IiNuK9eFUIO/+pxh7ndSJXG8T80qIiw2ByKMDTGWMaykk0eY5/6ctGidgao4VpFSqrSL0WVSEoV31Nc3/j8c/mzlyfGVVEqhtRcez1KppyvPlsJiuranRzbtuEXKbywtQz7WUTNcaJZhwSSIq3rqRqI8roZSO3fh8yxY84RKGQ47c25yjy1rn1DZZ2KaYkC6lylcV0axYMhnDiRK8lupPq8W2xAUS0IleD4M08he/yYQ2xuU9ceVMy9DMPv/S5EIOyGtO3gqdjrF0nsS07CYyurIc1kUYJz2nXWLbdi/FPPKptTuEfeFQZw+PFHnSu06EoqB2l76Qgx7FBaTvlBV8Y8N6nBdYWZhvUZSoJIWdyckhZoFBDFsX/h/co1Vla8gPPSIlOC4iFtphm+4VcDw26FtJLQtW4DGPWj9+8PvaLCqS8W0KBOKOc4+PBDiL+9VR2Z7qQvndCeGLGu22Ao0tCgns7Y6S0Z02qh5gQ6O91qQTCIxLa3sWfB7e1MUClvquDoMEntu/HtxdBvgsm0Omiq6N3T6FRTyLvSnOPQww/h+LNPq4iwczqs0xqcnDsBrCkUdgcG5OLkacvXRW3gTZ8QFEJ1W1tTUWFZGRJvb8Xeu25XlVzltak0VvfgQ7W3K+Ckg5xxCNFLcaog+lOZZzekPvjwgzj27NPKK+0JPLFP55ynTeuoKcXmQmHT6LA7dWPRMwJooKJab5VFFRuUliLxzjvYeeM1aF3/NszWPYhvKQQvOwQ2tmojYNi9/yBCoSCGDlGuefdxRa6Y4sYSVFjdc+vNOPGHpb2CV+uqlJhGYdcrk195pVW11RRotlY4mVrRFDCR/WvCYCd1zvub1HHQg4MoTQuiJIzM4RYcWnwzBn3NA6ZRhSigrjZptsI7OILAKDrz7c0SsXhC/d9BA9Tf3PNNjglpFMUS5MBEo2j8859U8YO8Ra20rFfwzpKSZy26Y+QS+tzQ6e9aJ25Jt/GocdPM6c+Vej3XxgyDRNZt4Z5pHGYsDd+wLGquqQT3UemqGeAWuCahD/wCQufckd8ux0m6aZT7b6maXkEtkKJMl3jLQtuunWha9jJa3vibyiZTBZp8kT6BB2y/prGUae6KZ+3X3O6RnusCaGhQzuVmbj+YMs2vMEB3jWFXLVAJkgyCIysx/LvXwDdkKqTtgxnbjszhp3DypbeQ2PYOwpP+UxVDAsNHQAyogre8HLbXhwy1xAUcG0GLm/EYzGgUqffeQ9v2d1SyNXlgv4o/uN8PvcyRenfWvgsDpJQeznkG/EfT16wy5fz5FFp2YAAr+qDbfrZp5vQlpV7Pv6nSWGdmccoMG/APq8DoxY9DK2mv5qhhW9h7112IvrYazONWcvx+5az4qwai0bRx7NgJjB87EpwYmUohc/h9pd5mPO5Ek16v8gTz1+wpJGGklLZPCJax7D3HhWfC3AsuMJjj/XVYRCv28EJXCzZ47LvbDPNzOmOlRidbQC1BMpNC9Ve+ocDbptutkW9m0DDkllsQ37ZFZYqVd0kRWyKBeMsuhBgwVtcR37DOiWforFMTFecq55grveXL5qc+KAFCGeGbL3v55czScJik30V1eLEnVRdYJMIveHHNsay07gtpylsp8HmZak/RKysQPu8CxzkSBN49w/S7bcNXMxjBMWMV6HynmKapniE6AinGwYMhda55IOAEMp3L6KeDHDDLPB6RMMyGyStWLZdFaoI9MoAGHQFqkJi6YvWj0Wz2j6W6rlFMgw7hsVvy7u4Ko5q/19sRSC5FRkyjzwTWaW44bcCFgzI/Xs5FwjQOZJn2TVUDKLj3Ow/e02J0LZLmezzGdUnTfDcohCYlxaxOCspoPKHCUIWrQE1z7W8UMbbt2aUqt71laz6KQSzUXGGYtv3laW6jdU89xbynBdWDCxeyc//6ejRtmfNtW0a9QgjistsNqUJf9WsuDs/lAalb43dLYDSeVGXrj0K6PQ0V8jrXHk+a1g2TV6xer4x5Ly20rE+Lu7fChs98ekpA8yyTDOUZy7K4EILSUKUXTcPgG25UDUw08t0af2xoL4+fack74En1r5+8fNWvc33MvT3L+rpJbsEcE8BRnjZtkwuumYmEck6Co8codW/bs1ulsgRZ8zMteSktzhgPaBrLgZfU3NUH8KfcKlvIBL/uec7DeXWcegY5F7BtZqdTKitTtFvjDAyy9j7OKdljpizzplMFj1NtY3da4yNi6quvbWyWmfPTtrWsTNc1Aq8kQY3OoZDTKXYGwZOTQ3aIbiYp5d6kaVySU/tTAX/a7fKFvTbUMS44v8cjuCdhmGRwyOHmp7t2b8DpPyrekmtl2PYzx018a9arrzad7ssT7HSJoQ7MhQQWkBtm1Y3zce3HGudzKc5vMxUdFEhSw/KpvSxRxLpTSGtLKSiw8ai3UKztkssFE15a+RLNKdb81NfBPgxxisACzm+bPWMWY/xOG3JGUNMEdWak3RcdHE+6/VWZYiG2C5ZiGJl7bYaCGb9GL0iQwyS3WUwu3hM++j/zG3ZklZOzaJF65nTpZx8Sv0N4PTgWOcTT522XzjgXkn3VBi4TjNX63BemKC1FhVf18lSnbBPFqZSEcV6e4iCHJksvTln2YcGxQjDx9PZQ6cqcpD+M1Dvsi49wEFGFLzuSdmyPN0+ybfZJQH5KMjlWSgy0pCwJ6To5VA4RDMhYNok+akskGMNOKeWbQtNe8+ptG8f+ZW28k8YpW/D/98XJeudlx86OCBHfks2GD7RFqwMe38A2quUDoJeh4hkrURkK7W2yrOzkF15Idn6OMjnzP0LgH8urs7LgtVl6FbavKkua9HG9PsvwMY58oZuaE3bsYJ3zc7ls7T/iJWr8s47/Ay+9uZ8NbH67AAAAAElFTkSuQmCC
