name: quickshear
version: 1.1.0

copyright:
  - license: BSD-3-Clause
    url: https://github.com/nipy/quickshear/blob/master/LICENSE

architectures:
  - x86_64
  - aarch64

build:
  kind: neurodocker

  base-image: ubuntu:24.04
  pkg-manager: apt

  directives:
    - environment:
        DEBIAN_FRONTEND: noninteractive

    - install:
        - ca-certificates
        - python3
        - python3-pip

    - run:
        - python3 -m pip install --break-system-packages --no-cache-dir quickshear==1.2.0 nibabel

    - entrypoint: bash

deploy:
  bins:
    - quickshear

readme: |
  ----------------------------------
  ## quickshear/{{ context.version }} ##
  Quickshear uses a skull stripped version of an anatomical image as a reference to deface the unaltered anatomical image.

  Example:
  ```
  mri_synthstrip -i input.nii.gz -o stripped.nii.gz -m mask.nii.gz
  quickshear input.nii.gz mask.nii.gz defaced.nii.gz
  ```

  More documentation can be found here: [link_to_documentation](https://github.com/nipy/quickshear)

  To make the executables and scripts inside this container transparently available in the command line of environments where Neurocommand is installed: ml quickshear/{{ context.version }}

  Citation:
  ```
  Schimke, Nakeisha, and John Hale. \u201CQuickshear defacing for neuroimages.\u201D Proceedings of the 2nd USENIX conference on Health security and privacy. USENIX Association, 2011.
  ```

  Licenses: BSD-3-Clause license

  ----------------------------------

categories:
  - "data organisation"
