# this template file builds cat12, new versions here: https://github.com/ChristianGaser/cat12/releases
name: cat12
version: "26.0.rc3"
draft: true

copyright:
  - license: GPL-2.0
    url: https://github.com/ChristianGaser/cat12?tab=GPL-2.0-1-ov-file#readme
    
# inspired by: https://github.com/m-wierzba/cat-container/blob/master/Singularity
# discussed here: https://github.com/ReproNim/neurodocker/issues/407

architectures:
  - x86_64

variables:
  matlab_version: 2023b
  matlab_runtime_version: v915
  matlab_mcr_root: "/opt/mcr/{{ context.matlab_runtime_version }}"
  cat12_inner_zip: "CAT_R{{ context.matlab_version }}_MCR_Linux.zip"

files:
  - name: cat12.zip
    url: https://github.com/ChristianGaser/cat12/releases/download/{{ context.version }}/cat-standalone-Linux.zip

build:
  kind: neurodocker

  base-image: ubuntu:20.04
  pkg-manager: apt

  directives:
    - template:
        name: matlabmcr
        version: "{{ context.matlab_version }}"
        install_path: /opt/mcr

    - template:
        name: miniconda
        version: latest
        conda_install: "python=3.9 traits nipype numpy scipy h5py scikit-image"
        pip_install: "osfclient"

    - group:
        # Based on: https://github.com/ReproNim/neurodocker/blob/91e3247ffb0d176f77c3ac3b3837acf8f252fd06/neurodocker/templates/cat12.yaml
        - install: ca-certificates curl unzip
        - run:
            # Install cat12
            - mkdir -p /tmp/cat12-extract {{ local.install_path }}
            - unzip -q {{ get_file("cat12.zip") }} -d /tmp/cat12-extract
            - unzip -q /tmp/cat12-extract/{{ context.cat12_inner_zip }} -d /tmp/cat12-extract
            - mv /tmp/cat12-extract/cat_standalone/* {{ local.install_path }}/
            - rm -rf /tmp/cat12-extract
            - chmod -R 777 {{ local.install_path }}
        - run:
            # Test
            - "{{ local.install_path }}/run_spm25.sh {{ context.matlab_mcr_root }} function exit"
        - environment:
            FORCE_SPMMCR: "1"
            SPM_HTML_BROWSER: "0"
            MCR_INHIBIT_CTF_LOCK: "1"
            MCRROOT: "{{ context.matlab_mcr_root }}"
            SPMROOT: "{{ local.install_path }}"
            XAPPLRESDIR: "{{ context.matlab_mcr_root }}/x11/app-defaults"
            PATH: "{{ local.install_path }}:{{ local.install_path }}/standalone:$PATH"
      with:
        install_path: /opt/cat12

deploy:
  bins:
    - run_spm25.sh
    - spm25
    - cat_standalone.sh
    - cat_parallelize.sh

readme: |
  ----------------------------------
  ## cat12/{{ context.version }} ##
  SPM25 standalone with CAT12 toolbox in Matlab Compiler Runtime

  Example:
  ```
  run_spm25.sh {{ context.matlab_mcr_root }}/
  ```

  Example with nipype:
  ```
  osf -p bt4ez fetch TOMCAT_DIB/sub-01/ses-01_7T/anat/sub-01_ses-01_7T_T1w_defaced.nii.gz /neurodesktop-storage/sub-01_ses-01_7T_T1w_defaced.nii.gz

  gunzip /neurodesktop-storage/sub-01_ses-01_7T_T1w_defaced.nii.gz

  python
  ```

  in python run:
  ```
  import nipype.interfaces.spm as spm

  matlab_cmd = '/opt/cat12/run_spm25.sh {{ context.matlab_mcr_root }}/ script'
  spm.SPMCommand.set_mlab_paths(matlab_cmd=matlab_cmd, use_mcr=True)

  import nipype.interfaces.cat12 as cat12

  cat = cat12.CAT12Segment(in_files='/neurodesktop-storage/sub-01_ses-01_7T_T1w_defaced.nii')
  cat.run() 

  ```

  More documentation can be found here: http://141.35.69.218/cat12/CAT12-Manual.pdf

  To run container outside of this environment: ml cat12/{{ context.version }}

  ----------------------------------

categories:
  - "image segmentation"
  - "image registration"
  - "structural imaging"

gui_apps:
  - name: "cat12GUI"
    exec: "bash /opt/cat12/run_spm25.sh {{ context.matlab_mcr_root }}/"
