name: oshyx
version: "0.4"

architectures:
  - x86_64

build:
  kind: neurodocker
  base-image: jerync/oshyx_0.4:20220614
  pkg-manager: apt
  directives: []

deploy:
  bins:
    - julia
  path:
    - /opt/ants-2.3.1/
    - /opt/miniconda-latest/bin

readme: |-
  ----------------------------------
  ## Open Source Hypothalamic-ForniX (OSHy-X) Atlases and Segmentation Tool for 3T and 7T

  *Version {{ context.version }}*

  OSHy-X is an atlas repository (https://osf.io/zge9t) and containerised Python script that automatically segments the hypothalamus and fornix at 3T and 7T in both T1w and T2w scans.

  If you intend to use OSHy-X, please cite this paper: TBA

  For more information, please visit https://github.com/Cadaei-Yuvxvs/OSHy-X

  ### Quickstart with an example image
  ```
  python -u /OSHy/OSHy.py -t /OSHy/sub-test.nii.gz -o /neurodesktop-storage/
  ```

  ### Usage

  ```
  Usage: python -u /OSHy/oshy.py
                 [-h] -t TARGET [TARGET ...] -o OUTDIR [-c CROP] [-w WEIGHTING]
                 [-d DENOISE] [-f FIELDCORRECTION] [-m MOSAIC] [-x TESLA]
                 [-b BIMODAL] [-n NTHREADS]

  Options:
    -h, --help            Show this help message and exit
    -t TARGET [TARGET ...], --target TARGET [TARGET ...]
                          A string or list of strings pointing to the target
                          image(s). Must be a NIfTI file. For a test run,
                          specify /OSHy/sub-test.nii.gz
    -o OUTDIR, --outdir OUTDIR
                          A string pointing to the output directory. Please
                          ensure this is within the mounted volume (Specified
                          with the -v flag for the docker run command.
    -c CROP, --crop CROP  Optional. A boolean indicating if the target image and
                          priors are to be cropped. If False, whole-image priors
                          will be used, which will improve the segmentation but
                          significantly increase the runtime. (default: True)
    -w WEIGHTING, --weighting WEIGHTING
                          A string indicating the weighting of the input
                          image(s). This can be either T1w or T2w. (default: T1w
    -d DENOISE, --denoise DENOISE
                          Optional. A boolean indicating if denoising is to be
                          run on the target image. (default: True)
    -f FIELDCORRECTION, --fieldCorrection FIELDCORRECTION
                          Optional. A boolean indicating if B1 bias field
                          correction is to be run on the target image. (default:
                          True)
    -m MOSAIC, --mosaic MOSAIC
                          Optional. A boolean indicating if a mosaic image is to
                          be plotted after running Joint Label Fusion. (default:
                          True)
    -x TESLA, --tesla TESLA
                          Optional. An integer (either 3 or 7) indicating the
                          field strength. (default: 3)
    -b BIMODAL, --bimodal BIMODAL
                          Optional. A boolean indicating if bimodal priors are
                          to be used. If FALSE, then only unimodal priors
                          (specified in --weighting) will be used.(default:
                          False)
    -n NTHREADS, --nthreads NTHREADS
                          Optional. An integer indicating the number of threads.
                          This is passed to the global variable
                          ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS and the -j flag
                          in Joint Label Fusion. (default: 6)
  ```


  ### Output

  All output is written to the output directory (specified using the `-o/--outdir` flag.)

  Contents of the output include:

  * `sub-XX_Labels.nii.gz`: Output from Joint Label Fusion. The label file for the left and right hemispheres of the Hypothalamus and Fornix. If `--crop` is `True` then this label file will also be cropped. The labels are as follows:
      - 1 Left Hypothalamus
      - 2 Right Hypothalamus
      - 3 Right Fornix
      - 4 Left Fornix
  * `sub-XX_Intensity.nii.gz`: The input intensity image for Joint Label Fusion segmentation.
  * `sub-XX_resampled_Labels.nii.gz`: sub-XX_Labels.nii.gz but resampled to the input target image.
  * `sub-XX_hypothalamus.nii.gz`: sub-XX_resampled_Labels.nii.gz but with only hypothalamus labels.
  * `sub-XX_fornix.nii.gz`: sub-XX_resampled_Labels.nii.gz but with only fornix labels.
  * `sub-XX_mosaic.png`: A 16 slice coronal visualisation of the segmentation.
  * `*_log.txt`: The log of the piecewise registration between the atlases and the target image.
  * `sub-XX_TargetMaskImageMajorityVoting.nii.gz`: Labelled voxels where Joint Label Fusion was not performed. This is the case when 80% or more of the atlases agree on the same voxel.
  * `sub-XX_TargetMaskImageMajorityVoting_Mask`: A mask of voxels where Joint Label Fusion segmentation is performed.
  * `sub-XX_volumes.csv`: Volumes of the four labels (as described above). Units for volume are in mm<sup>3</sup>.

  ----------------------------------

categories:
  - "image segmentation"
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAIAAAAlC+aJAAAACXBIWXMAAC4jAAAuIwF4pT92AAAF8mlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNy4xLWMwMDAgNzkuN2E3YTIzNiwgMjAyMS8wOC8xMi0wMDoyNToyMCAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV2ZW50IyIgeG1sbnM6ZGM9Imh0dHA6Ly9wdXJsLm9yZy9kYy9lbGVtZW50cy8xLjEvIiB4bWxuczpwaG90b3Nob3A9Imh0dHA6Ly9ucy5hZG9iZS5jb20vcGhvdG9zaG9wLzEuMC8iIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIDIyLjUgKFdpbmRvd3MpIiB4bXA6Q3JlYXRlRGF0ZT0iMjAyMS0xMi0wNlQxNToxNzozNCsxMDowMCIgeG1wOk1ldGFkYXRhRGF0ZT0iMjAyMS0xMi0wNlQxNToxNzozNCsxMDowMCIgeG1wOk1vZGlmeURhdGU9IjIwMjEtMTItMDZUMTU6MTc6MzQrMTA6MDAiIHhtcE1NOkluc3RhbmNlSUQ9InhtcC5paWQ6YzQxMGQ2NmQtOTViZi0yZDRkLTg4YzgtODRhMTI3M2U0Nzg3IiB4bXBNTTpEb2N1bWVudElEPSJhZG9iZTpkb2NpZDpwaG90b3Nob3A6MzQwZGQzMjItOTkwZC1mNzQ4LWJmNWYtY2Q3YzZlOWYxYmU2IiB4bXBNTTpPcmlnaW5hbERvY3VtZW50SUQ9InhtcC5kaWQ6NThhODJjYWMtZGEwZC1lMTRlLTlhN2ItZTAxZjUxOWI5YThjIiBkYzpmb3JtYXQ9ImltYWdlL3BuZyIgcGhvdG9zaG9wOkNvbG9yTW9kZT0iMyIgcGhvdG9zaG9wOklDQ1Byb2ZpbGU9InNSR0IgSUVDNjE5NjYtMi4xIj4gPHhtcE1NOkhpc3Rvcnk+IDxyZGY6U2VxPiA8cmRmOmxpIHN0RXZ0OmFjdGlvbj0iY3JlYXRlZCIgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDo1OGE4MmNhYy1kYTBkLWUxNGUtOWE3Yi1lMDFmNTE5YjlhOGMiIHN0RXZ0OndoZW49IjIwMjEtMTItMDZUMTU6MTc6MzQrMTA6MDAiIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkFkb2JlIFBob3Rvc2hvcCAyMi41IChXaW5kb3dzKSIvPiA8cmRmOmxpIHN0RXZ0OmFjdGlvbj0ic2F2ZWQiIHN0RXZ0Omluc3RhbmNlSUQ9InhtcC5paWQ6YzQxMGQ2NmQtOTViZi0yZDRkLTg4YzgtODRhMTI3M2U0Nzg3IiBzdEV2dDp3aGVuPSIyMDIxLTEyLTA2VDE1OjE3OjM0KzEwOjAwIiBzdEV2dDpzb2Z0d2FyZUFnZW50PSJBZG9iZSBQaG90b3Nob3AgMjIuNSAoV2luZG93cykiIHN0RXZ0OmNoYW5nZWQ9Ii8iLz4gPC9yZGY6U2VxPiA8L3htcE1NOkhpc3Rvcnk+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyIj8+0V1zEwAADAFJREFUaN7VmltsHNd5x39zn71yySW5FC+iLDKSbNGxJTGxHaW2YqdojNjxQ4HGAYoACYLe0wJF0jc/tQ9Fi/ahD30pjAJBixYpkIe0RSKlcGLJidzoYkmWZZq3pShRJJfcXe5lZnYuZ6YP1EiULetCLun6PO3u7Ox8/+983//8z/+sdKiri50akiSbiT2OXYSIT+nQUvuQtTb+oLzDAHRJVmTjUwwgCj1Z0j/FAALRlCTpUwwgFHYURTsJQIcOUOK3efgM9MPNLMoyXXnkB85DBKqabSMA9Z5XD8BvQx6m4Ar0wFdgBCx4M53+RyTr4Bjf+Q6+z+nTnP4V16/Rat27BwJJbmcP3KMcj8JLYEAeAihDJ+SgAzqhY2Dgz4+M/1d3D5/7HIU++grU65w9y6mT+L4yOCh6erhyhTd/gW1vfKCSSo1azQ/aBUD5mM/H4QXIwgLMgg4epECGBfiVJM8EgbN7+KLTwvNotZifp1jk0sXEL3/5jevXvusHz7z6jYlvf7vxlRfJ5Wg2qdURAohkOReKervWso/OwCCMwfPQhAa4cAHSANRBl5XWyMjVJ55oJJKRbTvFORImAwOoKrUayyVpaXGPYz/W1ye99LUrXzw6WyggK9TWWLjOzAynTnH58t7S8g1otR3AATgIj0IPDENNUf4+mWo26ktgPfucHBFevYppEkWoKukMusbaGqUSskyuk3Qa22JlBd/n0CGOHCHfTaGXjg5Mk95edu2iXOb114dP/LTywQeN9pbQE/AaHIU8dEELzg8MnPidr5cyWb9UotAXZTIg4bbwPFZWKBZZWqS+RrNBo055hZUS5RUsC9dhbo5ymSCg0cBpEQRYNisraDq2bTz+2YioVZxtJ4Avw2FwQEAn7IWfWNZ506Snl70jvPoq9TrT0ywtUlrGdSBCCHwfQFGIIsKQjRRfXmW5hGXRqFOvUa9TqVCtsLysDg4Yf/hHVmmZ995rD43ugmdAg3nIwTlYgJ8JwdkzDAziOAQ+qTT1OvUawO7d/N4fMDlJsUgmi6owV+TgQZ47hmnyr//Cz04AVFZp1CmV6OtjYABVSU5MfGt2ppBKLb744tLf/O2PD4+Lv/pLmo2tAvgMjEICmuDCCfifdZawbaYmAa5fQ9dvJ1g3MEwcB0UhmcCyeOppXnmFvXtxW9RfYXaWmWkA3+PaPNUKto0iJy6/OyZJX4LFH/zAKK3s+fcf/sPoiPjun7C4uKUScuEYDMMq/DVcuOtXhSAMb76uVPjftxkeJpVCCDo7yeUoznHqJG+8wcwsmsb81dv3eh6rK6QzTl/flXJ5VDeSnvfk9PQjtVrj+9+7dPgIFy6yvLR5AAK+CcBrMP2g/CWz/wC9vagqskyzQaNBucLkFNNTzEzdbI+No1pBN9bCsByK0SA4BObZMyOd+dlXvz73G8coFpme2gyGl0CGP4bxTdycSpPtoLuXg4/z1NPsHkZR7pczRU8kviXLl0HA9XTmRyffGooiLl3muWObAfCFnd+XmeZjivJPsAAWTIyN/d2163oU8cbPOXDgoUtoFYIdBqCqSJItRBYKoJZKiclJ7asvn+3K05HjFz+/S/ndA8A34Z0dBiDLSUm6LsQsFCAN9anJLy4tiueff2d0FN3grbd4wF2DAh0wt8MAJElT1WQQXIZFKMBeeOTChcNrtaV9+68cGWdXP+fP30eZ3wIwt/M9IEmKqnX5fgWuwSzshzxI75z/TRFMvvy16aNfIJHk5JvrAvZeicA0B+W22gQPVkJGR+7zGwTl9+AyVMBC+skP/6MjilhY5E//7F6cJitmtuOwIsummRhSlFSEiEJvh7yJKNS0Tt8vx7sCDZ6BfpChZ3a29NWXz3X30N/P6dN3X+AUJWWag449qwhhed4KkmQavbreDUEYujtCRGkhrCgS8SSMw14wIFxcHOzpPTF2sN5scPFdJt7/6L3ZZPIR25oMQ+/mDIVhy/crYdjStE7T3AVKGLa21QBUlEQYelHkx5LsKIxCEmTQKpX3D469ZzlMTXHxTo7U9W5V67DtmXXw6p1qx3IcS5YNVe0wE7sBt7UYhq1tqiJJuvV0GwIQ0AITaDbk48cZGqKnGzNFy7q1Ag4oStq2p+Opu9ueOIqEEFbg12VJ0/QuwyhEod/2ulLVpCwbQjQB6IIXYA+ooEFRhP8py7OGQT5PbZLVKkJSDHOXJKktZy6KwgfxhULPKzl20XWXdaM3kxkzjD5JapsRFoa+fNtf2Qf94IMFNjRqtbVqlTDCVXglw+vwlJL2JK3lzG+M/r6+EEDgrwX+mqIkDXMwqWYCYXteKQr9LQNwJenW/GdBBwlCsGCNaLVUolwm1UM6xZehO6j9RVC7tGlrUQjbtiZte5YoTCZHTHNIUZJb6wE/BqBCElrggwsO1A5SlZo0bVSNhMMk7IHXYHCL3mgUCdddtJoTQjRNcyiV2q+qHZudgUCWTUkCOqAAIXjgQkui/LtYz9rM11mewb7KeqM8Cb+/3uMPVUJ3Hb5f9f2qoqZ1vUc3CoFf8f3qLWZ4UKc99CRJjqJO2A2JmFG8/cw9jT/iUjqLfQZ1DQNCyMAxOAM/bpc7LYKmYxdbzpwk66nUfjMx9FCqRAhLkhTQIQOJuAeqn+W8AxGMVxlYIx07zB2QhSfuDFptB594buuGJy1renci+UgYup67EvPjfftYg1WwQEAEywr/vY9LVSiBAQYkQYc8hBBCF3RC+X7e6GbaUgjL91YlJMPoM82BiCAUzj0X47Qc6iIqgQq7ISlx8gX5n8ejqgIhRBBBCvLQDT5cg2WYhxvbAIANqqQchpam5kyzX5L1UDgQ3g1xED7qR78VYF7nhpOk+jRvPKm4XWEdCMEHATJk40OKq7ACElyKdU77AdyqqyCoBUFNVTK60a3pXWHkfUjtRiMi+n7A8/D5gAOTHbm3c+lWYN5otOj1b0YvQAIDUpCEBViBJJwDd1sB3BI8QVD3/aqiJEyjX1FT61N02858FoZhGHZjvxBdP2pPHOF8H+kFhus35ZEMBphgwCpUwYNT4O8AgNvLedDwvBJRaBgFTe+SUEPN4UsRozAIBchABrqhBw4wMcDjv6azRbiuTkEHBarQhCl4u40s9DAw6kFQl2XD0Ap+SiERkodcXOYhtCABWcQ4s8OMVSnH9ORCFWwQcK69NLoJFeS48+yCJvgbNh3rtSKBBxL1LvpBBQtkEFCPiejSJwsAwIB+cKEOFuhxIEo8Dx5CIw9GDFMCASq8daeN9UkAUKAXCqCBAzak40DkWM75FDPI0As5cGOpNA/vtkULbSn+XCpKBWHWJQtKzPZR7DI7UAfBah912AUiXoMrcAbsrajRrQ8tkTeNIVwZARlIgQIKSCDHeRZgYvV0vZkanVWyJuQgCwGc2aKc3mr0Wpeh97Zq82Hg4IMa07u2AUC8yxf71lazlQtaz48yYxNGQYY5mPqYE5qdGLreoyhpqzEZRYKBOOsRaHHo62LUhhB0Ii3MUznYqlhB+gOj/5zWfTyoB+4Skf8JAND1gqpmbHsGInTohDRoEMS5XwfjgR2LhCqnQhagI2gWgsnjsn7c6Eul94mg4XtlIaydA5BIDEdEth2f/awDyMcNsM6bKriwCg1oggIex+/0GHDmLSRdzyeSe4Swfa8cBPVtB2CaQ0DLmb+DRrugG3Kw7kusZ7MBc1AGGRJgxFfvlFeet+p5q4qSNoyCYRS2FYCUzjzmeSteq/ThK+v7q654KRCwAtOwBBr0cpNhw3vs5pq23ZRlfbsASJKaTI363ornfiT6JlyGYRgBF4owBzPgQh7y8T8zFuF+58dh6EnbEb2ipMzEbtddDPy1j12Mh+Ew5AAJCczoJtsnIAMV+Df49QNkajuiT6b2ua0Fzyvd75gADGRdN9IDTlBEjblVgzJUPwmRpmq5bPaQoqYfothQUolH+f8wNC2XTj+2ifOeRGLPBpvxIVPWProcULVOq/n+Q9pbAGHkS5KyiRvbpoV0vVvTu63mlU0GIamybG7u0XJbci8rqUb94oeMbx6qDzZrFW+1hBKJPRA6GxfaTWwyhbvpGdg8AEmSTXMojDy3tbjF0zQh7E0f9f4fjrk+R/ObsxgAAAAASUVORK5CYII=
