name: nftsim
version: 1.0.2
architectures:
  - x86_64
  - aarch64
structured_readme:
  description: NFTsim is a neural field simulation framework for large-scale brain dynamics. This container allows users to simulate various neural models including corticothalamic and cortical circuits using configuration files.
  example: nftsim -i /app/configs/eirs-corticothalamic.conf -o eirs-corticothalamic.output
  documentation: https://github.com/BrainDynamicsUSYD/nftsim
  citation: ''
build:
  kind: neurodocker
  base-image: ubuntu:24.04
  pkg-manager: apt
  directives:
    - environment:
        DEBIAN_FRONTEND: noninteractive
        PATH: /opt/nftsim/bin:$PATH
    - deploy:
        bins:
          - nftsim
        path:
          - /opt/nftsim/bin
          - /opt/nftsim/configs
    - install:
        - build-essential
        - ca-certificates
        - git
        - make
    - workdir: /opt
    - run:
        - git clone --depth 1 https://github.com/BrainDynamicsUSYD/nftsim.git /opt/nftsim
    - workdir: /opt/nftsim
    - run:
        - make nftsim CXXFLAGS='-std=c++11 -lm -Wall -Wextra -pedantic -march=native -mtune=native -funroll-loops -O3'
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAmlJREFUSEvllV1IU2EYx39nO9Ol0+bmV2OKlSbrJvHKCNNVEEJ2ISIOdpOVBOK9trooqBulEALropJFFwVRF12si31I131c2qhdhNJGbay1g+3jbHEmSmuuTpk39XIuDu/hOb/3ef7P83+FjL89j9qlrWYqcI7PiaTaCIR/D5DPgyCUqcBWS5TLw9vlNPVGLaYabSnlbwAWX68SS8icPFSNTvwhla0AsnKeJ88lHJfChZNbG0TuTjfR1VHJ9Ydxrt6LFfZrjSYS8bX3zVZDcwt9A6MYzY2FzxtdtA64GegkEAgQCoW4MN7FlLOOB74k+45eY3h4GIu1lbOnTzE7O1vyf0mS2N1uUwdQoicnJ6mK3edjXMY+eoOhoaECYPzMGDMzM/T39yPL8gYomUyyEo6qAwSDQdra2jCbzSiBbre7BCCKYhFAIakuUW9vL36/H4/Hw+Dg4KaA+fn5IsDc3ByWvd207+9Go13rwrIa2Gw2nE4nLpeLnp4eJiYmSjJIp9NFOjgcDj5JonrA0tISkUiEbDaL1+tVVaLDx0d+D2C32/H5fESjUfR6fZHIigZdB49R32gFQXkEDLV17DTVIwiaX5fogGWZl8EUt9zPUEBKG37fRTW1RvoGHDS37EEo4y8/1eDiSBxpNcf0HZlwOEwqlSqagz8CrE+ykt/jK7vo7qzk8kKM208TJZO8o8rAkRNOdRkoRhdayRD6kCGXA40GOqw6Wpt0vI9kePEmxaPFr0R0dir0BsSKCjSCpmAJ1TXGstah+sKRc/DqncBCcAwZcXtutCxVnA+M80Va3R4AW7FrVUf6LwHfAA+Ur1jBngS7AAAAAElFTkSuQmCC
categories:
  - programming
  - hippocampus
readme: |-
  ----------------------------------
  ## nftsim/1.0.2 ##

  NFTsim is a neural field simulation framework for large-scale brain dynamics. This container allows users to simulate various neural models including corticothalamic and cortical circuits using configuration files.

  Example:
  ```
  nftsim -i /app/configs/eirs-corticothalamic.conf -o eirs-corticothalamic.output
  ```

  More documentation can be found here: https://github.com/BrainDynamicsUSYD/nftsim

  Citation:
  ```

  ```

  To run container outside of this environment: ml nftsim/1.0.2

  ----------------------------------
