name: brainnetviewer
version: 1.7.20191031

copyright:
  - license: GPL-3.0-only
    url: https://www.nitrc.org/projects/bnv/

architectures:
  - x86_64

auto_update:
  method: sources
  sources:
  - id: standalone
    method: artifact_listing
    url: https://www.nitrc.org/frs/?group_id=504
    version_regex: BrainNetViewer(?P<version>\d{8})_sd_Linux_x64_compiled(?P<runtime>\d{4}[ab])\.zip$
    download_base: https://www.nitrc.org/frs/
    target:
      file: brainnetviewer_zip
      variables:
        artifact_date: version
        matlab_version: runtime
build:
  kind: neurodocker
  base-image: ubuntu:22.04
  pkg-manager: apt

  directives:
    - install:
      - openjdk-17-jdk
      - bash
      - ca-certificates
      - unzip
      - libxext6
      - libxt6
      - libxmu6
      - libxrender1
      - libxcomposite1
      - libxrandr2
      - libxss1
      - libasound2
    - template:
        name: matlabmcr
        version: "{{ context.matlab_version }}"
        install_path: "/opt/matlab"
    - run:
      - ln -s /opt/matlab/{{ context.matlab_runtime_subdir }} /opt/matlab-runtime
    - run:
      - unzip -q {{ get_file("brainnetviewer_zip") }} -d /
    - run:
      - printf '#!/bin/bash\nls -la' > /usr/bin/ll
      - chmod +x /usr/bin/ll
      - mkdir -p /neurodesktop-storage /neurodesktop-home /neurodesktop-share /neurodesktop-trash
    - copy: brainnetviewer /usr/bin/brainnetviewer
    - run:
      - chmod +x /usr/bin/brainnetviewer
    - entrypoint: /usr/bin/brainnetviewer
deploy:
  bins:
    - brainnetviewer

categories:
  - functional imaging
  - visualization

icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/p9sAAAAASUVORK5CYII=

readme: |-
  ----------------------------------
  ## brainnetviewer/{{ context.version }} ##

  BrainNet Viewer is a brain network visualization tool for visualizing structural and functional connectivity patterns.

  Homepage: https://www.nitrc.org/projects/bnv/
  Example: `brainnetviewer`
  License: GNU General Public License Version 3 (GPL-3.0)

  ----------------------------------

files:
  - name: brainnetviewer_zip
    url: https://www.nitrc.org/frs/download.php/11585/BrainNetViewer20191031_sd_Linux_x64_compiled2018a.zip
    sha256: 3cd6a0c92a8ec69a014c7aadf36cea7f7131ddc591742e57243318300f8644aa
variables:
  upstream_version: 1.7.20191031
  matlab_version: 2018a
  matlab_runtime_subdir: '{{ {''2018a'': ''v94'', ''2019b'': ''v97'', ''2020a'': ''v98'', ''2020b'': ''v99'', ''2021a'': ''v910'',
    ''2021b'': ''v911'', ''2022a'': ''v912'', ''2022b'': ''v913'', ''2023a'': ''v914''}.get(context.matlab_version, ''R'' +
    context.matlab_version) }}'
  artifact_date: '20191031'
