# Generated by Neurodocker and Reproenv.

FROM neurodebian:sid-non-free
ENV DEBIAN_FRONTEND="noninteractive"
RUN printf '#!/bin/bash\nls -la' > /usr/bin/ll
RUN chmod +x /usr/bin/ll
RUN mkdir -p /afm01 /afm02 /cvmfs /90days /30days /QRISdata /RDS /data /short /proc_temp /TMPDIR /nvme /local /gpfs1 /working /winmounts /state /autofs /cluster /local_mount /scratch /clusterdata /nvmescratch /vnm
COPY ["README.md", \
      "/README.md"]
COPY ["app_test.sh", \
      "app_version.sh", \
      "build.sh", \
      "/neurodesk/"]
RUN chmod +x /neurodesk/*.sh

# Save specification to JSON.
RUN printf '{ \
  "pkg_manager": "apt", \
  "existing_users": [ \
    "root" \
  ], \
  "instructions": [ \
    { \
      "name": "from_", \
      "kwds": { \
        "base_image": "neurodebian:sid-non-free" \
      } \
    }, \
    { \
      "name": "env", \
      "kwds": { \
        "DEBIAN_FRONTEND": "noninteractive" \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "printf '"'"'#!/bin/bash\\\\nls -la'"'"' > /usr/bin/ll" \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "chmod +x /usr/bin/ll" \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "mkdir -p /afm01 /afm02 /cvmfs /90days /30days /QRISdata /RDS /data /short /proc_temp /TMPDIR /nvme /local /gpfs1 /working /winmounts /state /autofs /cluster /local_mount /scratch /clusterdata /nvmescratch /vnm" \
      } \
    }, \
    { \
      "name": "copy", \
      "kwds": { \
        "source": [ \
          "README.md", \
          "/README.md" \
        ], \
        "destination": "/README.md" \
      } \
    }, \
    { \
      "name": "copy", \
      "kwds": { \
        "source": [ \
          "app_test.sh", \
          "app_version.sh", \
          "build.sh", \
          "/neurodesk/" \
        ], \
        "destination": "/neurodesk/" \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "chmod +x /neurodesk/*.sh" \
      } \
    } \
  ] \
}' > /.reproenv.json
# End saving to specification to JSON.
