name: convert3d
version: 1.1.0

copyright:
  - license: GPL-2.0
    url: http://www.gnu.org/licenses/old-licenses/gpl-2.0.html

architectures:
  - x86_64

build:
  kind: neurodocker

  base-image: debian:bookworm
  pkg-manager: apt

  directives:
    - template:
        name: convert3d
        version: nightly

deploy:
  bins:
    - c3d 

categories:
  - "data organisation"
