name: fmriprep
version: 25.2.3
copyright:
  - license: Apache-2.0
    url: https://github.com/nipreps/fmriprep/blob/master/LICENSE
architectures:
  - x86_64
build:
  kind: neurodocker
  base-image: nipreps/fmriprep:{{ context.version }}
  pkg-manager: apt
  directives:
    - deploy:
        bins:
          - fmriprep
  add-default-template: false
  add-tzdata: false
readme: |-
  ----------------------------------
  ## fmriprep/{{ context.version }} ##
  fMRIPrep is a functional magnetic resonance imaging (fMRI) data preprocessing pipeline that is designed to provide an easily accessible, state-of-the-art interface that is robust to variations in scan acquisition protocols and that requires minimal user input, while providing easily interpretable and comprehensive error and output reporting. It performs basic processing steps (coregistration, normalization, unwarping, noise component extraction, segmentation, skullstripping etc.) providing outputs that can be easily submitted to a variety of group level analyses, including task-based or resting-state fMRI, graph theory measures, surface or volume-based statistics, etc.

  usage:
  ```
  fmriprep replace_with_bidsdirectory replace_with_outputdirecotry participant --fs-license-file ~/.license.txt

  ```

  More documentation can be found here: https://fmriprep.org/en/stable/

  To run applications outside of this container: ml fmriprep/{{ context.version }}

  ----------------------------------
categories:
  - functional imaging
  - workflows
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAACj0lEQVRIS+2VUWhSYRTH/3Y3tWwzhNpsw1jEalBtFDopAl+EHjYiRhi9SExsogWGDppPsb0ke2mZxAJXIx+slwYJJj1YD1kxxlSIYuFM0KWVMdHt0lWX98ZuyZTdZW/1vdyHc7/z+87/f77z8Qb1y2vguPy+s+i+8gTfVqpveP9Ii4Pn7lcEeVsBuKc70Hv5GQpNhzYQsh9fYvHpNXTrn9cHaD8xiBbV9Q2ADzMm5FOR+gEQCHHs6gJ4PB4LKVEkXt+QYceertqAQmEF4dDNquKWShTSqVl8Tr9BobCKVsUlSBV6JmE2/gqpWRfS8w/Ab94Lae8Q2k9Z2DysByT5Fe7p/RztBlqOX8SBM7cRmTqN7OILdh8hFEM5slQb4HA4YDQaK0BWqxXj4+NYj2m1WrgfzjByzE30YGxsDDabDWazGbfuTG0OEIlEMBgMLISiKBSLRQagVqsRj8eZ7/bdXSC/vEM0GgX9j9Pp5AYQCoXQ6XQb5KIBBEGgr68PSqUSiUQCKpUKo6OjyOfz8Pl89QNoKkmSSKfTsNvtcLlcCAaDGBgY4A6gT5/L5dgKOjs7kclkGInoNTk5CbfbDYVCgVgsBjru8Xi4AyQSCYaHh1lAMplEqVRiASaTCaFQCH6/HzKZDBqNhkm+ZYkOHzGikd9U7v0VREITFQCLxcJI1N/fD6/X+2eA8xfeQrSzraz5zzuyLhFdgVgshlwuRyAQKB+g8PcBotajyH8KQyTtQX5pnjvg9978VUGmXEFHRdvKrVEsPB6CTDWC8F3V5je52iyiPeDzmxkP6DnVQADLuwisUkDbSTOK33NYK1JIzd1jAdsaBNVnEZchJBAA8X2NNR+cajm29OD8B2xqw78p0Q934M/Yyes09AAAAABJRU5ErkJggg==
