name: bidscoin
version: 4.6.2

categories:
  - "data organisation"
  - "bids apps"
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAFiUAABYlAUlSJPAAAAcTSURBVFhHxZcLUJVlGsf/BxAVEkyjEZcZcRIHb4SY103H1HQIGnWzzCnZ3co0Q9sZtx1rx0u6SbJqTim2QovCEBoiAV4IS4WjA16QdUEuwpGrJRzudw/Is//v9SM9erw0ju1v5j3f996f8zzv+zzPByK3l5CQEHlcJCYmWu2ll1uV5uZmfejjxcPDw1oAZ2dnvevRMNfXy+WyMrlcWip1ra16q20mT56sBDBoP0QT5KGpb22FpaMDVZmZKPz2WwxesAD//fxzTHn/fXQXFcHhqadQlZeHisZGDBg6FINnz4abpyc8n35aX+EmI0aMgKGmpkYGDhyoN9mmsqoKXQ0NyA4NhdPIkRjUuzcsXV3wW7oU7RTkiSef1EfeTc3Zs6jJz0duVBT6LV8Odx8f+Hh56b1E6eMOulhyzp+Xf7/8smTGx8uJ4GBpqaq62Xkbp9n+GZf46ccfZQOfuTt26D22ubBmjRjXrpUUo1FvETFoP7os6GYx7tmDy3FxWBweDgd3dzgYNCvZJnXVKnS1twOOjjBQI1Peew9F33wD2NvDvm9fnPn4Y3jMmIHm0lIsMpnUnLwdO9BOjfXy84MPTfCLBirMZokMCJAOHiRbWJqa1NPMQ2ZKS5PKK1dkM6fvf+st+QefB4OCZN+UKXL5+++pwi7JWLVKYocNkz0DBohx+XI1t4fUN98UY1aWelcCFJWXS9pHH0lLY6NqvJOsDRtkDTdpyMuTo+vWyW6aZhvrW1gKsrMly3hKvtsZJl8GBMomtuUmJ0snr3R5Soq+gjXHFy6UsxSgiWNQ39IiZ3bulHIudC/MFy5I2eHDeo2237pVtnOjQ0uX6i03McbEyHq2n+fGSdTG3/l+w2LRe29xlWcm56uv5NzFi2IwXbsmp2bNQlBOjrLRwxDKc+HKZxuLg4MDGmn/q3z3DQjExI0b4Dt2rDbsnlznjao8cQJtPAN2FSUl8Hz+eb3rwZzbuxd9+ex0dkZAdjb8DhyA9+ZQjPYdi+uHD+GZIUNuDrwPFcnJcB09Gq11dbD7KSsLfUaNQllqqt5tzfn169FFx9NSX48rGRk4t2IFtHsxads2DPf1xe/nzsWCv32IIX+Yjwa2N7S1IZwaivHwUPPvxMx/buGY6H370L+7G4b8U6ckmd5supMTvBYuRH8u2kP50aPY/dJLWLBxI9oGD0bm6tW0qsCppgZ1FNqNQpn43mCxYBidy4yYGPiNH6+EHvjssxg6f76+ElAWHw8zr2I75x3YvRupSUnI51rKD2yZPQfOPmNgV10NN9p09AsvYPjixfpUa5I++ADFCQkYQNdqprv9kALcF/7LpMAA9FmxEp/Om4c2CtuPzcmNDXB2cYWdNuZPUXthzjyD67W1yKmoQG5BAc598glw44bW/QtX9u9HJ339u3n56GhswmKa5EGcXrkS7qH/xF+oyRfnzsOXtP9x/nNtc4W6FzoVJpMc3LJFVk+aJPEREbJ1wgTJi4oSE92xxg+LFkmsp6eYYmMl0slJqjIyVLstzCdPSi3Nm5WeLs9xm+Z7+BgrV9xDLG2eHRsLF0avGrrVQLrNSXS7TwwapI+4RfXJk3DhyacHhYXRryQ9HX5LliD2iy9QSvPEff01Io4cwUR/f32GNTYF0Oik+vNOn8YRqq+qvQ2LeGcn0o/fjpkLx1ClvbhEbx7ifsOHI5cCnOHVtOvsRK++TliXcBDPzZmjz7ibewpwO3+lBtwYRl+kBvw+Y/wjJQxWW1lqeSbseDG1ZWp5sH73zDBMnj8PU19/Hd7jxqmx90UT4EGUFxbKn93d5dPXXpOrdMnZjA1FRUXyRy8vaWLwaqFPrywu1kf/Oh5KAxppvMfRwcGwp4NxYjgtOnYM4YWFcKfaH4WHFkDjErOb70JC0E3fH0iPOJap1qPyqwR4HChH1MOlsDBkb9qEn41GVa9ISUE788GzzGwKIiJUm0Yxr2ja22+jiYHsfmjjHoimgR4iXV2lq6NDdunNB8ePl5/pTH544w25evy4ynDqCwrkiL+/NPAQMlaoccyOpaOuTr2bmVdY9O+LaiYdNJe0VVdLm42cUsNKgDBufOzVV2W/t7eqJ02fLtcoALNhVY8fN049/2UwSNqSJer9P5s3K4HSly2TkoQESZw2TcIdHVVf4tSpkrN9uyTPnKnWtoWVCdzGjMEsRkboiajBzk59utj36aPqHXrgeZcBZgJNFU2/oCWc/nRIU3ftQglvSgDD+ih+H2hJh6OrK4Rjp0dGwjsoCO0MdndiJUAls6JDM2eiqbhY1bU8wEBXrAWUfQy3I5ctQ92lS4h0cUHStGnwfucdDH3lFYRR4ASGYb+1a5VQeTxLvfv3B02BG/xuYEKLThbNVd9FMHP7/xdxcXHqBspOJqW/NReZkGp7KwG08ltqIjo6Wt8c8j8aCvDhUTADMAAAAABJRU5ErkJggg==

architectures:
  - x86_64
  - aarch64

build:
  kind: neurodocker

  base-image: ubuntu:24.04

  pkg-manager: apt

  directives:
    - environment:
        DEBIAN_FRONTEND: noninteractive
        FSLDIR: /opt/miniconda-latest
        FSLOUTPUTTYPE: NIFTI_GZ

    - install:
        - python3-pyqt6     # Avoid GUI issues
        - build-essential   # Needed for pip (needs gcc)
        - dcm2niix
        - libgl1
        - libxcb-cursor0
        - tk
        - dbus
        - qt6-wayland       # Make sure wayland is supported

    - template:
        name: bids_validator
        version: 1.13.0

    - template:
        name: miniconda
        env_name: bidscoin
        env_exists: "false"
        conda_install: -c conda-forge -c https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public/ fsl-libvis fsl-avwutils fsl-flirt
        pip_install: setuptools==78.1.1 bidscoin[spec2nii2bids,deface]=={{ context.version }}
        version: latest

    - environment:
        PATH: /opt/miniconda-latest/envs/bidscoin/bin:$PATH

    - deploy:
        bins:
          - bidscoin
          - bidscoiner
          - bidseditor
          - bidsmapper
          - bidsparticipants
          - deface
          - dicomsort
          - echocombine
          - medeface
          - physio2tsv
          - plotphysio
          - rawmapper
          - slicereport
          - fixmeta
          - dcm2niix
          - spec2nii
          - bids-validator

    - test:
        name: Basic integration test
        script: |
          bidscoin -t   # NB: Requires a graphical display
          pngappend     # Test FSL tool

# Test image with:
# sudo docker run --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix bidscoin_${toolVersion}:TAG bidscoin -t
# sudo docker run -it -v /root:/root --entrypoint /bin/bash -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix bidscoin_${toolVersion}:TAG
# bidscoin -t

readme: |-
  ----------------------------------
  ## bidscoin/{{ context.version }} ##

    ,-----.  ,--.,------.   ,---.               ,--.
    |  |) /_ |  ||  .-.  \ '   .-'  ,---. ,---. `--',--,--,
    |  .-.  \|  ||  |  \  :`.  `-. | .--'| .-. |,--.|      \
    |  '--' /|  ||  '--'  /.-'    |\ `--.' '-' '|  ||  ||  |
    `------' `--'`-------' `-----'  `---' `---' `--'`--''--'

  Contains a GUI and CLI tools needed for DICOM to BIDS conversion, as well as MRS spectroscopy and physiological data to BIDS conversion
  
  Tools included:
  ```
  bidscoin: https://bidscoin.readthedocs.io/en/{{ context.version }}
    - bidscoin
    - bidscoiner
    - bidseditor
    - bidsmapper
    - bidsparticipants
    - deface
    - dicomsort
    - echocombine
    - medeface
    - physio2tsv
    - plotphysio
    - rawmapper
    - slicereport
    - fixmeta
  dcm2niix: https://github.com/rordenlab/dcm2niix
  spec2nii: https://github.com/wtclarke/spec2nii
  bids-validator: https://github.com/bids-standard/bids-validator

  Example:
  ```
  ml bidscoin/{{ context.version }}

  # Getting started:
  bidscoin -h

  # To convert DICOM to BIDS:
  bidsmapper inputfolder bidsoutputfolder
  bidscoiner inputfolder bidsoutputfolder
  ```

  More documentation can be found here: https://bidscoin.readthedocs.io

  Citation:
  ```
  Zwiers MP, Moia S, Oostenveld R. BIDScoin: A User-Friendly Application to Convert Source Data to Brain Imaging Data Structure. Front Neuroinform. 2022 Jan 13;15:770608. doi: 10.3389/fninf.2021.770608. PMID: 35095452; PMCID: PMC8792932.
  ```

  To run container outside of this environment: ml bidscoin/{{ context.version }}

  ----------------------------------

copyright:
  - license: GPL-3.0-or-later
    url: https://github.com/Donders-Institute/bidscoin/blob/master/LICENSE.txt
