name: datalad
version: 1.3.1

copyright:
  - license: MIT
    url: https://spdx.org/licenses/MIT.html

architectures:
  - x86_64
  - aarch64

categories:
  - data organisation
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAPoAAABuCAMAAAA5xf5aAAABI1BMVEUAAAAzMzP/ogAyMjIyMjL/oACpciL/oAD/ogD/owD/ogAzMzMzMzMzMzP/ogD/owD/ogAzMzMyMjIyMjIzMzM0NDT/ogA0NDQzMzMyMjL/ogD/ogAzMzMzMzP/ogD/ogD/owAzMzMzMzMzMzMyMjIyMjIyMjL/ogAzMzMzMzP/nQD/ogAzMzP/ogD/ogAzMzP/ogD/ogD/ogD/owD/owAzMzMyMjL/ogAzMzMzMzP/ogD/ogAzMzMzMzP/ogD/ogD/ogAzMzP/ogD/ogAzMzP/owD/owD/ogD/ogD/owD/owD/ogAzMzMzMzP/ogD/ogAzMzNFPS5hTCfQhwx4WSP/ogAzMzNBOi/xmgNTRSvmlAZ4WSKPZRywdxPXjApgTCjEgg6bshSYAAAAVXRSTlMA3NwzvxQCMvd3VdX8d+Yc9OVvTEEN7iHMJvqYHPhlRwrvtaRlVS0nFgcGy4txtJqKfhINrYNhQBLzxLw569/U0Vs7ppM3LJGDt6EiqWpZT3/s4uJIFg8W7AAACV9JREFUeNrc2tt20kAUgOGNwdGaIAWSkljQhkMMNct4KAgKVbSeW+0N+/0fRZqmNMyetJkJrV35b7yRLr6ZNDsMhcV6ryGuh+jWSnYn6E0tKGYp8hEmsgOTwYYrlxJ5cMtR+tblnnPVTn3YaCVMpMH/KEVOa4decemcnNYdF5RO5DS3zopI/wlxjoHpdawC0hevIK5/lV13Cki/tM+vsrtmAekZ993VCkjPaJ85BaRnvOZL4wLSM+57t4j0xX2Is3xn2gtrYnu/0PS4aUdEn/mQEtN6wXGnfHx02vc3RvdGQffsZw7nrRul82k20o7E7kbXxcvs3gAAGpiozNFJdeAzw1nyZ9YtANAwUenG6DAYIqndEvy/E+Kp9Vg+OpvrZLhWBjdGp42MDNtu6iJK2ZekkyuOZjdvjw51uu1jbsuPUFwtUKazoYHC3OHt0SFEvhEka9mYmip9XMbUbpFukSnXgURODTdOb+l4J+gwQi5jTOQbpfs63hE6K6U/1vhEnp9u6XhX6PRON4Q4VsbN07t4d+it1F/2Cm6ePsc7RAebn1oXazJBLr3S8LxGxc5MbzRXWSl31dKwoTnmSXkD9GfSdDK4LfHcK5kQN9Uz0jXgGvLL3Ic4z85JZ7uLX/uS9B5yNc83vY1rdQewatBVo1su9yoLVrEgF33/YIn88FaObiKXJ9qgkEEi1pWn01XuDCBZkIP+5n2kfHFfiq7xdBPO0tdpDNYa6Cr08jrNgvU6yvTqx5h5+FyG3uTpDVjmYTK3RRbMkKeP117T9sg7mSjSvz1eOXc+S9Ad4a6fYLIKkLry9MZ1RwOBIn3nTLj9ejv6J88FrxHZZCx4mRSdyowmkFqGGv1htN3x5ue5zTlk2ndBkC5N73CvoJVV6dEvOfy+J0WnT7I+LJtxH2RpoQydLtYpCDpVpX+qwv7WXnSjl6CHnHzCAGBArgPSSJru0jnCZSrSlwP9zYez0bb3Uoauc3Qblvnk+Y5kStONa5fTUaPv7kP10xJ57zmw3RwfX0Iy8dogSpOikytpDIJ8Qpcbb48fyDzSVHh6j9BdEOXkow9AkKVIf7cTM7ef5TmqcOgFz3LvOr3gWyCopUZ/9HDlfPJU/YBKp8svvjgb0vQJ90mB5qnRI/nh33uRVP1YspL1blzPN9z6IKivTv9YXY42GXoX+ZysM/g43yNNCIICRXr8eXXvZXZ6hcjLIpgNNFaTolMYA5quSj/Yh+qXKrDdrPQTJJnCZ7wpkOYoTe9f94W2iYr07wyeH0aj7XUmuhVeccY25Y4qSbYcnT5C2HTbO4r0pwBfd+LRluUO39CRNhVfz3hCb3KSdLpcQ+Dqq5/S/H14Ptr+ZHikcWwUdJR2WtmeclOorUKvkDORZE1Xmf70yYVzi9J/bMXdX20bTbfoiI2brL1PbYYqdH99wYwe+X5Pjf5j7a+GFqTE6VVUv83LDS39IA2NwII4Vp+gCp3O0nAMF42i1VSf66tgkdrOOzjPdMnTe7IpctWGEaVV1xEV6Q6/3G4wZQDg92zEG6bHj7nnOSVMViFbRDJqOtlwGToEEj8zJ13cd0a/8KU33HENReWiD3QUdWN02sHe+Ru5fKNGBUimsXE6eO3bpdNecXf5mQmC5punQ8P4v/Ttf9WabY/SQBCAx2pLr8YWo1ZDkRKNoiDIW0RBgYMAAsrFlxHUO/X//wpzcAe7zLTVGuL2+ci1G57bZXZ2dpx1Ovdm+82zUXWM+Oq0beu/queka7Wbx0Ag3zOuOuVW1Jpffj+ceslYB7lXFx1bdyCYW28Ce8jjqsPVK6FjLn/g2aHUzfEuVb1yQxKnZB984bh/g6/SfBA//Qw8L9/x5s/Oc4mv3xDx1/Iw6rVNynz/y83ntyGaR8wkXXsMvPqn5e7D0xRQgs9O926f1/t+rvCcH8tDqPeKG6P3j+HPMI73ktoHrwNrc9q3r5e/2DMU1Kn8g7272tvrUuf3FW749jWu+lEQZUuHv+fu+3fX19Hp1fXnx082ueANgeOtOq5+bsx/oaROyb54eDHmlYcvspsocIpbVh9jqh8A4+Xd7FOIQENcfd/Eqih1qJ9UmyWt2+sMa63NShyhgMa/ZFUrJU3rtWflkcGq/y/WBeHTdawKV8/nOijgegUASEWoG9YUBeyqo5o6nq0wXL1Rc3EfT49St3rkKObVFVNHDFdf2MhgD0LV9Sb7kp8k9cYQeTKzEPWBjTzl5KjPNYyEqlsZDOIoKeopG2OoLzIYQjLUCzbGUG+ZmHh13cYY6gUXE69udDCGulHC5KuXMY56DZOv7qRxj2mu0Cg6vpdm1IPfapfHdcNpTezkqHsoU9o+oQ+D1Sf7f/C32fAkKeq6iRKeATtyQeqNvUmf5mGHbyZDvbxnHh4HNP5/UimCiJ9JhLocqNsGyAx5dXlT6DZAppYEdQdFXIccxW1OvSFP64jsl+0EqC/ka28gHHHqLRRpAsFPgLoUjk0dCLrJqB/tTTqlr776VIpWwFBh1L3IotWR+uo9FChHSmhMlPOAYaC+urQ/D4Chxaj35RszhqL66igyB4aCrE5H9IHDVV1dnpw6MOiMuk2iHEFLlnoeGBqMehcFxsDRV10dpNzEAQZHVqfBsQUctvLqbnTdjlGXkjULODLKq/ciY/WCUR/KKSBDQf0ILyUsMyDw6ctbFCgBQ0599SoK2EUgGBqjfoJRIaKivvoJ7echD1B1HSPSuYKKx5cBbKESXbq9tYk62bpMmgoNFVEvkXgcqDaMKNdqbC2inwcZS5VSRYWuTurGn2BGJlHnFvTMAJGxq4r6jHQmruELjBMQaKWDKrJTlKg0YMfIVaYs+RZFSpI7LSt3tolp/m0Gg9RbKNO1dm+Z6hSjfZRwqwvLOvF9H9bo+zObqeTmedAHVTvs9qWCe/RqrXl97HtKXUHk08hi/MvFU8FMwsUTDAPV4183QjkR6qNQdXDcOOrQTII6NEPVIZWOo54vJUGdn1dD2MRiqIPew0A6ahxayS0YUYeRG0Md9D4GUGqo0UZEWn6oOjiBq7cfrA6NZoB5XZHmsTWpbqg6FNf5CyGdC20ZNMomUmZ5VVoGN+gVqi5RYKawOY9qFC2QYW1LnR7ZS1pToi4znrjSjHtzWpujDIYZ8YlyXqH24B1ObtbW0jt1QnFQa/Zd07T709qgeNHxLeAHNIV7bTuNrtaspS4HtUR+AyarKNGUrQroAAAAAElFTkSuQmCC

build:
  kind: neurodocker
  base-image: neurodebian:bookworm-non-free
  pkg-manager: apt
  directives:
  - install:
    - datalad 
  - run:
    - git config --global user.email "user@neurodesk.github.io"
    - git config --global user.name "Neurodesk User"

deploy:
  bins: 
    - datalad

readme: |
  ## datalad/{{context.version}} ##
  DataLad is a data management and distribution platform providing access to a wide range of data resources. Git for data using git-annex as backend.

  Examples:
  ```
  datalad install https://github.com/psychoinformatics-de/studyforrest-data-phase2.git
  datalad create -h
  datalad --help
  ```

  More documentation can be found here: http://docs.datalad.org/en/latest/

  You may also want to read the guide: http://handbook.datalad.org/en/latest/

  To run container outside of this environment: ml datalad/{{context.version}}
