name: neurocommand
version: "1.0.0"

copyright:
  - license: Apache-2.0
    url: https://github.com/NeuroDesk/neurocontainers/blob/main/LICENSE

architectures:
  - x86_64

categories:
  - workflows
  - programming

variables:
  apptainer_deb_url:
    try:
      - value: "https://github.com/apptainer/apptainer/releases/download/v1.4.4/apptainer_1.4.4_amd64.deb"
        condition: arch == "x86_64"

build:
  kind: neurodocker
  base-image: ubuntu:24.04
  pkg-manager: apt

  directives:
    - environment:
        DEBIAN_FRONTEND: noninteractive

    # Install system packages: CVMFS deps, lmod, apptainer deps
    - install:
        - ca-certificates
        - curl
        - wget
        - lsb-release
        - fuse3
        - libfuse2
        - libglib2.0-0
        - libseccomp2
        - squashfs-tools
        - uidmap
        - lmod
        - lua-bit32
        - lua-filesystem
        - lua-json
        - lua-lpeg
        - lua-posix
        - lua-term
        - lua5.2
        - git
        - git-annex
        - tree
        - sudo

    # Install CVMFS from official repository
    - run:
        - wget https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
        - dpkg -i cvmfs-release-latest_all.deb
        - rm cvmfs-release-latest_all.deb
        - apt-get update
        - apt-get install -y cvmfs cvmfs-config-default
        - rm -rf /var/lib/apt/lists/*

    # Install Apptainer from deb package
    - file:
        name: apptainer.deb
        url: "{{ context.apptainer_deb_url }}"

    - run:
        - apt-get update
        - apt-get install -y {{ get_file("apptainer.deb") }}
        - rm -rf /var/lib/apt/lists/*

    # Install Python environment with miniconda
    - template:
        name: miniconda
        version: latest
        install_path: /opt/miniconda
        conda_install: python=3.12 datalad
        pip_install: pandas nilearn matplotlib nipype osfclient

    # Configure CVMFS - create directory structure
    - run:
        - mkdir -p /etc/cvmfs/keys/ardc.edu.au
        - mkdir -p /etc/cvmfs/config.d
        - mkdir -p /cvmfs/neurodesk.ardc.edu.au

    # Copy CVMFS configuration files
    - copy: neurodesk.ardc.edu.au.pub /etc/cvmfs/keys/ardc.edu.au/neurodesk.ardc.edu.au.pub
    - copy: neurodesk.ardc.edu.au.conf /etc/cvmfs/config.d/neurodesk.ardc.edu.au.conf
    - copy: default.local /etc/cvmfs/default.local

    # Copy lmod module initialization script
    - copy: module.sh /usr/share/module.sh

    # Copy CVMFS mount helper script
    - copy: cvmfs_mount.sh /usr/local/bin/cvmfs_mount.sh

    # Copy custom entrypoint script
    - copy: entrypoint.sh /neurodocker/startup.sh

    - run:
        - chmod +x /usr/local/bin/cvmfs_mount.sh
        - chmod +x /neurodocker/startup.sh

    # Set environment variables for lmod and CVMFS
    - environment:
        MODULEPATH: /cvmfs/neurodesk.ardc.edu.au/neurodesk-modules
        CVMFS_REPO: neurodesk.ardc.edu.au
        LMOD_CMD: /usr/share/lmod/lmod/libexec/lmod
        BASH_ENV: /usr/share/module.sh

    # Verify installations at build time
    - run:
        - apptainer --version
        - cvmfs_config --version || true
        - python --version

    # Create neuro user and grant passwordless sudo
    - run:
        - useradd --no-user-group --create-home --shell /bin/bash neuro || true
        - echo "neuro ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/neuro
        - chmod 0440 /etc/sudoers.d/neuro

    # Start as root to allow CVMFS mounting
    - user: root

deploy:
  bins:
    - apptainer
    - singularity
    - cvmfs_config
    - datalad
    - python
    - pip
  path:
    - /opt/miniconda/bin

# Apptainer runtime arguments for CVMFS FUSE support
apptainer_args:
  - --fuse

readme: |-
  ----------------------------------
  ## neurocommand/{{ context.version }} ##

  Neurocommand is a complete neuroimaging environment that provides access to the
  NeuroDesk software ecosystem via CVMFS.

  CVMFS is automatically mounted and the module system is initialized at startup.

  ```bash
  # Run with FUSE support (required for CVMFS)
  apptainer run --fuse neurocommand.sif

  # List available modules
  module avail

  # Load a module
  module load fsl/6.0.7.6
  ```

  **Included Tools:**
  - Apptainer/Singularity container runtime
  - lmod module system
  - DataLad for data management
  - Python with: pandas, nilearn, matplotlib, nipype, osfclient

  More documentation: https://www.neurodesk.org/

  To run container outside of this environment: ml neurocommand/{{ context.version }}

  ----------------------------------

files:
  - name: neurodesk.ardc.edu.au.pub
    contents: |-
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwUPEmxDp217SAtZxaBep
      Bi2TQcLoh5AJ//HSIz68ypjOGFjwExGlHb95Frhu1SpcH5OASbV+jJ60oEBLi3sD
      qA6rGYt9kVi90lWvEjQnhBkPb0uWcp1gNqQAUocybCzHvoiG3fUzAe259CrK09qR
      pX8sZhgK3eHlfx4ycyMiIQeg66AHlgVCJ2fKa6fl1vnh6adJEPULmn6vZnevvUke
      I6U1VcYTKm5dPMrOlY/fGimKlyWvivzVv1laa5TAR2Dt4CfdQncOz+rkXmWjLjkD
      87WMiTgtKybsmMLb2yCGSgLSArlSWhbMA0MaZSzAwE9PJKCCMvTANo5644zc8jBe
      NQIDAQAB
      -----END PUBLIC KEY-----

  - name: neurodesk.ardc.edu.au.conf
    contents: |-
      CVMFS_USE_GEOAPI=yes
      CVMFS_SERVER_URL="http://s1osggoc-cvmfs.openhtc.io:8080/cvmfs/@fqrn@;http://s1fnal-cvmfs.openhtc.io:8080/cvmfs/@fqrn@;http://s1sampa-cvmfs.openhtc.io:8080/cvmfs/@fqrn@;http://s1nikhef-cvmfs.openhtc.io/cvmfs/@fqrn@;http://s1bnl-cvmfs.openhtc.io/cvmfs/@fqrn@"
      CVMFS_KEYS_DIR="/etc/cvmfs/keys/ardc.edu.au/"

  - name: default.local
    contents: |-
      CVMFS_HTTP_PROXY=DIRECT
      CVMFS_QUOTA_LIMIT=5000

  - name: module.sh
    contents: |-
      # Initialize lmod for all sh-derivative shells
      trap "" 1 2 3

      case "$0" in
          -bash|bash|*/bash) . /usr/share/lmod/lmod/init/bash ;;
             -ksh|ksh|*/ksh) . /usr/share/lmod/lmod/init/ksh ;;
             -zsh|zsh|*/zsh) . /usr/share/lmod/lmod/init/zsh ;;
                -sh|sh|*/sh) . /usr/share/lmod/lmod/init/sh ;;
                          *) . /usr/share/lmod/lmod/init/sh ;;
      esac

      trap - 1 2 3

      # Set MODULEPATH for NeuroDesk if CVMFS is mounted
      if [ -d /cvmfs/neurodesk.ardc.edu.au/neurodesk-modules ]; then
          export MODULEPATH=/cvmfs/neurodesk.ardc.edu.au/neurodesk-modules:$MODULEPATH
      fi

  - name: cvmfs_mount.sh
    contents: |-
      #!/bin/bash
      # CVMFS mount helper script for neurocommand
      set -e

      CVMFS_REPO="neurodesk.ardc.edu.au"
      CVMFS_MOUNT="/cvmfs/${CVMFS_REPO}"

      # Check if already mounted
      if mountpoint -q "${CVMFS_MOUNT}" 2>/dev/null; then
          return 0 2>/dev/null || exit 0
      fi

      # Run CVMFS setup
      cvmfs_config setup 2>/dev/null || true

      # Mount using cvmfs2 with FUSE
      if command -v cvmfs2 &> /dev/null; then
          cvmfs2 -o rw,fsname=cvmfs2,allow_other,grab_mountpoint "${CVMFS_REPO}" "${CVMFS_MOUNT}" 2>/dev/null || \
          cvmfs2 -o rw,fsname=cvmfs2 "${CVMFS_REPO}" "${CVMFS_MOUNT}" 2>/dev/null || true
      fi

  - name: entrypoint.sh
    contents: |-
      #!/bin/bash
      set -e

      # Mount CVMFS as root if not already mounted
      source /usr/local/bin/cvmfs_mount.sh 2>/dev/null || true

      # Switch to neuro user and execute command or start shell
      if [ -n "$1" ]; then
          exec su - neuro -c "source /usr/share/module.sh; export MODULEPATH=/cvmfs/neurodesk.ardc.edu.au/neurodesk-modules:\$MODULEPATH; $*"
      else
          exec su - neuro -c "source /usr/share/module.sh; export MODULEPATH=/cvmfs/neurodesk.ardc.edu.au/neurodesk-modules:\$MODULEPATH; exec /bin/bash"
      fi

tests:
  - name: check_apptainer
    script: apptainer --version

  - name: check_python_packages
    script: |
      python -c "import pandas; print('pandas:', pandas.__version__)"
      python -c "import nilearn; print('nilearn:', nilearn.__version__)"
      python -c "import matplotlib; print('matplotlib:', matplotlib.__version__)"
      python -c "import nipype; print('nipype:', nipype.__version__)"
