name: pydeface
version: 2.0.2

copyright:
  - license: MIT
    url: https://github.com/poldracklab/pydeface/blob/master/LICENSE.txt

architectures:
  - x86_64

variables:
  conda_version: 4.7.12.1
  conda_dir: /opt/miniconda-{{ context.conda_version }}
  conda_download_url: https://repo.anaconda.com/miniconda/Miniconda3-{{ context.conda_version }}-Linux-x86_64.sh

build:
  kind: neurodocker

  base-image: vnmd/fsl_6.0.3:20200905
  pkg-manager: apt

  directives:
    - environment:
        CONDA_DIR: "{{ context.conda_dir }}"
        PATH: "{{ context.conda_dir }}/bin:$PATH"

    - run:
        - bash {{ get_file("miniconda_sh") }} -b -p {{ context.conda_dir }}
        - conda init bash
        - python -m pip install --no-cache-dir --upgrade "pip<24.1" setuptools wheel
        - python -m pip install --no-cache-dir "numpy==1.21.6" "nibabel==4.0.1" "nipype==1.5.1" osfclient "pydeface=={{ context.version }}"
        - rm -rf /root/.cache/pip

deploy:
  bins:
    - pydeface

readme: |
  ----------------------------------
  ## pydeface/{{ context.version }} ##
  pydeface is defacing utility for MRI images


  Example:
  ```
  pydeface infile.nii.gz
  #or
  pydeface infile.nii.gz outfile.nii.gz
  ```

  More documentation can be found here: https://github.com/poldracklab/pydeface/

  Citation:
  ```
  https://github.com/poldracklab/pydeface/
  ```

  License:
  PyDeface is licensed under MIT license.

  To run container outside of this environment: ml pydeface/{{ context.version }}

  ----------------------------------

categories:
  - "image segmentation"
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAATNElEQVR4nOVbe3Bc1Xn/nXPu3n1KK9nWw29bxi/J2GBsDH4gJCzLPP5I28iEMoSSNoVS0mk7CQxDQVYbmjZTl5AMZTK0EzKlk8QqbULADja2ZQzG2DLGxsgG47eNH1iP1a60j/s4ne/cXWklr/auX9CZfB6Nd+/ee875vvP7nue7wO85sa9qXpnrIiC/9IXgGpMEWGtTEy87f57dXl4uUV0tWUuLnfPe5mbe2tHB6N4vystlU2urfa2Fwq4V02hq4mqC1lbrot+bm/mJ9vZwVyymmBOhEIsFOhOLW3fEc93b1tbGb9+61boWwmDXgvFsptvvuScgUv1zOOO3MiZvgMSklLQrNfCxpnT4EQywIaMa45+Z0o5wsN02t3d4bX3PnA0bugbGb2oSqG6VrAU5EfRVCoDJLMY/XbnSm5JmowX5NUDeAcYnBYWALSUxCmLctOXA5CQGzhh0zkD/BGNI2jZSttUpGH+H2/iNbdrr5m7efG5AEFdJPdiVDrC2qUmsSjO+r76+gnnYX4DhXg/ns4iphEWM2JIBDiqkJAPIwNiQuRUzUipMMMboE9c4534hlHD6Tesck/K3tuTP37Bx4341VFOTyKViX5oAttTWanVbt5prm6r1mb1jH2cM3wkIrTxuWUhYls0ZI6iSLeC5Z8+aPq0O2SQdoSi4a5yLoKah3zRTAP6rz5BPL968+TTZCLS0yMtFA7uch9QONjczsubtjbc36kys8QtR029aMKQ0IdWmXcw0Y2CcO5xZJqSdVmW6WdPU/+raCMJIo0gr9niQtMzzto3vz92w6SfDkXhNBdAM8BayWQD2NNSt9gitmTYybllm2p7lHJNxAds0YMf71bRaURF4IOAwZxgweroBywL3+sC9XtKGnIJIY8XSGNNCmoa4Ya49a/U+2rBpV+flqAS7lJsJbrTr2+5eWhq2vL8ICK0xYhg2LZYxlhvmtOO2DauvD1ppKUqX3obwrYvhnzwFntGj1BKseD8Sx48humcPujZtROL0aXBdV38DKBm+FgfyVtijaUlLHuo3kvffvOntXRm1vOoCkFnMF5u+N0OaWNidMgzG4BlxcLL8iQQgBMq/9geouPc+6GPK8s5j9fejc8PvcObnP4PR1QkRDEFaI2+qBMyAEJpty+5+M9V4qUJglwL7DPN+wRf2GsQ8y8s87bpeVo6qln9AqGaOs2C1o4SYoYDJQJ6eIzI6O3Hk75sRad8JT7gkrxBsKS2fEIJJDAihUHVgBRk8SOy8Y/kon5Dr/Zq2sNc0TQZo+Zg3e3tRNG8epn3/B/CUjlIMKAM41PvlmFAqISlB2DaOP/+vOLf2V+kxRt5UW0rbJwQnIfTK5MrFG7btzKA233TcTQAqsgOTGpe/DOkeZ+fdmI/FEJw1G9P/ec0g88SQG/NqADbAPH2e/DffRfkffh1GdycYeYqRGGGMJy2yoigNMv2379XXV5B7JPTmm47n+5F0iWC0q6FudYnuWd6dTOWFPS3YNgx4wmFM/btmivEHmb9UIrQQ2TYm/dVfo/jGm2DFYg6KRpyeiYRlmz4hynUh/5OurW5qyit1PtIP5FfJkHzQWLs8oGnPRFIpKy/zzgJg9/djyhNPwj9lyuUzPzigEyZ7vahqboEIBWGbZl4kETqjpmmW6HrDrhX1z9AGqtD5UgQgAdZUXS33N1Xr0uYv0LgEyLxrJehHoxhz9z0oWXrblTOfGZdzNZZeUYkJjzymBJwPBWkS5J79jD+1s7FuphICRYw5iI+o9y0tdjxS+b1iXZ9BQc6Ifj5NtEgRDGDcg99yQpVC9L1AUgzbNsbcdTeCs2YpV5lXFWjDpJQewT3cYj/ONzbPafVbW+32e2rHaBJ/22eahEJRyO6PXrES3vHjHSvuvkuXpgppF1lx3/2QRspVwGQP+gzDCnrEivYV9XW0oaTWw+/jwy+01dZSOCuREn9ZpHtGmVJSIYK57b4WCqFi1TcGFjzk99wh7SWRUicpMaq2DoEZs2DF48MTyovXlbZLkPJp+k5q7SYARpWX7U23+CHlN+OWRQlI3q2knabFBKtr4JswUUE1e/dt+p7ewSslhSyPByVLljoRpgvKCAUx05Q6F8v2NNbVEArkMH74kAmUz4f09/rqQx5PVcKylBF2mQXSNFCydNkAVIdMwDmi0Zjrbl3EbC6BpceguYTfN2KeMIysgCY0y8ZD6ltt7cgCyJAtWRNnTKbzebjCv6gY4VsWD1kk7Twx8eqvX8f8xfVoefaHSKUMdd2NRkKNk0pLBK6bDv/UKtjJpLstAHhChdHsnnUrV3qxdauVUwCShmpttd5saAhKiYaEZVHlJr8fI7+fSiroeysrnVie3Bb9D6C3J4InnloN0zSx5vkXsXvPhwoRlpVfCHlRQ8LRNARn1ygBFGBsSQDSK/j0CjN+vbIIWS6RD9zW3KxmGyNTs71cVKQc/c/v+zmHnUwhWF3thKnp3aWF02/h0hJ886EH0NnZhRX1t2HGtCq1u5wULQcVgpoMJkLzbijc0zJGyRLnXCxV39vaBvjWBm5yLtqSscU+TYikYVPmobmPDQRmzBxYHKPFcq5SWjsex5P3/RGW1y7F/IU3wZd1T7qGMABh+k4739sbxRNPt8AyLYWaFcvrcOuihQo1QgwmU/6qKohAoDA7QHVIqqJILAPwI9D5xEUCKHcuSskWZiDsPq7jm30TJw1Kg8i2cf6/W1Uqq5dXYPKCBYh88jHMG25EqLpGCWhg/LQwlDqRfgf8eOAbTVjz4xfR2FCHmdOvg22TcJwnMmrhraiEKCpWWadCXx4vwxhjKZtUX85RHm7t2oSki4AcFEDaRzKG8UqmUlLl1k0CYFS5SZe21CKEgNHVhdQX5+EdO04ZyVNtbcBbb0ELBOCbMlVliiXLliFUcz204uJBYUhJxU80P/U4ltffjhvm1iAYDA6iJXteIRQCjJ4e180i8VIpngEVfd2GzhiLO2k+HASoL6tXy+0db/rRgwq6OS0hF/dnQispdfx/FkX37UX86BGIcBhC90IPhx3jaJrqev8nB3DhjdfgGV2GUE0NwkuWIjS7Gr7JUwZQtOTWm53FZ+oIWfMSarjfD++EiYgfPw6WqSHmIQqNNc71UVZwHIDIarJ5LS2DCKBa/PYVt/gZ2ETD0avCTAxNnGX8iIIzZmDqU88g9tE+RD/coxBB93GfD8LnA6M02bZh9kbQtWUzujZvUqlzcHY1iubfhOL5C+CfORPC48mfUBUWB2RyAzugaX5LygkADtR0dAwiIEOWR5NIgQoel0cZ/Rw3HhVN96q/1BdfoP9gB3p27ED0g91InTsLKxIB93iUQDwlpVT8V5Xh6J7diLy/A8LvH1SVpcsQun6uqiJfKZGNYYwZ2de0i3i4nJGHwy9T1qLjrrIy6GW1KFlWq8LX/sOfoeedbYjt26s+pzovgGkCwueHCBUpGzBEVda9rgqjFavuxbgHHxq665cRXmv5vgvDZBK6q+sbQmTRh5eqMmWt9CKdwx2mdpyKo5kCKZXCI7t2IbbvwxFVhcZKnj2rrjnDDRpEN+s/nOgpYxjPWuYDGcJ3fdxAXPZwxovpdM4NEKryG4sqi++bNDl3HYCEwQaF4Qgk7T4nT1F/FV9vyqkqdiSivIxWFELxgoUD4ymXmUyqZyg5KkgIjDFLSkPjrCc7M9TSklHh4dKWlmh7Q90RnfNJBiVC+fwATUqRYF8MRne3EoC7xJzFD7o9G5JOiUdSlXe3oXd3O2QyCd94sl3p8dMeiM4NSJBu7JPYNcZY0rL6ewP2Z+piS8ugABSlrSKAHvrgyswADxLGhQuDQrkUYhwZcORTFbO7W9UFnWecVZk93bATcdeUOEN0WGmBRT3SyJ0M4fz5TEy6i87nwXK28QxdP+2EZaHvk4MD1yhup7A1E9cXTCp/EAMZn4oQ04chdKSWHTITxY8dKygKVENLaXvJuDJ0LH1te1SdF6TTCi1zU2s6FGYa3k9S7CklLyQSpPO7vgMfO1la5vR3yC1ShbLKGWcSJbdxL1KVLNuSZpZiDKU+WQnSiMt0UnsSxI7svAfZAqCGJPo/aSf2MMl7NM5LTUnx8MiaoIyZrqvdIDugjR6N1v9dD69Xx/RpUzBpwliEggEIKrJdJJS0wDIWPZ9Qsn7LICT28X4VSxSkdlJyCu4EsDV7s4kGI8G0IWQtLd3tDfXvBYS4s88waJUiLwI8HqQ6OxH/aC+MRUvwwkuvINoXRyDgw7jKckydPAHXTZ2MqqkTMXniOIyrLEPA74cYFuE5oHPs7kgoybjAxKlT6D/0qbIVbtkgGUAP5zxhWmdsKXZnbzbREJ9I3VhkXwTQKhi7K9PekZfSi+pq24Ixi5bguWefxNGTp/HJ4WPoOHgYu/d2YMu2nbClrdBQNmYUZl03FbNmVKFqykRMHF+J8jGjoet05jKUaceOZDTCyQEo2Yrs2A4zEoGntDTvoSkRNVUENE2LpIy3Frz1VmT4oamWfTMVRBVPIvVGzGAXPJyPLkQNKCvr/mA3JhkJzL9xjvojSqZS+OJCF06dPovPjp7EocPHcOT4Kbz9XjvWb9oGzjiKi0MYW1GGKZPGY87s6Zg1fSrGj63AqFElqj4wZK40Knreebtg/0+9RimLjJB8mb63XiygoZSRUPvyun8Pe/U/7TUM18II+WJKSyc++hgq7n9AHV9xam7K4aJIKCdOncHJU2dw+OhJfHb0OI6dOI1z5zsR6+uHx6OhtKQY48dVoorUp2oSZs+YhknjK1FcXIT+j/ai4zuPgvsDrskQ+RK/ECxumgejKXvu7W1tdLwn8wsACvVy94ramTrTPjSl9KRzZ+aaGofDqHn5FXVGkB7L+V/5eAfGucph/fEEPj9zHh2fHsbRYydx+NhJJaQLnd2IJxLw+7woKw1j7HXTUH/6E8w8cgApr4+sel4BUN9Aia6LaMr8k/kbN/08V88Ayym5QRS8HPbqD0YMI28/wCAKujHh4UdV0jLS2aAjDMr/0tLmuQ1eb7QPpz8/q4Sxd/9BHD91BsdPn8UjPUcxg5uIy1xdWEPmoX4BlrTsT88Jfd6dixYZzIn+8iOAiM7UVwNy5121FV5T62AMYUMqDXRvqLAtVP/0P+CvmlbwEVkGIRkvkEt1zHgc7Q9/G9rnpyA0zTXIklJaIY9HxAyjccHGLRtG6iLjuR5WXWBNTXzRuq1nU9J6OqRpdJ97uwlFW4aJoz941jnLd1bi9tiAalDRM8N8JlYwUymVx5/+t59AP3JIFUlcmQfoeFzEDLOVmJd5Wuj4iItqbbWoQeLmjW0vdKdSr4Y9Hs0G8jYe0Y6LYBCx/ftw/Ll/UXH6SH1/bqRiAduGpuu48Ov/wdm1vwKKw65+nyo/Xs5FzDSOpJj2iDoDyPL7w4nnG4zcInlBXTe+3W+aR4NCaAStfM+QMfSUjkbn79bhxHNrBlpj3Pz1UC4oS3QOQC6sfwMnfrQGnlGjVB9h3secrE99Nm37jxenG63zdZHyfAOqB1evZnPfeKc7YZmrqBXNK4QgKed7jpqZtOIwzr26Foee+C6saHSg70cJIhci0lUktcNUZOEcp158Acf+6R/BfX5XFKmUl9yepvF+03p4wca295Uxd2mSYnlHHeYVdt5x28KApr8pGUqpIYlOX137BiIRZRDHf+vPUFpXP/SGDJyHGb2+gwdw+qWfIrLjPYhMLTCPAOxB5gn6f75gw5aXCu0VZCiQMgNmhEDdWNSQVIh7pE5QYiB0/TyMufMuFN+0EJ4xY4a4SbOnB7EDHehc9zoiu3YqI0pnBm6qQypJHWIBTWMZ5iU1d13NRslcQvB79N/onI+lhqR8PcLZO2z39SmIU8DkHTdOtdARUX9B8uQJlVE6rTZBp9Ljxjxg+jinYo8Zt8xHL5X5yyoCZ/zp1sZlY0uY/rOg0Bp7DUNFXa4qoQRBBtGEnUoNMEjXKbZXfwUYTApySCFKdJ0nTPNQwrYeWrix7d1L7RO+7Cp4dlBBHeOC8yd1wfWYYao+2HRDFSu04JE+lHQ3dI7xlXR4K8Bg2PYvz5l4rGHTpsvqFCe67DOQTLRInmJnQ+0cH9d+qHF+J4X6faZaByWS3K27zI0y7wnYUgq/pjFdvYVi7ZdcPj5v/eb1V/KuANEV97JlS37fivoGxvj3bMj6oKYJ6sxIpF+XcbLqwVdlctmMNLP0uozMvDaj02szmqbeIZK23Gcx+fynRWdeWdXakbrSt0WIrkozn2wGR4uzePq+b2X9XEj2gA3cJRir9qVfmKKyFB28qpenhsUSdBYrCC7q5SkOCmhS9OKUZZ8SHBsFE7/YHwpvzuz0lez6kHlxFYkWlf2yI6Fjf7Rrvm2zJYBcJpmcLSUqLSmLKVEhQahFMCBpqSpyty0RYwwHpJTvCU172+vp2zX7te3RYYhzeu7/37442ey87DjcItPie1KpoiN93WMDuq+yT3lQgF6GiiatWFkodKjTslILXn+9f/hzVMlZdRUZ/1JenZVZr83Sq7CFQpaQ9GW9PsvwJVKmK0M1ZHV0sOH1uUy19qt4iRq/r/R/w9UeCbuda2QAAAAASUVORK5CYII=

files:
  - name: miniconda_sh
    url: "{{ context.conda_download_url }}"
