name: pydeface
version: 2.0.2

copyright:
  - license: MIT
    url: https://github.com/poldracklab/pydeface/blob/master/LICENSE.txt

architectures:
  - x86_64

variables:
  conda_version: 4.7.12.1
  conda_dir: /opt/miniconda-{{ context.conda_version }}
  conda_download_url: https://repo.anaconda.com/miniconda/Miniconda3-{{ context.conda_version }}-Linux-x86_64.sh

build:
  kind: neurodocker

  base-image: vnmd/fsl_6.0.3:20200905
  pkg-manager: apt

  directives:
    - environment:
        CONDA_DIR: "{{ context.conda_dir }}"
        PATH: "{{ context.conda_dir }}/bin:$PATH"

    - run:
        - bash {{ get_file("miniconda_sh") }} -b -p {{ context.conda_dir }}
        - conda init bash
        - python -m pip install --no-cache-dir --upgrade "pip<24.1" setuptools wheel
        - python -m pip install --no-cache-dir "numpy==1.21.6" "nibabel==4.0.1" "nipype==1.5.1" osfclient "pydeface=={{ context.version }}"
        - rm -rf /root/.cache/pip

deploy:
  bins:
    - pydeface

readme: |
  ----------------------------------
  ## pydeface/{{ context.version }} ##
  pydeface is defacing utility for MRI images


  Example:
  ```
  pydeface infile.nii.gz
  ```

  More documentation can be found here: https://github.com/poldracklab/pydeface/

  Citation:
  ```
  https://github.com/poldracklab/pydeface/
  ```

  License:
  PyDeface is licensed under MIT license.

  To run container outside of this environment: ml pydeface/{{ context.version }}

  ----------------------------------

categories:
  - "image segmentation"

files:
  - name: miniconda_sh
    url: "{{ context.conda_download_url }}"
