name: pydeface
version: 2.0.2

copyright:
  - license: MIT
    url: https://github.com/poldracklab/pydeface/blob/master/LICENSE.txt

architectures:
  - x86_64
  - aarch64

build:
  kind: neurodocker

  base-image: ubuntu:24.04
  pkg-manager: apt

  directives:
    - environment:
        DEBIAN_FRONTEND: noninteractive

    - install:
        - ca-certificates
        - build-essential
        - python3
        - python3-dev
        - python3-pip
        - python3-venv

    - run:
        - python3 -m venv /opt/pydeface
        - /opt/pydeface/bin/pip install --upgrade pip "setuptools<81" wheel
        - /opt/pydeface/bin/pip install pydeface=={{ context.version }}

    - environment:
        PATH: /opt/pydeface/bin:$PATH

deploy:
  path:
    - /opt/pydeface/bin
  bins:
    - pydeface
    - python

readme: |
  ----------------------------------
  ## pydeface/{{ context.version }} ##
  pydeface is defacing utility for MRI images


  Example:
  ```
  pydeface infile.nii.gz
  ```

  More documentation can be found here: https://github.com/poldracklab/pydeface/

  Citation:
  ```
  https://github.com/poldracklab/pydeface/
  ```

  License:
  PyDeface is licensed under MIT license.

  To run container outside of this environment: ml pydeface/{{ context.version }}

  ----------------------------------

categories:
  - "image segmentation"
