name: clearswi
version: 1.0.0

architectures:
  - x86_64
  - aarch64

variables:
  julia_archive:
    try:
      - value: julia_1_9_3_linux_x86_64_tar_gz
        condition: arch == "x86_64"
      - value: julia_1_9_3_linux_aarch64_tar_gz
        condition: arch == "aarch64"
  julia_tarball:
    try:
      - value: julia-1.9.3-linux-x86_64.tar.gz
        condition: arch == "x86_64"
      - value: julia-1.9.3-linux-aarch64.tar.gz
        condition: arch == "aarch64"

build:
  kind: neurodocker
  base-image: ubuntu:20.04
  pkg-manager: apt

  directives:
    - install:
        - git
        - wget
        - ca-certificates
        - vim

    - workdir: /opt

    - run:
        - cp {{ get_file(context.julia_archive) }} {{ context.julia_tarball }}
        - tar zxvf {{ context.julia_tarball }}
        - rm -rf {{ context.julia_tarball }}

    - environment:
        PATH: $PATH:/opt/julia-1.9.3/bin

    - copy:
        - install_packages.jl
        - /opt/install_packages.jl

    - environment:
        JULIA_DEPOT_PATH: /opt/julia_depot

    - run:
        - julia /opt/install_packages.jl
        - chmod a+rwx /opt/julia_depot/packages/CLEARSWI -R

deploy:
  bins:
    - julia

files:
  - name: julia_1_9_3_linux_x86_64_tar_gz
    url: https://julialang-s3.julialang.org/bin/linux/x64/1.9/julia-1.9.3-linux-x86_64.tar.gz
  - name: julia_1_9_3_linux_aarch64_tar_gz
    url: https://julialang-s3.julialang.org/bin/linux/aarch64/1.9/julia-1.9.3-linux-aarch64.tar.gz
  - name: install_packages.jl
    contents: |
      ENV["JULIA_PKG_PRECOMPILE_AUTO"] = 0
      using Pkg
      Pkg.add(PackageSpec(url="https://github.com/korbinian90/CLEARSWI.jl"))

categories:
  - structural imaging

readme: |
  ----------------------------------
  ## clearswi/{{ context.version }} ##
  Published as CLEAR-SWI. It provides magnetic resonance images with improved vein and iron contrast by weighting a combined magnitude image with a preprocessed phase image.

  Example (run in julia):
  ```
  using CLEARSWI

  TEs = [4,8,12]
  nifti_folder = CLEARSWI.dir("test","testData","small")
  magfile = joinpath(nifti_folder, "Mag.nii")
  phasefile = joinpath(nifti_folder, "Phase.nii")

  mag = readmag(magfile);
  phase = readphase(phasefile);
  data = Data(mag, phase, mag.header, TEs);

  swi = calculateSWI(data);
  mip = createMIP(swi);

  savenii(swi, "<outputpath>/swi.nii"; header=mag.header)
  savenii(mip, "<outputpath>/mip.nii"; header=mag.header)
  ```

  More documentation can be found here: https://github.com/korbinian90/CLEARSWI.jl

  To run container outside of this environment: ml clearswi/{{ context.version }}
  ----------------------------------
