name: clearswi
version: 1.0.0

architectures:
  - x86_64

build:
  kind: neurodocker
  base-image: ubuntu:20.04
  pkg-manager: apt

  directives:
    - install:
        - git
        - wget
        - ca-certificates
        - vim

    - workdir: /opt

    - run:
        - cp {{ get_file("julia_1_6_3_linux_x86_64_tar_gz") }} julia-1.6.3-linux-x86_64.tar.gz
        - tar zxvf julia-1.6.3-linux-x86_64.tar.gz
        - rm -rf julia-1.6.3-linux-x86_64.tar.gz

    - environment:
        PATH: $PATH:/opt/julia-1.6.3/bin

    - copy:
        - install_packages.jl
        - /opt/install_packages.jl

    - environment:
        JULIA_DEPOT_PATH: /opt/julia_depot

    - run:
        - julia /opt/install_packages.jl
        - chmod a+rwx /opt/julia_depot/packages/CLEARSWI -R

deploy:
  bins:
    - julia

files:
  - name: julia_1_6_3_linux_x86_64_tar_gz
    url: https://julialang-s3.julialang.org/bin/linux/x64/1.6/julia-1.6.3-linux-x86_64.tar.gz
  - name: install_packages.jl
    contents: |
      using Pkg
      Pkg.add(PackageSpec(url="https://github.com/korbinian90/CLEARSWI.jl"))

categories:
  - structural imaging
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAIAAAAlC+aJAAAACXBIWXMAAC4jAAAuIwF4pT92AAAE9klEQVRoge1ZMUzyXhC/fvk2d3TGWEejLsbFpOBkXEzUV1fjVHR1KoOjSUc2mE1a4wzBmBADizEGHYwo3UuiU5n7H376fLwWhA+08Z/+Jjj6jvu9d3fv7qoEQUC/GX/iNmBcJATiRkIgbiQE4kZCIG4kBOJGBIFGo5HP5zOZjKIo8/Pzuq6XSqVut0tErusqipLJZPqpw6owKpVK+GFd1xVF0XU9UlU+n9d1nSvMZDK5XC6sRxGLOdd1Dw4Orq6u8JUx1ul08LXdbqfT6U6nMz09TUT9SkBFUYhI07RUKiXKDw8PV1dXRYnrurOzs/gM5ZGqGGNzc3NEVK/XYQlj7Ozs7PO54APNZhMS0zQ9zwsENJtNfPA8T1olAb9KyyNRLBaJyDAMIrJtexhVzWZTVVXp+XdTfN8P/xbGBAlomkZE2DXG2JCqbNuWnn83he/H4H+dFIF2u83tAJN2uz2MKiwUDXgP4tPTUyLa29uL9OyJ4/b2loi2traIaGNjg0u+hO/7RATOwB8i6nQ6rVaLiBYWFr7B2ghcXFwQ0fLyMhFls1ku+RKXl5ckbXQghO/gcx/ehTRNY73wfT/Sf8RVkhdByF3I9334uaZpojYKgqBer0+WAPKBCPEvEYhitrAsi0L5I1KVYRhSVPwlopmZGfzc7XanpqaGOcrBuL6+lu4BEfCWWq328PAAyfPzM+Tb29vSw+vr67u7u29vb9VqtdVqvb6+yupEujzfj3kCA7IQTyOREL0orMo0TQqlyvcshAvl/Px80MZOAsg2lmVJxGDA4Fx0fHxMRIVCwXXdT6m0MeVy+VtPgDFGUUddLpcpKrIlVeGb+9MUxBa2R0oIkyolsFxV1fBPSPDi2khVMNI0TS7pKeYqlcrR0RHuBFVVl5aW+hVz2EgRKNf6FXPZbHZ/f99xnJ2dHdM0T05Owh6Sy+UKhYJt2whlqPI8T1SFElBV1aenpx4XEnfCtm3DMHDbaZpmGIZt28iDA0IQvifekSKwZ3CAer0eeT7wIh6j/UoMyQl7TuA34v/Ykf0uJATiRkIgbiQE4kZCIG6MTKDb7TqOg6mgNHiEsNFoSEtyuZyiKKVSSZI7jsPlGCH2FPpDIrKu6gfP83i5xhjjn1H0orUtFovSKjyjaVpkWYbaTtQzEkYjgHLSsizepPu+z6tLDAekMRtGHujNxdaeNwAQ/gQB6S/DiGx30IKAudiIgS0vnv+ZwAgxwPupfpOLVCoFp7q/v+fCWq1GRJubm0R0c3PD5Y+Pj0S0trY2vAGRGIFAOp1WVbXVajmO0+8ZzAk/2yWiQqHAGFtcXCSiu7s7LseMDcO5sTDSeaFpIiLDMCJnMHiA96wIAIS1qqq8G+beyBfi67cHMUzk0zLGmNQfws14wkEAgCrCAC0iAkDszX+OQPDRN/McKg15IIcpMBpBL04UMeUURzg/SoCDe5Q4qMH8jGd3nmfgTth13ACiufEQCKJemYCVZVmwuGcI9eFdFLrXYiMQzv2QYBhDvXMRfvWGHe+fCYxbzL28vFDvnAu3QbVardVqqqqKrx/xLgNHtLKyMuZfv2N4rnjFIO5ou91GyEqjfYSBqqrSJBl7Hy4rxjmBEQjw9yB4AdMvCwV9gjsQ0n/4beJPEIBl4tTRNM3IOSEPjLBBcLbwy9x+g8QvkYwW40ZCIG4kBOJGQiBu/HoC/wFkWD/gxOxGxgAAAABJRU5ErkJggg==

readme: |
  ----------------------------------
  ## clearswi/{{ context.version }} ##
  Published as CLEAR-SWI. It provides magnetic resonance images with improved vein and iron contrast by weighting a combined magnitude image with a preprocessed phase image.

  Example (run in julia):
  ```
  using CLEARSWI

  TEs = [4,8,12]
  nifti_folder = CLEARSWI.dir("test","testData","small")
  magfile = joinpath(nifti_folder, "Mag.nii")
  phasefile = joinpath(nifti_folder, "Phase.nii")

  mag = readmag(magfile);
  phase = readphase(phasefile);
  data = Data(mag, phase, mag.header, TEs);

  swi = calculateSWI(data);
  mip = createMIP(swi);

  savenii(swi, "<outputpath>/swi.nii"; header=mag.header)
  savenii(mip, "<outputpath>/mip.nii"; header=mag.header)
  ```

  More documentation can be found here: https://github.com/korbinian90/CLEARSWI.jl

  To run container outside of this environment: ml clearswi/{{ context.version }}
  ----------------------------------
