name: gigaconnectome
version: 0.6.0
architectures:
  - x86_64
structured_readme:
  description: >-
    Functional connectivity is a common approach in analysing resting state fMRI
    data. The Python tool Nilearn provides utilities to extract and denoise
    time-series on a parcellation. Nilearn also has methods to compute
    functional connectivity. While Nilearn provides useful methods to generate
    connectomes, there is no standalone one stop solution to generate
    connectomes from fMRIPrep outputs. giga-connectome (a BIDS-app!) combines
    Nilearn and TemplateFlow to denoise the data, generate timeseries, and most
    critically giga-connectome generates functional connectomes directly from
    fMRIPrep outputs. The workflow comes with several built-in denoising
    strategies and there are several choices of atlases (MIST, Schaefer 7
    networks, DiFuMo, Harvard-Oxford). Users can customise their own strategies
    and atlases using the configuration json files.
  example: |-
    ml gigaconnectome/0.6.0

    giga_connectome [-h] [-v]
                           [--participant-label PARTICIPANT_LABEL [PARTICIPANT_LABEL ...]]
                           [-a ATLASES_DIR] [-w WORK_DIR] [--atlas ATLAS]
                           [--denoise-strategy DENOISE_STRATEGY]
                           [--smoothing_fwhm SMOOTHING_FWHM] [--reindex-bids]
                           [--bids-filter-file BIDS_FILTER_FILE]
                           [--calculate-intranetwork-average-correlation]
                           [--verbosity {0,1,2,3}]
                           bids_dir output_dir {participant}
  documentation: https://giga-connectome.readthedocs.io/en/stable/index.html
  citation: >-
    Please cite the following paper if you are using giga-connectome in your
    work:


    @article{Wang2025,
        doi = {10.21105/joss.07061},
        url = {https://doi.org/10.21105/joss.07061},
        year = {2025}, publisher = {The Open Journal},
        volume = {10},
        number = {110},
        pages = {7061},
        author = {Hao-Ting Wang and Rémi Gau and Natasha Clarke and Quentin Dessain and Lune Bellec},
        title = {Giga Connectome: a BIDS-app for time series and functional connectome extraction},
        journal = {Journal of Open Source Software}
    }

    giga-connectome uses nilearn under the hood, hence please consider cite
    nilearn using the Zenodo DOI:


    @software{Nilearn,
        author = {Nilearn contributors},
        license = {BSD-4-Clause},
        title = {{nilearn}},
        url = {https://github.com/nilearn/nilearn},
        doi = {https://doi.org/10.5281/zenodo.8397156}
    }
build:
  kind: neurodocker
  base-image: bids/giga_connectome:0.6.0
  pkg-manager: apt
  directives: []

categories:
  - functional imaging
  - bids apps
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAdzklEQVR4nOV7CXBd1Znmd85d33vaJcuWvEjybpnVNjaxA5IJuw1haTkhJCFsIqGrJ2RS3Ukq6ZLVPT3ZOiFJdQhjGleFUCFIYdiMwRhoC4JDbLxgbHnBlrxblmVtT2+7955zpv5z9WTJi2wSOj1Tc+DJek/33Xv+/fuXA/x/vthf6zkNDQ2stbVVP6+zs/Oszy0tLVX0b3V1tWpsbKTf1X/6xvCfthp4XV0rC4mtRWnpbNXcVCfB2PmIYnV1TbyzcwcrLW0dzhD5/wQDGhoaeFbSzU3NEmxIinzp0no3HYFlwrcdbsfSaQCu/gF4KpOWmRTsWIDOHemWlpYg/JpiNTXLDWIg0Izm5mb5SWoG+yQJX7cOvLYWMiutpUvrozwnKJDMmcYZm6Okqmacl0shS7nBi5WSpA8KnDOp1ACgDkOil3HWKoXY5CmxM5KRXS+9tDKefQYxsrW1VTU3N4v/WxjA6urqeFZNa2pqzFjl7BLD5wuVUjcbDFcywyhjjEcB6dIjlVL6lX16aBQMjIfqwhnzpFQpIYKTENjMLfaazMiWEzhx5L3m5tTZmP1fwoC6ujqjs7OatbQ0BvR70iyabMC8izF1m2E5U5SSeUoSsQJSBlISqfo/cgVsxOOVlAAnATPGmWSAwTk3wA1OnySDwOsQUrwuBH7dq05+QIygZ9J3/xJtYH8J8dmH31z38DhuyAeYad1rcWOSVMIUQaAUpFCCJM2YfpJSjN7oB4ccGLaIUVoB9Ev/yoh4KAZmGNxk3OBKKnVCiOAFKP7oqmf+bTddS1rX0tIi/hzfwP4M2llNTY1BTqqmpsGMjetYYpnWd7hpzpWSCPeFFFKRRmtqmRbr4KNO7Y8zFbJC80RBkNBHbCu8VinSIShOH3DSC9PkhgUpRFsQBL8wUpmV5CPm1tdbm1asCD4uE9jHJX5ufb25acUK/9q6+nzHNL5hm87XwVRB4GcCpSS0cisYZwh42OIMEEohE3BAMtimgmkoEKXn3iZpiJQMjCILTNM2DW5mfOE3pbx0w9rmf29vaGgwGxshgQv3C+zjEF9fX2+uWLHCv/mO+yqsqPsoN+xbhe8bQRD4YOTLmXG6pM98oEIgObyAoSQvgG0oHO8z9TcitgK5gvMtYgQAybnBLNs1hPQ3+5nkN1Y3rXy7vr7eWrGiRwIX5hfYxyX+lroHqrjtPGlazmIvnQqEFOSkSOJsNMLJ6xucQUgDjAssubQH18zqh2MpbN4fQ/PGIpyMW3BMAbKfC1lSScHApROJWEKItrSXuH/Ns0+uq6urs5ubq4ML0QT2cdT+uroHqiKWvdK0nNpMJu0pKUJXPcoiwok3lslBCpzIMCybfxL3XN2BwGeQiiPHDfDmjkL8fO14bQamESAIwu+db/tSCrK6wHFcWynZnvKS9xETLtQn8PNRTw4vJP6LVa7tPmnZRHzSU0qeQXz2SVlXTgSYpkkBjTaK7ngGDuvFp6d2QQqOeNpAPM3QnzIxpyKOSQVd6E8G4OCwzPDWGi+cm73gnJNLsTLplM8Yr4rYsZU33Hl/Le25pqGBbsL+bAbU6PCyTtR89p4Cx8x91Ladxel02gu1mew99OaGfgEmD5WXCLYMQzPA930MJJLo6xtAYUE+bv7MApQW5yKVFjAMCwY34AVEiMTkSaWa4N54HELQ3w3NwPMxgsyPMWamM2mPc6PKdaO/uuHW+2a0NDYGJMDRaGSjYvrZs1nnL3/JcsbN/J7tRr4XZDJKSMGykh/uzZVk2p4t7c1DwtMZD4bJMbG8DDWL5uLqhQtQMWEs1OEnkNi9EgHLBTdtuKwX7rirMFD+Lfzh/b1YtXoNdn60nxAhIhFXM4IYIKUcRJAhrAh14BQRii4gc3CjtpdJv6jifffOmzetj3KTc4Eldi7G1NQ0GITwblxWf0vEdZ8KApEnAl9yg2uXTeYZCDbCm3f2W/D8ADJIIRqNoHr6FFxbeyWumHMJigsLQMFi177DeOvN1ZhT8A7mVSXgZVLYcQiIF3wR82uWoSAvit6+fryy9m2sfr0FRzs6YRqGZgTnPGSAEuHGQyAxAkOQYzQ4V5btwkun/nmV7P6XulEySnY26rPI6ua6e8YaVvRl07TnZdJpn3OYIVQFfMFgGMCSy7pxzcx+RCyFDfsieH13BSqmXIzrauZh9szpiEZcxAcS2LKtFW+98x42b21FR9cAvvm3d+Nz11dizZq1+MVvNyEtoqieVo4bP3MVahbNQ04spol/Y90fseatP+Dw0Q64jg3HsXWo9AQ5UAbHOB1DUK4hfcM0Tc55ZzKdvPX15ic3hBihMTgvAxoG01nK43PLZnzbcqINgZeGFJITFuVM6genPI5l87txb81xCMEhJIch+tHrXo2iOQ2w7RiOdRzHO+9twdvr38fuve1hEiQFYtEIvr/825gxvRLff/QpvLr2LRTlO0inPQgpMffSatx56w2Yc0m1JvjQkQ4899IarHt3A3r7kjCdGEpzfRictO5MDKFoMQjHcU0vnXlhQPIvtVSPSdadxRTM0xmwbt06TjD3+rqHp3KD3yuFMJVSARk+qRs5trTHMSYvwOJZfQgCjv4UB6PERbrId3bi8N71WPVuPzZsXI+jHV2az67rwHVtJBJJjCkuRvnYfCTifTh8cA9iLuDYNkzDgh8E2LRtJ1p37cPll1Zj6fW1mHf5RXjkq1/CTdfV4tW16+D2rcbiWf2IOgzvt0XR/H6IIVyTkGjoFIkFge9L23E/E/MyNWhsfKWzpsEcwt5nY0BDKH2dXNgsuNs0o5M8LyWUUpwxChhkfzpT0WpH6keS54YJQuzMsOFlEnhi5VN480ML+VGFWCyimWPqUCiR8XyUlZUiFs3BoaMd6OruA/nUQEj9d8sykWfGtBNdv3Ertm7bicVXz8ctN1yDionl+NvbcuDtOQIwSz/v9nknkRuR+NmacfDIEZtS+wQGcEmxlyGXK/m1G2+8+51XX1seX1a3jDc3Q5w1DK5bt46Tilj5U0o543dIKU0loSij0VhcG42CY4aqt/lgDDl2BlwkweChODfA/q4Ydh9zUJgXQV5uDIZmDm1KaiJpTa2aBNu2sLftAPr6E0OhjhhA4S/r/QvyckBJ9HMvvoav/cMP8dgTT6B3TxMCwZHwbPQnoTHEvKo4ZpYnkaZopIayMK0F0vdh2fYCuyB/FgNTndXVI/JwPkS9TlVr9a9O1Fpg2k6V8H2yWrrdkMMg7pL0Kew9+6civLNvLGw3AosrfLA/ipXvjMGAF0HUAfxAIAiCITRIoM22bEypmqi1qW3/Ia3yFObIwrKgKRAC8QHCDnGtbpWTxuNT8y/HpdWTYWkJc40hSM6+INwBuFaoncPdm96vIo4ahQrizuq6OrsWkFTAOcME6pYt403rmsS8WzZFGdgSxZBD+Typ0vDbapTHGKKOwsHOAC/vmY8FS29AW9teND65Gr1JA3lRkjZpGUnjFPP8wEdRQT6qKiYilc6g/eARrfKmaUAIMg8PXsaDVAoF+XmYNns6ahbNx/w5F6F0TAkCP4W+HR/ASj0HPyAztLTWfXAght1HI7BNggGkSeFOqaqipApIk6XCtZWI/rSxsbEjW8sYwQDy+qQ1N97+QJFSWKTI1Yf1mREMyOoPMcI2AkSiURi5F6MXUfQkXkXEFuDcRCCypY9wUYkgCATGFBehMD8XiWQKHcdP6KgwkEghk8kgFo1i5owpmHPJLFz9qSu05MlUevvieG/jFvzHu1uxf18nvnLVdFw6oQ+Bn9HEr3y7FD1JA1GHItTwzeryGyMlMC1nUtpn0wB0DJblNRlZBjCt/S1UoLUrTcsaIwNBN9Mxf/gK1ZkkFkp4akUZDAgcaN8JAxmYRuRUOBq8nlSb7JrUfMrkSRokfbjzI20Clmli8oQyzJw2GTWLrsCsGVN0mCQUuadtP/64YQv+uPEDHOvoRCKZRCAtdC2pR/Sysfjfz7+EJ1/YiYyKIscl0xiOC0OyKP1WUkjTtHMszq6oQ936ztpqNNTWMuo9aAbopsVsKjvXcq46rjC4E/NlZhBfnTu/J1VlhgUQnvcF/CCEwdlKONlzNjdIZzII/ACzpk/WZnHw0FFcOe8y3HDNpzF/7sXIy83RZkCAZ/WWD7Fh0zbs3NOmQZRpmIhFXQ2qcmNRzK6egbRVhpZdb6BnABhbHAIhXYYaKS5NgGJMKkhHCTk/szA32rK8caB0WegHTPpBwKdp+XJ5y9I3IgC/REnpKqggW4k6Yw1+RM4Hki4TME0+KGXKAA3NBGKQFwTwUykkkymUlhRjcgU5QODa2oW4bcm12gd0dnXjvY3v4r1NH+DD1j3o6urRqkcgiBhDUJiKo4l0GmXjSlFWkofurg4cP7IPeTGqGzLNvLPBWtoSFVC05hqYHowXMTDEO2vC7pR56kKmrq2rtyJSjQ1pDF3AWW6p/1eSvLeFSZVTIGFg/8FOMC41AzzPRzqd0R6ebHja5AqN6hYuuByTKyfqcEefb9uxGy3rN2Lr9l04cvT40Oc5OVEdGYgwKrPR5j3f1xpUVTkJbiSKtm270N3bD9O0QrsfTJLOtt+wHqv9WaHwqAtzapnD3/gwIw5TpWHCoTHVWVWfin6ExX1pIc9JQaQ7cbI3joEU+YeE3nhJUSHmXjYbi66cg0uqZ2i7llLBMLi2/Z/96tfYtbcdvk+M5IhEHCp4hpVxXeggTBAST1qihIRlmKieMVXff/uufcj4Ao7jnqdmEIqTGMk5j/CIUwJgf21tLVpaWpg5vFlpg0c4FyWhoxvcyWmL1D7jKTiWgTvn9WBs948RbHcoxqC7sxBjy6ehdtHluGT2TIwdU6w3e/jYcTy/ai3Gl43FNVdfid372rFp6w7EcqI63OkS36C0hQibJrqSHgKaUDh+gLy8HEybUqEd5N59lC7rptLQ9edaUpEXEDBsx4WPcfRZayv5PHV6LkB9OvtUy2YED8OCBwGhTMDwufk9uLemE8mUQLJX4aqKNC6dWYPCy+6FG8lFX38/1m8IE6HNH+zAseNd+J//+A292V172uG4jg57tAjtkY4OYYZhxIQZL/kSgenlpRg3pgg9PX3aWZJGEAOC4MKKwFpRDDYIg5sBLBvJAM59xUCQ6sylt6QY0j5HKSVCMykRYvBUFNzkyEgDRWw3Dnz0Ll7dkMTWLX/SiRDBX9/zMbF87KD0Mjh8pEMDa1JzMotTuf3pGyYJG5A6lElMrpyESCSik6WTPX2wLEsTdT4NGEaDYnxk8d0c/ibwOXdsXd0alYs6ETJDbSA7pR6Qa9lIpgbwxLNP4T9aXRREBFzXRSRiYyCRQGXFBBQX5qOruxdHj3XCpOyRh7Y+6qbJwweBvj5r/zt27dNO0XWcC7D/U+RTUqOkHCl0DCfOEBmhlO7EnvXGlAhZCp19JjYdiCHHFYjaCrYhdFlr92EDeztjKCmIID83B45NG5TafimTcxxHO8CTPb0jpDca8SPsf2rW/g/octyF2P/gjUCAVgnhK8V7z2BA6eBkhvBYgkEe1vAvhJEjdqcTIU7Ky3QOTqXsQCj9WaS8BqnSLyMVRGCxQNcKfUHgKNAV3qrKMP7vaz+kpUee/3xNrND8KQQKjCf7LyketP9jQ/Z/IRrANRbikIGfsALvyDDHr4arAyu1k0Faub2DAIpM5nRsqWNuxJboipv4xRvlqCrqQ06E48sP3ouFi6dh8a4UXlnzNgoK8jU4Sqd85OXlYtrkSo0P9rUf1LcMN5/tEp+5dJtcI0lqCQpMqRiPiOtg87bWQfs3P4b9D7VaEhKeN5I5g6uuicZSOtOKs+2MMZ9T007v48ybk9m6loQvFLYfK8TabQYe/82rEIGHL3/+dlRWjNe43dAITaGkuABjigswkEzoIoiGyCSR0aRHmIEzHet96WDmrIu1Grfu3quLJbrOcAHSD8tj4eyBELItA3dAC3tQ6zn9aG5ukp2/3MH0WArHJkAm6BuD/dlz3JjB4gJ5EYnSAgubNr2P51a9gbKxY3DPXbdrIlMZTytSxYRyxGJRdHScRLe2/5Gl+uzARPZJJFHDpIozkEgrVIy1MbsqikQygR17DmvIbRih+pOW0MsY9tKac2r+gCRJma7PmNrsd+5OnKUewBRQo39LpTO7mcN6OTcLlPJGZbFQDGoQ7rpuFM0vrNGQt3bRfGzZthMvrn4dtmlh6uSJWpoEgOLxJKJRQqMh0doXkJUOYQDaDfUaGAwucfeift1DLO36Pnq6ZiLV3wVwV4cqStgJclPRhapf+vtkXoahnaxt24PJGQU/NSBN/l62rd/SspwS9lNhMFQJxazkTV3SmrDVtOxKX3DGlCAHclYjow91EySQuoTV09uHlU8/h8bv/B3u+dytGu0dPNqNaVNnao05eOiItn3amJbyoCJIwvsirBdQjpHxJVI+x721Sdxf26Wttu/kfhS4e1F3eRl+3lWOEz0J5LgMlZWT/YrKKn9SxSSfZo4oLO/du88+uL/dOnL4kMG4ibyCAiY877gfyB3hE9cNDeaYWWKocVDX1Mybl70Wv+ULX1vFGL+eM0Qoj6QJjXOZQliBCZ0ZZW5E9POvrMWXln0W93zxLjQ9+xTKC6k9NoDWj45oYsmGKbRRhYh8hO7xMQ434uocIje/FOUlFq6/uAXpNDHDAQwbAVOYV9mH6WNc5M5fmrxjyVXJi8oiwujabgZdu6ywFGoqY8FlA6ncvxHv7Txmvvba69EPtu9wTcN4d5yTPEmSKF227MyqcGNjI9XKSCbKF2IdU5njBjerdLn3PPEqm46SZ3YcE79/6S1cXD0d1886iKob9iB6aDnSJy6BSHUgmaESeKCTo5LiMl3qmlA+DuXjSlFVMR7l40oQi+XCQj+C7dvQd6IbzHJ1ZzkIEmBWkXzkWz/onpQjZfzNH+Yefn6DKwe6GGnO0H5MG3bhBPGpi65NLf7ef+9f9c7u/h//6w9//8orTYmGKfebjc1NWv1pjVBtYgBpwpo1rU5xRdFPbTfyUJBJCSmVboqM3v8nhBiGyXgKuG9xGp+f1460x5DxJBwjiV09M7CXfQFTqiahvLQIhUWFuh9ATou0iGyZcohjnd3Y23YIY1O/w8KJu5ASuQi8BKLF0337ssdOJtb/JnrizZ/kKT8N7kShFXR4KCSHKjzIdBxW4YRg/J0/TPOqmnX9R3Z+5afjZ/Us12XN7GzayMWopUxd1aXLvnaF4ZirlBBjhBCCuq84z6IucdI3UJIr8N2b96GixEcycGicBSqIw43kwJ3zcwizCsnkADpPnMSBw8d0YnPw0DGcONmtiyPx/jjiKYkJJQYeXHwScyZ1A2aBLLy6qbPrlR/lxlv+NYZIcYjwDDusSun0fTgl2hwAPwU/NaAm3P0Yc2ff0gTGPg/d5wiTInY6EUNa0NrqFPHinzuO+6DvpYKwOTK6FpBnHshwlBV4+MGyoyiMBehPhY+hii1nAr/fuRBbDxWhv/sYevv7kUhmdH1xcD5QV5OohmgSBhAGbBOYMaYHX//WD7qKD7xpH3/+kbzIzJtQcPXDEMlu9Kz9EUTiJJhNhZ7BUDqID0gLmOGEDdREd1D24O+NSOWCbzLGHlVK0VQLVb3PXHPnzrU2bdrkX39X/cwInNXgqAqCTMDIpY6mAVzBDzgoO/3q4uO4fV43+lOWrt0X5/j44GAM3/ldEXoTTKNHKq4SwXoekIchLBy0CTEYxZ6ungQWX3NdsvH+RQPtj15bauaXo7z+BRixIv3MdNt6HP9tPaSXDMtzhAG4pb9v5JYS4XrcjjTEKJwoyx968YRhRxcwxg6QUM86ILF06VJRV9dkvP7Mit1CZX5mmGaGxoCo9TwaA4aaJjpXKMabOwpAzSBqnRPxVL4OWD7GFefo7i+FTorXesZjsDNE6TP5AsrxKc/IcTnuWHpVsv+tn+bJZA/sstmaeBVkNMHu5IWY9K2NKLvvGRTd9I/IufhWWMVVKLrxuxj/8KsYe/cTMCJ52lT8ozuQ2tpMJb87B7fMzwmis6awdsuWWGG07HHHiXwhk0l5SipqO486WUJ/pe6xZUjMKk/prs2uYxFdu88ZrLdQHYBWFs6ejufpEel0GhUVlcGvGr968vBjN5fCSxJExLgvPwVnwqVa1VP73tH27ky4DNzJPet+EtteQudzj1B4ULEpV6L0S0/9EWEbLDgnIdQjpF7h+pdeinsi8T0Z+FsdJ2qDUfp/7om+UJJAxArb6Jvbc/DunlzE0xw5dljjC+v34QpLX2eXA9UBKquqPHbiQ0sMnGDQztRDx2/uQXzD05rwzKGtOPr4Z3H4Z7U48tgSdP7uq0i0vqoBlQqowgVtChoYWw4yR1uZ33OwAsAYigSjSpKGJAg2rm1+ut3zU1+XUrQ7TsRWipgweiZCNFLRJDdC+YLQDBkanhrti1nGaJMSmDhpYqBOfmRCW5/SRMjMAHpb/o3yd+TO+RuYBeMh/TSC7v2Ib/wtgu6DIHfFTBci3omeN36kIwLjJgsS3SroPUKF0aoLmRJTLS2NgkbOaAgxlUzcJ5Vsd1yaB1E0KTZqOYfsXw3zDxdcvBm+AV3PHrZNKbSqi4ETSLWth5FfDnfSPFIXSC+Bgpq/Q/6nH0Jy95voWHkXjq38HDKHt4FZkWGhMkyScCFjcrSHTSvKBA0frnnuyXVpL3mfhGx33ZhDA0nnc4y0/9ENZvSlQ6RmwGlAR0nE339Wv41ddjtEogtu5QIULWmAd2wHup7/B6Ta3oXoPw7mxE4RrwewOe1Z7/tCGEBAWdJQAY2h0hBixk/fK4RoJXMwmG68DJrEJ3cARRdwDQNtbW2WOe4Sj5kEdrKclGB2BOmD74MiQ2TyIkSqFqL084/r6HCi+b9BpPpg5IwBOc1sj0MFnrLyxzFrzJTjAPZ+DAbQahYrVpQJGjZ67ZknWtIZ7w7he8/TNJZpOSZoClYJmiYZ3OVfxoywIWLjQHu7ncqdKqzC8ZKATVjbDadRyL7ThzbDiBWj7IEmcDuKE81fh3diH7ibq4HQENNoPsFPITLxcmXEincB6DsnDjj3aqQTGqEmND++G4nEfZ7n/Q9wdNp2xOTh6QZqbQRKCfmXMIO+SWnzkcOHDcrqSi66LknYnhqxpMYqk4Qz8XKt9voAhhVB0HcU6QMbNfEaFA1fZEbCk5FZN9K7pwehMP+YDAj3tmLFioAc44sv/ro3fmzHv2Qyqc9KrQ1Ov2U7pmGYJuNcpyRK0UvSv8MYMurtwzIWzZPQMDRn8tU1r0fd2keSlNiAQhsxQAnwSC64kzNk30ZOidYC+tuI5IibkMluFa2+yYhetGQngNf0HBkg/hwG6F3SLC6BpdraWvla07+/l+np+0rg+18MhLeKcd5lWg6VxU3TNGi2jhb5QuI6tZO18xz+ImbR5zTRQVpENRhKdfILCvm2bdsjL/9hj6KsTqQHBF3K3Tyk2/+E+PvPaAIp7nev+YGODozbp1Sf/uYlwKNFonjpP1Nm8veMse4w9WDhFMhfsrInubJDiHSQwjWtag51mwKuMUxzMjeMKLXcQ+9NbXMZlhmGnyDhYTc4e3gKYD4DEiLwOiT4H5hMvvDiM08+lN7x8i1Hf/twwO2oSWqvghTciit06ps5+uGgRmRra1xLnoif8GCzaZRMbWCM/VM2EcInf2wunDGk9xQ2e4PigmjUnKHArlBCXEEDJQysGJzlGKZp65I2laboGEgghJKyX0IkmEIblNqswP5kIL09d0Jx99M/+UlC9bQXoKByRWr/hju7X/6uyhzdwZgTY5ABoyIIs6J6VkEJH9JLKQhfRqtv5MVL/yllFYz/MWNsORGvC6XnqAd8Ikfo6CTZ8CNtDQ101u/haBxGxOFeLOPJMW7EKMkIOmzBFKPDBJ4X9yQO84CnhYlkT9umJGWk2fvW1/8vc8WKh/R7pdQ3hZf8+9SW5rEEeDLHdyEY6CY3o8vtVv5YFpk4B+6sGxG7aEkrgG8zxl4OU3om/xpHZ1nIiGHHZpuXfZwTn0PHZ6mASQVbOjE6LHEiNzkVwB0Abgt6D030ew6NGawuC6t0WocRLaITZc8A/asZyz85XO1HPAh/xYPT2TkEGk5Yty4kLHvR8APV2c/PdUx2ODFNTXVGXV0T9fwrBq+lz/cOOrozrj9jc/ivW2d79gWDZlLnwbHgsxI2GObI3qmcd877/h+007Cv2h6RUQAAAABJRU5ErkJggg==

readme: >-
  ----------------------------------

  ## gigaconnectome/0.6.0 ##


  Functional connectivity is a common approach in analysing resting state fMRI
  data. The Python tool Nilearn provides utilities to extract and denoise
  time-series on a parcellation. Nilearn also has methods to compute functional
  connectivity. While Nilearn provides useful methods to generate connectomes,
  there is no standalone one stop solution to generate connectomes from fMRIPrep
  outputs. giga-connectome (a BIDS-app!) combines Nilearn and TemplateFlow to
  denoise the data, generate timeseries, and most critically giga-connectome
  generates functional connectomes directly from fMRIPrep outputs. The workflow
  comes with several built-in denoising strategies and there are several choices
  of atlases (MIST, Schaefer 7 networks, DiFuMo, Harvard-Oxford). Users can
  customise their own strategies and atlases using the configuration json files.


  Example:

  ```

  ml gigaconnectome/0.6.0


  giga_connectome [-h] [-v]
                         [--participant-label PARTICIPANT_LABEL [PARTICIPANT_LABEL ...]]
                         [-a ATLASES_DIR] [-w WORK_DIR] [--atlas ATLAS]
                         [--denoise-strategy DENOISE_STRATEGY]
                         [--smoothing_fwhm SMOOTHING_FWHM] [--reindex-bids]
                         [--bids-filter-file BIDS_FILTER_FILE]
                         [--calculate-intranetwork-average-correlation]
                         [--verbosity {0,1,2,3}]
                         bids_dir output_dir {participant}
  ```


  More documentation can be found here:
  https://giga-connectome.readthedocs.io/en/stable/index.html


  Citation:

  ```

  {% raw %}

  Please cite the following paper if you are using giga-connectome in your work:


  @article{Wang2025,
      doi = {10.21105/joss.07061},
      url = {https://doi.org/10.21105/joss.07061},
      year = {2025}, publisher = {The Open Journal},
      volume = {10},
      number = {110},
      pages = {7061},
      author = {Hao-Ting Wang and Rémi Gau and Natasha Clarke and Quentin Dessain and Lune Bellec},
      title = {Giga Connectome: a BIDS-app for time series and functional connectome extraction},
      journal = {Journal of Open Source Software}
  }

  giga-connectome uses nilearn under the hood, hence please consider cite
  nilearn using the Zenodo DOI:


  @software{Nilearn,
      author = {Nilearn contributors},
      license = {BSD-4-Clause},
      title = {{nilearn}},
      url = {https://github.com/nilearn/nilearn},
      doi = {https://doi.org/10.5281/zenodo.8397156}
  }

  {% endraw %}

  ```


  Note: Citation content is wrapped in Jinja2 raw blocks to prevent template
  processing conflicts with BibTeX syntax.


  To run container outside of this environment: ml gigaconnectome/0.6.0


  ----------------------------------
copyright:
  - license: MIT
    url: https://opensource.org/license/mit/
