"""Replace post-release labels and retire OpenRecon ARM64 container variants.

Run with --apply to update recipes and withdraw obsolete catalog records.
New release records must be generated by building the renamed containers.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from builder.openrecon_updates import uses_openrecon
from builder.update_plan import next_container_version, rewrite_scalar

REVISION_SUFFIX = re.compile(r"\.(?:post|r)\d+(?:$|[.+-])")


def migrate(root: Path, *, apply: bool = False) -> dict:
    writes: dict[Path, str] = {}
    versions = []
    openrecon_names = set()
    for path in sorted((root / "recipes").glob("*/build.yaml")):
        original = path.read_text()
        recipe = yaml.safe_load(original)
        current = str(recipe["version"])
        openrecon = uses_openrecon(recipe) or any(path.parent.glob("OpenReconLabel*.json"))
        if openrecon:
            openrecon_names.add(path.parent.name)
        retire_arm = openrecon and "aarch64" in recipe["architectures"]
        if not REVISION_SUFFIX.search(current) and not retire_arm:
            continue
        version = next_container_version(current)
        suite_path = path.with_name("fulltest.yaml")
        suite_text = suite_path.read_text()
        suite = yaml.safe_load(suite_text)
        if str(suite["version"]) != current:
            raise ValueError(f"{suite_path}: version does not match {current}")
        if list((root / "releases" / path.parent.name).glob(f"{version}*.json")):
            raise ValueError(f"{path}: release {version} already exists")
        updated = rewrite_scalar(original, ("version",), version)
        suite_text = rewrite_scalar(suite_text, ("version",), version)
        if retire_arm:
            updated = re.sub(r"(?m)^\s*- aarch64\s*\n", "\n", updated, count=1)
            if yaml.safe_load(updated)["architectures"] != ["x86_64"]:
                raise ValueError(f"{path}: expected x86_64 after retiring ARM64")
        if path.parent.name == "spmpython":
            # This is an upstream package post-release, not a container revision.
            updated = rewrite_scalar(updated, ("auto_update", "method"), "sources")
            updated = updated.replace(
                "  package: spm-python\n",
                "  sources:\n"
                "    - id: upstream\n"
                "      method: pypi\n"
                "      package: spm-python\n"
                "      target:\n"
                "        variable: upstream_version\n"
                "        fulltest_variable: upstream_version\n",
            )
            updated = updated.replace(
                "spm-python=={{ context.version }}",
                "spm-python=={{ context.upstream_version }}",
            )
            updated += f"\nvariables:\n  upstream_version: {json.dumps(current)}\n"
            suite_text += f"\nupstream_version: {json.dumps(current)}\n"
            suite_text = suite_text.replace("${version}", "${upstream_version}")
        elif recipe["auto_update"]["method"] != "sources":
            raise ValueError(f"{path}: decouple installed software before migrating")
        writes[path] = updated
        writes[suite_path] = suite_text
        versions.append({"recipe": path.parent.name, "old": current, "new": version})

    obsolete = sorted(
        path for path in (root / "releases").glob("*/*.json")
        if REVISION_SUFFIX.search(path.stem)
        or any(path.parent.name == f"{name}_arm64" for name in openrecon_names)
        or (path.parent.name in openrecon_names and "arm64" in path.stem)
    )
    if apply:
        for path, contents in writes.items():
            path.write_text(contents)
        for path in obsolete:
            path.unlink()
    return {
        "versions": versions,
        "withdrawn_releases": [str(path.relative_to(root)) for path in obsolete],
        "applied": apply,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=REPO_ROOT)
    parser.add_argument("--apply", action="store_true")
    args = parser.parse_args()
    print(json.dumps(migrate(args.root, apply=args.apply), indent=2))


if __name__ == "__main__":
    main()
