#!/usr/bin/env python3
"""Synchronize released Neurocontainers metadata into an OpenRecon PR."""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import tempfile
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Sequence


RECIPE_PATTERN = re.compile(r"^[a-z0-9][a-z0-9.-]*$")
VERSION_PATTERN = re.compile(r"^[A-Za-z0-9._-]+$")
VERSION_ASSIGNMENT_PATTERN = re.compile(
    r"^(?P<prefix>[ \t]*(?:export[ \t]+)?(?:version|VERSION)=).*$",
    re.MULTILINE,
)


@dataclass(frozen=True)
class PreparedSync:
    """Files and PR notes produced while preparing one OpenRecon recipe."""

    paths: tuple[str, ...]
    notes: tuple[str, ...]


def validate_recipe(recipe: str) -> str:
    """Return a safe recipe name or reject path and branch injection."""
    if not RECIPE_PATTERN.fullmatch(recipe):
        raise ValueError(f"Invalid recipe name: {recipe!r}")
    return recipe


def validate_version(version: str) -> str:
    """Return a safe release version or reject branch and shell metacharacters."""
    if not VERSION_PATTERN.fullmatch(version):
        raise ValueError(f"Invalid version: {version!r}")
    return version


def update_params_version(contents: str, version: str) -> str:
    """Update the first supported version assignment in params.sh."""
    validate_version(version)
    if not VERSION_ASSIGNMENT_PATTERN.search(contents):
        raise RuntimeError("params.sh has no supported version assignment")
    return VERSION_ASSIGNMENT_PATTERN.sub(
        lambda match: f"{match.group('prefix')}{version}",
        contents,
        count=1,
    )


def prepare_recipe(
    source_root: Path,
    openrecon_root: Path,
    recipe: str,
    version: str,
) -> PreparedSync | None:
    """Copy one recipe's OpenRecon metadata into an existing checkout."""
    recipe = validate_recipe(recipe)
    version = validate_version(version)
    source_recipe = source_root / "recipes" / recipe
    source_label = source_recipe / "OpenReconLabel.json"
    if not source_label.is_file():
        return None

    relative_recipe = Path("recipes") / recipe
    target_recipe = openrecon_root / relative_recipe
    target_label = target_recipe / "OpenReconLabel.json"
    target_params = target_recipe / "params.sh"
    target_readme = target_recipe / "README.md"
    bootstrapped = not target_recipe.is_dir()
    target_recipe.mkdir(parents=True, exist_ok=True)

    notes: list[str] = []
    if bootstrapped:
        notes.append(
            f"- Create `{relative_recipe.as_posix()}` in OpenRecon because it did not exist yet"
        )

    if not target_params.is_file():
        target_params.write_text(
            "#!/bin/bash\n"
            "# Auto-generated by neurocontainers CI.\n"
            f"export toolName={recipe}\n"
            f"export version={version}\n"
            "export baseDockerImage=vnmd/${toolName}_${version}\n",
            encoding="utf-8",
        )

    params = target_params.read_text(encoding="utf-8")
    updated_params = update_params_version(params, version)
    if updated_params != params:
        target_params.write_text(updated_params, encoding="utf-8")

    shutil.copyfile(source_label, target_label)
    paths = [
        (relative_recipe / "OpenReconLabel.json").as_posix(),
        (relative_recipe / "params.sh").as_posix(),
    ]

    source_readme = source_recipe / "OpenReconREADME.md"
    if source_readme.is_file():
        shutil.copyfile(source_readme, target_readme)
        paths.append((relative_recipe / "README.md").as_posix())
        notes.append(
            f"- Copy `recipes/{recipe}/OpenReconREADME.md` from neurocontainers "
            f"to `{relative_recipe.as_posix()}/README.md` for OpenRecon PDF generation"
        )

    return PreparedSync(paths=tuple(paths), notes=tuple(notes))


def run_command(
    command: Sequence[str],
    *,
    cwd: Path | None = None,
    capture_output: bool = False,
) -> str:
    """Run a subprocess and return stripped stdout when requested."""
    result = subprocess.run(
        list(command),
        cwd=cwd,
        check=True,
        text=True,
        capture_output=capture_output,
    )
    return result.stdout.strip() if capture_output else ""


def existing_pull_request(repository: str, title: str) -> str | None:
    """Return the URL of an exact-title open PR, if one already exists."""
    output = run_command(
        [
            "gh",
            "pr",
            "list",
            "--repo",
            repository,
            "--state",
            "open",
            "--limit",
            "100",
            "--json",
            "title,url",
        ],
        capture_output=True,
    )
    pull_requests = json.loads(output)
    return next(
        (item["url"] for item in pull_requests if item.get("title") == title),
        None,
    )


def sync_recipe(
    source_root: Path,
    recipe: str,
    version: str,
    repository: str,
) -> str | None:
    """Create or reuse the OpenRecon metadata PR for one released recipe."""
    recipe = validate_recipe(recipe)
    version = validate_version(version)
    source_label = source_root / "recipes" / recipe / "OpenReconLabel.json"
    if not source_label.is_file():
        print(f"No OpenRecon label found for {recipe}; skipping OpenRecon PR.")
        return None

    title = f"Update {recipe} OpenRecon metadata to {version}"
    existing = existing_pull_request(repository, title)
    if existing:
        print(f"Open OpenRecon PR already exists for {recipe} {version}: {existing}")
        return existing

    with tempfile.TemporaryDirectory(prefix="openrecon-sync-") as temp_dir:
        openrecon_root = Path(temp_dir) / "openrecon"
        run_command(["gh", "repo", "clone", repository, str(openrecon_root)])
        run_command(["git", "config", "user.name", "neurocontainers-bot"], cwd=openrecon_root)
        run_command(
            [
                "git",
                "config",
                "user.email",
                "neurocontainers-bot@neurodesk.github.io",
            ],
            cwd=openrecon_root,
        )

        prepared = prepare_recipe(source_root, openrecon_root, recipe, version)
        if prepared is None:
            return None
        status = run_command(
            ["git", "status", "--porcelain", "--", *prepared.paths],
            cwd=openrecon_root,
            capture_output=True,
        )
        if not status:
            print(f"No OpenRecon changes detected for {recipe}; skipping OpenRecon PR.")
            return None

        timestamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
        branch = f"sync-openrecon/{recipe}-{version}-{timestamp}"
        run_command(["git", "switch", "-c", branch], cwd=openrecon_root)
        run_command(["git", "add", "--", *prepared.paths], cwd=openrecon_root)
        run_command(
            [
                "git",
                "commit",
                "-m",
                f"Update {recipe} OpenRecon metadata to {version}\n\n"
                "Auto-generated from neurocontainers CI.",
            ],
            cwd=openrecon_root,
        )
        run_command(["git", "push", "origin", branch], cwd=openrecon_root)

        changes = [
            f"- Update `recipes/{recipe}/OpenReconLabel.json` from neurocontainers",
            f"- Set `recipes/{recipe}/params.sh` version to `{version}`",
            *prepared.notes,
        ]
        body = (
            "## Summary\n\n"
            f"This PR updates OpenRecon metadata for **{recipe}** from the latest "
            "successful neurocontainers build.\n\n"
            "## Changes\n\n"
            + "\n".join(changes)
            + "\n\n🤖 Generated by neurocontainers CI"
        )
        url = run_command(
            [
                "gh",
                "pr",
                "create",
                "--repo",
                repository,
                "--title",
                title,
                "--body",
                body,
                "--head",
                branch,
                "--base",
                "main",
            ],
            cwd=openrecon_root,
            capture_output=True,
        )
        print(f"OpenRecon pull request created for {recipe} {version}: {url}")
        return url


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--recipe", required=True)
    parser.add_argument("--version", required=True)
    parser.add_argument(
        "--source-root",
        type=Path,
        default=Path.cwd(),
        help="Neurocontainers checkout (default: current directory)",
    )
    parser.add_argument(
        "--repository",
        default="neurodesk/openrecon",
        help="OpenRecon GitHub repository",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    sync_recipe(
        source_root=args.source_root.resolve(),
        recipe=args.recipe,
        version=args.version,
        repository=args.repository,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
