name: blender
version: 5.0.1

copyright:
  - license: GPL-3.0-or-later
    url: https://www.blender.org/about/license/

architectures:
  - x86_64

build:
  kind: neurodocker
  base-image: ubuntu:24.04
  pkg-manager: apt

  directives:
    - environment:
        DEBIAN_FRONTEND: noninteractive

    - install:
        - ca-certificates
        - libdbus-1-3
        - libegl1
        - libfontconfig1
        - libfreetype6
        - libgl1
        - libglu1-mesa
        - libsm6
        - libwayland-client0
        - libwayland-egl1
        - libx11-6
        - libxcomposite1
        - libxcursor1
        - libxdamage1
        - libxext6
        - libxfixes3
        - libxinerama1
        - libxi6
        - libxkbcommon0
        - libxrandr2
        - libxrender1
        - libxss1
        - libxxf86vm1
        - xz-utils

    - workdir: /opt/blender-{{ context.version }}

    - run:
        - tar -xJ --strip-components=1 -C /opt/blender-{{ context.version }} -f {{ get_file("blender_archive") }}
        - ln -sfn /opt/blender-{{ context.version }}/blender /usr/local/bin/blender

    - environment:
        PATH: $PATH:/opt/blender-{{ context.version }}

deploy:
  bins:
    - blender

gui_apps:
  - name: blenderGUI
    exec: blender

categories:
  - visualization
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAPVklEQVR4nOVaCZRVxZn+/6q7vdcrTUOzqECQFrElCoLgMoCICdjMMYKSMG4xDJ5jEJ2gJsYlk2g4LoRBJwHX4DIEiM1Rw8AwLGELW8TgsAooEKFBoLvp5fV7991bt2rOX/c1/brplqYlkNj/OY/mnvduVf1f/cv3/1WolIK2LAzauDBo48KgjQuDNi4M2rgwaOPCoI0LgzYuDNq4GOdjUqUkIDKIr3x5kPpo3gt+rLzQatd1Ex/ywwfsK0b/FUDRjwDwb78/eM6psJJascS6t77pLJ/68Qk3gEAC2BwBEcC4fuIo+6Yp/8MYA1ABAPKvmQuoEPDkjuV3ColCKCNGz26AwhUo7E2vL07MvmeaqDzCtfIy+JpZgAwAGIfkjmWdxdz7D3sBgKeYx1Vg0UokMjfXAseL5m+xb31uhFV4fXn4Du0Vfg0ASHOD5K6VHf2SR9azZHXPGgEuU9KhryUyz2HKIpewRjw82Bl638Z08P7xASBJ+bc49pmVnP/gHKtsz9gTSXAxBYICJgiAdg4aXuGIR+xbnvkVj+aqsw0Cns9+gJICkBkg3RjGSx59NPLpimcrkuBJKQ0GiilEMhWvnQ2Om9N9qT32+THWRVfENHgUvgih8waAolQlv9LkemYZANKOUlpc8sIoa+Pri2p9BckAJILSQVohc6NcOZKb1dbNTw52rv7eznRXOvcAqK8+cXOS/GRlR+/9x5f4VWWXC6UYqhAECUxwlEa2zUB887a7ndFPvs1M56QVnUMA1MloLA5szlaVpe2DIGCgVL090v/Sn/VrDb/XPKfR90oKziLZMXfv+qHwlwVveFJb2UntFKBEZF47B5xkh8vescc+/69GwcVJsiKFDLAVLoFnBEBq54Pj+6xkyaO/UaVbJ5hfkp1a46EMEWp9Ca6vmnVxSpVZJjiBmfVX65anr7f7jjrYWvaILQYgtWUqGccTM0Yvy0mUDi9zwUPaF7LQFkpLZkNFFL1+55scB7lnorQcAwGu+UGx861HFmEr2CO2HIBwYG/3mnw5Z8LxasGrQYrMFmmkrSH05TMRnQVSHlcXC9JFAkrGmMizwXIvGjTNGfPcT3hOpwCkAGhhXMCWAxCavzi61659cZRrcgTXp6Lm9IbOEYD8+XRThT6OngJkqAKLMwzDCShdL9Cuh7+URjogDdjjmBdutHpdW9FSvoCtiQHulg+6B2temZGsOlZEObtegfAfBMrfeuEUHBlzskplzbEiVCKzqelopxWgsFBZGRZqoGqSEpSTUcrQiCvhZTORKMi0mJ4j5kkQwDympJUGgmaPZBHGPz9dFBl4++6WgIBnnAV0LKBFKoBEFb2PiFinezho+DsExhQYjnI3zukvls9Ykky6uRLqU5teODBhpNJbrZH7idVn+PNGr+tW8ILCo5iR5wM3FAgPVazcFod3dvF2ryoO9qz+cYZKdK50yUOYwFS8CFMlQLYFRjDq3y+LDBq/83TugK3iAS00Lxo78d/P3Ko2vbPAFRKCRqmPdi3TUJZgTpk9ZOJYe9D4tZjR/rQBVZ44ZHjr3hydWP92CTFGqiIZ1oGA0uBMRLiy+PiXO9mX3nD0y9aLrWWC9N4p7k9jSQnADRBlB0z33YdnRo9um1CWUEL7bSPlc0ywRH5hiXP7tDuNzr1dPYTwAI2Tlt1ofBmCz0396O/blOu+O2Up1hwdUOvVg0BWYXFgEMnen/3goktYdseguRSJZ60WqKPFVOXtWNY5+d5jq81kda9qv77KO6m8YiLbBkMUFL0VvXf293k0R6nADxkduVeiCsWBzQXB0b09lBfPZNHcCqNLn32sW/8TSMpTRiKSxA0Iyg+a8dfvXAXVpdckBNa7AzI3zwYn3vPGn+TcNfO55qwAzwoAaYMnlk6/Ua15eVkyUOApbBCoNE7AhE22kJG3M+uBP1zJsjpICIRWRgUCkqtmDfH+PPclK1HW12BEPML3aDyZ132J9U8TJ9tXjd2rv9DzGuAf3hVJvHL7Id9LZgdp9Fkxrl3MvHdOrtljQFVTS2dnS/mg5jirffMHT1vrX1kW80F4EmRj5cMZUdpcGXbxUzeT8rTzwDkotwZr3rjrRftPv14VVB/vW+2hV+EqtyIZfmhMVbb/2+aix/fULHj8Ts0s6BP4YHa5NMGH3D86xwKDskka2mBwlPE1r09qbvms9ZrX7QDXvpiYNXaduW/tE2WucskMKTidOhv3Mriy4vl9/svpO/KQfh8pUwJUz5vyZPaRjyaXuRjzJUjiAdQbqPswkAa1zcpciGftKHk7tvTFYVRFUnOV3C967d0bqs32W22mLOITNB2to8YNmNi77kdB+efm2QNAUj2OWnl37W/7J2bffVRWHR50wgOvsb83gEwpSeYfuerWafpZV3Ic/F0rOkX3r/r5MRfixC6bY43av5V0yl3wvFUzF0tSinFQVFLbUWUW3TQ10yTaiCFhUooFyL0oennJncsvPzsAyJTJJ2qwdt5DDxjLn92c9ANDp6KmTL4hBBYRHLP7gD2hRuH07uaSeyh9oTr9esi/hVQy2wLH/b9FA8JhiSYqsHoOWkepNj3ch4UpgP/ZhuKvBoBSese0yZfuiCZeHfeetWvxSxVJcEO6nl68MHHK64jEX5nPI0dYTkEyXKahzwj8Y/uu94RkSqkWEXgGSJxC+kd2DQy1DLtDrN2FFXFft1br2amUhi8VBEf3Dm9qLONMKDCiAcnNJb28hb9Yz4JEfoXABikuDNhMUJCjbm/DMcJSl5t2FRq6AawXjcQnAmGfSS6ioci8MQi0X4cVAwCznCAgUp22seROggykurxPqyxA0a5ToBI+xD/42XfhDz/d4yXj+TEiHmnK68oMUUYMZYh23Zah7uelia6ZadvcPOUlQracCoI874ItJmeSMkQLIZCcM8k7dN+un1IcRLox0+I6OzQYhyiDFG7emQMgqV9ngDh+wKx97XuvWVvmza3y0AsUKVtvZkRsTKZYtoXMLP5Z34yh903KdRgDZG5D30VpS7djcKI0GrLG0EysviNn2wyYAjjFdZoSqkBdL2BW0bfW1GOiIDj2WadIehCs+71+h3ktB0ClGp50gLF9aZf4q2N38MNbJ5RTiqP0lBalqWGZYSnDimQcUWNnXOQMvmObSlTl6O9OXbkXtRj4e9ddoXm0jlUKnH7f2VmZ1eODXFNFJePx5hTXVSMzYh0i4Iii4knmhX1raZ1hUxUhuXt1cX3Drv4d6pNgJLO05QBgGFgS//urEcG8SaVBrIoo7SkpTtfhNjgqr8dSe8Lcnro1JQNg2QXHyBdPId8KjAS1uz4q+QVVabqDIyWg6UDOXTNv9zM6ftjeUlFiiwQs1f/E5gC5S89kRR0dlVlTcOXMnFufmRnSb4oIDGTVF1ztWflYjaeo81CfjRRKk1GA7LqpxQAoKaH6d5MfjGx6dWltgF5jVqd9DLmb76Djdb9uavS++SPNLn0SVMiQ1fBOhUdrfSUbZoYwU8QD9LJqS4fV/umt/hqflLXxDt/wnIm/v8YrvPExx1BGno1OjqWsbENZOZZy8hx0LNupTPQbf1vmvW/+EO2MsBoLgYbYkunfj0Kyo1AoGnSPWAiAceGVC5vca9VELRBf8ZvrnLUvrS3zMI6BiDbcRDqxUSzHRib6/8ttkdFPleiuUIof6CpRBlA2bcQfrepDw4gfpANBJmlyJrhhxSIT511odr0srmsBbafhuoNDWzPE7lUDxBd7+gfJ2lye0e4L84KijfySYdt4fg/v5BG7dlMD3I8XdpMLphyoFeiBDBpwEQrOEQ7Mueu1jlbvocdbBED501fvYIkThb5s1LyoO7Pj3LNufqqfM2j8jvQqMPxRCETtomeL7Q9nLyQ+X3fclQ6iw5UBmR0+jt775mCjU6GrWaFu/tXFhmaEKkG96eHvkjtXFCTnTvpUiMARtN70+ARMRExgXmaXtXlTlgwlV2ssrKk5ZKy8j08Zqq6q0sGHx7NNsFhW/nbn7t921spTitSLThsm1SRwrh63tEZgnBHXaJQSySJ06Vp7/IrEa+O3e9uWXKBLYV1RIkDggxJJ/VdbR+pZF07U8U2dJCXXvnGVO+f+Q8L3M/VmNaLQCkFkmMgiA8f9tCnlmwWAdyp8P9cBQ1HwYdxjSrF8B6KyU9E7kYnz+1kXX5NqOob1ewMhMGQAZKq87y2Tch00JDRMS3pilEZcoBDxqp5i/uSDtXMmPRx8viVLj8dNQMMOGx/cOPlMvQACwd/1x4LYrHGzcPlzH3qBZD6l5cbKaytDo5Jl7YkMHr+huYY8NuUC4vDOSGLev5WYlftHUYwJuHOUX/mdh5yRP57HrOjpj6NU2M2GWDmrnDFyDyZqunkBMbRTe/0haUGZY4OREApYl8vfMnoO+j3vcukOllVArFFIL26pyiPtRenWfv6nG+6xKg98myaIkc/rtNzULvJ4ngVRv3hqL+eqMZ82d5yHzTVEpO+COrilnRKewQoKK1hO5+CMzgVTscDduvgCtuChg9WCxWUQOE319/Ww1PJWgZVhor4uQ0WNT4SfGj8MgNrwpKgrFJD70KqpRG5yasbj+TZEYxff9KOcO/7zP77ssASbBKApJVO09UyOpOssJbZ0xg0ZG2atKEtCXEmq75s/JCHTBSRGqBsFlCdpUokIWmniEk1Z0sn3GY/nWirq5vf+XdbEeXeg5aSal02vG5ttidWxQd2VogtMrWsdnARh4S9vif7l7fcqXPACqYi6nNUbavoUifqAloom8i95N3rP7O/yrHx5OovFv/kFiTRaHV856xq1Yrqu2RMBugjK+jJraKlQeiai1j7KIX7RtVMj46Y/oW+TtMBd8ZzdEEnFBG/36g7+wp/Pd2Klwyrpihww93Rm3ZSEbJSCoLKIlCUVj1lD7y+2b5i0WhOzFsYqPKdXZFLBSCaq0Vvz6k3eprmvZMhYt4SQkPDpII17VFpqv08/ECUeEnZ6wpJZSsPmwDJMBvQu7z38CWv45OlGlz6JRudTf7/X5EiogPG3vD8wuX3xA/6hT26LmmDo9hV1cFSYAfRZI1ED4vOMDlpRfw9ZnTeZvYf82uw35n2D7g2RtOJiJZ6fa3J0UpwqY/WzhODQtkyxb2OR//mWof7x/dcFNeW9wavtoKjzY1g1PJr3mdG+64dG18tXGt8Y+GejW/9jGMkJF9+Yjv+j3BL7exAGbVwYtHFh0MaFQRsXBm1cGLRxYdDGhUEbF3a+F3C+5f8Bgno9AqHEni8AAAAASUVORK5CYII=

readme: |-
  ----------------------------------
  ## blender/{{ context.version }} ##

  Blender is an open-source 3D creation suite for modeling, animation, rendering, compositing, simulation, and scripting.

  Example:
  ```
  blender --version
  blender --background --factory-startup --python-expr "import bpy; print(bpy.app.version_string)"

  # for use on a CUDA GPU:
  ./blender --background ~/cube.blend --engine CYCLES \
    --render-output ./render/frame_####.png --render-anim \
    -- --cycles-device CUDA
  ```

  More documentation can be found here: https://docs.blender.org/manual/en/latest/

  To run container outside of this environment: ml blender/{{ context.version }}

  ----------------------------------

files:
  - name: blender_archive
    url: "https://mirrors.iu13.net/blender/release/Blender{{ context.version.split('.')[0] }}.{{ context.version.split('.')[1] }}/blender-{{ context.version }}-linux-x64.tar.xz"
