name: hdbet
version: 1.0.0

architectures:
  - x86_64
  - aarch64

build:
  kind: neurodocker
  base-image: ubuntu:20.04
  pkg-manager: apt

  directives:
    - install:
        - git
        - curl

    - template:
        name: miniconda
        version: latest
        conda_install: python=3.10 pip
        env_name: hdbet
        env_exists: "false"

    - workdir: /opt

    - run:
        - git clone https://github.com/MIC-DKFZ/HD-BET

    - workdir: /opt/HD-BET

    - run:
        - echo 'import os' > /opt/HD-BET/HD_BET/paths.py
        - echo 'folder_with_parameter_files = "/opt/HD-BET/hd-bet_params"' >> /opt/HD-BET/HD_BET/paths.py
        - mkdir -p /opt/HD-BET/hd-bet_params
        - cp {{ get_file("0_model") }} /opt/HD-BET/hd-bet_params/0.model
        - cp {{ get_file("1_model") }} /opt/HD-BET/hd-bet_params/1.model
        - cp {{ get_file("2_model") }} /opt/HD-BET/hd-bet_params/2.model
        - cp {{ get_file("3_model") }} /opt/HD-BET/hd-bet_params/3.model
        - cp {{ get_file("4_model") }} /opt/HD-BET/hd-bet_params/4.model
        - /opt/miniconda-latest/envs/hdbet/bin/python -m pip install -e .

deploy:
  bins:
    - hd-bet

categories:
  - image segmentation
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAIAAAAlC+aJAAAACXBIWXMAAC4jAAAuIwF4pT92AAAGemlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNy4xLWMwMDAgNzkuN2E3YTIzNiwgMjAyMS8wOC8xMi0wMDoyNToyMCAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV2ZW50IyIgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29tL3Bob3Rvc2hvcC8xLjAvIiB4bWxuczpkYz0iaHR0cDovL3B1cmwub3JnL2RjL2VsZW1lbnRzLzEuMS8iIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIDIyLjUgKFdpbmRvd3MpIiB4bXA6Q3JlYXRlRGF0ZT0iMjAyMS0wOS0yOVQwODo0MDowMysxMDowMCIgeG1wOk1ldGFkYXRhRGF0ZT0iMjAyMS0wOS0yOVQwODo0MDowMysxMDowMCIgeG1wOk1vZGlmeURhdGU9IjIwMjEtMDktMjlUMDg6NDA6MDMrMTA6MDAiIHhtcE1NOkluc3RhbmNlSUQ9InhtcC5paWQ6MDc1NTA1NzgtNTQ3Yi1mNzRkLTg5YWYtYmQwM2QxODQxOWVlIiB4bXBNTTpEb2N1bWVudElEPSJhZG9iZTpkb2NpZDpwaG90b3Nob3A6NWQ3YmNlZjMtNGY5NS1kZTQ2LWE5ZWQtM2E4MTAxNTdkODVhIiB4bXBNTTpPcmlnaW5hbERvY3VtZW50SUQ9InhtcC5kaWQ6OWM4YjJiMzEtZmUzMi1hMTQ4LTg5ZGItNDg5MjE1NTE4Yjg2IiBwaG90b3Nob3A6Q29sb3JNb2RlPSIzIiBwaG90b3Nob3A6SUNDUHJvZmlsZT0ic1JHQiBJRUM2MTk2Ni0yLjEiIGRjOmZvcm1hdD0iaW1hZ2UvcG5nIj4gPHhtcE1NOkhpc3Rvcnk+IDxyZGY6U2VxPiA8cmRmOmxpIHN0RXZ0OmFjdGlvbj0iY3JlYXRlZCIgc3RFdnQ6aW5zdGFuY2VJRD0ieG1wLmlpZDo5YzhiMmIzMS1mZTMyLWExNDgtODlkYi00ODkyMTU1MThiODYiIHN0RXZ0OndoZW49IjIwMjEtMDktMjlUMDg6NDA6MDMrMTA6MDAiIHN0RXZ0OnNvZnR3YXJlQWdlbnQ9IkFkb2JlIFBob3Rvc2hvcCAyMi41IChXaW5kb3dzKSIvPiA8cmRmOmxpIHN0RXZ0OmFjdGlvbj0ic2F2ZWQiIHN0RXZ0Omluc3RhbmNlSUQ9InhtcC5paWQ6MDc1NTA1NzgtNTQ3Yi1mNzRkLTg5YWYtYmQwM2QxODQxOWVlIiBzdEV2dDp3aGVuPSIyMDIxLTA5LTI5VDA4OjQwOjAzKzEwOjAwIiBzdEV2dDpzb2Z0d2FyZUFnZW50PSJBZG9iZSBQaG90b3Nob3AgMjIuNSAoV2luZG93cykiIHN0RXZ0OmNoYW5nZWQ9Ii8iLz4gPC9yZGY6U2VxPiA8L3htcE1NOkhpc3Rvcnk+IDxwaG90b3Nob3A6VGV4dExheWVycz4gPHJkZjpCYWc+IDxyZGY6bGkgcGhvdG9zaG9wOkxheWVyTmFtZT0iaGQgYmV0IiBwaG90b3Nob3A6TGF5ZXJUZXh0PSJoZCBiZXQiLz4gPC9yZGY6QmFnPiA8L3Bob3Rvc2hvcDpUZXh0TGF5ZXJzPiA8L3JkZjpEZXNjcmlwdGlvbj4gPC9yZGY6UkRGPiA8L3g6eG1wbWV0YT4gPD94cGFja2V0IGVuZD0iciI/Pn2KYBEAAALeSURBVGje7Zo9juowEMc3T9vRcQioKagokIIQLSWcIVwh6SmSE4QLkAtAiUQqRAE99FBQQZ33f2tpZBE7kA+yydNMsQr2TOKf7czMemJEUfRVZ/nzVXOpPcB3Km3DMMRF4Rsv8515CzEAAzBAjQHW67XjOIPBAE5wNpstFovr9Zqg/3g8giCYTqfGj8DQ87zj8ZiLIEojZHU6nUzTjN+t1WqtViulLdrRqxwDurKN59+QsgFgKADAg+/3O9rBY9s2dV0ul/joqXe5XJJCGIaTySTzhGYHwFPF0GUhBtd15XZo0twDNX5by7LKBlCOA42EJ7djykU7LpS3JcPyAFIp0AQrsd+8s06MVMnTy5RLqfBOosbJ3CeF/ExylKguQLfbFRebzUapkAushJeYnAycaVXcaFoF3/flUE0xhAIZxfWKAsgMyuyDYkV1ASDIIBCkabIx96ASaUVmACPicyEGYAAGYAAGYAAGYAAG+C15XWL6XFmJV4ABCpcgCBzHabfb75u8/o+szHcgw7N4C9UOQJSVsE2pTJRcWYK+53miDAUr2KIlvvXF3eS9RPJiQKlqAk/VFFl8348fopC+aZqWZVGZA9dyfYTOVDKMMAVA60fkAhGQ5GfLDFSVAcPhcIhXysBQSJUgHYDyZDMMQ3mV5ONOmMQrUVQvg2GpALryI8R1XaEjqmN0mqszEYtg23Z+gBQv8Wg00nWNx2Nxsdvt8He/34ufnU5HqT8cDsUKFOCG8p+HxtWoXJn26RlW4PsTvvl2u5G3+f10+h05n8/yiJvNpvg5n88bjUZVAlnCRw206fv9Pv72ej3xc7vdfjwU56zOQ+Dmyc8KBQoCOs+rE4p0ygflcqNUCJILRE+BTHaaTx9HyBgwB7PSw+o+VigAAINI+NwE7fGohBadvjBJWEwSTFlhACK9Qb4gZ0R4a9GlW3G0o1fOgoQJJlgX48CAdZCzJi4xMQAD/NcAfwFbKGTWWfFLTgAAAABJRU5ErkJggg==

readme: |
  ----------------------------------
  ## hdbet/{{ context.version }} ##
  HD-BET (High Definition Brain Extraction Tool) was developed for robust brain extraction across different MRI sequences and scanners.

  Example:
  ```
  # Single file (CPU, fast mode):
  hd-bet -i INPUT_FILENAME -device cpu -mode fast -tta 0

  # Directory processing:
  hd-bet -i INPUT_FOLDER -o OUTPUT_FOLDER -device cpu -mode fast -tta 0

  # With GPU:
  hd-bet -i INPUT_FILENAME
  ```

  More documentation can be found here: https://github.com/MIC-DKFZ/HD-BET

  To run container outside of this environment: ml hdbet/{{ context.version }}
  ----------------------------------

files:
  - name: 0_model
    url: https://zenodo.org/record/2540695/files/0.model?download=1

  - name: 1_model
    url: https://zenodo.org/record/2540695/files/1.model?download=1

  - name: 2_model
    url: https://zenodo.org/record/2540695/files/2.model?download=1

  - name: 3_model
    url: https://zenodo.org/record/2540695/files/3.model?download=1

  - name: 4_model
    url: https://zenodo.org/record/2540695/files/4.model?download=1
