name: dcm2niix
version: v1.0.20240202

copyright:
  - name: dcm2niix license
    url: https://github.com/rordenlab/dcm2niix/blob/master/license.txt

architectures:
  - x86_64
  - aarch64

variables:
  dcm2niix_source_dir: dcm2niix-{{ context.version | replace('v', '', 1) }}

build:
  kind: neurodocker

  base-image: ubuntu:20.04
  pkg-manager: apt

  directives:
    - install:
        - ca-certificates
        - pigz
        - unzip

    - condition: arch == "aarch64"
      install:
        - build-essential
        - cmake
        - git
        - pkg-config
        - libjpeg-dev
        - libopenjp2-7-dev
        - zlib1g-dev

    - workdir: /opt/dcm2niix-{{ context.version }}

    - condition: arch == "x86_64"
      run:
        - cp {{ get_file("downloaded_file") }} dcm2niix_lnx.zip
        - unzip dcm2niix_lnx.zip
        - chmod a+rwx /opt/dcm2niix-{{ context.version }}/dcm2niix
        - rm -rf dcm2niix_lnx.zip

    - condition: arch == "aarch64"
      run:
        - tar -xzf {{ get_file("source_archive") }}
        - cd {{ context.dcm2niix_source_dir }}
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Release -DUSE_OPENJPEG=ON -DZLIB_IMPLEMENTATION=Cloudflare ..
        - make -j"$(nproc)"
        - cp bin/dcm2niix /opt/dcm2niix-{{ context.version }}/dcm2niix
        - chmod a+rwx /opt/dcm2niix-{{ context.version }}/dcm2niix
        - rm -rf /opt/dcm2niix-{{ context.version }}/{{ context.dcm2niix_source_dir }}

    - environment:
        PATH: $PATH:/opt/dcm2niix-{{ context.version }}

deploy:
  path:
    - /opt/dcm2niix-{{ context.version }}

readme: |-
  ----------------------------------
  ## dcm2niix/{{ context.version }} ##
  dcm2niix is designed to convert neuroimaging data from the DICOM format to the NIfTI format. This web page hosts the developmental source code - a compiled version for Linux, MacOS, and Windows of the most recent stable release is included with MRIcroGL. A full manual for this software is available in the form of a NITRC wiki.

  Example:
  ```
  ./dcm2niix ./test-dicom-dir -b y
  ```

  More documentation can be found here: (https://github.com/rordenlab/dcm2niix?tab=readme-ov-file)

  To make the executables and scripts inside this container transparently available in the command line of environments where Neurocommand is installed: ml dcm2niix/{{ context.version }}

  Citation:
  ```
  Li X, Morgan PS, Ashburner J, Smith J, Rorden C (2016) The first step for neuroimaging data analysis: DICOM to NIfTI conversion. J Neurosci Methods. 264:47-56. doi: 10.1016/j.jneumeth.2016.03.001. PMID: 26945974
  ```

  License: This software is open source. The bulk of the code is covered by the BSD license. Some units are either public domain (nifti*.*, miniz.c) or use the MIT license (ujpeg.cpp). See the license.txt file for more details.
  https://github.com/rordenlab/dcm2niix/blob/master/license.txt

  ----------------------------------

categories:
  - "data organisation"
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAASm0lEQVR4nOVbeXhVRZb/1XLvW/KSGBQSsBsHF4SA2oPYrqCyNEo7DK0+7Onl83McbXFD+dSx7cYk2jPOuIFg93TrZ7c9OqOTN9Mu44iiCLiBCzJCCCDqKEERMGR5yVvuUjXfqfdefFle8hKC/tEH7pf77q1bVefUOb86deoU8GdO7BtrV+uvWte5njD99XfkkJNmiMb42dUj2ajG/TpWHdWoY6rPojWaozHGusrWRxXYoRUKOzTVahaNxjgQRSzG/F6vazQ/Ib2lnCebDXMqJFlLWqR2Lz0j2VfZs7GWr6s9xz8UwmDDWpvWLBoDjy34iumTa94NJ9s7JzPGT4fGd8AwVimvijE+Wivf9IAxAa1VnHPxoVZ+m+ZsI6A2MB3c1Lj0jAO5uqJRLWLVtRp1dX1r0DcoABat112MH3vd8wHbqpjD4M8H1EyAjeV2GNCKGAWUD628HjVwMGGBMZKIgPYdKM9pZoy/rhl/hrv8+Yblp++lotFovRgu82AHWwGi9QKxBYbxyde/XKmtwEINdgkX1gTGOJSXJma01jBlGHGoNQP96wI/YzU6A42aQFEzgDMhOZNBMM7hO8m9YPhv5XoPbF9+bkOXRvRlYl+XAM6uWSPX1Z3rVUfrbTZ29C1a4zphh0cpLwXlpklNFTNDCz60FkhujNQGXEhBWqScpAPg35zO9JKdv5v1mQHOWuihagMbYr8YasEIzSctemUOpH0ft4KTlJOA8j3v4Jgu2CZNnD5jTIpgKZnHPq28XzXeP31FT008tAKoqeE5EJp447paIawaqsV3Uh4DRMaIDymRKHwupOR2CWlEvZ/ed/X2X1/YbLBhkEJgg2qa1K2OqRMWPlfhh8ufEFZ4jp9qNyoKMvivk4xGaF+GyqVynZ1wO3+8dfnsd3JmOfwCqMljPlT+ogiUnOIlW10GZuEbJK2VJ+wSqZTfwtzEnMEKgRev9nnMW8FuzJMUzew1zFcxxBiXvpPwGVChrfCLk65/6RRinsyhqO8xIGkzXU249uURPBBcaZhPtXvUML0VnMHxFNQw+2jUMdviZh4gCxuwl1opLoNcAy1Ix89rfPC8t2tqNK8r5HbntdM/1WuBBcyvXrT2JREum9VT7VsTLqrKgwjb1NniR64Q5VwDX2k0taQQtgQsmVk7Dfyt9oUMCqW8fdxzTmxYPnMfUMuAwp6j7K9CY0sLmDdx0epaEerNvOtr3P6D8Zh3ahXSUJB8eCYAX2vYnGPLh234ZWwH2jq9ooTAwITvJj0RLB2llP8YwOYgWs8Q6++bApSbUibesGaWkMFVyiPHRouc2jd3OKi9aDzOmTYKV67bhgNpF4KcPBwcsTwtqDnlaIzttHDR0ncRDkhjDsWQ1tqT4cOk39la27h8Rl1/0yMrUAVDDVg1YhKtI7dwKzDed1OKMcZJxT0fKAkIrFpyKqJvNmDDF+04PCjh5/XvYHSB2nAJVDTwvxeeitsebsSabc0oC0ljGgMTSYprCOkLL33Clgdm7iiEB7yvz6NRGNTXB0bcLEJlxLxHzOfeK60RCQgklMKXKReHBy1IxmBzBlswhCTHwVgDdT8gOJK+QlMijYgtkXJ8eL4G56wInCG/WGkuLMsDW05P6orHAM1iMajxi9ccAcUXK6dTM4ZeUwoJgfpBjJPNdqm/hhHK6LBtAGyoJkGqRoIstQVKQxJVFUFEggK79icRsgcGRsID5SR8YZd8b9J1L5+7tY6t6csUZM8Pz65ZK2geleqVa0QwMsJLttHoFwTLnn0gYLzzlKNx8dhRcNIHB4xUd4QLLJo3Dj87/ygELI73P23Hkie2oy0xMDCaVwxQnC8BsMZEo3oQ6/Vba5y2eH2wTaUbuGWPU55jlqZdBRjgeBqVZTaeuPlk/NW6zdibcMxo7U86uOvUYzE3VIFrH2tAa4cHwXsLaTBE2kXakFP7n//gOFRVBHDxvUUDowa3fK3S39m2bObWnlgg80tGo/U8xpjfccMrM0QgcrRKxxWjxfgARH1zfI0x4QAuGVuJy5Zuwrsft2FExIKfBztD8RFYD8Ff90gD3viHMzG9+nCs3TowMNLCSdoh6SXdywDctBZriZ+uXvFupaNR88fXLMoYy6zFiyTChBJbIpny0Rx3MCJiG/W3ZeYK2VlgzGIHrd6LuYz6aEApjaDkSDo+Pj+QNCBcDDASeFN8AgwXUKRqXd05hTBAMwppnfiTF0tcpmcrL00L26L86XwhUEekYGZUyF/IaWhzexqVFSGEjNoObZokU7BtiZKQjdKwbeorNcDYiZAtC2EC115acxE4LgicALB3881A5krV1IDV1UGrI+yJXAQqtZ8asmPbsxOup/CLaDXmTz0CnpOCEBQvGRpR3SVBjcXnH4mrZ1XBtixsakrj9n9vKAiMFI4TVkAqzzkLwLv5ZiBzhXIPfa3PkFZAeB7N/f27ygMRacCX7Q5qLqnGBeMd1N15F9rbO4wAivXq+qKcdhliDAt/+tf4l6v+EtF73oItJa0Jun9g7FlTfG4agGXrGvd3FZC5m3WTzsnNGqeYyK2BB31w3pynzfx90XePwJLaf0TD9o9QXhaBImTsRwUoXoqu1nsOZ6bujLvM4Hkeau9/FP/x8F2YVj0K6xr2oixM4PvVd7S6pigz05h82o1vhjYsPT1lvF0w/dUIb+3yY46k8DUYFTg4IuAqCVhIp1JoaYsb5iXn0H1MLAQ4ZOO+UvDI16bRERxCEAxpU1dv0ggEgmiPJ7H/yxaURQLw+i7HTCgeqHQ7d9sAS2YEgNwsYIKc+rQb60NgrJIKMwp8DgNlgJFBCgGlVAbUzRr/q4tQPJlMobmlzYxoRUWpuchUWlraEY8nutCo+7cZIdMrKkujXrDTWmkmpZ0KHTbG/K6hZTLybJwx3X7jCyEGfFsr9ys9HCbqy+Zz8dOW1jgmTTwWc+echeOOOQalwXIzukkngd1f7MbqNW/hjfWbEAjYsCxpBNmt7lx9BVtnTCuluBUOQfvfArANjZN6CICkmPK0FwjQmh+Hmoh5YiSddrHwikswZ/oMNLy2Hyt/04T9nzUazTlsRBjVU0fjukuvwHmzt+P+FY8iHu9EMBjoJYSiiHammHbzH/E+uoavi4j5m264HOecNAP3L1qL2EPvQgY0Tpt7FKbPOxojvx3Cay98gDuvWAl5oAp1ty1GWWkJXNc9iOi7LPzLdyRDIA8YDxGRvba2xnHVlT/ESeOmouZvn8aEk6twzV3TUHlkpFvaQGfcwdOPbMHqZ7filqWz8PeLr8Iv6u6DHEovSet8Txb0BH39jMsRaAXjZVlHdNjVgZA+kUyhmmx+xizcc/VqTJxShYW/OgvC4kikvG5GHSixsOD6KfA9hZTnYOqJEzFn5jQ898IrKCuLFO9PMDCtPFcAreZ3dmXIs281RYB2/H5+HEp/TLu0mXjM8BOpbirp4PvnT8fmtXvR2pzAD2+YAinpuWdmBC6yF2dwXQXfzfkNzESfZ8+cBsu2CkyNfZHWjEumPCchWlo/NI/qMvzxrjKNsUwTnCRU/MAPVkVono9Ewjh23NHYuHYXjp9SiVFjIkilfAjRuzZj6tlAIQmPVoRHfWs0xlRVwnHc4icrE9DS8ZTovpvMczeUlkJ/tcI7jIu+5638+rJzvBqEEDKem2/m+NJQGfZ93o6jjh9RdGYQCcD3fZSWhDC6cqTxGYoBQ1rVMmHTTaPRctrlyrbKc4UoJ8fcSLylewRB+iJPaxPyokIUwKSQWPHBn2x6gNKQcvALo8xO1CC+0mQCFJlhG+gnpdzkXvHcTSwWNRMr084m30u3UnJC73Vd5gmty3c1p7B5ZzvuOPUYoyytaRdxx7ibhftBwRnO0dmZQNJNoPzwMD7/tD3rlPZPZO900ffJtIuW1jbjJheDgTSY2vco0WJdt8FGt1EmINS8cel5LUyr9UwGCgZEyKEtsQVufXIbRrZyvDP/u3jp+1Pw1OwTEbFEvy6plAItLXE07dmNSaeMwY739qKjw4W0eEFQM8GQoEQgKGBLjj37vsSu3Xtg2wTWAzlEWjNpceUl94QSzsb8wSbqpuZZ1SC4iRFqFhIvPaZ1N62//2bFe7j9kW3419inePyZXUg7yqB3wYHRpPYCq9esxxkXjEMy7uD5xxoRoFA6JxvXxjToUn5m1EuCEls27MGWtz43McbX129EZ6LT+BMDEcUCuBWiel7e+NDstiht9eWhDs8vnAsX2Sr5P36q40tewAzyhRC2BV7dcQD/ufELrNy8D+nslFXIRM2eQiSM1994D9ubtuLy26Zj5eMNeOoPDSaSFAnJ7GhT5Eca5t9e24QHb12HD94+gL0HWvDUsy8iHDJMFaf+nqs504+aB7Hu+2SyR3FNEootYPsnLFr9jGWXX+4l2wsGRnKiKQ1KBC2NCHU6KLpiAYQVfQEjYQb58/ct+z3+6Y6b8bMlZ+OP972Jxrf3YOq5Y/Ht4ypAst/b1I7Nb36O99/4DLMvnoRZPzkGd9y9FB2dnQiHSQCUKFYYQLTWSlhB5nvJ7aPK+atkDRT0zS/De35UbeICmknB71VuKp2NCvcrarJ5izN8si+JzZ+245cXjs8AY8JBR6o3MNI7WtV1dCRw6+33IjIugSW/nYvK0Ydh1ZM78JvbXsOKW9bhT7/djFSHwqK7ZmL6JaNRd/dSbGn4ACUl4WIXQ5oJm0T0zyZnYEFvflm/G6OLVj8qQ+WXZrSg8OaIqSg76uVhiRWXn4AxFQHsa0sjHJQYU8aw8Mbb0doeh6SQVVZ1CNFpYeO6PuZdcC5mn3MmSgMj4HRSyEdDBjV8mcDbm97HE/XPo6Oj0zBPvkCOCDc6OlP43b23YelrPp7dsAsVERuer7Kjn/7A9ZMnfTjiLRd1dbk4cxfJvpiJxbZStIGxa9be6vPkPC6scq3cfoOk+cD4o2UbcdbEw81WVlnIxuK5Y/oERhpFEghdf3r6JTz3/FqMHVuFI4+sNCPT3NyGjz/5zCyBIyUho/b5zA8wIBqc4k/J6z9cMTdtBjVvP6BfAQB1KrpgEmnBF9U3vLyEB0c86CVaBtSCnBAsKfDqtmak0j4qK8K4dnZVtlO95ZfTBhMr1Bq7mvbio492ZzonhQmCVBxWmvUDeqt9rsYMHmTrVMoTwXLpJ9tijQ/MXNXf9jgvxAx9QAkSjctm/dpLtv0XZWNRQlJ/AsgJgS4CxoqIhUiQIxS0DfOuS4sdnon/8e6XSYmkDdGgbYRBF404lc+8y6h712Xq4EZonq9QYrTDNK64HRS+k/gY3LmKfJv8eb9oAXRNi+RHpOUVfjr5f5SNRVtNKIIIGEkBP93Xifea0rjm0vnkkyPekTDLYbLbbleC/iYR70iivSNhLipLz3qVzZbvTCTRFk/gx/Nngkcq8frWPbo0HDTaon33R41Lz8smWhdebbCBGMntohx/zaqpIliyirKxlJcqbs8wDxiX/91J+IvSFFpaWmCZaMbB55L4vjLTqQ6Pwk1/bNAbP4mr8tKISHe0Xrn9we89XEwuMSumqZwNUQoapaJlhJCmtFVRrBBITc+YOBLlJYGM3R90NlWmDqp3/bYvdEcKqrQ0IpxU/MrtD8x8uNhcQVZse7kKc0LgjFVQQlIuXa7fRrKtdCS9rnXCcEVbaIUcCVncCpSwwTJPNKhhyBcCrPAzTFqj/VScZgfyrwesK3+ffziIQJnLoFSaeZ6buHqwzBMNujs5c5hww8rRXET+IOzwHD/ZbvbhizGJYaHM3h1EqIwrN7UTvnPZ1mUz3hgs80RDG4+81HTKGOdc/JwJy1bpTqWZ2VPjhyS+rmmNCC2soAAXUJ77pErvuzaTKT60wxNsyJ2h/OHaWnNQYcL1ayYLKe5mwj7fhJ6dhMnVG5ZzA7lzAtCCWyFGAVvlphsU07dsu2/aSioylDT5HLGD6lyPYyuTF782WzF2M7SeIeywoMwM7aYNAxm8ov9mV7ZA27ThZ3YlzeZf5tiMxbkdgvYc8vY2a+gHWNOexxtjC5xMBruJXwwZUxmGg/K0gX5Ovmn9iUr7P2VKzwVn1dwKGrPVvps9MEVJpz38WjpMRLFwc3jKBgVmqbzynN1MyJeYYk80NDW90nUqZIgnRHoSw3ASdSr/NFe9FpPeemcKVPpMDU3JCRMBXaW1KiMNMdvwpheZw1XQqkVr3cEY26aVXs+k/arP9Ts77jkr3kPj1HDNpAyHgnKHHXsgMgVbPtj6SanXunM07BFVSLXSigeQQSAd75AVR+yUe5qcjQ/NS/T8LkaRnNiCYWP869oJZYjWm2OzJi2lWJWN1ouu47NmIXPojs+yQ1VxwfYIEmvBoo0xlovOUXKeuTfm880cosafK/0/rtClUXgGYvIAAAAASUVORK5CYII=

files:
  - name: downloaded_file
    url: https://github.com/rordenlab/dcm2niix/releases/download/{{ context.version }}/dcm2niix_lnx.zip
  - name: source_archive
    url: https://github.com/rordenlab/dcm2niix/archive/refs/tags/{{ context.version }}.tar.gz
