name: Validate Recipe YAML

on:
  pull_request:
    paths:
      - 'recipes/**/*.yaml'
      - 'recipes/**/*.yml'
      - 'builder/validation.py'
      - 'workflows/validate_all.sh'

permissions:
  contents: read
  pull-requests: write

jobs:
  validate-recipes:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install attrs>=23.0.0 pyyaml>=6.0.2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            recipes/**/*.yaml
            recipes/**/*.yml

      - name: Validate changed recipes
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Validating changed recipe files..."
          
          validation_failed=false
          
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ "$file" == *"/build.yaml" ]] || [[ "$file" == *"/build.yml" ]]; then
              echo "::group::Validating $file"
              if python builder/validation.py "$file" --verbose; then
                echo "✅ $file is valid"
              else
                echo "❌ $file failed validation"
                validation_failed=true
              fi
              echo "::endgroup::"
            fi
          done
          
          if [[ "$validation_failed" == "true" ]]; then
            echo "::error::One or more recipe files failed validation"
            exit 1
          else
            echo "✅ All changed recipe files are valid"
          fi

      - name: Validate all recipes (full validation)
        if: contains(github.event.pull_request.labels.*.name, 'validate-all')
        run: |
          echo "Running full validation on all recipes..."
          ./workflows/validate_all.sh

      - name: Comment on PR
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ **Recipe validation failed**\n\nSome YAML recipe files in this PR have validation errors. Please check the workflow logs for details and fix the issues.\n\nThe validation is based on the schema from [neurocontainers-ui](https://github.com/neurodesk/neurocontainers-ui/blob/main/lib/zodSchema.ts).'
            })

      - name: Comment on PR success
        if: success() && steps.changed-files.outputs.any_changed == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ **Recipe validation passed**\n\nAll YAML recipe files in this PR are valid according to the schema.'
            })
